### ISSUE TITLE
Write statement of work

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#10]
Write a document that includes definitions of

* [x] specific tasks and milestones for each group at NCSA
* [x] contributions expected by other groups within the program (DDPSC, MAC, KSU, WUSTL, Hudson Alpha)

(migrated from terraref/reference-data#4)

**Comment by rachelshekar** [comment]
@dlebauer  - I've tried to start on this but an unsure of the role that everyone will play in the project.  Maybe we can meet to discuss?

https://uillinoisedu-my.sharepoint.com/personal/shekar_illinois_edu/_layouts/15/guestaccess.aspx?guestaccesstoken=ZViV5KKdbRUs%2fJRO8Fm1pluet3hS7SE9oZZZTXBmLX8%3d&docid=1cd5c66e2450f419db87a3fe91a7664fc

**Comment by rachelshekar** [comment]
The draft is here:
https://drive.google.com/file/d/0B0lCOAt29Y79dW5uTGFiMzVHWnc/view?usp=sharing

**Comment by dlebauer** [comment]
@rachelshekar Thank you for preparing the initial draft. My changes were minor. The next step is to get feedback from developers and managers of each group. We can put a review on the agenda for Thursday Dec. 3 (@robkooper, @yanliu-chn, @max-zilla, @dlapine, @mchenry, others can review / comment ahead of that date).

Note that the non NCSA team contributions are put there for reference and context (and discussion); however, this document is not intended to define or change the scope of work for outside groups. 

* [ ] review at team meeting on Dec 3
* [ ] review with ISDA, NDS, CyberGIS project managers and PIs
* [ ] etch into stone

**Comment by dlebauer** [comment]
@rachelshekar please forward link to folk and PMs and PIs
