### ISSUE TITLE
504 gateway timeouts on TerraRef Clowder

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#102]
Regularly over the past week as ingest of data from gantry has ramped up, the Clowder instance at https://terraref.ncsa.illinois.edu/clowder/ has been issuing 504 Gateway timeouts. Initially @robkooper identified this as MongoDB running out of memory and was able to expand the amount of memory available to the VM, but this was only temporary as the problem has continued.

You'll likely encounter this when trying to log in. Based on the Roger logs there is still data being loaded into Clowder via the API, but without being able to log in it's difficult to verify. Either way, I expect that these gateway timeouts/Mongo memory load are slowing down the Roger side of things considerably.

We need a more permanent solution for this, as the gantry Globus tranfers are caught up to current but the Roger -> Clowder uploads are lagging around 2 weeks behind (processing dates around 4/30-5/2 recently). I expected this to be much further along after the weekend.

Could involve some combination of:
- moving the Clowder VM somewhere with a lot more memory
- modifying my upload script somehow, perhaps I can optimize how data is uploaded. I'm wary of removing some of the consistency checks - e.g. if we have a record of "2016-04-29 corresponds to collection 12345" I hit the Clowder API once to verify that collection still exists before putting the dataset into it. this check could be removed, but then if something happens to collection 12345 there would be problems next time a file from 04-29 arrived.
- some change to Clowder itself, i.e. an endpoint that will automatically create space/collection/dataset links in one step without needing 4-5 API calls to accomplish it?
- scaling this up some other way...

Ideas or thoughts? @robkooper primarily, maybe @jdmaloney might have some thoughts.

**Comment by robkooper** [comment]
I think one step is to move the mongo database to a better place with more memory and being replicated.

Also we can increase the timeout time in nginx so you get an answer back (after some more time). Right now this is the default which I believe is 60s, we can increase this to 300s (5 min) so if the server is busy we don't run into this issue.

**Comment by max-zilla** [comment]
Here is the Clowder upload workflow on the Roger side, with each API call in bold. When Globus task comes in from gantry, service monitors until it is SUCCEEDED or FAILED. Upon SUCCEEDED, it adds the task to a queue of 'unprocessed tasks'. There is one main Space everything goes into.

For next unprocessed task, iterate through each dataset (SENSOR - DATE):
- Is dataset in DatasetMap (name -> Clowder ID)?
  - NO:
    - create empty dataset (**POST /datasets/createempty**)
    - add ds to SENSOR collection
      - is SENSOR collection in CollectionMap?
        - NO:
          - create collection (**POST /api/collections**)
          - add co to space (**POST /spaces/spID/addCollectionToSpace/coID**)
        - YES:
          - check if GET returns 200 (**GET /api/collections/coID**) and return ID if so
          - if no 200, query by collection name (**GET /api/collections?title=SENSOR**) and return ID if found
          - if still no 200, delete SENSOR from CollectionMap and goto "NO" above (**invokes 2 calls**)
        - now add ds to SENSOR (**POST /api/collections/coID/datasets/dsID**)
    - add ds to DATE collection
      - is DATE collection in CollectionMap? 
        - same as process for SENSOR
        - **invokes between 2-5 API calls**
    - add ds to space (**/spaces/spID/addDatasetToSpace/dsID**)
  - YES:
    - check if GET returns 200 (**GET /api/datasets/dsID**) and return ID if so
    - if no 200, query by ds name (**GET /api/datasets?title=dsName**) and return ID if found
    - if still no 200, delete dsName from DatasetMap and goto "NO" above (**invokes 5-11 calls**)
- Now that we have dataset ID one way or another, iterate through each file in dataset
  - if not metadata.json in name, post file (**POST /api/uploadToDataset/dsID**)
  - if metadata.json in name, post metadata (**POST /api/datasets/dsID/metadata**)

Throughout these steps, log files are written to ensure individual files/datasets are not created multiple times. The log writes should not impact Mongo memory however.

So there are a lot of potential API calls here. I mentioned we could potentially remove some of the checks (e.g. "check if GET returns 200 if we have an ID" instead of just assuming the ID is still valid) but that could cause other problems down the road. 

A new API endpoint that accepted a dataset name and automatically returned an ID if it exists, creates it and attaches it to collections/spaces and returns the new ID if not, could reduce the number of API calls coming from python. But the database would still be doing the same tasks, so I don't know how much this would get us.

**Comment by max-zilla** [comment]
As an example (I'm watching this process in the background) - this simple GET request to verify if a dataset exists takes **15 seconds** to return this much data when the memory is full (which it has been for a couple days now):
```
GET http://terraref.ncsa.illinois.edu/clowder/api/datasets/573b50b9e4b08a9020ee78c9 

{
  "id": "573b50b9e4b08a9020ee78c9",
  "name": "cropCircle - 2016-04-30__14-08-00-422",
  "description": "",
  "created": "Tue May 17 17:11:21 UTC 2016",
  "thumbnail": "None",
  "authorId": "571fa2638081d46983d5bf6b"
}
```
...and this is one of the simplest calls in the list above. It should take like 20 milliseconds. This is the bottleneck on Roger right now.

I've streamlined my upload code as much as possible without removing checks or modifying Clowder API - I modified the dataset upload to collect all files in the dataset and upload them in one call to /uploadToDataset instead of one for each file, but in practice this isn't a huge difference because many datasets already only have 1-2 files.

Increasing the timeouts could help the user experience in the browser, but the API calls can't take this long (or longer) going forward if we're going to keep up with the stream.

**Comment by robkooper** [comment]
Not sure what is happening:

```
time curl -u U:P https://terraref.ncsa.illinois.edu/clowder/api/datasets/573b50b9e4b08a9020ee78c9
{"id":"573b50b9e4b08a9020ee78c9","name":"cropCircle - 2016-04-30__14-08-00-422","description":"","created":"Tue May 17 17:11:21 UTC 2016","thumbnail":"None","authorId":"571fa2638081d46983d5bf6b"}
real	0m0.395s
user	0m0.029s
sys	0m0.011s
```

**Comment by max-zilla** [comment]
The database calmed down when I stopped my upload service for a few minutes to push a couple code updates to improve the logging. Once I started the pipeline back up and the API calls came in, it slowed down again. Two consecutive calls before restarting/after restarting:

```
mbp2020:~ mburnette$ time curl -u xx https://terraref.ncsa.illinois.edu/clowder/api/datasets/573b50b9e4b08a9020ee78c9
{"id":"573b50b9e4b08a9020ee78c9","name":"cropCircle - 2016-04-30__14-08-00-422","description":"","created":"Tue May 17 17:11:21 UTC 2016","thumbnail":"None","authorId":"571fa2638081d46983d5bf6b"}
real	0m0.245s
user	0m0.022s
sys	0m0.008s

mbp2020:~ mburnette$ time curl -u xx https://terraref.ncsa.illinois.edu/clowder/api/datasets/573b50b9e4b08a9020ee78c9
{"id":"573b50b9e4b08a9020ee78c9","name":"cropCircle - 2016-04-30__14-08-00-422","description":"","created":"Tue May 17 17:11:21 UTC 2016","thumbnail":"None","authorId":"571fa2638081d46983d5bf6b"}
real	0m11.034s <--------
user	0m0.023s
sys	0m0.008s
```

The homepage returns 504 for me nearly every time when this occurs (i.e. after Login) I think because it's trying to show recent activity for me (1 minute ago, Max Burnette uploaded...) and it times out - other users wouldn't see this. 

The upload process is generally working, but you can see that simple calls might be taking several seconds. It just depends on how busy the upload is - maybe this won't be as significant when we don't have 2 weeks of backlog to get through.

**Comment by robkooper** [comment]
The good thing is that it is clowder that takes all the CPU, the bad thing is that it is clowder, from top

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
29546 clowder   20   0 2654388 1.203g  20572 S 194.4 31.2  41:40.94 java
 1060 mongodb   20   0 1281140 1.017g   6288 S   0.3 26.3 166:23.70 mongod
```

Can you see what happens if you add a sleep 1 in your code after you submit a dataset.

**Comment by max-zilla** [comment]
Added a 1s sleep after a new dataset is created or a new collection is created. No sleep when uploading files for now - don't want to add too much sleep time yet.

Seems to be a bit faster than before - will watch for a bit and see how it's looking.

**Comment by max-zilla** [comment]
After talking with Rob, we are thinking this is also related to heavy IO load. The script is writing a lot of logs and reading from logged completed tasks regularly - I wanted to write things a lot for safety in event of crash, but it's bogging things down. Going to adjust balance of <data in memory> vs <data on disk> to have more recent data in memory so it isnt reading from disk so much and hopefully this problem is reduced.

**Comment by max-zilla** [comment]
After I rewrote some of the API calls/IO frequency and Rob expanded the VM memory to 8 GB, this has been running without issue for ~18 hours with a fairly consistent mem usage:

```
             total       used       free     shared    buffers     cached
Mem:          7985       5756       2228          0        157       1614
-/+ buffers/cache:       3983       4001
Swap:            0          0          0
```

Even for me using the Clowder site itself and executing searches is behaving satisfactorily. Going to close this issue for now.

**Comment by dlebauer** [comment]
😀😀😀😀😀😀😀😀😀😀😀😀
