### ISSUE TITLE
Capitallization in StereoTop Metadata changed 5/23/2016

### ISSUE THREAD

**Issue by pless** [terraref/computing-pipeline#103]
The metadata format for the StereoTop sensor seems to have changed.
Specifically, in the json file, there is a different capitalization on variable names.

### Description

Example:

in file:
StereoTop/2016-05-23/2016-05-23__04-27-02-912/bd82d326-8faf-42e1-b64d-31199410024a_metadata.json

there are fields:
  "gantry_system_variable_metadata": {
      "Time": "05/23/2016 04:27:02",
      "Position x [m]": "200.9",
...
}

and a few hours later, in file:
StereoTop/2016-05-23/2016-05-23__06-49-00-163/8ece5b4c-9c62-4af6-8cfb-607e89fc695e_metadata.json

the field names have a new format:
    "gantry_system_variable_metadata": {
      "time": "05/23/2016 06:49:00",
      "position x [m]": "200.8995",
 ...
}

(the difference is that "time" and "position" are no longer capitalized)

### Context

This broke some json parsing code we are using here to test algorithm development.  we could make our parsers case insensitive, but it might be easier to keep the json field names consistent.

**Comment by dlebauer** [comment]
@TinoDornbusch or @rjstrand can you comment on why this is happening / fix it? I was not aware that the metadata formats were still being updated.

**Comment by TinoDornbusch** [comment]
Markus was updating the environmentlogger files to accommodate for the CO2 sensor being integrated in the data stream. He apparently used an older version with capital letters. Will fix that asap

**Comment by TinoDornbusch** [comment]
@dlebauer must have happened during some software update / test. Data format is back to previous stage. At this stage we do not touch metadata unless you specify. 
We still need to define and work on the usergiven.xml metadata to store experiment specific data.

**Comment by dlebauer** [comment]
@pless or @ZongyangLi or @max-zilla  if we are going to have to process the old data separately, could someone please close this an make a new issue?

**Comment by ZongyangLi** [comment]
@dlebauer I think we have solve this issue by some coding method. When we load metadata from json files, we simply make all keys into a lower-case. So I think we could close this issue.
