### ISSUE TITLE
Use LogStash to create log report/digest

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#106]
LogStash can be used to define templates that can parse log files (like we are generating with the gantry/globus monitors) to create aggregate reports for things like:
- files per day
- files per sensor
- times per transfer

We can use this (ideally on centralized log server) to create transfer reports and provide dashboards for monitoring.

**Comment by dlebauer** [comment]
Can this be used to track the entire pipeline ... from MAC to UI, Clowder, BETYdb and beyond? 

Would be good to track data access as well (but only publicly report aggregate rather than user-specific stats)

**Comment by max-zilla** [comment]
@robkooper may know offhand, but in general I expect moving to a centralized server would let us concentrate those things in one place. We just need those components (e.g. an extractor that would push data into BetyDB) to write their log to the right place and configure it.

http://stackoverflow.com/questions/18330541/how-to-handle-multiple-heterogeneous-inputs-with-logstash

**Comment by jdmaloney** [comment]
I've come up with these sensor file type requirements to make sure this quantity of these types of files exist for each sensor @dlebauer do these numbers look right?  If so, I'll start the automated check that things are matching up:

co2 Sensor —> 1 json; 1 bin
cropCircle —> 1 json
flirIR —> 1 json; 1 bin
ndvi —> 1 json; 1 bin
prisensor —> 1 json; 1 bin
ps2Top —? 1 json; 102 bin (haven’t seen these since June)
scanner3DTop —> 1 json; 2 png; 2 ply
stereoTop —> 1 json; 2 bin
SWIR —> 1 json; 2 txt; 1 hdr; 1 jpeg; 1 raw
VNIR —> 1 json; 2 txt; 1 hdr; 1 jpeg; 1 raw

**Comment by dlebauer** [comment]
looks good. Here is the 'master' list: https://docs.google.com/spreadsheets/d/1LLiQSFHbEWoo_FkvG1nl-XoSq_lZ_o6VazfxmPfOH9Y/edit#gid=0

**Comment by rachelshekar** [comment]
@jdmaloney - can you close this issue?

**Comment by dlebauer** [comment]
@jterstriep feedback appreciated

**Comment by jterstriep** [comment]
Logstash, or more accurately the ELK stack (Elasticsearch, Logstash, Kibana), can be used to centralize logs from multiple sources with different formats. Basically, anything that creates a log file can be sent to Logstash where it is transformed prior to being stored in Elasticsearch.  

So without knowing much about the "entire pipeline ... from MAC to UI, Clowder, BETYdb and beyond", I would give a qualified yes. It should be possible to monitor the entire pipeline, check performance, flag errors, and provide usage statistics.

**Comment by rachelshekar** [comment]
@jdmaloney  - is this running now?

**Comment by rachelshekar** [comment]
@jdmaloney - status?

**Comment by rachelshekar** [comment]
@dlebauer - please define what information you want the report to contain

**Comment by dlebauer** [comment]
@jdmaloney I think what you have is a good start - what are the next steps? Could you link to the current web page in the documentation? Can the interface be extended to log downstream datasets?

**Comment by jdmaloney** [comment]
@dlebauer Web documentation now has a link.  Can you elaborate on what you mean by downstream datasets?  

I'll be adding transfer metrics to the page here soon as we've started logging those and should now have enough data for those graphs to be useful.  For Level_1 stuff I'll talk to Max, this can definitely visualize it, just a matter of feeding it data when extractors complete their runs.

**Comment by dlebauer** [comment]
Downstream = Level_1 and other data product S beyond the raw files
transferred

**Comment by max-zilla** [comment]
Let's close this and make a follow-up issue to discuss Level 1+ data. Initial version complete.
