### ISSUE TITLE
Convert gantry coordinate system from right handed (x positive to left) to conventional (x positive to right)

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#109]
### Description

The coordinate system is currently placed with a 0, 0 point near the SE corner of the gantry. The x axis is positive going west. Units are meters offset from 0,0

When we create data products available for download, we can convert to any coordinate system.
### Further Suggestions / Request for Feedback

There are a few options
1. Change the coordinates used by the lemnatec scanner
   - this has been rejected in discussions w/ Ben, Bob Strand, and others 
2. Change coordinate system on ingest. We could do this as the first step in meta-data processing. 
   - something like `x = -x + offset` and `y = y + offset`. 
   - requires @rjstrand (or someone at MAC) to establish a new 0,0 point and measure offsets. 
3. Use the given coordinate system
   - the primary reason not to do this is that it means everyone has to understand this non-intuitive extra step.
### Related issues
- converting lemnatec meta-data to absolute geographic positions https://github.com/terraref/reference-data/issues/32
- store camera location and field of view https://github.com/terraref/computing-pipeline/issues/101

**Comment by dlebauer** [comment]
@rjstrand assigned to you. This is different than what we agreed last week, but after working with the existing reversed coordinate system I realized that it is sufficiently difficult to implement that it would make it more error prone to have each person writing code in gantry coordinate system to understand and handle appropriately.

**Comment by rachelshekar** [comment]
@dlebauer - can this issue be closed?

**Comment by dlebauer** [comment]
No, Ting Lee is working on this

**Comment by rachelshekar** [comment]
@tingli3 - please give an update.

**Comment by tingli3** [comment]
see #174
