### ISSUE TITLE
Launch VM from Clowder with copy of selected data, PlantCV, and Jupyter interface from Clowder

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#11]
Clowder will be set interface is set up for extracting and browsing datasets, 

Once a user selects a set of data, launch a docker container from Clowder interface that gives access to the data.

Demo will be done on Nebula, all Clowder dependencies on a single container

* Need to handle authentication, persistence of files. 
* Support sharing code with others
  * Save notebook in Clowder?
  * Support pushing github commits.

**Comment by robkooper** [comment]
See https://opensource.ncsa.illinois.edu/jira/browse/CATS-224

**Comment by dlebauer** [comment]
Google's Data Lab looks like a similar idea: Jupyter interface to large data https://cloud.google.com/datalab/

**Comment by rachelshekar** [comment]
See https://github.com/terraref/computing-pipeline/issues/12 for description of what this shoud look like

If this can not be ready by Nov 6., produce a screenshot

**Comment by dlebauer** [comment]
sample data and notes (README) are here: https://uofi.box.com/lemnatec-danforth-data

**Comment by dlebauer** [comment]
@davidraila I've put the draft mockup and data flow in #12 and will flush these out per discussion today.

**Comment by robkooper** [comment]
Initial goal is to launch a single VM, once this works we can work towards adding to Clowder the ability to select a VM and launch the VM.

**Comment by rachelshekar** [comment]
- [ ] pull from Clowder - needs help from @robkooper

**Comment by max-zilla** [comment]
There is a Clowder issue associated with this in JIRA:
https://opensource.ncsa.illinois.edu/jira/browse/CATS-224

I've created a branch for it to add the button that'll launch @davidraila's VM

**Comment by max-zilla** [comment]
I will demonstrate current status of this functionality on Thursday 1/28. We have the ability to launch tools with Clowder data included - currently the tool is a Jupyter notebook without PlantCV, but core components are written.
