### ISSUE TITLE
Add new BETYdb API help to documentation

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#113]
After issue #77 I added a section for Clowder API and Globus interaction to the Clowder page.

We should add a corresponding entry to the BetyDB documentation page once the API is finalized.

**Comment by gsrohde** [comment]
@max-zilla There is now documentation of the trait-insertion API at https://pecan.gitbooks.io/betydbdoc-dataentry/content/trait_insertion_api.html.  The BETYdb Docs menu will contain a link to the book containing this as soon a new release is done.  Can this issue be closed as soon as that release is done?

**Comment by max-zilla** [comment]
@gsrohde yep, that looks good for now.

**Comment by gsrohde** [comment]
Updated links to documentation were part of Release 4.10.
