### ISSUE TITLE
Create generic extractor for geospatial data from *_metadata.json files

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#117]
### Description

All datasets on the gantry come with a file named *_metadata.json. THis includes geospatial information that needs to be

1. converted to bounding boxes
2. converted to standard [0,0] at sw corner coordinate system
3. converted to geographic coordinate system (lat, lon)

See related code / algorithms 
  * some is in computing-pipeline/scripts/hyperspectral/CalculationWorks.py
  * @caicai89- is also working on this in #109, terraref/reference-data#33 

Use geostream API so that it can be plotted within Clowder

**Comment by dlebauer** [comment]
@caicai89- is this a duplicate of #101?

**Comment by max-zilla** [comment]
Yes, this is a duplicate. I will close as discussion is taking place there.

**Comment by caicai89-** [comment]
Right, the issue here is overlap with part of the #101
