### ISSUE TITLE
Finalize prototype architecture diagram

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#118]
https://docs.google.com/presentation/d/1LaOI3ESTFwn7b8x5oWZcdOWBLsCh2v4F7yqgQ836etU/edit#slide=id.p

**Comment by jdmaloney** [comment]
Made a couple formatting modifications to Slide 3, but otherwise it was already correct in its current state.  I think that's the only slide I'm responsible for, however if not, just let me know.
