### ISSUE TITLE
Mockup workflow for demo

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#12]
* Upload data to clowder
* PlantCV runs
* view results
* launch shell with data attached (would be nice, can also show 'mockup') later, Jupyter

**Comment by dlebauer** [comment]
Drafts: 

![image](https://cloud.githubusercontent.com/assets/464871/10827435/f5d383a2-7e3c-11e5-927e-43d6fa966775.png)


![image](https://cloud.githubusercontent.com/assets/464871/10827426/e1d1df0c-7e3c-11e5-8b49-9e9e61609da9.png)

**Comment by dlebauer** [comment]
I've placed a mockup for the demo as a [presentation on google drive](https://docs.google.com/presentation/d/1LMYKaG61Tj1bREamhy2Mn-OinHza-Z8ewCVJenTj3BM/edit?usp=sharing); anyone should be able to edit

@terraref/developers please comment / revise

**Comment by max-zilla** [comment]
Here is [my own mockup of the overall workflow](https://drive.google.com/file/d/0B42lleyRvKnlZGJFNENRRjctd2M/view?usp=sharing) I created to help my own understanding after our meeting last week. This might not be perfect but perhaps it could be a useful diagram for the presentation.

The 3rd slide has a few questions that we don't necessarily need to answer before Friday.

**Comment by yanliu-chn** [comment]
I'd like to clarify a few things:
- The Jupyter component we discussed last week is a technical piece we will need time to develop. It is different from the Jupyter demo defined in the demo workflow.
- That being said, the significance of the Jupyter demo, from implementation point of view, is merely installing a Jupyter docker along with Clowder on Nebula and share a file system.
- The demo workflow in my understanding is: 
  - upload an image file by using the Clowder UI to show the user interface of data uploading;
  - upload another image file by using the Clowder REST API to show the batch uploading capability;
  - open an uploaded file in Clowder to show the mask and chart extracted by plantcv extractor; explain the architecture of the data management system and the scalable extractor framework.

Thanks,
Yan

**Comment by dlebauer** [comment]
@max-zilla I've combined your slides with Yan's earlier [architecture draft here](https://docs.google.com/presentation/d/1LaOI3ESTFwn7b8x5oWZcdOWBLsCh2v4F7yqgQ836etU/edit?usp=sharing) to keep the ideas in one place. 

@yanliu-chn you are correct about the minimum requirement for the demo. It will also be good to demonstrate pushing via the API.
