### ISSUE TITLE
Sensor Fusion

### ISSUE THREAD

**Issue by solmazhajmohammadi** [terraref/computing-pipeline#121]
Overlaying the data coming from the stereo-vis camera, hyperspectral and 3D scanner. 
All the data separately needs to be stitched/registered and georefrenced. Currently working on rigid object and plants movement/ growth is not considered yet.

**Comment by rachelshekar** [comment]
Do we need an implementation of 3D-RGB on clowder? This needs to be corrected; the scanners run at separate times so the scale is off. Or should I just focus on 3D reconstruction from RGB. - Solmaz

**Comment by dlebauer** [comment]
@solmazhajmohammadi what is the status of this issue?

**Comment by max-zilla** [comment]
Relates to:
- IR data
- 3D data
- RGB data

Build estimated model from RGB data and use to correct 3D point cloud @solmazhajmohammadi does that sound correct?

**Comment by dlebauer** [comment]
@solmazhajmohammadi could you please divide this issue into separate tasks and define the outcome?

**Comment by solmazhajmohammadi** [comment]
The current script is aligning the raw data from RGB and 3D scanner. Since that the scans has been done in different time, 3D data needs to be adjusted based on the RGB data.
Following steps summarize the process:

- Aligning 3D and RGB (Done)

- 3D reconstruction from Stereo pair (In progress)

- Correct the point cloud data based on the 3D data from stereo camera (In progress)

IR and Stereo data is collected at the same time so corrected point cloud can be used to align the  IR data as well.

**Comment by dlebauer** [comment]
@solmazhajmohammadi what is the output of aligning two datasets? Will there be an adjustment to the coordinate systems of these data products? A new data product? Could you create a new GitHub issue for the steps required to add these algorithms to the pipeline?

**Comment by rachelshekar** [comment]
dependent on #224

**Comment by dlebauer** [comment]
closing since we currently have no plans to pursue a sensor future data product
