### ISSUE TITLE
Verify the organization of logger data before updating

### ISSUE THREAD

**Issue by FlyingWithJerome** [terraref/computing-pipeline#122]
@dlebauer @solmazhajmohammadi @TinoDornbusch @czender 
Hope I refer to the correct people:-)

In issue #116 Professor Zender, Dr. LeBauer and I discussed the errors raised by the EnvironmentalLoggerAnalyser.py in hyperspectral. We found that the organization of the environment logger data had been largely changed (possibly since 06.01); some data had been repositioned and reorganized. (e.g. wavelength and spectrum are in lists, sensor readings are no longer in the top level) The new logger data are not compatible with EnvironmentalLoggerAnalyser.py and thus we built a new script to deal with them. 
However it is neither user-friendly nor convenience in developing the hyperspectral workflow to have many versions of converters. It would be a good idea to discuss a stable format of the logger data and please check the format of new JSONs with EnvironmentalLoggerAnalyser.py before each update in the future.

There are two versions of EnvironmentalLoggerAnalyser.py in hyperspectral now:  [https://github.com/terraref/computing-pipeline/blob/master/scripts/hyperspectral/EnvironmentalLoggerAnalyser(pre_060116).py](url) will deal with the old environment logger data;
[https://github.com/terraref/computing-pipeline/blob/master/scripts/hyperspectral/EnvironmentalLoggerAnalyser.py](url) will deal with the current version of environment logger data (under construction).

I would be glad to answer any questions related to these scripts.

**Comment by solmazhajmohammadi** [comment]
@FlyingWithJerome I checked the xml files in the gantry system, it has not been modified since 5/23.  Markus Radermacher might be able to direct the issue.

**Comment by dlebauer** [comment]
@FlyingWithJerome sorry - @czender requested this change in reference-data#26 because it to make it easier and faster. We can consider it fixed now.

The neat thing about Git is you can do 

```
git tag v0.1 'old version of EnvironmentalLogger.py'
```

And then keep changing EnvironmnetalLogger.py. Don't worry about getting the extractor to work with the old versions of files. Once we get the pipeline up and running, we can go back and process the old files.

**Comment by FlyingWithJerome** [comment]
@dlebauer Thank you and yes, I agree with it. The new format reduces a huge number of codes.

**Comment by max-zilla** [comment]
@FlyingWithJerome do you think we're OK to close this issue?

**Comment by FlyingWithJerome** [comment]
Yes, I will close this issue.
