### ISSUE TITLE
Combine "live data" and "Maricopa" spaces in Clowder

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#125]

**Comment by max-zilla** [comment]
@robkooper last week we discussed and you recommended getting list of all datasets in space using API and looping through to assign to other space.

apparently we do not have a /api/spaces/listDatasets endpoint or anything to that effect. it would only take an hour or so to implement, do you know if anyone else has worked on this? if not, I will implement and create a pull request so it can hopefully be included in upcoming master push.

'Live Data' has 180k+ datasets (it is being written from ROGER) while Maricopa has 35k (it was the older space). I would merge Maricopa into Live Data, delete Maricopa, and rename Live Data to indicate it is from Maricopa Field Scanner.

**Comment by dlebauer** [comment]
Please transfer permissions too. Could you keep the Maricopa name instead of 'live data'?

**Comment by robkooper** [comment]
This is task https://opensource.ncsa.illinois.edu/jira/browse/CATS-545 in clowder. I have assigned this issue to you @max-zilla

**Comment by max-zilla** [comment]
Pull request created.

**Comment by max-zilla** [comment]
Clowder is ready to execute this, but I'm going to wait another few days until the Globus backlog is more relaxed because this will be database intensive.

**Comment by max-zilla** [comment]
Will do this process first thing next week. With help from @robkooper we will:
- temporarily stop pipeline and make new dump of database
- update database pointers for existing files to adhere to new Globus directory structure
- change ownership of previously transferred MAC files from Max to Maricopa Site
- merge these two spaces

**Comment by max-zilla** [comment]
@robkooper is there a regular dump of the production Mongo instance on Roger? i didn't see one in /backup but I want to pull one down to work out the proper queries here.

**Comment by robkooper** [comment]
Should be in roger/backup/mongo/clowder

**Comment by max-zilla** [comment]
Done.
