### ISSUE TITLE
Reprocessing of files after new calibration

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#127]
Discussion from email chain regarding how new calibration files are handled.

@jdmaloney @dlebauer @solmazhajmohammadi 

From @rjstrand:
New calibration files arrived from the 3D camera manufacturer in the past week or two.  It is possible that they started batch re-processing of the raw 3D data collected previously.

The Globus transfer system monitors FTP logs for files being moved onto the gantry cache server to know what to transfer to Illinois. In this process, some changes to .ply files were not recognized in the FTP logs and thus were not transferred - this is an unanticipated manner of file update. 

Generally, we probably shouldn't be replacing the original raw files whenever a new calibration file arrives. I create this issue so we can discuss as a group but we must make sure that changes on the gantry side correspond to expected pathways for Globus -> Illinois.

**Comment by markus-radermacher-lemnatec** [comment]
Yes I did start the ply files calculation around the 1st of July.
Therefor I deleted the directory gantry_data/LemnaTec/MovingSensor/scanner3DTop with all its content (the ply files where wrong anyway). That triggered a fresh ply calculation that took round about 20s for each single scan and may have taken several days.

Right now the ply calculation workflow still needs to be regarded as preliminary and works like follows:
* raw data from the scanner is stored in gantry_data/LemnaTec/3DScannerRawDataTmp/scanner3DTop
* this folder and the target folder gantry_data/LemnaTec/MovingSensor/scanner3DTop are frequently polled and if new folders are present in the source folder a ply calculation is triggered
* for the ply calculation all raw data files are copied to the ply worker program running on the main control PC in the gantry, There the ply files are calculated and all files (ply and raw) are copied to the target folder
* the step of deleting the original raw data in the source folder is still disabled, until this workflow has proven to be reliable

Right now the feasibility of the ply files still needs confirmation (Solmaz, I guess that is up to you). Up till then you should regard them as temporary.

**Comment by dlebauer** [comment]
@markus-radermacher-lemnatec why is the ply workflow run before transfer rather than at NCSA? Is this a special case?

**Comment by dlebauer** [comment]
@markus-radermacher-lemnatec any ideas how these files got on the server if not by FTP?

**Comment by markus-radermacher-lemnatec** [comment]
The core calculation is done by a program shipped by the 3D scanner manufacturer (Fraunhofer). This program is protected by a hardlock key and right now there are only keys available on the gantry PCs.
But in principle it is possible, but with the disadvantage, that changes in the 3D scanner hardware setup also make changes in the ply worker config files nessessary, which might be missed, if those two steps are locally separated.

**Comment by markus-radermacher-lemnatec** [comment]
-> any ideas how these files got on the server if not by FTP?

No, LemnaTec accesses the storage server only through the FTP access.

**Comment by rachelshekar** [comment]
@max-zilla and @jdmaloney : updates?

**Comment by solmazhajmohammadi** [comment]
@max-zilla @jdmaloney Do you think that deleting the data might solve the problem? Or maybe we can create a new folder and generate the missing files in the new folder?

**Comment by jdmaloney** [comment]
@solmazhajmohammadi @max-zilla No.  I have given Max a list of files that can be manually queued for transfer.  @max-zilla let me know if something is a blocker on that.  Rewriting data on the cache is what we don't want to do, so let's avoid anything that involves that.  I did check through and saw all new files are on the cache-server so we should leave those as they are.

**Comment by solmazhajmohammadi** [comment]
So, East scanner data looks good, but west camera needs to be recalibrated. We might need to restart the ply worker and regenerate new pointclouds some time soon. 
What is the safe way to deal with the new data?

**Comment by smarshall-bmr** [comment]
@solmazhajmohammadi I have the West scanner as being correct. Can you confirm that? I had it backwards myself for a while.

**Comment by jdmaloney** [comment]
@solmazhajmohammadi If you're going to reprocessing old data, then the best way is to write out the new files with a new file name so that the original files don't get modified and stay on the system. Something like ${original_file_name}.reproc${date}.bin so that way we know what the original file was that this was a revision of, and what date the revision was done (so if we do multiple revisions we can track them).

**Comment by solmazhajmohammadi** [comment]
@jdmaloney  just to be clear, old data would not be useful after the new calibration file is applied and probably they need to be deleted from cache server also. 

@smarshall-bmr Check my email that has been sent this morning. 
In all the scan that I have access, east camera is off. If you have any other data please send it to me via wetransfer.com
Direction setting needs to be corrected based on the scanning direction. So it is possible to see that west camera is failing if the scanning direction is from east to west.

**Comment by max-zilla** [comment]
@jdmaloney started the transfer on the current list of files.

**Comment by markus-radermacher-lemnatec** [comment]
Currently all 3D scan are reprocessed with new settings to avoid the skew.
The supposed naming is not supported by the ply worker, instead the following target folder has been used:
[cid:image001.png@01D1ED9D.ACD25950]


Von: JD Maloney [mailto:notifications@github.com]
Gesendet: Montag, 25. Juli 2016 18:22
An: terraref/computing-pipeline
Cc: Markus Radermacher; Mention
Betreff: Re: [terraref/computing-pipeline] Reprocessing of files after new calibration (#127)


@solmazhajmohammadi<https://github.com/solmazhajmohammadi> If you're going to reprocessing old data, then the best way is to write out the new files with a new file name so that the original files don't get modified and stay on the system. Something like ${original_file_name}.reproc${date}.bin so that way we know what the original file was that this was a revision of, and what date the revision was done (so if we do multiple revisions we can track them).

**Comment by jdmaloney** [comment]
@markus-radermacher-lemnatec Looks good, we see the files coming in, they're already arriving here at NCSA.  Thanks for redirecting the output!

**Comment by max-zilla** [comment]
@jdmaloney think we can close this?

**Comment by jdmaloney** [comment]
@max-zilla Yes, as long was we make sure that all future reprocessing does not over write existing data.
