### ISSUE TITLE
Some hyperspectral images (e.g., 20160707) missing metadata and frameindex files

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#129]
### Description

There are no metadata for 20160707, 20160630 hyperspectral images. 

These break our hyperspectral workflow. 

### Context

We already have pipeline writing to logstash using pipeline. Need to incorporate these into pipeline / globus transfer monitors?

### Further Suggestions / Request for Feedback   

What are these for?

More generally, how should missing data / errors be handled?

* Should extractor only run if all files are there?
* how to add info to existing log?

**Comment by FlyingWithJerome** [comment]
There are 3 critical files for JsonDealer.py: X_frameIndex.txt, X_metadata.json and X_raw.hdr; missing anyone of them would raise error or export a broken file. Right now our solution is the file checking function in JsonDealer.py in Hyperspectral Workflow: It will terminate the module when files are missing and print out a list of them like this:
`[jiarunm@cg-gpu01 hyperspectral]$ python JsonDealer.py $NEWJSON ~
One or more important file(s) is(are) missing. Program terminated:
edfbb37b-26cc-4a6f-8064-303046d14829_metadata.json is missing
edfbb37b-26cc-4a6f-8064-303046d14829_frameIndex.txt is missing`

**Comment by smarshall-bmr** [comment]
Is there any indication of why metadata wasn't included in these files? Is it for a series of dates or interspersed?

**Comment by czender** [comment]
@smarshall-bmr Good question. When we get an image, but incomplete metadata, is there something (besides fail) that the hyperspectral workflow should do?

**Comment by czender** [comment]
No one (including me) seems to have a suggestion for doing something besides failing when files are missing. In the past month we have made both the workflow scripts and the extractor better at diagnosing missing files, and this capability will improve as we encounter more anomalous situations. Since there is nothing else concrete to do now, I am closing this issue.
