### ISSUE TITLE
Ensure that PlantCV runs in Clowder

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#13]
TODO:
* [x] commit code to Clowder or PlantCV repository 
  * for PlantCV, I made a fork here: https://github.com/terraref/plantcv
  * [PlantCV extractor is in Clowder repo](http://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/extractors-plantcv/browse)
* [x] Document end-user functionality
  * some documentation is in the extractor [README](http://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/extractors-plantcv/browse/README.md)
* [x] commit plantcv docker file / script (push to dockerhub or similar repository?)
* [x] integrate in nebula
* [x] test sample input images

**Comment by rachelshekar** [comment]
- Need to be able to reproduce PlantCV worklflow from tutorial and embed on Clowder
- Use perimeters from tutorial. These can be changed using Jupiter later.

Plant CV perimeter settings work for the Danforth system only.  We will focus on this for now.

**Comment by rachelshekar** [comment]
Ensure that any two steps work - like object shape attributes (height)

**Comment by dlebauer** [comment]
1st step is mask. Second is analysis

**Comment by yanliu-chn** [comment]
plantcv extractor coding has been done. will create three issues this week to get it into the prototype framework:
- merge source code to dockerfile and create extractors-plantcv
- integrate in nebula
- test sample input images

**Comment by dlebauer** [comment]
Here is an example of plantcv running in Clowder: http://141.142.208.144/clowder/files/564214dce4b086fa6db9104f

TODO:
* [ ] commit code to Clowder or PlantCV repository (for PlantCV, I made a fork here: https://github.com/terraref/plantcv)
* [ ] Document end-user functionality

**Comment by rachelshekar** [comment]
* [ ] pull code

**Comment by dlebauer** [comment]
@robkooper I think the remaining task before closing this issue is to merge the pull request for the PlantCV docker file
