### ISSUE TITLE
TERRA ref architecture

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#132]
Please update this versions of the slides with TERRA-REF consistent design.

https://docs.google.com/presentation/d/1be6d12byKo59On--NZHKcRAoh9K-dOQeI23sUJQcgiA/edit?usp=sharing

I’m not sure what the globus connection is (are you just saying you use globus for transfer?) and how the user interacts with BETYdb (it has a separate GUI, right?)

**Comment by jdmaloney** [comment]
@rachelshekar Yep, just saying that the transfer protocol is Globus, the detailed path breaks down the bandwidth and service providers that are moving data between the locations.  I proof read slide 2 and it looks good to me, I don't see any technical things that need corrected.  Awesome diagram too, it looks nice!

**Comment by rachelshekar** [comment]
@max-zilla : please comment on/edit slides - especially 3 and 4.

**Comment by max-zilla** [comment]
@rachelshekar I have revised the deck a bit.

- cleaned up slide 1 KSU box 
- Revised Slide 3. I duplicated the original just in case, but updated to reflect the Globus pipeline we are going to use for Danforth.

For slide 4, there were some discrepancies between what I interpreted the extractors to be and who was assigned them.
  - Jerome working on EnvironmentalLogger -> NetCDF extractor: https://github.com/terraref/computing-pipeline/issues/115
  - Xingchen working on Hyperspectral -> NetCDF extractor:
https://github.com/terraref/computing-pipeline/issues/81
  - Pless working on Binary -> JPEG/TIFF conversion extractor:
https://github.com/terraref/computing-pipeline/issues/64
  - Also the full-field mosaic: https://github.com/terraref/computing-pipeline/issues/85

I didn't have anything yet for the NIR/SWIR portion.

Please let me know what you think of the updates...
