### ISSUE TITLE
Complete Danforth->NCSA pipeline

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#136]
PlantCV extractor is now ready V1. 

In this branch:
https://github.com/terraref/computing-pipeline/tree/Danforth-PlantCV-globus-mods

I have modified Noah's upload script to work with my Globus monitor script currently deployed in Maricopa. Need to polish/test it and confer with @nfahlgren but it's close to ready. This will let us stand up full pipe.

**Comment by max-zilla** [comment]
@nfahlgren and I are having a call today to go over my proposed changes.

Action items for this rollout, which I anticipate happening after we have migrated the existing MAC pipeline to the new Roger directory structure (#137):

- we should create a unique Globus account for the transfer from Danforth -> NCSA. Can use an existing account.
- map that Globus account on ROGER side to a unique Clowder account for Danforth, this will let us tell who is responsible for uploading the files.
- we will work w/ @jdmaloney to make sure these accounts have the necessary permissions to complete the Globus transfer.

So far, the MAC pipeline has used my own Globus account and Clowder account to upload the data. We should create a similar Globus+Clowder user that is uniquely associated with the MAC data source.

Eventually KSU will also get a similarly unique pair.

**Comment by robkooper** [comment]
@maxzilla We really should be using something else than your account for uamac. Best is to have an account for each site so it is easy later to find the data from a site in clowder. We can find a way later this week to change the ownership of all file, datasets and collections.

**Comment by max-zilla** [comment]
@nfahlgren the extractor is now running. I'd like to get a set of snapshots on my laptop so I can finish developing the Danforth pipeline code that we can deploy - so I can get the snapshots writing to the correct raw_data directories on Roger, etc. 

What do you think the best way to accomplish this is? The snapshots on the clowder-dev instance are in Mongo so not the easiest way to fetch them as they were originally. Can I get access to danforth#gridftp-ddpsc Globus endpoint to grab a chunk from there? Did you upload a bunch to Box or something I'm forgetting? Thanks.

**Comment by nfahlgren** [comment]
@max-zilla I'm going to create a user account for you on our infrastructure so you can log into our Globus endpoint. Then we can add some sample data to your home directory for testing. Let me know what username you would like and I will send you a temporary password.

**Comment by max-zilla** [comment]
@nfahlgren you can use mburnet2 for my account (it's my username on most NCSA systems). Thanks!

**Comment by nfahlgren** [comment]
@max-zilla sent you an email with the details

**Comment by max-zilla** [comment]
Thanks @nfahlgren , I was able to login via Globus to that endpoint. If you put some data in /home/mburnet2 I should have access now.

**Comment by nfahlgren** [comment]
@max-zilla do you just want some snapshot folders, or do you want the whole pilot experiment folder including the SnapshotInfo.csv file? And/or I can make a smaller sample set including the CSV file.

**Comment by max-zilla** [comment]
@nfahlgren the whole pilot experiment w/ CSV file is fine, if that's easy/feasible.

**Comment by nfahlgren** [comment]
@max-zilla I added a link to the data, let me know if it doesn't let you access it for some reason.

**Comment by nfahlgren** [comment]
@max-zilla the data set is 79GB, FYI

**Comment by max-zilla** [comment]
@nfahlgren cool, I can see it.

I'm at 300/500 GB on my laptop and I already filled it up once with stereoTop data last week, so let's give it a try :)

**Comment by max-zilla** [comment]
@jdmaloney on Roger, I think it would make sense to have:
```
/sites/danforth/raw_data/pilot_data
```
...and we can transfer the new data sent via Globus to
```
/sites/danforth/raw_data/snapshots
```
...to differentiate those sets. @nfahlgren what do you think about that? 

Also, part of what I'm going try to implement here is checking the metadata for a timestamp for the new data, so instead of snapshot123 in a long list we can have:
```
/sites/danforth/raw_data/snapshots/2016-10-01/snapshot123
```
...and so on. Reactions?

**Comment by nfahlgren** [comment]
@max-zilla I think that will work. Where would the SnapshotInfo.csv file go? There is one per experiment (collection of snapshots, like the pilot data set). Not that it has to stay like that going forward...

**Comment by max-zilla** [comment]
@nfahlgren i'll have to look at the code and how we currently use it. If need be we could introduce a different structure:
```
/sites/danforth/raw_data/snapshots/experiment123/snapshot123
```
...but another option could be modifying/generating SnapshotInfo.csv during transfer so we generate them for the dates or something. I'll know more soon.

**Comment by nfahlgren** [comment]
@max-zilla yeah, the CSV file is used by the uploader, but it's not used by the extractor (since the metadata from the file is loaded into Clowder). If that helps.

**Comment by nfahlgren** [comment]
@max-zilla the uploader also requires an experimental metadata file, I forgot to link to that, but the path is: `/home/nfahlgren/projects/lemnatec/sorghum_pilot/sorghum_pilot_ddpsc_metadata.json`

**Comment by max-zilla** [comment]
@nfahlgren yeah I thought that was the case - since my Globus transferrer will basically replace what your uploader does, I might be able to use the Snapshot.csv & ddpsc_metadata file there. Basically use some of your uploader snippets will be used in my Globus script to identify what to queue and what metadata to send with each - one idea that is similar to the way we handle other datasets would be to stick a snapshot's metadata into a metadata.json file and send that to Roger (which will put it into Clowder as well as make it accessible)

**Comment by maxzilla** [comment]
I believe you're sending emails to me accidentally. Just thought you'd want
to know.

**Comment by max-zilla** [comment]
@nfahlgren another step @robkooper alluded to - you'll want to create a Globus user for us to use - not mine or yours, but generic to the pipeline. The MAC user is called 'terraref' but you could use 'terraref_danforth' or whatever you want. But we'll need to have the credentials for that account stored in the config for the pipeline uploader services. @jdmaloney can make sure it has the necessary permissions on Roger once created.

**Comment by max-zilla** [comment]
@nfahlgren @robkooper @jdmaloney Today I have completed work (I hope) updating and testing the Globus transfer monitor for Danforth. This afternoon I am initiating the Globus transfers for the sorghum_pilot_experiment snapshots. If it's similar to downloading the data, this will probably take 16 hours or so - the PlantCV extractions will begin once the files are uploaded to Clowder, which will happen once we have worked through the last few weeks of backlogged Maricopa data. 

Noah, soon I will write up a list of action items that will happen at your end to deploy this properly. You can look over this and see if everything seems suitable or not.

**Comment by max-zilla** [comment]
**PREP**
Create/determine which Globus user will do these transfers. I will need the credentials so I can whitelist and add to the checking registry on Roger. This can be anyone but we recommend making a Globus user specific to this project for clarity.

**COMPONENTS**
- The **docker image for the monitor service**. This is the piece that will accept new lists of files, generate Globus transfers to Roger as necessary, check with the Roger service to verify when transfer completes. Using the develop branch of this repo should be sufficient.
```
/computing-pipeline/scripts/gantrymonitor/gantry_monitor_service.py
```

- The **Globus uploader script** - this is akin to Noah's previous Uploader code, reading SnapshotInfo.csv and so on, but instead of sending directly to Clowder it builds a Globus transfer list and sends it to the monitor service.
```
/computing-pipeline/scripts/plantcv/PlantcvClowderUploader_Globus.py
```

**PULLING DOCKER IMAGE**
The docker image was built using Dockerfile in https://github.com/terraref/extractors-lemnatec-indoor/tree/master/plantcv
- install docker
- ```docker pull maxzilla2/terra-gantry-monitor```

**CONFIGURATION**
The docker image hides substantial complexity in terms of dependencies, but you will need a directory locally where:
- you will put custom_config.json
- log files from monitor service will be written (../log)
- completed records of successful transfers will be written (../completed)

**custom_config.json contents**
A configuration file looks something like this. For me, if I had a folder structure like:
```
/Users/mburnette/globus/sorghum_pilot_dataset/snapshot295351/...
/Users/mburnette/globus/sorghum_pilot_dataset/SnapshotInfo.csv
/Users/mburnette/globus/sorghum_pilot_dataset/sorghum_pilot_ddpsc_metadata.json
```
I would define my custom configuration file to point to the necessary locations:
```
{
  "log_path": "/home/gantry/data/log",
  "completed_tasks_path": "/home/gantry/data/completed",

  "gantry": {
    "incoming_files_path": "/home/gantry/snapshots",
    "deletion_queue": "",
    "ftp_log_path": "",
    "directory_whitelist": ["/Users/mburnette/globus/"] <<<<<<
  },

  "globus": {
    "source_path": "/Users/mburnette/globus", <<<<<<
    "delete_path": "",
    "destination_path": "danforth/raw_data",
    "source_endpoint_id": "DANFORTH_GLOBUS_ENDPOINT_ID", <<<<<<
    "destination_endpoint_id": "403204c4-6004-11e6-8316-22000b97daec",
    "username": "DANFORTH_GLOBUS_USER", <<<<<<
    "password": "DANFORTH_GLOBUS_PW" <<<<<<
  },

  "ncsa_api": {
    "host": "http://141.142.170.137:5454",
    "api_check_frequency_secs": 30
  }
}
```
I put <<<<<< next to the parameters that will change in your instance. The paths with /home/gantry can be IGNORED as those refer to locations inside the docker container. destination_path is the destination root on Roger.

**EXECUTE STACK**
For example, on my laptop:
- I am user mburnette with ID 501
- my sorghum_pilot_dataset directory is in /Users/mburnette/globus/sorghum_pilot_dataset
- I want to write log output to a /monitor_logs directory under /globus

First, we run the monitor service using the docker container and mounting our desired paths:
```
docker run -p 5455:5455 -e USER=mburnette -e USERID=501 \
-v /Users/mburnette/globus/monitor_logs:/home/gantry/data \
-v /Users/mburnette/globus/sorghum_pilot_dataset:/home/gantry/snapshots \
-v /var/log:/var/log \
maxzilla2/terra-gantry-monitor
```

...this creates 3 mounts (the -v Volume flag):
- your desired log path, mapped to Docker container's /home/gantry/data
- your folder containing experiment snapshots. mapped to Docker container's /home/gantry/snapshots
- your /var/log, mapped to /var/log
...allowing logs to appear in your desired log path outside Docker.

You can use ```-e USER=``` and ```-e USERID=``` to determine which user on your system will be used to write log files, etc.

**SEND FILES**
Now you can call the uploader script in a similar fashion as before, only now you just need to feed it a directory of snapshots and a metadata file. 
```
python PlantcvClowderUploader_Globus.py -d "/Users/mburnette/globus/sorghum_pilot_dataset" -m "/Users/mburnette/globus/sorghum_pilot_dataset/sorghum_pilot_ddpsc_metadata.json"
```
Note that if your directory for snapshots changes, you'll need to update custom_config as well (directory whitelist and source path) so the files end up in the correct locations on Roger.

Please don't execute these without checking with me, but I think these are the basic steps.

**Comment by nfahlgren** [comment]
@max-zilla when you say Globus user, do you mean a Globus ID and/or a local user account on apollo?

**Comment by max-zilla** [comment]
@nfahlgren Globus user, i.e. the user who will perform the Globus transfers. We are using the 'which Globus account made this transfer?' as the way to know which Clowder user should upload the data into Clowder, and for logging purposes.

**Comment by nfahlgren** [comment]
@max-zilla do you have time tomorrow to have a phone call to get the monitor going? There are a couple parts I could use some advice on.

**Comment by max-zilla** [comment]
@nfahlgren sure. just shoot me an email, i should be around all day.

**Comment by dlebauer** [comment]
@nfahlgren does it make sense for the method be called 'PlantCV' and the citation 'Fahlgren et al 2015'?

@max-zilla can you update the insert script for the PlantCV extractor to add 'PlantCV' as the method for these? The SQL equivalent is: 

```sql
update traits set method_id = 6000000001 where citation_id = 6000000003;
```

**Comment by max-zilla** [comment]
@dlebauer  I've updated the script to add a column 'method' at the end with value 'PlantCV'. will deploy update now.

@gsrohde let me know if I should be sending method_id = 600000000001 instead, but if Bety throws errors on the API upload I guess i'll know sooner.

**Comment by max-zilla** [comment]
@gsrohde I must be missing something:

```
  "errors": {
    "schema_validation_errors": [
      "Element 'method': Missing child element(s). Expected is ( citation ).",
```

for Method = "PlantCV"

I have citation_author, _year, _title in other columns.

**Comment by dlebauer** [comment]
@maz-zilla the citation is different (data gets Fahlgren etal 2016 unpublished; method is Fahlgren et al 2015)

**Comment by max-zilla** [comment]
@dlebauer I'm not quite following. The error message seems to suggest I need a 'citation' column in the CSV - but #33 only lists citation_author, _year, _title and _doi as valid fields.

Here's what's going in them now:
```
- citation_author = Fahlgren, Noah
 - citation_year = 2016
 - citation_title = Unpublished Data from Sorghum Test Runs
```
...so that seems to be the 'data gets Fahlgren etal 2016 unpublished' part of your comment.

But if 'method is Falhgren et al 2015' then do I need a "citation" column in the CSV as well? @gsrohde can you help me sort that out?

**Comment by gsrohde** [comment]
@max-zilla Unfortunately (confusingly), the error message you are seeing pertains to XML uploads.  All upload formats are converted to XML internally, so the error message you are seeing comes from the post-conversion stage.  CSV files should only contain `citation_*` columns.

**Comment by gsrohde** [comment]
@dlebauer Are you saying the citation for the trait datum and the citation connected with the method are different?  If so, I may not have accommodated this case.  I'll have to check.

**Comment by dlebauer** [comment]
@gsrohde different citations on data and methods is the standard case; having the same citation would be an exception. However we can require methods.name to be unique and sufficient to identify a record in the methods table so stating a method should _not_ require a citation.

**Comment by dlebauer** [comment]
To clarify methods.citation_id must be not null and point to a record in citations. However only the method name should be an option in the insertion API.

**Comment by gsrohde** [comment]
@dlebauer, @max-zilla: I will have to make a few changes to the API code.

@dlebauer There is, fortunately, only one violation of the uniqueness condition for methods.name in `ebi_production`.

**Comment by nfahlgren** [comment]
@max-zilla working on starting the gantry-monitor docker service, pointed at a small test dataset (one snapshot). I ran:

```
sudo docker run -p 5455:5455 -e USER=nfahlgren -e USERID=501 \
-v /home/nfahlgren/projects/lemnatec/test/monitor_logs:/home/gantry/data \
-v /home/nfahlgren/projects/lemnatec/test:/home/gantry/snapshots \
-v /var/log:/var/log maxzilla2/terra-gantry-monitor
```

and had two errors:

```
/usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.restful is deprecated, use flask_restful instead.
  .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
  File "/home/gantry/gantry_monitor_service.py", line 1072, in <module>
    os.makedirs(config["log_path"])
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
...no custom configuration file found. using default values
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/gantry/data/log'
```

The permission error might have to do with the permissions on the monitor_log directory, but not sure about the Python error.

**Comment by max-zilla** [comment]
@nfahlgren I think what you need to do is add a custom_config.json file to your /monitor_logs directory. This will get mounted into docker container at /home/gantry/data and loaded.

I think you roughly want this:

**custom_config.json**
{
  "log_path": "/home/gantry/data/log",
  "completed_tasks_path": "/home/gantry/data/completed",

  "gantry": {
    "incoming_files_path": "/home/gantry/snapshots",
    "deletion_queue": "",
    "ftp_log_path": "",
    "directory_whitelist": ["/home/nfahlgren/projects/lemnatec/test/"]
  },

  "globus": {
    "source_path": "/home/nfahlgren/projects/lemnatec/test",
    "delete_path": "",
    "destination_path": "danforth/raw_data",
    "source_endpoint_id": "e4c4e5f2-c14d-11e5-9a1f-22000b96db58",
    "destination_endpoint_id": "403204c4-6004-11e6-8316-22000b97daec",
    "username": "terrarefdanforth", 
    "password": "DANFORTH_GLOBUS_PW"
  },

  "ncsa_api": {
    "host": "http://141.142.170.137:5454",
    "api_check_frequency_secs": 30
  }
}
I put <<<<<< next to the parameters that will change in your instance. The paths with /home/gantry can be IGNORED as those refer to locations inside the docker container. destination_path is the destination root on Roger.
- the source Globus endpoint ID, i used ddpscbioinfo#apollo
- put your Globus user but not password - **put the password in when you create the file**

For the second error, is there a /log subdirectory under /monitor_logs on your machine? do you have access to it? that's the one it's trying to hit with Permission denied there. That's where it wants to write the various log files.

**Comment by nfahlgren** [comment]
@max-zilla closer. It's running but not finding the custom_config.json file (now in /monitor_logs).

```
/usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.restful is deprecated, use flask_restful instead.
  .format(x=modname), ExtDeprecationWarning
...no custom configuration file found. using default values
2016-11-03 22:24:15,892 INFO    : gantry - - loading data from /home/gantry/data/log/active_tasks.json
2016-11-03 22:24:16,915 INFO    : gantry - - loading data from /home/gantry/data/log/pending_transfers.json
2016-11-03 22:24:17,921 DEBUG   : gantry - - tidying up pending transfer queue
2016-11-03 22:24:17,921 INFO    : gantry - - loaded data from active and pending log files
2016-11-03 22:24:17,922 INFO    : gantry - - 0 pending files
2016-11-03 22:24:17,923 INFO    : gantry - - 0 active Globus tasks
2016-11-03 22:24:17,923 INFO    : gantry - - generating auth token for globus_username
Traceback (most recent call last):
  File "/home/gantry/gantry_monitor_service.py", line 1097, in <module>
    activateEndpoints()
  File "/home/gantry/gantry_monitor_service.py", line 462, in activateEndpoints
    generateAuthToken()
  File "/home/gantry/gantry_monitor_service.py", line 452, in generateAuthToken
    password=config['globus']['password']
  File "/usr/local/lib/python2.7/dist-packages/globusonline/transfer/api_client/goauth.py", line 87, in get_access_token
    raise GOCredentialsError()
globusonline.transfer.api_client.goauth.GOCredentialsError: Wrong username or password
```

**Comment by max-zilla** [comment]
@nfahlgren sorry, i didn't check the filename when I sent you that.

The file should be called **config_custom.json** (i flipped the two parts) Sorry about that!

**Comment by nfahlgren** [comment]
@max-zilla awesome, that worked! How should we proceed with testing?

**Comment by max-zilla** [comment]
@nfahlgren sweet.
next step is to try and send your snapshot:
```
python PlantcvClowderUploader_Globus.py -d "/home/nfahlgren/projects/lemnatec/test" -m "/home/nfahlgren/projects/lemnatec/test/sorghum_pilot_ddpsc_metadata.json"
```

replace with your JSON file if the name is different. 

**However let's hold off a few more hours**, @jterstriep might be testing some extractors on Roger so I have the NCSA side of the pipeline offline right now so it doesn't trigger them accidentally.

I'll check with him but I should be able to start it back up later today.

**Comment by max-zilla** [comment]
@nfahlgren I'm putting the pipeline back up, so if you want to test this now you can. No worries if you want to wait until Monday.

**Comment by nfahlgren** [comment]
@max-zilla I got this error:

```
Traceback (most recent call last):
  File "PlantcvClowderUploader_Globus.py", line 279, in <module>
    main()
  File "PlantcvClowderUploader_Globus.py", line 129, in main
    send_files_to_globus_api(json.dumps(globus_transfer_object))
  File "PlantcvClowderUploader_Globus.py", line 275, in send_files_to_globus_api
    requests.post(api_url, data=transferobject)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.99.100', port=5455): Max retries exceeded with url: /files (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x2942f50>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by max-zilla** [comment]
Looks like the uploader script can't communicate with the docker service API - that's the 192.168.99.100:5455 IP it references when it says 'connection refused'. 

That IP is here in the script:
https://github.com/terraref/computing-pipeline/blob/master/scripts/plantcv/PlantcvClowderUploader_Globus.py#L265

we probably just need to update to whatever the correct docker ip address is on your system.

**Comment by nfahlgren** [comment]
@max-zilla I tried changing the docker service configuration so that it would give the container the same IP address you are using, but after trying some things I think that's only possible if I create a custom network for the container. For now I just edited the script as you suggested (we could make a flag to control the API address).

I'm running into one last (I think) problem. Our Globus endpoint requires authentication against the local LDAP system and I think that's blocking the monitor from starting the transfers:

`2016-11-06 00:23:19,996 ERROR   : gantry - - Globus transfer initialization failed for ddpscIndoorSuite - 2014-06-03__13-02-56-453 (503: NoCredException (409 Conflict): Credentials are needed for 'ddpscbioinfo#apollo')`

**Comment by max-zilla** [comment]
@nfahlgren yes, this is the final piece that we still handle manually at Maricopa. I have an issue to resolve this but hasn't been a priority yet:
https://github.com/terraref/computing-pipeline/issues/105

I think you just need to"
1.  go to www.globus.org and login as the terrarefdanforth user
2. Click 'Endpoints' at the top and find the ddpscbioinfo#apollo endpoint. It should say 'not activated' or similar under 'credential'.
3. Click 'not activated' then click 'Reactivate Endpoint'
4. Enter the username + password of the user account on your server (NOT the terrarefdanforth globus user, but local account) - @jdmaloney might be able to help if you aren't sure which account to use or how to assign one
5. Click 'advanced' and enter the hours you want to auth for. I just put 9999 but it has a max limit of 1 week - at Maricopa I reauth every Monday morning. You might be able to just do this before you run the python script each time if you do it intermittently.
6. You should see activation confirmation

After that transfers should work until auth expires.

**Comment by nfahlgren** [comment]
@max-zilla I think that did it, it definitely transferred the test snapshot directory

**Comment by dlebauer** [comment]
@max-zilla and @nfahlgren what is the status here? Can it be closed?

**Comment by max-zilla** [comment]
@nfahlgren i know this is a closed issue, but next time you are going to run something with this please do a docker pull on the image first. @jdmaloney and I found a flag in the globus transfers that needed to be changed so timestamps were properly updated and I pushed it this morning.
