### ISSUE TITLE
Roger Globus directory structure

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#137]
Recent discussions have suggested a reorganization of the data on ROGER would make sense for a few reasons:
- division of raw and derived data products
- division of site (MAC, Danforth, KSU...)
- more generalized support for additional sensors and sources

The first version of the Globus monitor would expect a set of sensors under a /MovingSensor directory, and support for EnvironmentalSensor was hardcoded. This isn't sustainable and the Danforth data represents an entirely new stream.

Generally speaking, I think we'll want to:
- reorganize data so ua-mac is one folder alongside danforth, ksu, etc.
- under the site level, some division of data products. a chat with @robkooper @dlebauer and @jdmaloney led to talking about "raw data" and "derived data" sub-folders; I also liked "level0", "level1"... divisions.
- under the data product level, sensors.
- under sensors, dates.
- under dates, datasets.

Making this issue so discussion can happen leading into Thursday's meeting - @jdmaloney might have some thoughts based on our discussion earlier today.

**Comment by craig-willis** [comment]
If the data will be accessible to users via Globus, then it might also be worth considering the relationship between the directory structure, how the data is versioned, and how the directory structure relates to published DOIs.  Some of this is discussed in the doc attached to https://github.com/terraref/reference-data/issues/43.

**Comment by jdmaloney** [comment]
![uploads/27e26753-18e9-466d-97e3-27e7b5ed5370/Screen Shot 2016-08-03 at 5.33.27 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F27e26753-18e9-466d-97e3-27e7b5ed5370%2FScreen+Shot+2016-08-03+at+5.33.27+PM.png)

Proposed file tree we can talk about at tomorrow's meeting, Craig the Globus sharing with the above structure could be done out of the sites directory being the Globus root directory, allowing access to all sites, the raw_data (level 0 products), and the derived prodcuts (level 1...level N), but not the other stuff.

**Comment by max-zilla** [comment]
@jdmaloney I think that outline makes sense. Seems to be the best place to outline a bit more on what will actually happen here.
.
.
.
**how it was done before**
- on gantry, map the following directories in Docker
```
docker run -p 5455:5455 
	-v /var/log/gantrymonitor			: /home/gantry/data 
	-v /gantry_data/LemnaTec			: /home/gantry/sensors 
	-v /gantry_data/LemnaTec/ToDelete	: /home/gantry/delete/sensors 
	-v /var/log							: /var/log 
	maxzilla2/terra-gantry-monitor
```
- on Globus transfer, replace /gantry_data/LemnaTec in file paths with an empty string to get "base path"
```
/gantry_data/LemnaTec/EnvironmentLogger/2016-01-01/2016-08-03_04-05-34_environmentlogger.json
/gantry_data/LemnaTec/MovingSensor/co2Sensor/2016-01-01/2016-08-02__09-42-51-195/file.json

		VVV just base paths VVV

/EnvironmentLogger/2016-01-01/2016-08-03_04-05-34_environmentlogger.json
/MovingSensor/co2Sensor/2016-01-01/2016-08-02__09-42-51-195/file.json
```
- transfer to ROGER using that path as destination
```
ROGER Globus root: 
	/projects/arpae/terraref/raw_data/ua-mac

(root)/EnvironmentLogger/2016-01-01/2016-08-03_04-05-34_environmentlogger.json
(root)/MovingSensor/co2Sensor/2016-01-01/2016-08-02__09-42-51-195/file.json
```

This setup doesn't support the new climate data, which exists on /gantry_data/MAC (i.e. unreachable from Docker, which mounts /gantry_data/LemnaTec) and it doesn't fit the proposed ROGER folder structure outlined above.
.
.
.
**after**
- instead we should mount one level up. here, we mount /gantry_data directly to a Docker directory called /sites (so inside docker we'll have /sites/LemnaTec, /sites/MAC)
```
docker run -p 5455:5455 
	-v /var/log/gantrymonitor			: /home/gantry/data 
	-v /gantry_data						: /home/gantry/sites 
	-v /gantry_data/ToDelete			: /home/gantry/delete/sites 
	-v /var/log							: /var/log 
	maxzilla2/terra-gantry-monitor
```
- on Globus transfer, replace /gantry_data/LemnaTec in file paths with _the correct Globus destination route_. This means removing the MovingSensor distinction and the LemnaTec/MAC distinction present on the gantry for consistency:
```
/gantry_data/LemnaTec/EnvironmentLogger/2016-01-01/2016-08-03_04-05-34_environmentlogger.json
/gantry_data/LemnaTec/MovingSensor/co2Sensor/2016-01-01/2016-08-02__09-42-51-195/file.json
/gantry_data/MAC/lightning/2016-01-01/weather_2016_06_29.dat

		VVV prepare for Globus destination structure VVV

/ua_mac/raw_data/EnvironmentLogger/2016-01-01/2016-08-03_04-05-34_environmentlogger.json
/ua_mac/raw_data/co2Sensor/2016-01-01/2016-08-02__09-42-51-195/file.json
/ua_mac/raw_data/lightning/2016-01-01/weather_2016_06_29.dat
```
- transfer to ROGER using that path as destination
```
New ROGER Globus root: 
	/projects/arpae/terraref/sites

(root)/ua_mac/raw_data/EnvironmentLogger/2016-01-01/2016-08-03_04-05-34_environmentlogger.json
(root)/ua_mac/raw_data/co2Sensor/2016-01-01/2016-08-02__09-42-51-195/file.json
(root)/ua_mac/raw_data/lightning/2016-01-01/weather_2016_06_29.dat
```

@jdmaloney does this correctly show the Globus root as /sites? If you were going to make the Globus root /terraref, then the destination paths would start with /sites/ua-mac instead of /ua-mac.


These changes also mean that Danforth transfers will use similar restructuring:
```
Danforth source path 

VVV becomes VVV

/danforth/raw_data/<sensor>/<date>/<timestamp_if_needed>/files...
```
As discussed last week, <sensor> for Danforth can actually be something like <danforthIndoorSuite> or something to reflect that it is actually a constellation of several sensors, but that still allows for folder consistency.

**Comment by max-zilla** [comment]
Once we migrate over and the pipeline is up and running for this new structure, we can pause the pipeline, migrate old files to the new structure, and run a database update on Clowder so existing file pointers point to the new locations.

**Comment by max-zilla** [comment]
@jdmaloney how does this match your thinking:
1. shut down everything - FTP, MAC+Roger monitor services, etc.
2. update Globus on the gantry to mount the /gantry_data level instead of the /gantry_data/LemnaTec level
3. prep new Roger directory structure (looks like already done)
4. update Globus on Roger to mount the /terraref (or /sites, but that would not allow Globus users to access the previous data)
5. deploy new Gantry monitor service and verify proper transfer to new destination structure (LemnaTec sensor data, EnvironmentLogger, MAC lightning/weather)
6. deploy new Roger monitor service and ensure proper Clowder upload of new files; this will be delayed until we catch back up with previous tasks (will probably take another week or two but it seems to be outpacing incoming data now)
7. migrate old Roger data directories to new structure and update Clowder Mongo DB to point to updated locations - this can happen later

**Comment by jdmaloney** [comment]
@max-zilla That looks good to me, a few notes on certain steps.

2. I believe this is already happening, when I log into Globus and open the endpoint it drops me in /gantry_data and I see both Lemnatec and MAC
3. Yes, a bit of tweaking still (user directories created, double check permissions, sticky bits, etc.) but very much mostly done.
4. I need to check on how to best make the move of the Globus Endpoint on the ROGER side since it's a share on top of the ncsa#ROGER endpoint it's different than the gantry side, I'll want to know this procedure before we begin, it'll either be modifying the existing endpoint in some form, or deleting that one, creating a new one (maybe with @dlebauer 's Globus instead of mine??), and re-enabling the sharing for the current list of users.  Either way, should be doable, and yes put it at the ../../../sites level.  While yes it will temporarily obscure the current directory, we should be able to move that data over soon enough.  Putting it somewhere else would expose more files than we want, and we'd end up having to move it a third time.
7. Can this be done online with the pipeline running in terms of your code?  It's of no problem to the file system/Globus, just checking to see if this needs to be done inside or outside a pause of the pipeline.

**Comment by max-zilla** [comment]
@jdmaloney slightly edited your comment so Markdown didn't screw up your numbers.

#7 we can migrate the files with the pipeline running, it'll just mean that Clowder will have a bunch of broken links until we update its database. For updating the database we'll need to stop Clowder and probably the Roger monitor as well, but we can leave the gantry monitor running and it should be fine.

Once these steps are done I should be clear to turn on the Danforth pipeline as well.

**Comment by max-zilla** [comment]
@dlebauer @robkooper JD and I plan to make this move on Thursday.

@jdmaloney Rob agreed with your earlier suggestion - we can move the existing Roger files to the new directory structure during the same downtime on Thursday, and update the Mongo pointers later.

**Comment by max-zilla** [comment]
@jdmaloney i'm also preparing a simple script that I realized I would need last night - to go through the received-but-not-yet-uploaded-globus-xfers JSON logs on Roger and change the file paths there. These JSON files are created when a Globus task completes, and added to a queue waiting to go into Clowder. After that they are updated with a SUCCEEDED property (you can fetch the contents of them via the API anytime to check a given Globus ID's status). Since they were sent to Roger before we changed the directories but we're going to move the files they describe today, I'll need to update them so later they correctly know where the files are to send to Clowder.

**Comment by max-zilla** [comment]
Created a new user on terraref Clowder production instance.
email: terrarefglobus@ncsa.illinois.edu
first name: Maricopa
last name: Site

This will be the user shown for files coming from Maricopa. When we set up the Danforth pipeline, we will create a corresponding Danforth Site user to receive those files.

**Comment by jdmaloney** [comment]
Created Globus account with email: terrarefglobus@ncsa.illinois.edu; Globus ID: terraref@globusid.org; that email is a mailing list managed by NCSA major domo

**Comment by max-zilla** [comment]
This migration is now complete and the pipeline is back up.
