### ISSUE TITLE
Extractor to process stereo camera files into .jpg

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#138]
Email discussion with another team:

we do have some code written that processes files necessary for our algorithms, so perhaps we can upload that and start there?

The code can be found in a private repo

This repo was written with for Ubuntu so I have not tested it.

I have a slightly altered local version (I'm working on mac)
thats not on any remote repo. 

The main key thing is after the view file is compiled we simply need to run it on a source file
which the platform team should provide.

**Comment by dlebauer** [comment]
closing issue, moving to source code repository for separate project
