### ISSUE TITLE
Clowder terms of service

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#140]
https://terraref.ncsa.illinois.edu/clowder/tos

- [x] ask Erika and Nadia for feedback
- [ ] create shortened version referencing longer version
- [ ] post shortened version in documentation, other locations

**Comment by rachelshekar** [comment]
sent reminder to Erika

**Comment by rachelshekar** [comment]
@robkooper  - I just sent you the comments from Todd.  Please respond directly to him and cc me and Erica.

**Comment by rachelshekar** [comment]
@robkooper - what are you going to do?  Use the Clowder Terms of Service as is?

**Comment by robkooper** [comment]
I showed David where he can edit license. He took clowder text and data sharing and combined into a single document.
