### ISSUE TITLE
3D Scanner data shift in Z-coordinate

### ISSUE THREAD

**Issue by ZongyangLi** [terraref/computing-pipeline#148]
### Description
Here is an example of height histogram estimation using 3d scanner data:
![plot278](https://cloud.githubusercontent.com/assets/20230686/17778728/ab206ea8-652a-11e6-815a-b6fa4e9986ed.PNG)

X-axis in the diagram denotes Z-coordinates in point cloud data. Since Z-coordinates value are in the range of [-2000, 2000], we divided the histogram into 400 bins, X-axis 0 denotes Z-coordinate -2000 and X-axis 400 denotes 2000. Y-axis denotes the point count in associate range.

I guess the reason why diagram is unexpected is:
Z-coordinate shift as gantry Z position moved. Z position move from 3.615m to 3.915m, as ground plane peak shows in the diagram move from around 70 to 100.

### Another issue:
We are uncertain about Y-coordinate definition. Before July 8, Y-coordinate in "-west_0.ply" is almost from 0 to positive, but in July 9, these Y-coordinate is from around 0 to negative. To obtain a more precise plot height estimation, we might need a certain Y-coordinate definition.

**Comment by rachelshekar** [comment]
@ZongyangLi  - did you ever get this resolved?  

If not, @solmazhajmohammadi can help.

**Comment by solmazhajmohammadi** [comment]
I think the issue regarding the Z-coordinate shift is resolved. 
Future Plan: We will add it to the transformation matrix in metadata.
