### ISSUE TITLE
Check infrastructure capacity, transfer between MAC and UI/NCSA

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#16]
Find out how long it takes to transfer 3TB of data from UA. Can the infrastructure handle it?  Can the network handle it?

* this is for whole pipeline, needs to be evaluated against Roger, Nebula/ADS, campus cluster
* how long does it take from sources (UA, Danforth), how long does it take within NCSA?
* what is rate of data loss during transfer? Where / how much / how long to cache locally at AZ?
* use of Larry Smar's off-the shelf streaming system / West Coast pipeline?
* build network profile / test capacity

**Comment by dlebauer** [comment]
to be assigned to Dan Lapine

**Comment by dlapine** [comment]
Are we doing based on real world measurements or starting with theoretical estimates using the known pathways? For real world tests, I'll need access to the resources at AZ

**Comment by dlebauer** [comment]
@dlapine the goal is to make real-world measurements. I've sent an email to our collaborators at AZ to request access.

**Comment by rachelshekar** [comment]
Start with theroretical
They have I2.  100 GB - unsure if they will use this entire bandwith for this project.
Local equipment is more important

**Comment by rachelshekar** [comment]
It will take ~1 hour to move 3TB

**Comment by dlapine** [comment]
One hour is a good estimate to the first order of magnitude. Speeds to Nebula or ICC may be slower. Speeds at the Az endpoint may be slower

**Comment by dlebauer** [comment]
We will have a meeting Dec 4 with AZ team

**Comment by jdmaloney** [comment]
PerfSonar tests between UA and NCSA show up to 6Gbps of bandwidth between the two sites. Testing with MAC will have to wait until 1Gbps fiber is in place, ETA mid January 2016.  The 1Gbps link will be the bottleneck.  If we can saturate it, a 5TB data transfer will take approximate 12.5 hours.

**Comment by rachelshekar** [comment]
Some testing has been completed.  We can not test to MAC until line is in but testing for UA is done.

**Comment by jdmaloney** [comment]
Performance seems to be within expectations, transfers at this point are running at 80%+ network capacity with minimal tuning.  Closing issue.
