### ISSUE TITLE
Clowder extractor requirements

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#163]
After discussions with @robkooper and @dlebauer we are starting to migrate initial versions of extractors to separate repositories so this repo can become focused on the pipeline itself (and extractor integration) while development of underlying algorithms and extractor code can be separated. 

I've created two so far:
- https://github.com/terraref/extractors-lemnatec-indoor (plantCV)
- https://github.com/terraref/extractors-stereo-rgb (demosaic, eventually full field stitching)

In order to deploy these in a full production context, several things are necessary:
- [x] add code to PyClowder that supports configuration of a mounted path, so remote files don't need to be downloaded if a locally mounted equivalent is available. I implemented this for both download + upload in [this branch](https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/pyclowder/browse?at=refs%2Fheads%2Flocal-mount-path-downloading) that we can use
- [x] update Clowder to send full file path in RabbitMQ messages, so the extractor can perform the mounted path comparison. This is implemented in [this pull request](https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/clowder/pull-requests/987/overview).
- [x] push that Clowder code to TERRA production instance. @robkooper this is the trickiest part in some ways, because the production instance is sync'ed to Clowder master branch, which was last updated Aug 9. The conflict between only deploying stable, tested Clowder branches and being able to deploy critical updates like the one above that supports full file paths.
- [x] create a VM on Roger Kilo and give floating IP to @jdmaloney so he can create necessary mount points. then we can leverage local file path to avoid downloading co-located files.
- [x] mount data files to VM and run extractor

The local file path stuff is necessary so that we can pipe extractor outputs into the appropriate Level1 data directory instead of into a randomly assigned /tmp directory. I don't know whether it makes sense to deploy the extractors without the Clowder code update, unless we want to do another move later like we did with the recent folder restructuring.

**Comment by max-zilla** [comment]
@robkooper I will bring this up at Clowder meeting today. I think we can (at least temporarily) switch TERRA production instance to be sync'd to a different branch than master:

- create new terra_production branch that will be sync'd on 141.142.170.137 (new production VM)
- get my pull request merged into develop: https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/clowder/pull-requests/987/overview (this is necessary for the local path mapping of extractors)
- terra_production can then be develop instead of master (I think - trying to merge pull requests only into master will break things)

Once this new TERRA branch is deployed properly, we can start with the demosaic and environmental logger extractors.

**Comment by max-zilla** [comment]
@robkooper you mentioned this morning that there are no messages in RMQ right now. so does this mean that we will need to manually submit existing datasets for extraction when I deploy the demosaic extractor? is this intentional? that will also mean we have a backlog of things to generate sha512 for, etc. is the RMQ instance properly configured for terra production instance?

**Comment by robkooper** [comment]
The way clowder/rabbitmq works is that each extractor registers itself with rabbitmq. At that point it creates a persistent queue. Any new messages coming in from that point forward will be routed and can end up in that queue. If there are no extractors the messages will wait in the queue until an extractor is ready to service that queue. If the extractor has never registered itself with rabbitmq (i.e. a new extractor) the queue for that extractor will not exist and message will not be put in that queue. Once the extractor comes online it will only process new messages and not any old messages. However there is a method in clowder to have it ask to (re)run the extractor on a specific dataset/file.

**Comment by max-zilla** [comment]
The pull request for Clowder to send file paths so I am clear to get these going:
https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/clowder/pull-requests/1012/overview

Tomorrow (tuesday) I will get this code moved out to Clowder and work on getting the extractors running.

**Comment by pless** [comment]
Hi Max,
  This is amazing work that you've been doing.  Please let us know when things are on clowder and/or if there is anything we can work on in the meantime to make it easier for us to deploy subsequent extractors.  Thanks!

**Comment by max-zilla** [comment]
Processing is now underway for demosaic extractor. Example output:
https://terraref.ncsa.illinois.edu/clowder/datasets/57e3e58c4f0c2cccebc50c41

On Globus (easiest way to get in bulk) this will be under /sites/ua-mac/Level_1/demosaic - there are a few messy folders there from the deployment debugging that will be cleaned later.

Will watch this tonight to see how it goes and move onto next extractor in the morning.

**Comment by max-zilla** [comment]
Initial extractor deployed. I will close this issue and update other extractors in their respective issues.
