### ISSUE TITLE
Migrate Clowder to ROGER Kilo

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#164]
@robkooper @jdmaloney 

Tomorrow (thursday the 8th) we plan to migrate the TERRA production instance from Roger Juno to Roger Kilo. 

Checklist:
- [x] shut down Maricopa Globus pipeline. JD, we haven't yet transferred all the reprocessed 3dscanner data, but I have a record of the last one queued so we can resume there when we start back up tomorrow/Friday. This is done.

- [x] shut down Roger service that performs uploads to Clowder - Max will do this at the start of the day Thursday (this way it can keep processing files overnight)

- [x] install necessary dependencies for ROGER-side service monitor on the new Kilo VM

- [x] copy service monitor log files over to new VM (under ```/home/globusmonitor/computing-pipeline/scripts/globusmonitor/data```)

- [x] install Clowder on new VM

- [x] migrate Mongo database from Juno production instance to Kilo

- [x] perform mongo update scripts on database to update file pointers, reassign ownership. Determine if the PNG/PLY moves above also necessitate a DB update

- [x] fire up Clowder

- [x] use Clowder API loop to merge old and new Maricopa spaces in Clowder

- [x] change terraref proxy server

- [x] mount filesystem read/write instead of read-only

- [x] update MAC endpoint to point to new IP for globus API

**For later, not necessarily tomorrow**
- [ ] Move PLY files under ```/projects/arpae/terraref/sites/ua-mac/raw_data/scanner3DTop/``` into the /sites/ua-mac/Level1 directory - these are the processed 3D files. these should go in the same dataset as their PNG siblings in Clowder

- [ ] Move PNG files under ```/projects/arpae/terraref/raw_data/ua-mac/3DScannerRawDataTmp/scanner3DTop/``` into the /sites/ua-mac/raw_data directory - these are the raw files for 3D scanner. Metadata files should go here also (they might be already)

- [ ] Update Clowder database pointers to reflect these new locations

**Comment by jdmaloney** [comment]
- [ ] Move Terraref data into File Set, migration starting this afternoon (Wednesday), Max is shutting down Clowder for it

**Comment by max-zilla** [comment]
This is done. I'll move the PLY/PNG move to a new issue and close this one.
