### ISSUE TITLE
Deploy environmental logger extractor

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#165]
https://github.com/terraref/extractors-environmental
The environmental logger extractor is ready to be deployed.

- [x] create a VM on Roger Kilo to host & install dependencies

- [x] Notify @jdmaloney of VM IP so he can mount necessary directories:
- read-only: **/sites/ua-mac/raw_data/EnvironmentLogger**
- read/write: **/sites/ua-mac/Level1/EnvironmentLogger**

- [x] update extractor config to point to TERRA production

- [x] run test on a single file, then enable

**Comment by max-zilla** [comment]
@jdmaloney I have created a VM called terra-extractor-environmentlogger.

Floating IP: 141.142.170.143

reads ```/sites/ua-mac/raw_data```
writes: ```/sites/ua-mac/Level_1/EnvironmentLogger``` (not yet created)

Is that all the info you need? Not sure if we can reuse anything you did for the demosaic extractor exports on the READS side, can't remember if the mount point is the same. If you need to create a new one, the READS could be /sites/ua-mac/raw_data/EnvironmentLogger for more specificity.

**Comment by jdmaloney** [comment]
@max-zilla 

These exports have been created as well as the directory in Level_1

**Comment by max-zilla** [comment]
This extractor is deployed and running - results will accumulate in /ua-mac/Level_1/EnvironmentLogger.
