### ISSUE TITLE
Split 3d scanner PNG/PLY into raw/level1

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#168]
Moved from https://github.com/terraref/computing-pipeline/issues/164...
- [ ] Move PLY files under /projects/arpae/terraref/sites/ua-mac/raw_data/scanner3DTop/ into the /sites/ua-mac/Level1 directory - these are the processed 3D files. these should go in the same dataset as their PNG siblings in Clowder
- [ ] Move PNG files under /projects/arpae/terraref/raw_data/ua-mac/3DScannerRawDataTmp/scanner3DTop/ into the /sites/ua-mac/raw_data directory - these are the raw files for 3D scanner. Metadata files should go here also (they might be already)
- [ ] Update Clowder database pointers to reflect these new locations

**Comment by solmazhajmohammadi** [comment]
It seems that PLY files in the Level1 data still belongs to the old calibration file. 
New configuration file has applied and pointclouds are stored in the following path from 2016-04-25 to 2016-08-22: 
"LemnaTec/MovingSensor.reproc2016-8-18/scanner3DTop "

**Comment by max-zilla** [comment]
Thanks for reminder @solmazhajmohammadi , still need to finish transferring these.

**Comment by solmazhajmohammadi** [comment]
@ZongyangLi You can follow up the issue here.

**Comment by ZongyangLi** [comment]
@solmazhajmohammadi Got it, thanks!

**Comment by max-zilla** [comment]
I just queued all of these up, they should get transferred over tonight.

**Comment by solmazhajmohammadi** [comment]
Great thanks @max-zilla

**Comment by max-zilla** [comment]
I believe @jdmaloney and I have moved the remaining PLY files from raw_data into Level_1, and new PLY files should be going into Level_1. closing this isse
