### ISSUE TITLE
Use ADS for storage in nebula

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#17]
This is blocked by #5. Once the VM is up and running we will mount ADS in the VM.

**Comment by robkooper** [comment]
I will mount ADS in the filesystem for clowder on nebula.

**Comment by rachelshekar** [comment]
- [ ] mount
- [ ] test

**Comment by robkooper** [comment]
Tested both NFS and SAMBA. Problem is with the user permissions on the files. Each application needs it's own user to be able to write. Will try and use SAMBA to mount partition multiple times for each application.

**Comment by dlebauer** [comment]
what would work across the variety of storage options that we have? Roger, Campus Cluster, ADS, Blue Waters Lustre (which will be archived on tape), Nebula

**Comment by dlebauer** [comment]
do we want to use ADS? David and Rob need to discuss if this is still applicable

**Comment by rachelshekar** [comment]
Where is this @robkooper ?

**Comment by rachelshekar** [comment]
@robkooper - - can this issue be closed?

**Comment by robkooper** [comment]
We lost our free access to ADS, closing issue
