### ISSUE TITLE
Store fixed sensor metadata using JSON-LD

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#170]
If there is metadata descriptive of the sensors that will not change e.g. for an entire season, we can use JSON-LD to reference one location for that so it isn't duplicated many times and we only have one place to update.

**Comment by craig-willis** [comment]
https://github.com/terraref/reference-data/issues/54 will define the format and  method for storage.

**Comment by rachelshekar** [comment]
@max-zilla - can this be closed?

**Comment by craig-willis** [comment]
@rachelshekar I think this needs to stay open until we are actually storing the sensor metadata.  terraref/reference-data#54 will define the format and method; this will be the actual work to get it stored.
