### ISSUE TITLE
Create polygons for sites table in BETYdb 

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#174]
### Description

The spring planting plots are described in this [spreadsheet on google drive](https://docs.google.com/spreadsheets/d/1QQaWc0UaQQKfEtnSO1G2za8tKU2huC0_VYMBqm5CKAo/edit#gid=1066629008)

* the plot layout is described in the 'experimental plot plan' table, the important bits are:

| dimension | value|
|----|----|
|# rows	|32|
|# rows / plot	|2|
|# plots (2 rows ea)|	864|
|# ranges	|54|
|# columns|	16|
|row width (m) 	|0.762|
|plot length (m)	|4|
|row length (m)	|3.5|
|alley length (m)|	0.5|

I began working with these data in R. The following code uses the above dimensions to generate the points and then convert them to polygons in WKT that would be suitable for entering into the database 
([20160421_plots.csv.txt](https://github.com/terraref/computing-pipeline/files/490411/20160421_plots.csv.txt))
except that we need to 

* [ ] put them in gantry coordinate system and 
* [ ] convert them to a geographic coordinate system.
* [ ] insert them into the database
  * ultimately we need something like the follw
The integer values for 'plot' are 1-864 are associated with plots in the terraref instance of BETYdb named "MAC Field Scanner Field Plot _i_" 

Here are the sites in TERRA-REF BETYdb that we are trying to update: https://terraref.ncsa.illinois.edu/bety/sites.json
Here are the sql statements in a system that puts (0,0) at the bottom right of the field: 
[insert_site_geometries.sql.txt](https://github.com/terraref/computing-pipeline/files/490413/insert_site_geometries.sql.txt)

```r
# code in https://github.com/terraref/reference-data/blob/master/scripts/maricopa_field_metadata.Rmd
require(udunits2)
library(dplyr)
library(tidyr)
library(ggplot2)

x_origin = 0 
y_origin = 0
length = 3.5
alley = 0.5
row_spacing = 30
ranges = 54
columns = 16

row_spacing_cm <- ud.convert(row_spacing, 'in', 'm')

dx <- 2 * row_spacing_cm
dy <- length

x <- x_origin + (1:columns - 1) * dx
y <- y_origin + (1:ranges - 1) * (length + alley) 

grid <- data.frame(expand.grid(x,y)) %>% 
  transmute(plot = 1:(ranges*columns), x1 = Var1, y1 = Var2, x2 = x1 + dx, y2 = y1 + dy) #%>% 
  #tidyr::gather(key = 'lat', )

theme_set(theme_bw())
ggplot(data = grid) + 
  geom_text(aes(x1+dx/2, y1+dy/2, label = plot), size = 2) +
  geom_point(aes(x1,y1), size = 1, alpha = 0.4) + 
  geom_point(aes(x2,y2), col = 'red', size = 1, alpha = 0.4) +
  ggtitle('gantry plot layout') + xlab('x') + ylab('y')


grid2 <- grid %>% gather(key, value = x, starts_with("x")) %>% gather(key2, value = y, starts_with("y"))   %>% select(-starts_with("key"))  %>% arrange(plot) %>% setDT

library(spatstat)
library(wellknown)
write.csv(merge(grid, plots, by = 'plot'), file = '20160421_plots.csv.txt')

insert <- plots[,list(sql = paste0('update sites set geometry = ', geometry, 'updated_at = now(), where name = ', paste0("'MAC Field Scanner Field Plot ", plot, "';")))]

writeLines(insert$sql, con = file('insert_site_geometries.sql.txt'))
```

Related issues:

* https://github.com/terraref/reference-data/issues/32
* https://github.com/terraref/computing-pipeline/issues/109
* https://github.com/terraref/reference-data/issues/51

**Comment by dlebauer** [comment]
@JeffWhiteAZ or @smarshall-bmr 

1. could you please provide information for mapping these plots to the gantry (0,0) coordinates?
2. do you have similar dimensions for the second planting?

**Comment by smarshall-bmr** [comment]
https://docs.google.com/spreadsheets/d/1eQSeVMPfrWS9Li4XlJf3qs2F8txmddbwZhjOfMGAvt8/edit#gid=883764630

https://docs.google.com/spreadsheets/d/1eQSeVMPfrWS9Li4XlJf3qs2F8txmddbwZhjOfMGAvt8/edit#gid=1433617856

These are the plot locations as given in the gantry coordinate system for the first and second planting respectively. The y coordinates change a negligible amount as to the point that the y coordinates are given as the same between plantings. The x axis is offset to the north approximately 50cm for the second planting.

**Comment by tingli3** [comment]
@dlebauer I have a few questions related the R code:
1 Q1: the plot number in the picture given by ggplot2 in the R code does not match with the excel below (is it important?)
https://docs.google.com/spreadsheets/d/1QQaWc0UaQQKfEtnSO1G2za8tKU2huC0_VYMBqm5CKAo/edit
For example, the location of plot 17 is not consistent with the excel.

2 Q2: what is the correct lat lon for the four corners that we should build the projection on? I have design a projection system using the lat lon of the corners provided before. 
Location	Latitude	Longitude
S-E	33.07459197	-111.97480975
S-W	33.07459172	-111.97504692
C-W	33.07547558	-111.97504675
C-E	33.07547550	-111.97481017
N-W	33.07642747	-111.97504728
N-E	33.07642819	-111.97481064
However, I found that the corners points I used are actually the six points SW SE CW CE NW NE  in the sheet below. I am not sure what is the relationship between the three lat&lons.
https://docs.google.com/spreadsheets/d/1pTgmpf9kltYW1SHo_K51cynVTYs6-JdS6rt4usfwV10/edit

3 Q3: why the bounding box is much larger. The bounding box I got from the grid calculated in the R code is much larger than the bounding box of the corner points in the google sheet mentioned in Q2.
>boundingbox=c(min(grid$x1),min(grid$y1),max(grid$x2),max(grid$y2))
> boundingbox
[1]   0.000   0.000  24.384 215.500

4 Q4: I saw many people talking about gantry coordinates and lemnatec coordinates. I wonder what's the relationship between these different coordinates. Also, how they are related to coordinates with SW corner as (0,0) .

5 There is an example of how to add lat1 and lon1 for X1 and Y1, add lat2 and lon2 for X2 and Y2 to grid data frame using the projection I provided before.

```
require(proj4)
options(digits = 15)
x1y1=cbind(grid$x1,grid$y1)
x2y2=cbind(grid$x2,grid$y2)
proj= '+proj=tmerc +lat_0=0 +lon_0=-111.843479 +k=1 +x_0=12285.092664 +y_0=-3661028.344732 +datum=WGS84 +units=m +no_defs '
latlon1=project(x1y1, proj, inverse = T, degrees = TRUE, silent = FALSE, ellps.default="sphere")
latlon2=project(x2y2, proj, inverse = T, degrees = TRUE, silent = FALSE, ellps.default="sphere")
grid$lon1=latlon1[,1]
grid$lat1=latlon1[,2]
grid$lon2=latlon2[,1]
grid$lat2=latlon2[,2]
```
But I failed to run the code from `grid2 <- grid %>% gather(key, value = x, starts_with("x")) %>% gather(key2, value = y, starts_with("y"))   %>% select(-starts_with("key"))  %>% arrange(plot) %>% setDT` . I am not sure what that part means.

**Comment by dlebauer** [comment]
@tingli3 I answered your questions inline above

**Comment by tingli3** [comment]
@dlebauer Thank you. 

The true SW and SE lat & lon will be very important in the projection definition. If USDA is the truth lat & lon for the SW and SE, I need to update the projection based on it and make sure after projection the SW will be (0,0) and SE will be something like (2*.***, 0). Please tell me whether my understanding is correct.

However, here the coordinate system we generated using R code start at (0, 0) and ends at (24.384, 215.500). The four points given by USDA is approximately 27.5m * 110m. If that is the case, I wonder whether the four corners of the gantry plot layout should match with the 4 points of USDA. Specifically, whether the SW point of the plot1 is the SW point of USDA points and SE point of the plot16 is the SE point of USDA points, and how to handle the difference.

**Comment by dlebauer** [comment]
@tingli3 there are two different issues.

First, is to determine the coordinate reference systems. That should be covered in issue https://github.com/terraref/reference-data/issues/32. There are four (or more) points used to align the two (MAC and USDA) GPS systems. These are in concrete posts around the edge of the field. There are also points used to align the gantry coordinate system with the MAC RTK GPS.

Second is this issue, to determine the bounding boxes of the individual plots in these different coordinate reference systems. 

I will send you an email with a complete discussion of how these points were collected.

**Comment by tingli3** [comment]
@dlebauer So, what is the X and Y in the R code corresponds to ? Where is the true (0,0) ?

**Comment by dlebauer** [comment]
@tingli3 First, I apologize on behalf of all involved that this is such a mess. 

But to try and clarify, there are a three (X,Y) coordinate systems 

1. the gantry / lemnatec system that has reversed X. These are
2. the 'corrected' X,Y with (0,0) on the SW reference point. This does not yet exist, but is covered in (https://github.com/terraref/computing-pipeline/issues/109) that this would be helpful for plotting and because humans are used to X increasing to the right / East
3. the values used in the R code and experimental design. These are in relation to the corner of the planted area, which will change each season.

To map the plots (3) to the gantry (1), it is necessary to align the X,Y pairs in the R code with the X,Y measured coordinates provided by @smarshall-bmr in this spreadsheet: https://docs.google.com/spreadsheets/d/1eQSeVMPfrWS9Li4XlJf3qs2F8txmddbwZhjOfMGAvt8/edit#gid=883764630

**Comment by tingli3** [comment]
@dlebauer 
So, the first step is to convert the gantry system based on its bounding box to make sure that X starts at 0 and increases to the East using something like x'=-y+22.135 and y'=x-3.8. But this assumes that the six point given is the bounding box (22.135m*203.5m) of the gantry field. 

If this is not the case, I think the first step is to find out the bounding box of gantry field , and how the gantry should be converted (set 0,0 X-axis Y-axis for it), and how it is relate the to the XY of the plots. Is it possible to use the min and max in the https://docs.google.com/spreadsheets/d/1eQSeVMPfrWS9Li4XlJf3qs2F8txmddbwZhjOfMGAvt8/edit#gid=883764630 to get bounding box of the gantry coordinates? If this is the case, which sheet (RangeCentersSorghum1 or RangeCentersSorghum2) should be used? And it seems that range 1 and range 54 does not have value in RangeCentersSorghum1 and the value in this two sheet are different.

**Comment by dlebauer** [comment]
@tingli3 I think it would help if you could create a map with the different coordinates reference systems and available reference points. I am confused that x'=f(y) instead of f(x), and it would really help to clarify. Otherwise, I am afraid that the discussion we are having here will add to the confusion.

... and as you sort this out please document the issues and solutions https://github.com/terraref/documentation/issues/7

**Comment by dlebauer** [comment]
@tingli3  RangeCentersSorghum1 and RangeCentersSorghum2 are for the first and second planting seasons, respectively.

I believe the GPS reference points that compare UA MAC and USDA GPS's correspond to concrete pylons that are in the ground a few meters outside of the planted area.

**Comment by tingli3** [comment]
@dlebauer 
Using x'=f(y) instead of f(x) is to transpose X and Y as the X goes S to N in the gantry coordinates (the X and Y of the gantry should be inversed).

For the two planting seasons, are the coordinates recorded in the same gantry coordinate system? Which one should be used? Finding the exact bounding box of the gantry data is very important.

**Comment by dlebauer** [comment]
@tingli3 

For the two planting seasons, the coordinates are recorded in the same system. We will need to recreate the plot boundaries each time a new crop is planted, and the bounding box of the planted area as well as the plots themselves will change.

**Comment by tingli3** [comment]
@dlebauer  
From the information, I assume we are going to use one system and put all the data with different bounding box into it.  Also, the two planting seasons at least must have to have the same (0,0) point (though we do not know where it is  ) and XY axes (I think this should be true). That means the same gantry coordinate in both two seasons should exactly point to the same point. Is this correct?
And, as the bounding box is changing and (0,0) point is unknown, the new gantry coordinates with X increasing to the east will also not start exactly at (0,0). The (0,0) point of the plots may corresponding to a gantry coordinate not exactly (0,0). Is that OK?

**Comment by dlebauer** [comment]
Yes that is okay. Only the plots change. I think we should discuss in
person, but please map what you have so it is easier to understand.

**Comment by dlebauer** [comment]
I was very confused and when you (@tingli3) pointed out x'=f(y) I realized that I misunderstood the gantry coordinate system. 

But drawing a map helped me. This may be incorrect, but it is my current working hypothesis of how the different coordinate systems overlay.

If x goes positive to the north and y goes positive to the east, we don't need a coordinate system with x going east. That was only because if x increases to the west / to the left, images, plots, and perspective are inverted.

So, we should review these maps and be able to encode this in a database and use it to subset data and visualize the experimental design.

![fullsizerender](https://cloud.githubusercontent.com/assets/464871/19012014/82518344-876d-11e6-89eb-e568ad5199f5.jpg)
![img_1714](https://cloud.githubusercontent.com/assets/464871/19012015/8b6cbe8a-876d-11e6-8659-2d2f3ebb6da4.JPG)

[p.s. Did anyone else ( @pless @LTBen @rjstrand @smarshall-bmr @doctorroboto et al ) catch on that x is increasing to the north?]

**Comment by tingli3** [comment]
This R code corrects the order of plotID and add column and range ID to each plot. Grid[i,] corresponds to plot i. The X1, X2, Y1 and Y2 need to be updated using the true gantry coordinates.
```
require(ggplot2)
require(udunits2)
x_origin = 0 
y_origin = 0
length = 3.5
alley = 0.5
row_spacing = 30
ranges = 54
columns = 16
row_spacing_cm <- ud.convert(row_spacing, 'in', 'm')
dx <- 2 * row_spacing_cm
dy <- length
x <- x_origin + (1:columns - 1) * dx
y <- y_origin + (1:ranges - 1) * (length + alley) 

grid <- data.frame(expand.grid(x,y))
names(grid)=c('x1','y1')
plot = 1:(ranges*columns)
grid=cbind(plot,grid)
grid$x2=grid$x1+dx
grid$y2=grid$y1+dy

grid$column=(grid$plot-1)%%16+1
grid$range=floor((grid$plot-1)/16)+1

for ( i in (1:27)*2 )
{
  grid[((i-1)*16+1):(i*16), 1]=c((i*16):((i-1)*16+1))
}

grid=grid[order(grid$plot),]

theme_set(theme_bw())
ggplot(data = grid) + 
  geom_text(aes(x1+dx/2, y1+dy/2, label = plot), size = 3.5) +
  geom_point(aes(x1,y1), size = 1, alpha = 0.4) + 
  geom_point(aes(x2,y2), col = 'red', size = 1, alpha = 0.4) +
  ggtitle('gantry plot layout') + xlab('x') + ylab('y')


```

**Comment by tingli3** [comment]
This is the R code for projection. Lat&lon can be returned through gantry2latlon(gantry_x, gantry_y) e.g. gantry2latlon(3.8,0). How the choose of the point (currently CE) and projection will effect the error needs to be experimented later.
```
require('proj4')
options(digits=15)
gantry2latlon <- function(gx,gy)
{
  #you can replace CE with other points such as SW SE ...
  CE=c(-111.974810166667,33.07547550)
  CE_gantry=c(101.750,0)
  dx_g=gx-CE_gantry[1]
  dy_g=gy-CE_gantry[2]
  proj= '+proj=tmerc +lat_0=0 +lon_0=-111.843479 +k=1 +x_0=12285.092664 +y_0=-3661028.344732 +datum=WGS84 +units=m +no_defs '
  #or you can use
  #proj= '+proj=tmerc +lat_0=0 +lon_0=-111.974928458333 +k=1 +x_0=50000 +y_0=0 +datum=WGS84 +units=m +no_defs '
  #proj='+proj=utm +zone=12 +ellps=GRS80 +datum=NAD83 +units=m +no_defs'

  CE_UTM=project(CE,proj)
  x_UTM=CE_UTM[1]-dy_g
  y_UTM=CE_UTM[2]+dx_g
  #return (round(project(c(x_UTM,y_UTM),proj,inverse=T),15))
  return (project(c(x_UTM,y_UTM),proj,inverse=T))
}
```

**Comment by yanliu-chn** [comment]
Next:
- generate polygons to be inserted to betydb in postgis sql statements. send to Scott.
- two site tables for two seasons. tables use USDA GPS reference points.
https://docs.google.com/spreadsheets/d/1eQSeVMPfrWS9Li4XlJf3qs2F8txmddbwZhjOfMGAvt8/edit#gid=883764630

https://docs.google.com/spreadsheets/d/1eQSeVMPfrWS9Li4XlJf3qs2F8txmddbwZhjOfMGAvt8/edit#gid=1433617856

- work out sql query statements on querying the tables to output MAC and gantry coordinates.

Due Oct 14th.

**Comment by yanliu-chn** [comment]
From Andy French on Sept 2, 2016:


1.     Use the USDA RTK system as the base reference, it is likely more accurate than the M&S (this is not CASE IH as understand). The USDA RTK system was checked a while ago (2007 so not so recently) three AZ base stations  (designations AZMO, AZSC, AZCLL) and differed from the NAD83 reference frame by 2, 1.2, 1.9 cm for the X,Y, Z coordinates respectively. We routinely check our locations against the USGS National Map and locations are typically within ~2cm
2.       We (Bill Luckett and I) checked the location of the M&S base station with the USDA rover (with some error because the M&S antenna is behind a locked fence to the west of the scanalyzer field). Thanks to Pedro for additional information we’ve confirmed the 2.5 m discrepancy is due to an inaccurate position used in commissioning the M&S base. This discrepancy appears to be constant across MAC fields. I suspect the M&S system precision is excellent even though its accuracy is not. Because of these factors, moving between the ‘best’ coordinates and the M&S coordinates is a matter of book-keeping to make sure one records your GPS source GPS.
3.   Bill and Bob Strand have collected locations of the concrete piers using the USDA RTK system. Thus a linear transformation matrix can be easily created to move between scanalyzer coordinates and the currently best possible UTM13 coordinates. This matrix and the offset matrix from #2 can be stored in your PostGIS system.
4.       At some unknown time in the future the inaccuracy of the M&S system will have to be addressed, but as this is not under UA control, cannot be forced. To me this represents a risk, maybe a small one, that one day we will be surprised to find the bias go away. My opinion is that it would be better to maintain more control over your geolocation positioning accuracy.

**Comment by yanliu-chn** [comment]
@tingli3 Upon Andy comment 3: need to confirm with him the EPSG number:
http://spatialreference.org/ref/epsg/26948/
http://spatialreference.org/ref/epsg/26949/
http://spatialreference.org/ref/epsg/26950/

**Comment by yanliu-chn** [comment]
@tingli3 Need to clarify if the 2.5m is on x or y or both directions by going through the email. Ask if needed.

**Comment by yanliu-chn** [comment]
@tingli3 Upon Andy comment 2: need to ask Andy or Bob whether the Lematec coord derived using the linear regression results for MAC coord system has been corrected in the definition of b0, b1 and b2.

**Comment by yanliu-chn** [comment]
@tingli3 Need to confirm with Andy and Bob or @dlebauer whether the lat lon info associated with Lemnatec gantry raw data is the corrected values based on Andy's comment 1.

**Comment by dlebauer** [comment]
@yankiu-chn are you are asking if the gantry points were corrected to the USDA coordinates? I believe the answer is 'no', as they are labeled UA MAC but maybe @rjstrand @JeffWhiteAZ or @Andrade-Pedro can comment

**Comment by yanliu-chn** [comment]
@dlebauer I meant column B and C from row 4-9 in [UA-MAC-F13_RTKRef_9-2-2016](https://docs.google.com/spreadsheets/d/15OxGNJCMsQC4xUCvMiv8i-ERBx1hAKp_LiDIW31tIVA/edit?usp=sharing) sheet.

**Comment by yanliu-chn** [comment]
@dlebauer ok, so UA-MAC-F13_RTKRef_9-2-2016 is all about MAC coord. I revised my comment.

**Comment by dlebauer** [comment]
@yanliu-chn yes, it is from the UA-MAC RTK GPS; the comments say 'from the tractor', which implies the UA-MAC data. 

@JeffWhiteAZ will we be getting any data (other than for correction of the UA-MAC system) from the USDA RTK GPS coordinates?

**Comment by tingli3** [comment]
Here is another example of Rcode using the linear regression method to get the lat and lon.
All the files need are in [projection.zip](https://github.com/terraref/computing-pipeline/files/512326/projection.zip).


```
data=read.csv("coords.csv")
require('proj4')
options(digits=15)
gantry2latlon_lm <- function(gx,gy,data)
{
  
  proj= '+proj=tmerc +lat_0=0 +lon_0=-111.974928458333 +k=1 +x_0=50000 +y_0=0 +datum=WGS84 +units=m +no_defs '

  lonlat=cbind(data$Longitude,data$Latitude)
  projectxy=project(lonlat,proj)
  data$projectX=projectxy[,1]
  data$projectY=projectxy[,2]
  
  fitX=lm(projectX~gantryX+gantryY,data)
  fitY=lm(projectY~gantryX+gantryY,data)
  
  predictdata=data.frame(cbind(gx,gy))
  names(predictdata)=c('gantryX','gantryY')
  X=predict(fitX,predictdata)
  Y=predict(fitY,predictdata)
  
  result=project(cbind(X,Y),proj,inverse=T)
  return(result)
}
```

**Comment by JeffWhiteAZ** [comment]
Short term, we should not receive more data using the USDA GIS system. In the medium term, possible sources of such data would be:

1.       Mapping additional concrete pylons, etc. under the Gates Foundation project.

2.       Specific measurements made by A French or others using USDA equipment
Note also that any work done with WAAS GPS (e.g. in UAVs) should match the USDA coordinates, albeit with lower accuracy (0.25 to 2 m RMSE).
- Jeff

**Comment by yanliu-chn** [comment]
@tingli3 @dlebauer Summary of today's working meeting:

https://github.com/terraref/documentation/blob/version1/spatial-reference-system-data.md

@tingli3 please read the sites table section to be clear about the input and output.

**Comment by tingli3** [comment]
@yanliu-chn 
Why UTM 13 zone?
UTM 13 zone is from -108 degree to -102 degree.
I think UTM 12 zone is more suitable as the longitude is around -111degree.

**Comment by JeffWhiteAZ** [comment]
Not sure of context of question, but AZ is mostly within UTM 12.
- Jeff

**Comment by tingli3** [comment]
I mean in this document https://github.com/terraref/documentation/blob/version1/spatial-reference-system-data.md. All projection is in UTM 13

**Comment by Andrade-Pedro** [comment]
Is a typo, it should be UTM Zone12

**Comment by yanliu-chn** [comment]
I inherited the type from Andy's earlier email. :) I have corrected it in both the document MD and the comment in this issue.

**Comment by tingli3** [comment]
[sql.zip](https://github.com/terraref/computing-pipeline/files/525164/sql.zip)
This is an example of generating SQL statements with range.csv and row.csv as example input. Please make sure that range.csv (must have 54 entries) and row.csv (must have 32 entries) have correct values (For the row.csv, I assume all the row start at y=0 and each plot covers one column = two rows). I am using the values of planting season 2 in these two files but I do not quite understand the 2016_F13_TERRA_sorghum_field_book.xlsx. The values in the two files should be corrected by someone. 

In the SQL part,
plotid is the ID of each plot; col is the column ID; range is the range ID; geomgantry is a polygon of the plot directly using (X,Y) gantry coordinates (How to handle the inversed X and Y in gantry?); X and Y is the gantry coordinate of the SW point of each plot; gantryw is the length of the shorter edge and gantryl is the length of the longer edge in gantry coordinates; geousda is a polygon of the plot using lat and lon generated from https://github.com/terraref/documentation/blob/version1/spatial-reference-system-data.md; lon and lat is the longitude and latitude of the SW point of each plot; utmw is the length of the shorter edge and utml is the length of longer edge calculated by project the lat&lon into UTM.

**Comment by dlebauer** [comment]
@gsrohde could you please review and run the SQL boundaries?

**Comment by dlebauer** [comment]
@tingli3 thank you for doing this.

Could you please 

1. fix the insert statements so that they work on BETYdb, e.g. if you look at the original post / examples the insert statement should be something like 
```r
paste0('update sites set geometry = ', geometry, 'updated_at = now(), where name = ', 
    paste0("'MAC Field Scanner Field Plot ", plot, "season ", season, " ';"))
```
2. run this for both the first and second planting seasons
  * I've added the border information for season 1 in the [spreadsheet]( https://docs.google.com/spreadsheets/d/1eQSeVMPfrWS9Li4XlJf3qs2F8txmddbwZhjOfMGAvt8/edit#gid=883764630)
3. Modify the script so that it will work for any number of rows and columns

**Comment by dlebauer** [comment]
@tingli3 also, could you please check your code and inputs into the repository?

**Comment by dlebauer** [comment]
@tingli3 please also add elevation 353

**Comment by yanliu-chn** [comment]
@gsrohde could you test the sql statements and let us know what to improve?

**Comment by yanliu-chn** [comment]
@dlebauer could you ask the right person to define the format in the excel so that we know for sure how to extract columns in order to figure out the number of rows and columns explicitly and implicitly? An explicit way is to specify the number of rows and columns in the sheet and tell us where the numbers are. 

And, if you want to derive the plot coord for any number of rows and columns, tell us the formula to derive the plot id from the range and column id.

**Comment by dlebauer** [comment]
@yanliu-chn will the ranges and rows worksheets that I created work? If not, please go ahead and define what you need, and we can work backward from there. 

@JeffWhiteAZ is there a standard way of naming / numbering plots based on the ranges and columns? Is there a reason that the numbers increase alternatively going L-->R and then R--> Left going North?

**Comment by yanliu-chn** [comment]
@dlebauer i think we need one single format that does not change across years. In that format, we should have enough info to derive the geom and plotid. That's all.

Our current assumption on the range-column sheet is: 
- the `range` column defines range index, starting from 1, incremented by 1. The largest number we can get, say `X`, is used to calc the number of ranges: `X-1+1`; 
- the same assumption for the `column` column
- There is no gap along `column` direction
- The deference b/w any consecutive columns is the column size
- `range` must have the `x` coord for the south and north to figure out the range size

If this assumption holds for all the sheets to be produced in the future, we are fine. We don't want to expect variations such as for some year, the `column` `Y` value becomes the column size, not gantry Y; `column` patterned as `1 3 5 9 11 15` and the index increased by 2.

**Comment by dlebauer** [comment]
@yanliu-chn please move forward with this assumption - since it doesn't currently exist, once you specify the format (in documentation) then it becomes the de-facto standard!

**Comment by dlebauer** [comment]
I tweaked the code to insert polygons for season 2 by adding

```r
  betydb_insert[[i]] <- paste("INSERT INTO sites (sitename, geometry, updated_at, created_at) VALUES (", 
                         paste0("'MAC Field Scanner Field Plot ", grid$plot[i], " Season 2', "),
                         geom_latlon, ", now(), now());")
}

```


to the final for loop.

and then filled out the information by running 

```sql
update sites set city = 'Maricopa', state = 'Arizona', country = 'USA', time_zone = 'America/Phoenix', greenhouse = 'f', user_id = 6000000004, updated_at = now() where sitename like 'MAC Field%';
```


the `geom_gantry` information will be useful for extractors that use the gantry coordinate system, but it does not fit into BETYdb. Where can it be stored? Or can we modify the geometry column so that it can optionally return these points?

**Comment by gsrohde** [comment]
@dlebauer (and @tingli3) Please **don't** include the `created_at` and/or `updated_at` columns in the insert and update statements!  A trigger function handles these automatically so that `created_at` and `updated_at` are set to the current time when a row is inserted, and `updated_at` is reset to the current time when a row is updated.  Setting them explicitly overrides this behavior, and using `now()` sets the column to machine time, not UTC time.  (There is a function I defined, `utc_now()`, which will return UTC time, but _you don't need to use it in this case_.)

**Comment by gsrohde** [comment]
@yanliu-chn I think the lines in the MAC --> USDA (M2U) section of https://github.com/terraref/documentation/blob/version1/spatial-reference-system-data.md are mis-labelled: Mx/Ux is the longitude and My/Uy is the latitude, correct?  So is 0.000020308287 the longitude offset or the y-offset (which is really latitude)?  Also, are you still assuming Mx/Ux are in UTM units here, or are these in degrees?  @tingli3's script seems to assume they are degrees; he applies the offsets _after_ doing the proj4 projection.  If they really _are_ degrees, could you clarify this in the documentation?

**Comment by yanliu-chn** [comment]
@gsrohde Thanks for pointing this out. I just fixed it. It was a typo. You are right. Mx/Ux is longitude in degrees; My/Uy is latitude in degrees. I have specified in the original doc that it was to convert from MAC lat,lon to USDA lat,lon.

**Comment by gsrohde** [comment]
@yanliu-chn Thanks for fixing.  I guess using the terms "lat" and "lon" makes it clear that in the MAC --> USDA (M2U) section we are no longer working in UTM coordinates.  What was confusing to me is that in the Gantry --> MAC section, the variable `Mx` is used to represent the easting coordinate in the UTM system whereas in the MAC --> USDA section, `Mx` is used to represent the longitude.  (Similarly for `My`.)

**Comment by gsrohde** [comment]
@dlebauer, @yanliu-chn I'm not sure which SQL statements I should be looking at.  The statements generated by the code in SQL.zip mentioned in comment https://github.com/terraref/computing-pipeline/issues/174#issuecomment-253279547 doesn't seem to directly relate to BETYdb, but @dlebauer references SQL statements designed for BETYdb in his comment https://github.com/terraref/computing-pipeline/issues/174#issuecomment-253669138.

**Comment by dlebauer** [comment]
@gsrohde I unassigned you when I realized more work needed to be done. But I went ahead and inserted these  .... 
[insert_season2_sites.sql.txt](https://github.com/terraref/computing-pipeline/files/530098/insert_season2_sites.sql.txt)

for this case I am not worried about the incorrect use of now(), but now that I know I won't worry about it.

**Comment by tingli3** [comment]
@dlebauer Please give me an example of the sql statement I should generate.

**Comment by dlebauer** [comment]
@tingli3 please see https://github.com/terraref/computing-pipeline/issues/174#issuecomment-253869609

**Comment by gsrohde** [comment]
@tingli3 ... but leave out the `created_at` and `updated_at` columns.

**Comment by tingli3** [comment]
@gsrohde Can you give me an example sql?

**Comment by gsrohde** [comment]
@tingli3 The file David attached to the comment https://github.com/terraref/computing-pipeline/issues/174#issuecomment-253869609 has several example insertion statements.  Here's the first (but with the timestamp columns omitted, as they should be):
```
INSERT INTO sites (sitename, geometry) VALUES ( 'MAC Field Scanner Field Plot 1 Season 2',  ST_GeomFromText('POLYGON((-111.975049874375 33.0745312921391 353, -111.975033517034 33.0745313124814 353, -111.975033529346 33.0745670737771 353, -111.975049886694 33.0745670534346 353, -111.975049874375 33.0745312921391 353))', 4326));
```

**Comment by tingli3** [comment]
[season1_sql.txt](https://github.com/terraref/computing-pipeline/files/534607/season1_sql.txt)
[season2_sql.txt](https://github.com/terraref/computing-pipeline/files/534609/season2_sql.txt)
Could someone please help me to verify these results?

**Comment by dlebauer** [comment]
@tingli3 

* I've already generated and inserted the season2 plots. 
* The season 1 plots should have update rather than insert statements; the sitenames do not include  Season 1` for the first season
* please add your code to the github repository here: https://github.com/terraref/computing-pipeline/blob/master/scripts/geospatial/field_scanner_plots.R

**Comment by dlebauer** [comment]
@tingli3 issue #187 will check for consistency with other field measurements.

**Comment by tingli3** [comment]
@dlebauer The season 1 and season 2 sql statements are based on the example given. If season 1 is different from season 2, please give me another example. Also, I have added the code.

**Comment by dlebauer** [comment]
@tingli3 I already inserted season 2

For season 1, the first line would be

```sql
UPDATE sites 
  SET geometry = 
    ST_GeomFromText('POLYGON((
      -111.975049873054 33.0745274579941 353, 
      -111.975033515714 33.0745274783365 353, 
      -111.975033525032 33.0745545428892 353, 
      -111.975049882377 33.0745545225468 353, 
      -111.975049873054 33.0745274579941 353))', 4326));
  WHERE sitename = 
       'MAC Field Scanner Field Plot 1';
```

P.S. I reformatted your R code following http://adv-r.had.co.nz/Style.html so ... please pull changes before updating.

**Comment by tingli3** [comment]
[season1_sql.txt](https://github.com/terraref/computing-pipeline/files/542606/season1_sql.txt)

**Comment by dlebauer** [comment]
@tingli3 all set - thanks! Closing - can you please update documentation (https://github.com/terraref/documentation/issues/7)?
