### ISSUE TITLE
Create a correlation plot comparing scanner height measurements vs manual height measurements

### ISSUE THREAD

**Issue by nshakoor** [terraref/computing-pipeline#175]
### Description

For the November meeting, can someone do the comparison of plot level height distributions calculated from the sensors and the ground truth measurements for height? I know it's not an ideal comparison, but it's a measurement that most of the TERRA teams have to provide in their milestones (e.g. "Demonstrate algorithm predictions are within 20% of ground truth values"). It would be ideal if the REF team could set a standard method for doing this for some of the general phenotypes, like height.

**Comment by rmgarnett** [comment]
@pless and I will work on this for the annual meeting in November.

**Comment by dlebauer** [comment]
@rmgarnett is there anything you need to complete this?

**Comment by rmgarnett** [comment]
The work is completed. How shall I report the results?

**Comment by dlebauer** [comment]
@rmgarnett good question. Having the results (and putting this in a quarterly report) is sufficient to close this issue because it specifically follows from a milestone.  Please put the figure and summary stats here here for quick reference. I'll put the rest of my thoughts in #210 which deals with automation of the height extractor.

**Comment by rmgarnett** [comment]
[correlation analysis.pptx](https://github.com/terraref/computing-pipeline/files/668205/correlation.analysis.pptx)

**Comment by pless** [comment]
on the last slide of this pptx, both axes have the same label.  is that
correct?

**Comment by rmgarnett** [comment]
Fixed.

**Comment by dlebauer** [comment]
I don't see the fixed version ...

**Comment by rmgarnett** [comment]
I edited my original comment; the file above contains the modified figure.

**Comment by dlebauer** [comment]
Thanks!

**Comment by dlebauer** [comment]
@rmgarnett what are your suggestions for dealing with the ground issues? Are these responsible for the poor predictions of plants under 60 cm?

![img_2204](https://cloud.githubusercontent.com/assets/464871/21431391/e1878202-c81b-11e6-8e79-f98d1b949a1e.PNG)

**Comment by rmgarnett** [comment]
New correlation plot with better ground rejection and discarding bad data:

<img width="491" alt="screen shot 2017-01-27 at 12 56 33" src="https://cloud.githubusercontent.com/assets/583945/22383597/1d0966d4-e490-11e6-8468-72426d90fdb6.png">

Things look a lot nicer.
