### ISSUE TITLE
Create timecourse representations of sensor data from the gantry

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#178]
_From @nshakoor on September 28, 2016 22:17_

@pless Can we create movie-like timecourse representations of sensor data from the gantry?

_Copied from original issue: terraref/reference-data#58_

**Comment by max-zilla** [comment]
let's revisit this once we have the plot-level chops; becomes more trivial then

**Comment by dlebauer** [comment]
closing this. Once we have plot-level geotiffs, we will be able to use imagemagik / ffmpeg
