### ISSUE TITLE
PLY files not being generated

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#181]
@jdmaloney @rmgarnett and I noticed there do not appear to be PLY files generated for the 3D scanner data since 08/22.

```
LemnaTec/3DScannerRawDataTmp/scanner3DTop/
```

04/25 - 10/08
Actual raw PNG files.

```
LemnaTec/MovingSensor/scanner3DTop/
```

04/25 - 08/02
PNG + PLY files. Some empty directories in the last few days I spot-noticed.

```
LemnaTec/MovingSensor.reproc2016-8-3/scanner3DTop/
```

04/25 - 08/18
PNG + PLY files. Initial reprocessing.

```
LemnaTec/MovingSensor.reproc2016-8-18/scanner3DTop/
```

04/25 - 08/22. Second batch of reprocessing. 

Since the reprocessing on 08/18, we have not seen any new PLY files. @solmazhajmohammadi @smarshall-bmr do you know why this would be? @rmgarnett would like to compare hand height measurements from these dates and needs the PLY data to do so:
- 08/24
- 08/31
- 09/08
- 09/15
- 09/22
- 09/29

Related issues:
- https://github.com/terraref/computing-pipeline/issues/168 @jdmaloney is finishing this up so on NCSA side, /ua-mac/Level_1 will have PLY files and /ua-mac/raw_data will have PNG + JSON files.
- https://github.com/terraref/computing-pipeline/issues/98 eventually we will write extractor to convert PLY to LAS.

**Comment by dlebauer** [comment]
Any thoughts @TinoDornbusch, @smarshall-bmr, @ZongyangLi or @pless?

**Comment by smarshall-bmr** [comment]
After the 8/18 reprocessing the ply generator has been nonfunctional on the LemnaControl computer. This was a known issue but it wasn't fixed because of concerns at the time about the ply generator's resource usage. There had been talk of running the ply generator elsewhere in the pipeline but given my current understanding it could probably simply be reimplemented here.

**Comment by rmgarnett** [comment]
In addition to the dates listed in the issue, there are also hand measurements available for September 29.  It would be fantastic if we could extract the PLY files for these seven dates to complete the requested correlation analysis.

**Comment by TinoDornbusch** [comment]
The ply worker has been restarted and ply conversion is resumed.

**Comment by rmgarnett** [comment]
@TinoDornbusch: any idea when they'll complete for the requested dates?

**Comment by TinoDornbusch** [comment]
@rmgarnett I checked today. The ply worker roughly needs 1h per field scan. Hence transformations should be finished by Thursday morning.

**Comment by rmgarnett** [comment]
Fantastic, thanks!

**Comment by smarshall-bmr** [comment]
As of right now the ply worker is working on 9/2/16, just for reference.

**Comment by ZongyangLi** [comment]
@TinoDornbusch Could you please tell me where can I find these ply worker's output, I can not find new ply data in Globus Terraref in "/ua-mac/Level_1/scanner3DTop/" or "/ua-mac/raw_data/scanner3DTop/"

**Comment by max-zilla** [comment]
@ZongyangLi they are being generated on the server in Arizona. 

As they are generated they should be logged in the FTP log, where they will be queued for transfer to NCSA. They should appear in Level_1/scanner3DTop. @jdmaloney we don't need to do anything special for these right?

**Comment by ZongyangLi** [comment]
@max-zilla Thanks!

**Comment by max-zilla** [comment]
@TinoDornbusch @smarshall-bmr @jdmaloney 

These are not being moved into 
```
/MovingSensor/scanner3DTop
```
They are being generated into 
```
LemnaTec/MovingSensor.reproc2016-8-18/scanner3DTop
```

Currently that directory is not whitelisted - files in the log going in there are ignored. (The whitelist was introduced to avoid transferring temp/test files on that machine). We thought the reproc folder was a one-time thing - JD generated a list and I manually submitted them.

I'll add that directory to the whitelist for now so that the new PLYs will go, but I don't know if that should be the permanent home for these now...

**Comment by TinoDornbusch** [comment]
@max-zilla According to Makus Radermacher this directory was requested to keep track of the different 3D transformation matrices

**Comment by max-zilla** [comment]
@TinoDornbusch OK, thanks. I'll just keep it in the whitelist for now.

**Comment by max-zilla** [comment]
@jdmaloney are these captured automatically? I tail'd xferlog on the cache server and:
```
Tue Oct 11 12:14:50 2016 1 ::ffff:10.160.21.83 8147712 /gantry_data/LemnaTec/MovingSensor/stereoTop/2016-10-11/2016-10-11__12-16-42-554/518a50e3-5503-4e57-86ec-a7501c2d0d5e_right.bin b _ i r lemnatec ftp 0 * c
Tue Oct 11 12:40:40 2016 1 ::ffff:10.160.21.81 37644117 /gantry_data/LemnaTec/EnvironmentLogger/2016-10-11/2016-10-11_11-42-38_environmentlogger.json b _ i r lemnatec ftp 0 * c
```

These two files are 26 minutes apart and I'm pretty positive PLY files were generated during that time.

**Comment by max-zilla** [comment]
@TinoDornbusch @smarshall-bmr 

This morning @jdmaloney and I did some detective work. We think the PLY pipeline still needs a little attention:
- New .ply files are going into the 8-18 reproc folder.
- The FTP log file "xferlog" has entries for SOME .ply files, but not all. On Tuesday 10/11 there was activity before 3am and after ~11pm, but no .ply entries between those times. 
- We see .ply files on disk that we do not see in xferlog. August 25th datasets are the last entries we see in xferlog, after that there are no more .ply entries.
- Did the FTP pipeline change at all during the recent PLY restart compared to other sensors? Any reason that we wouldn't see new files in xferlog?

I added the reproc folder to the whitelist so for now, new files should be queued for transfer - however this triggers off xferlog, so there are a bunch of .ply files yesterday that didn't get sent. JD and I can handle these manually today/tomorrow but we should figure out what's going on for the long term.

**Comment by max-zilla** [comment]
@ZongyangLi the PLYs should be transferred through August 25 and we'll work with the MAC team to determine why later PLYs didn't appear in the FTP logs. @jdmaloney and I can work to get these manually transferred if necessary - in the very short term I can transfer the ~5 days you need to Roger if there are no updates tomorrow.

**Comment by smarshall-bmr** [comment]
@max-zilla @rmgarnett The ply worker is working on October now, all the days that manual measurements were taken should be available soon if they aren't already.

**Comment by max-zilla** [comment]
@rmgarnett I'm going to send these days manually:
```
08/31
09/08
09/15
09/22
09/29
```
This is just Globus, not the pipeline, so it won't appear in Clowder (yet), but for your purposes this will make these dates available on Roger for access. I'll start that transfer now.

**Comment by max-zilla** [comment]
@rmgarnett @ZongyangLi @jdmaloney to avoid polluting the long-term directory for the pipeline I made a temporary directory for this purpose:
```
08/25 in
/ua-mac/Level_1/scanner3DTop/

08/31 - 09/29 in:
/ua-mac/Level_1/scanner3DTop_manualcheck/
```

...this is because the manualcheck stuff also includes the original PNG files too and it's hard to exclude them via Globus UI. But this at least gives you data to work with. The files are big so they'll probably be transferring for a few hours...

**Comment by ZongyangLi** [comment]
@max-zilla That's great, actually I need both json file and ply file to get that height distribution. Files all in a directory should be great for me.

**Comment by max-zilla** [comment]
Update after 2 hours:
```
Total Files 8848
Directories 1269
Bytes Transferred 567.33 GB
Effective Speed 82.08 MB/s
Pending 3924
Succeeded 6198
```

~60% done.

**Comment by max-zilla** [comment]
@ZongyangLi @rmgarnett all done:
```
Bytes Transferred 1.11 TB
```

**Comment by ZongyangLi** [comment]
@max-zilla Thanks!
I am trying to run script on Roger. After uploading a shell script with some python script to my space on Roger, I try to run that shell script and got a permission denied. I think it might be the wrong way I was used for PBS commands. Is there any much easier example for me to run execution on Roger rather than that in [https://wiki.ncsa.illinois.edu/display/ROGER/ROGER+User+Guide](https://wiki.ncsa.illinois.edu/display/ROGER/ROGER+User+Guide)?

**Comment by max-zilla** [comment]
@yanliu-chn @robkooper any help you can provide Zongyang? I've not used the HPC stuff on Roger before.

**Comment by yanliu-chn** [comment]
Simplified user guide:
- use `module load` to load software; use `module avail` to see avail software;
- run shell script using `bash scriptname.sh` or `chmod +x scriptname.sh; ./scriptname.sh`

If you could paste both the command line and error message here, I could be of more help.

**Comment by ZongyangLi** [comment]
@yanliu-chn 
I input `bash height_distribution.sh` and it shows `ImportError: No module named numpy`.
So I use `module avail` to search a `numpy` module for python. It seems there is not numpy module available.

**Comment by yanliu-chn** [comment]
Do the following before you run anything:
```bash
module purge
module load gdal-stack-2.7.10 nco
```

**Comment by ZongyangLi** [comment]
@yanliu-chn Thanks! My test script is running now. 
May I close the terminal that connect to Roger when the program is running?

**Comment by yanliu-chn** [comment]
if you run `qsub -I ...` before you run the script, you shouldn't close the terminal. if without the `-I`, you don't even get a terminal.

**Comment by jdmaloney** [comment]
@yanliu-chn It appears he's just running on the head/login-node.  

@ZongyangLi This is not recommended to do, the head/login-node is not meant for running jobs, just for logging into the cluster and things like code compilation or simple file movement/editing.  You can use the command Yan gave if you want to watch the job run (aka leave terminal window open):
qsub -I -l walltime=12:00:00,nodes=1:ppn=20
That will give you a prompt on a new node that is not roger-login, something like cg-cmp## or cg-gpu##, then run the same thing you did to start the task you have running now.

If you want to submit and forget about it (and have it email you when it's done), you'll need to write a job file.  Here's one that I think would work for you (piecing together what I've seen discussed in this issue) copy and paste the below into a text file and then run the following command from the login node: 
qsub $path_to_file
Replacing $path_to_file with the full path to your file you create from the below, you can see the state of the job by running: qstat and looking for your user and job name

Job File begins with next line (put in your email, the name of your job, and add the full path to that script:
#PBS -S /bin/bash
#PBS -m ae
#PBS -M you@youremailhere.edu
#PBS -N Whatever_you_want_to_name_your_job
#PBS -l nodes=1:ppn=20
#PBS -l walltime=12:00:00

module load gdal-stack-2.7.10 nco

/full/path/heightdistribution.sh

**Comment by ZongyangLi** [comment]
@max-zilla Got it. I will try it in this way today.

**Comment by ZongyangLi** [comment]
@jdmaloney I am running jobs on Roger now. And I save the result in the directory of "/projects/arpae/terraref/users/zongyang/heightDistribution" on Roger.

When those jobs are finished, should I transfer those result by Globus Online? If yes, I guess I still need a NCSA RSA token. Is that right?

**Comment by max-zilla** [comment]
@ZongyangLi unforutnately @jdmaloney is out for 2 week vacation starting today. If @yanliu-chn and @robkooper do not know, I can try to find someone else to help.

**Comment by ZongyangLi** [comment]
@max-zilla Thanks!
@yanliu-chn told me that I can copy files to my directory. It works for this issue since the result in this issue are some text files. But I am going to generate full field stitched creation and it will create tons of images. It seems it's not a good idea of copying files to my home directory space.
@robkooper any ideas?

**Comment by dlebauer** [comment]
@ZongyangLi `/home/zongyang/` is your home directory; `/projects/arpae/terraref/users/zongyang/` and everything under `/projects/` is part of the large file system. 

But ... should this be written to a subdirectory of `/projects/arpae/terraref/sites/ua-mac/Level_1` ?

**Comment by ZongyangLi** [comment]
@dlebauer 
For this issue I am providing data in special dates for @rmgarnett about #175 so I'm not sure whether should this be written to `/projects/arpae/terraref/sites/ua-mac/Level_1`

For that full field stitched creation, I think it's great to put that tile files to Level_1 directory. Maybe we should discuss it in #85

**Comment by max-zilla** [comment]
@ZongyangLi I think it makes sense to put the full field mosaic in Level_1, you might give it a name with _manual at the end or something so we know this was not generated as part of the Globus pipeline. Other people will probably be interested in that output so it makes sense to put it in one of the more exposed data locations. Just my 2 cents.

**Comment by ZongyangLi** [comment]
@max-zilla Okay, i will start working on that.

**Comment by ZongyangLi** [comment]
@max-zilla It seems I can not create a directory on Level_1: permission denied.
Also, I didn't try to create files by script to /ua-mac/Level_1 yet, I think it might be not allow.

**Comment by max-zilla** [comment]
@ZongyangLi in that case, you should try writing to your /users directory David mentioned. We can move the files later if we want to.

**Comment by solmazhajmohammadi** [comment]
@max-zilla Can you please check the PLY files from October
I can see the PLY files have been generated in the gantry cache server and some of the PNG files have been transferred, but PLY files are missing from Level1_data 
Thanks

**Comment by max-zilla** [comment]
@solmazhajmohammadi no one responded to my message from 6 days ago:

> We think the PLY pipeline still needs a little attention:

> - New .ply files are going into the 8-18 reproc folder.
> - The FTP log file "xferlog" has entries for SOME .ply files, but not all. On Tuesday 10/11 there was activity before 3am and after ~11pm, but no .ply entries between those times.
> - We see .ply files on disk that we do not see in xferlog. August 25th datasets are the last entries we see in xferlog, after that there are no more .ply entries.
> - Did the FTP pipeline change at all during the recent PLY restart compared to other sensors? Any reason that we wouldn't see new files in xferlog?

The short answer is, everything after August 25 hasn't been sent because it isn't being logged. I can find some time to transfer these manually  ( @jdmaloney is out for 2 weeks) but the FTP logs are the intended way for the pipeline to work - we don't want to manually queue these more than we have to, especially because it takes some time to carefully determine what's new and what isnt.

@smarshall-bmr any ideas?

**Comment by solmazhajmohammadi** [comment]
@max-zilla There was an update on system last week, but I dont think that will affect this. I'll ask Markus and post his response here

**Comment by markus-radermacher-lemnatec** [comment]
The software update should not affect your ftp transfer. Currently the final output folder of the ply files is set to MovingSensor.reproc2016-8-18 and will stay there. Let me know, when you want the output folder to be changed.
Important to know is, that the process from a scan to the final ply files is separated into two steps. 
1. Writing the scan data to the 3DScannerRawDataTmp folder
2. Reading this data and writing everything to the 8-18 folder (with the current setting the original data will remain in the tmp folder)
So, if you are missing the ply files after a scan, maybe the PlyWorker software is not running.

**Comment by rachelshekar** [comment]
May need @jdmaloney  to look at the FTP log if LemnaTec doesn't control.

**Comment by max-zilla** [comment]
@jdmaloney and I manually queued a bunch of these yesterday in the meantime, but I think JD is going to follow up with LemnaTec as we think this needs to be fixed on the MAC side.

**Comment by max-zilla** [comment]
@jdmaloney can you give a little update here on current thinking? I will be in AZ next week and could potentially look at this with @TinoDornbusch @smarshall-bmr @markus-radermacher-lemnatec

**Comment by rachelshekar** [comment]
@jdmaloney - update needed

**Comment by max-zilla** [comment]
@jdmaloney and I noticed this suddenly got fixed this morning - PLY files are now moving (currently on Nov 5) and counting. @smarshall-bmr @TinoDornbusch was anything done this morning to address PLY transfer over FTP? Was anything restarted? whatever was done, this is now working...

**Comment by solmazhajmohammadi** [comment]
@max-zilla PLY worker has been restarted today. The licensing issue has been resolved,  you should see the ply data from side cameras as well.

**Comment by TinoDornbusch** [comment]
Yes, ply worker is working again.

However for the side 3D we have still have to do some adjustment. @jdmaloney We need to delete the folders on the gantry cache server: 
/gantry_data/LemnaTec/MovingSensor.reproc2016-8-18/scanner3DLowerOnWestSide
/gantry_data/LemnaTec/MovingSensor.reproc2016-8-18/scanner3DLowerOnEastSide

They do not contain properly calibrated data. 

Newly computed ply files for east scanner will be computed as soon as the target folder on the cache server is deleted.

Computed ply files for west scanner will be computed as soon as we got the calibration files from Fraunhofer.

**Comment by jdmaloney** [comment]
@TinoDornbusch These directories have been deleted, we'll be removing the data that was in them from the ROGER side as well so things are in sync.

**Comment by TinoDornbusch** [comment]
@JD Maloney. We or better the software are not able to create folders under /gantry_data/LemnaTec/MovingSensor.reproc2016-8-18

**Comment by TinoDornbusch** [comment]
@jdmaloney  now it works thanks. Ply worker is running now for east scanner system

**Comment by jdmaloney** [comment]
@TinoDornbusch I made no changes to the directory, must have been something in the software. Just saw your last two messages.
