### ISSUE TITLE
Compute indices, Extract plot level indices and spectra from HSI data

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#183]
Given output of the hyperspectral extractor and the plot boundaries
- [x] compute indices defined in [documentation under "Spectral Indices"](https://github.com/terraref/documentation/blob/master/spectral_indices.md) (Start with NDVI and EVI until we have the system down) 
- [x] add as layer to hyperspectral datasets
- [x] compute means by plot
  - @czender do the hyperspectral datasets contain gantry (x,y) and / or geographic (lat, lon) coordinates? 
  - @hmb1 in what format do you want the plot boundaries? For example,  https://terraref.ncsa.illinois.edu/bety/api/beta/sites?key=9999999999999999999999999999999999999999 is where the definitive plot boundaries are stored 
- [ ] insert means into BETYdb @hmb1 #348

**Comment by remotesensinglab** [comment]
[List of VIs_18Oct2016.docx](https://github.com/terraref/computing-pipeline/files/537312/List.of.VIs_18Oct2016.docx)

**Comment by dlebauer** [comment]
@remotesensinglab thanks for posting. I copied these to documentation (https://github.com/terraref/documentation/blob/master/spectral_indices.md) ... which supports Latex markup if anyone is feeling ambitious.

One question that comes up: the inputs are reflectances at the specified wavelengths (e.g. NDVI=(R900-R680)/(R900+R680)), however the VNIR imaging spectrometer measures at intervals of 2/3 nm, e.g. `[... 679.464, 680.105, 680.745, 681.385, ...  899.081, 899.721, 900.361, 901.002... ]` (see 
[0727bd3e-dc1a-4c5b-a020-50f4f8effaeb_raw.hdr.txt](https://github.com/terraref/computing-pipeline/files/537906/0727bd3e-dc1a-4c5b-a020-50f4f8effaeb_raw.hdr.txt) for all VNIR bands)

Would it make more sense to a) use the band closest to the specified wavelength, b) average the bands that fall in the intervals [679, 681] and [899, 901]? Or c) other? 

... Note that at this point we are _not_ trying to simulate other sensors (at this point) though that could be done using the plot-level spectra, and the [PEcAn RTM](https://github.com/PecanProject/pecan/tree/master/modules/rtm) package has RSR curves and utilities for these conversions. The different sensors used to estimate a particular index will be recorded in the methods.

**Comment by remotesensinglab** [comment]
I suggest using the band closest to the specified wavelengths.

**Comment by czender** [comment]
Answering question above:
> @czender do the hyperspectral datasets contain gantry (x,y) and / or geographic (lat, lon) coordinates?
Coordinates are in gantry(x,y) space. Bounding box info is in both x,y and lat,lon. So, in partial answer to next question, presumably x,y values in meters from southeast corner would be most straightfoward.
> @hmb1 in what format do you want the plot boundaries? For example, grid.csv.txt or grid.json.txt
@hmb1 please respond.

**Comment by rachelshekar** [comment]
@hmb1 and @FlyingWithJerome please update this issue.

**Comment by hmb1** [comment]
HI David,
 do you have a long name for the spectral-index TCARI/OSAVI
Thanks

**Comment by dlebauer** [comment]
@hmb1 CF doesn't have a standard name but for NDVI it is 

* standard_name normalized_difference_vegetation_index
* definition: "Normalized_difference_vegetation_index", usually abbreviated to NDVI, is an index calculated from reflectances measured in the visible and near infrared channels. It is calculated as NDVI = (NIR - R) / (NIR + R) where NIR is the reflectance in the near-infrared band and R is the reflectance in the red visible band. Reflectance is the ratio of the reflected over the incoming radiation in each spectral band. The calculated value of NDVI depends on the precise definitions of the spectral bands and these definitions may vary between different models and remote sensing instruments.
* units: 1

So following this, we can use 

* TCARI / OSAVI optimized_soil_adjusted_vegetation_index

**Comment by hmb1** [comment]
Hi David, & Charlie,
 The ncap2 script "hyperspectral_indicies_make.nco" Is running circa 90 seconds for a 127G input file. Its size is less than 5% of original file-size.  I have sacrificed some performance over legibility.  Prior to calculating the indices the required wavelengths are hyperslabbed out from the "rfl_img" netCDF variable ; and have var names like R600, R710, R790 etc.  If these  vars become an issue then I can  we can split up the script and run it in two stages. 

The var names are as specified in spectral_"indices.md" and are case-sensitive. As I understand it these indices are ratio's and have no units as such.

For a given wavelength the nearest band is used 
(see comments above)

**Comment by dlebauer** [comment]
@hmb1 

* It is okay to sacrifice performance for legibility - we can refactor later if necessary
* the script is easy to read ... though I don't see where it writes a new file ... 
* could you add a section to the [README](https://github.com/terraref/computing-pipeline/blob/master/scripts/hyperspectral/README.md) with this script and an example of its use?
  * @max-zilla should the hyperspectral calibration and index calculation be separate extractors?

@remotesensinglab could you please review the [script for computing indices](https://github.com/terraref/computing-pipeline/blob/master/scripts/hyperspectral/hyperspectral_indices_make.nco) that Henry wrote and provide any feedback?

**Comment by hmb1** [comment]
With ncap2 scripts  the single input and single output file are defined on the command line. Scripts cannot open files directly.  New variables are defined in output.

**Comment by czender** [comment]
@hmb1 I prefer files to be self-documenting. Look at hyperspectral_calibration.nco for an example. Please add equivalent information at the top of all scripts you write for Terraref or NCO.

**Comment by czender** [comment]
The opening message in this issue states "https://terraref.ncsa.illinois.edu/bety/api/beta/sites?key=9999999999999999999999999999999999999999 is where the definitive plot boundaries are stored but we could convert these to..." But this address gives me a "Bad Gateway" issue. Please explain/fix. @hmb1 now that pipeline works with test dest, how about adding a step that calls your scripts and thus adds the computed indices to the data file?

**Comment by dlebauer** [comment]
@czender the database is down (but @robkooper is working on it). @robkooper or @gsrohde is the database somewhere we you can hit https://terraref.ncsa.illinois.edu/bety/api/beta/sites?key=9999999999999999999999999999999999999999 and post the output?

**Comment by dlebauer** [comment]
The database is back up and the sites are 
[sites.json.txt](https://github.com/terraref/computing-pipeline/files/732683/sites.json.txt)

The sites of interest have names like "MAC Field Scanner Season 2 Range * Pass *"

**Comment by dlebauer** [comment]
@hmb1 here is the appropriate query https://terraref.ncsa.illinois.edu/bety/api/beta/sites?key=9999999999999999999999999999999999999999&limit=none&sitename=~MAC+Field+Scanner+Season+2+Range

@max-zilla

**Comment by rachelshekar** [comment]
@craig-willis - naming conventions

**Comment by rachelshekar** [comment]
Next, compute the means of the indices and the calculate the ratios.

**Comment by czender** [comment]
I think @rachelshekar intended to say compute the means of the reflectances then calculate the ratios using the mean reflectances. Soon we use subsampled data to avoid soil, glare, but for now just use the entire image. @hmb1, is this clear?

**Comment by hmb1** [comment]
HI Charlie thanks for that clarification - that is the mean over the whole plot right ?

**Comment by czender** [comment]
Yes, implementation can be as simple as this:

NDVI= ( R900 -R680) / (R900+R680 );
NDVI@long_name="Normalized Difference Vegetation Index";
NDVI_avg= ( R900.avg() -R680.avg()) / (R900.avg()+R680.avg() );
NDVI_avg@long_name="Normalized Difference Vegetation Index";

Soon we will use where() clauses to exclude unwanted points, but for now the above should be OK. Obviously it does not make a mathematical difference if averaging before or after addition and subtraction, but it is crucial that averaging be done before division or multiplication.

**Comment by dlebauer** [comment]
@czender by

>it is crucial that averaging be done before division or multiplication.

I assume this statement should be qualified by 'in order to make the results comparable with lower resolution sensor data'? Is this correct? see https://github.com/terraref/reference-data/issues/86

**Comment by czender** [comment]
The method I recommend implies energy conservation and, yes, scale invariance of the result. Avoid averaging ratios if possible.

**Comment by hmb1** [comment]
Hi Charlie,
 Am looking at the performance of   hyperspectral_calibration.nco   do you really need both 'xps_img'  and 'rfl_img' in the final NetCDF file ?

if not we could modify the formula to:
``xps_img= (rfl_rfr_fct/(xps_img_wht-xps_img_drk))*(xps_img-xps_img_drk);

This would save the cost of defining a huge var in ouptut ?

....Henry

**Comment by czender** [comment]
We need rfl_img in the output, not necessarily xps_img which is de-interleaved version of the contents of the _raw (.bil) file. Have kept both so all information would be in one file. @dlebauer would you prefer all HS info in one file or can we eliminate xps_img (and shrink output files by ~30%)?

**Comment by dlebauer** [comment]
I'll defer to @remotesensinglab

If xps_img can be recovered from reflectance then perhaps there is no need
for it to be in the level 1 product. Perhaps it could be added as a
separate level 0 or level 1 product.

**Comment by remotesensinglab** [comment]
I agree. No need to keep xps_img.

**Comment by solmazhajmohammadi** [comment]
@hmb1 we are working on adding some extra vegetation indices to your pipeline. I see you wrote everything in nco(netcdf operator), can I use "import numpy" to do the squerroot and etc
 there are some indices which require square/squareroot/log and iterate over a bunch of wavelengths.

**Comment by hmb1** [comment]
Hi Solmaz,
 Can you please post the formulas here:
 The ncap2 operator has its own scripting language which has nothing to do with python. It has  a sqrt() function built in 
...Henry

**Comment by hmb1** [comment]
..and also log(), log10() ,pow()

**Comment by rachelshekar** [comment]
@solmazhajmohammadi will work with Chris to provide metatdata

**Comment by dlebauer** [comment]
@solmazhajmohammadi and @ac-gl-chris please see https://github.com/terraref/reference-data/issues/72 for more info on how this should be done https://github.com/terraref/reference-data/issues/105

**Comment by rachelshekar** [comment]
@solmazhajmohammadi - please update

**Comment by dlebauer** [comment]
All indices have been inserted into the database following review in https://github.com/terraref/reference-data/issues/105 

To query Reflectance Indices via API: https://terraref.ncsa.illinois.edu/bety/api/beta/variables?key=9999999999999999999999999999999999999999&limit=none&type=%7EReflectance+index

**Comment by hmb1** [comment]
Hi David,
 the following index names don't play nice with ncap2 as they contain the chars '/' or '-':
 We have a few options for how to deal with them 
 1) change '/' to '_'
 2) truncate '_' and what follows   
 3) for DWSI just remove the '-'  

 We can do the name mods in BETYDB or I can mangle the names in my python script - its your call ?


        "name": "ND900/680",
        "name": "SR900/680",
        "name": "SR700/670",
        "name": "SR750/710",
        "name": "PRI531/570",
        "name": "MSR705/445",
        "name": "TCARI/OSAVI",
        "name": "DWSI-1",
        "name": "DWSI-2",
        "name": "DWSI-3",
        "name": "DWSI-4",
        "name": "DWSI-5",


...Henry

**Comment by hmb1** [comment]
nb the following names are already being used in hyperspectral_indices_make.nco
( but we can rename if @ac-gl-chris agree's

SR->SR900/680
RERI->SR700/R670  
ZM    ->SR750/R710
PRI570->PRI531/570
msr705->MSR705/445  
DWSI1->DWSI-1
DWSI2->DWSI-2
DWSI3->DWSI-3
DWSI4->DWSI-4
DWSI5->DWSI-5
DWSI3
DWSI4
DWSI5

**Comment by dlebauer** [comment]
I'd you can send me a file with oldname,newname pairs I can update them in
the database

**Comment by hmb1** [comment]
Hi David,
  pls use this list instead of the one I sent earlier
  Many Thanks
...Henry
...

**Comment by dlebauer** [comment]
@hmb1 I don't think there was an updated file attached to your last message. copy-paste is fine

**Comment by gsrohde** [comment]
@dlebauer @hmb1  I think it's worth considering how you want to the names to display in the BETYdb Web app.  Are the original names with the offending characters more universally recognizable?  If so, it would be best to display them that way, either by storing them that way or "decoding" them before display.

**Comment by dlebauer** [comment]
I don't think the original names are that much more recognizable, though
they do (should) match index database.de

Maybe we could put these in the label field

**Comment by gsrohde** [comment]
My general philosophy is that the end user should be exposed to machine idiosyncrasies as little as possible.  In this case, this can either be effected by storing the name you want displayed or making the Rails code utilize some well-defined mapping from stored name to display name.  I leave it up to you to decide how important this is to you.

**Comment by hmb1** [comment]
HI David here are the renames list:

"ND900/680", "ND900_680"
"SR900/680", "SR900_680"
"SR700/670", "SR700_670
"SR750/710", "SR750_710"
"PRI531/570","PRI531"
"MSR705/445", "MSR705_445"
"TCARI/OSAVI", "TCARI_OSAVI"
"DWSI-1","DWSI1"
"DWSI-2","DWSI2"
"DWSI-3","DWSI3" 
"DWSI-4","DWSI4"
"DWSI-5","DWSI5"

**Comment by remotesensinglab** [comment]
I vote for using "_" in lieu of "/" or "-"

**Comment by hmb1** [comment]
Hi David
found the following anomalies in the BETYDB indices

names "PRI" and  "PRI531/570" have same formula
name "NDVI" - Has no description field (formula field)
name "RDVI"  two entries with  different formula's

...Henry

**Comment by dlebauer** [comment]
@hmb1 I updated the names from https://github.com/terraref/computing-pipeline/issues/183#issuecomment-299022115

* NDVI with no formula is a generic NDVI that has no formula w/ specific wavelenghts for hyperspectral
* RDVI were duplicates (the difference was sqrt vs ^0.5)
* I deleted the Duplicate PRI

**Comment by ac-gl-chris** [comment]
Hi

sorry I was in vacation last week.
RDVI: We took the formular from [here](http://harrisgeospatial.com/docs/broadbandgreenness.html#Renormal)
PRI: Was a duplicate I missed

Chris

**Comment by hmb1** [comment]
@dlebauer  
one more typo
"name": "Chl index"

**Comment by hmb1** [comment]
@dlebauer, @ac-gl-chris 
HI Guys heres the latest meta data 
pls check for typo's etc 
...Henry
[n2_ind.txt](https://github.com/terraref/computing-pipeline/files/992724/n2_ind.txt)

**Comment by rachelshekar** [comment]
waiting for plot level data processing; reassigning to June

**Comment by czender** [comment]
Current behavior is:
if you add the -h switch to HS workflow invocation it will create an indices file in the same location  as the hyperspectral netcdf file. Name is same as HS file with "_ind" suffix:

 `hyperspectral_workflow.sh -h  -i "$DATA/2017-04-15__06-11-47-765/1a15d90f-cd79-471e-b593-0b466fff557a_raw -O ~/rgr -o tst_vnir.nc`
 
 creates the hyperspectral file "~/rgr/tst_vnir.nc"  and the indices file "~/rgr/tst_vnir_ind.nc" 

We enable this by default so that running HS workflow always creates indices file. Then the option would be to turn this feature off, not on. I like the default behavior to be as close to the desired production behavior as possible. What do you think @max-zilla and @dlebauer  and @hmb1 ? The main reason we did not do this to begin with is that I thought there might be a separate workflow/extractor to process L1 data into L2 data, but no one has mentioned creating such extractors. In any case, given calibration issues, it is likely that most L1 changes will also change the L2 product so re-generating L2 indices each time L1 is re-run makes some sense.

**Comment by dlebauer** [comment]
I like the default behavior you propose. We can devide into two steps in the future when it becomes necessary.

**Comment by max-zilla** [comment]
yeah this makes sense. i added the -h flag to the extractor already so if we change this i'll need to remove the flag but that's easy.

**Comment by czender** [comment]
@hmb1 Can you please implement this? i.e., automatically produce the L2 indices file in the same directory as the L1 output, and give the user a switch that can turn-off producing the L2 file.

**Comment by dlebauer** [comment]
I looked at these files and it appears that they are larger than the input files, in part because they retain the rfl_img and xps_img variables. Here are a few additional things that we should do:

1. remove xps_img and rfl_img from the `_ind.nc` files
2. move these files to Level_2
3. Propagate the same updates to meta-data as specified in https://github.com/terraref/reference-data/issues/83, except in this case I think we can remove additional fields, including everything related to the calibration step.

**Comment by craig-willis** [comment]
This is a stale issue with no comments in last 2 months. Please create new issues if work remains or put this content in the documentation.
