### ISSUE TITLE
UAV data preprocessing calibration information

### ISSUE THREAD

**Issue by Mamatemenrs** [terraref/computing-pipeline#185]
There are calibrated reference panels and blackbody images taken with UAV sensors before and/or after the each flight mission.   There are also 4 white,grey and black panels laid on the ground during the flight. Knowing the  proprieties of these targets would helps us radiometrically correct the UAV images.
### Description

What are the reflectance properties of calibrated reference panels for multispectral camera?

What are the thermal properties of reference target for thermal camera?

What are the reflectance properties of the reference panels laid on the ground during the flight?

Is there any other ground truth data collected during the flight for aerial data processing, such as surface reflectance, temperature and other environmental data? These type of data would be helpful for further atmospheric correction. 

Thanks everyone. 
Matt

**Comment by rickw-ward** [comment]
Can you invite Andy French to join and answer?

**Comment by dlebauer** [comment]
@Mamatemenrs I've assigned this to @rickw-ward and @anfrench who can hopefully answer your questions

**Comment by anfrench** [comment]
there are two sets of reference reflectance panels: one that PDS uses, it is small, PDS will need to provide the specs; the second set consists of 4 8m x 8m canvas tarps, nominally 4%, 8%, 48% and 64% reflectance across vnir bands. We have data from an ASD spectrometer on many but not all flight days that can be used to give the most accurate actual reflectances for each. Kelly Thorp can provide the numbers. The tarps are old and the dark targets are more reflective than nominal and light targets darker than nominal. 
The thermal target is a passive black body, I dont know the surface emissivity, it is around 0.97. There are thermistors in the back of the metal plate to provide physical temperature of the body. The black body is stored in a wood box, insulated, to dampen thermal variations.  Id guess it is accurate to 2C.
There is a met station on farm for air temperature, humidity, wind speed, wind direction, solar radiation. we have a sun photometer that can be used for atmospheric water vapor content but currently dont deploy it routinely.

**Comment by dlebauer** [comment]
@anfrench 
* I assume you accidentally closed this (the 'close and comment' button is next to the 'comment' button). ... 
* Can you contact or provide contact information for PDS? 
* Can you (or Kelly) provide the ASD spectrometer values (we also have data from a sky-facing radiometer on the Gantry, and these data are available)

@Mamatemenrs can you collate all of the information and work with @craig-willis to document and archive it where it can be accessed programmatically (e.g. via the Clowder API)?

**Comment by anfrench** [comment]
Phoenix Drone Service contact is Mark Yori, mark@phoenixdroneservice.com; I think Mark is out of town currently but back next week. Kelly too is out until Monday, kelly.thorp@ars.usda.gov; i have some of the data but it is best if they come from him directly. roughly the actual reflectances are 6%, 13%, 44%, 55% for blue-NIR if that helps stage the analyses.

**Comment by rachelshekar** [comment]
@Mamatemenrs - please update this issue

**Comment by Mamatemenrs** [comment]
Eventually, @rickw-ward and his group have processed the UAV data. So, I have no more updates on this issue. Thanks.

**Comment by rickw-ward** [comment]
is the question what metadata and how to store it?

**Comment by dlebauer** [comment]
The Original question requests specific information about the targets.

Similar to these 

https://github.com/terraref/sensor-metadata/tree/master/targets

https://terraref.ncsa.illinois.edu/clowder/files/5873a9544f0cad7d8131b36a?dataset=5873a9434f0cad7d8131b29a&space=

https://terraref.ncsa.illinois.edu/clowder/files/5873a9544f0cad7d8131b363?dataset=5873a9434f0cad7d8131b29a&space=

https://terraref.ncsa.illinois.edu/clowder/files/5873a9544f0cad7d8131b35f?dataset=5873a9434f0cad7d8131b29a&space=

https://terraref.ncsa.illinois.edu/clowder/files/5873a9544f0cad7d8131b35b?dataset=5873a9434f0cad7d8131b29a&space=

**Comment by rachelshekar** [comment]
@remotesensinglab, @Paheding, and @rickw-ward do we still need this info?  If we already have it, where is it?

**Comment by rachelshekar** [comment]
reminder to @remotesensinglab, @Paheding, and @rickw-ward

**Comment by remotesensinglab** [comment]
Attached is values we got from MicaSense for some of the reference panels used during the UAV data collection. If processed in Pix4D recent version, it may be incorporated in the software  already, but worth checking during the processing. 

[Ref panel values.docx](https://github.com/terraref/computing-pipeline/files/882943/Ref.panel.values.docx)

This can be closed.

**Comment by dlebauer** [comment]
@craig-willis assigned to you to enter into sensor metadata

**Comment by dlebauer** [comment]
reopened until this has been added to available metadata

**Comment by craig-willis** [comment]
@dlebauer  

The attached document appears to contain per-device (RedEdge/Sequoia)  reflectance values for two different panels.   In the past, I've created objects for the panels themselves (i.e., LabSphere or SphereOptics) or for the RSR values on particular devices. In this case, it looks like I should create separate devices for the RedEdge and Sequoia and add the reflectance values for each device.
 
Does this make sense?

**Comment by craig-willis** [comment]
Notes from 6/8 meeting: 

What we have is information about the percent reflectance observed by the imagers, what we need is:
* Factory reflectance for the panel.
* Ideally RSR curves for sensors or some clarification of what the information in the document means.

@solmazhajmohammadi  Says they took measurements of these and uploaded.

**Comment by dlebauer** [comment]
> Factory reflectance for the panel.

I think @solmazhajmohammadi put that on google drive

> Ideally RSR curves for sensors or some clarification of what the information in the document means.

are the values the camera sensitivies in each of these or the %reflectance given the panel, in which case to get RSR we may need to divide these values by reflectance of the panel in given wavelengtht

**Comment by rickw-ward** [comment]
REDEDGE Camera (micasense):  Each panel from MicaSense has a different set of values for calibration.   We have used at least two different micasense panels.  We are tracking the identity of the reflectance panels so can provide the info about the panel ID and its factory reflectance values.  

Sequoia (Sensefly):  It is possible to use the same panel used for the RedEdge, but in fact we use Airinov calibration targets for the Sequoia (https://odoo.airinov.fr/en_US/shop/product/airinov-calibration-target-for-sequoia-496).    The reflectance values are written directly on the targets, and we can provide a closeup of each one as part of the documentation.

@dlebauer and @NewcombMaria I want to talk about how we store the UA-MAC UAV data for Terra-Ref.  Is this thread most appropriate for that- or is that a different or new thread?   I will propose that the primary data products to be TERRA-REF curated for each flight be comprised of a set of 4 (sequoia), 5 (RedEdge), or 1 (thermomap) geo-registered orthomosaics for each observed band (and perhaps one for NDVI?).  Plot level indexes or single band data would be available via extractors.  Plot level stats would be generated from analysis of plot level  extraction results from the TERRA-REF database.    This approach would make data available for anyone's use asap post-flight, because we won't be converting to plot level means etc. which requires GIS work.  Making the single band orthomosaics the primary initial data products would enable other groups to investigate the robustness of the data by, for instance, plotting NIR vs Red reflectance values.  Calibration seems to be a labile field- so I wonder if it would be wise to store the uncalibrated orthos as well as the calibrated ones so that new approaches could be applied at a later point.

**Comment by rickw-ward** [comment]
BTW- i'm out of my comfort zone- but if co-registered orthomosaics can be combined into a data cube is that a way to reduce the complexity of folder structures/file names, etc.?

**Comment by remotesensinglab** [comment]
I think storing both RAW and calibrated ones would be very helpful. There are possibility that new methods can be developed for calibration which requires raw data. The raw data has other uses as well, e.g., 3D point clouds from UAV RGBs and LiDAR, or other systems.

**Comment by Paheding** [comment]
@dlebauer The average values in the above word document are albedos for the reference panels corresponding to each specific band.  These average values should be used in Pix4D for obtaining absolute reflectance image and accounting for effects for illumination. Utilizing the albedos values in Pix4D can be found here:  https://support.pix4d.com/hc/en-us/articles/203891879#label3&gsc.tab=0

**Comment by rachelshekar** [comment]
@craig-willis - please comment

**Comment by max-zilla** [comment]
@dlebauer @craig-willis need specifics on this - david will take a look and we should discuss.

@solmazhajmohammadi spectrometer measurements for hyperspectral calibrations on Drive -  havent uploaded anything for UAV yet.

**Comment by dlebauer** [comment]
@Paheding and @remotesensinglab should provide information about what needs to be stored; @craig-willis can help provide information about how this can be stored so that it can be handled by downstream extractors.

**Comment by craig-willis** [comment]
Just to be clear, there are two different concerns here. 

1) Information about the panels themselves with the factory values.  I think this can be covered by the information offered by @rickw-ward. We've done this for the LabSphere and SphereOptics panels.  

2) Information needed by extractors. In other cases, we've stored RSR curves in the sensor fixed metadata.  For example https://github.com/terraref/sensor-metadata/blob/master/sensors/ndviSensor/sensor_fixed_metadata.json.  This information is converted to JSON and stored in Clowder as needed by extractors.  Based on the discussion today, it sounds like the averaged values in the attached document will work?

**Comment by craig-willis** [comment]
This is a stale issue with no comments in last 2 months. Please create new issues if work remains or put this content in the documentation.
