### ISSUE TITLE
Requirements for UAV data products needed for plot level analysis

### ISSUE THREAD

**Issue by remotesensinglab** [terraref/computing-pipeline#188]
### Description

For plot level analysis, it would be ideal to have the UAV data processed and prepared in Geotiff file format. 
1. mosaicked and georeferenced.
2. Multispectral data are calibrated using white reference panel data taken before and after the flights.
3. Thermal data are calibrated with blackbody readings and corrected for emissivity when vegetation fraction is less than 1. 

Thanks

**Comment by wheatbreeder** [comment]
Agreed.  We also need annotation regarding camera specs, conditions during flight, flight pattern specs, date, time, etc.     

Should original imagery be warehoused?

How do we add more people to this?  I am a neophyte with github
rick

**Comment by remotesensinglab** [comment]
Good point, Rick! Flight conditions, date and time, etc are very helpful to correlate the data to plant physiology. 

Wasit

**Comment by remotesensinglab** [comment]
To add more people, go to Assignees, and select the people you want to add.

**Comment by dlebauer** [comment]
@remotesensinglab and @Mamatemenrs 
* do you have the files that you need?
* can you review and flush out the UAV documentation? https://terraref.gitbooks.io/terraref-documentation/content/user/protocols-UAV.html

**Comment by rachelshekar** [comment]
@remotesensinglab and @Mamatemenrs please update this issue

**Comment by rachelshekar** [comment]
Rick has already processed some of the data.  He will provide reference data.  Wasit will create Level 1 phenotypic data.

**Comment by rachelshekar** [comment]
Wasit et al  will work on the documentation and requirement for UAV products and data. I think Rick is doing plot level phenotype analysis for the UAV data.

**Comment by craig-willis** [comment]
This is a stale issue with no comments in last 2 months. Please create new issues if work remains or put this content in the documentation.
