### ISSUE TITLE
QA/QC for VNIR scans

### ISSUE THREAD

**Issue by nshakoor** [terraref/computing-pipeline#190]
With the VNIR installed and operational, we need to determine scanning parameters and camera settings to make sure we are getting usable data. 

@czender What are the current sanity checks for the VNIR data?

**Comment by dlebauer** [comment]
@nshakoor it is not clear how this is related to QA/QC.  Given the description above, is this buidling on the work that @JeffWhiteAZ began in the [Hyperspectral calibration and deployment campaign](https://drive.google.com/drive/u/0/folders/0B4JvLJOau3GmR3JRcHZRZEwwR1E)?

**Comment by czender** [comment]
We archive xps_img_max:
xps_img_max=xps_img.max($y,$x);
xps_img_max@long_name="Maximum image exposure at each wavelength";
xps_img_max@units="Counts on scale from 0 to 2^16-1 = 65535";
No light was detected for wavelengths where xps_img_max==0.
Light was overexposed (saturated) for wavelengths where xps_img_max==65535.
Procedures could be put in place to monitor/respond to these situations.

**Comment by nshakoor** [comment]
@dlebauer From what I understood on the call this morning, we have no idea if the VNIR data is usable and this needs to be addressed. Maybe QA/QC is not the right terminology, but what can we do to get this sensor operating so that it is producing viable data? It might be a number of things.

**Comment by dlebauer** [comment]
I think @smarshall-bmr and @solmazhajmohammadi were describing the night-time operations. There are many github issues that cover the individual steps; I think #88 is one of the more relevant @czender. We do still need a good automated QA/QC for all of the sensors; some of this is covered in #84 - but that could be broken out into more sensor-specific analyses.

**Comment by smarshall-bmr** [comment]
VNIR data collected during the day should be usable. Right now the only issue with daytime scanning is the amount of time it takes and the fact that the spectralon panel we are using to calibrate images is more than twice as reflective as anything else in the image. This means we have to crank the exposure time way down to avoid overexposing the spectralon panel and the rest of the image is very dim, even in direct daylight.

**Comment by czender** [comment]
During the calibration telecon a few months ago, it was suggested that the most appropriate spectralon panel to use for calibration would have reflectance closer to that of the brightest plant or soil, e.g., r ~ 30%. Using spectralon r ~95% reduces the dynamic range of the crop measurements by factor of ~3, if my understanding is correct.

**Comment by smarshall-bmr** [comment]
I have the simulated time of the VNIR scan down to 5:56. Does anyone have an opinion on if it is better to run this in a single day or split it over two?

**Comment by solmazhajmohammadi** [comment]
@smarshall-bmr I think it is better to split it over two days and run it around noon.
