### ISSUE TITLE
Upside-down in GeoTiffs

### ISSUE THREAD

**Issue by ZongyangLi** [terraref/computing-pipeline#191]
When I used stitched field map to understand ply files, I notice that it seems upside-down in our field map creations: a higher X position shown in the bottom of the map.
<img width="1346" alt="unormal" src="https://cloud.githubusercontent.com/assets/20230686/19737114/c39c01d0-9b77-11e6-8361-a8e93eebbcc0.png">
In this field map, there is a moscaic in the right-bottom corner, the position of the source image is  x: 23.7335, y: 0.001. The right-top corner's mosaic has a position of x:22.683, y:0.495. So I think this might be unexpected.
@dlebauer I believe I made a mistake on those geotiff creations and I need to update this part of scripts. I am sorry about that, I didn't check carefully when I use [demosaic.py](https://github.com/terraref/computing-pipeline/pull/96/commits/0f1c7d0c44ed6f4236004944af3c7316ff9a1958) as a base script.   The right visualization should be:
<img width="1313" alt="normal" src="https://cloud.githubusercontent.com/assets/20230686/19737227/36baa482-9b78-11e6-9863-1e278133eb33.png">
@max-zilla May I update to repo [extractors-stereo-rgb](https://github.com/terraref/extractors-stereo-rgb) and [extractors-multispectral](https://github.com/terraref/extractors-multispectral) directly? And after that could you update it to Clowder and reprocess the existing creations on `/ua-mac/Level_1/demosaic/` and `/ua-mac/Level_1/flirIrCamera/`.

**Comment by max-zilla** [comment]
@ZongyangLi yes, please update those repositories directly and let me know if you don't have permission. I'll push the updates to Clowder extractors. Thanks!

Reprocessing files can be included in the discussions I have this week with the NCSA team about running the extractors on old files as well (before we finished the code).

**Comment by ZongyangLi** [comment]
@max-zilla Yes, I don't have operate permission to those repo. Please give me the permission. Thanks!

**Comment by max-zilla** [comment]
@ZongyangLi just added you to both as a collaborator with write permissions.

**Comment by ZongyangLi** [comment]
@max-zilla I finished updating scripts.
