### ISSUE TITLE
(re)processing all data

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#197]
objective is to run all deployed extractors on all applicable files/datasets that haven't been processed yet. intend to use Roger job scheduling to do so.

**extractors**
For each of these, implied is that files/datasets will only be queued if metadata belonging to the extractor in question is not found already attached to the document.

_file extractors_
```
ncsa.file.digest = on every file
ncsa.image.preview = on every image file
ncsa.image.metadata = every image file

terra.environmentlogger = on every environmentlogger.json file
terra.ply2las = on every .LAS file
terra.netcdf = on every .nc netCDF file
```

_dataset extractors_
```
terra.demosaic = on every stereoTop dataset
terra.flir.converter = on every flirIr dataset
terra.plantcv = on every Danforth ddpscIndoor dataset
```

More to be run as they come online.

**Comment by max-zilla** [comment]
@robkooper 
The basic template for mongo query I've come up with for datasets:
```
demosaic
db.datasets.find({"name": /stereoTop.*/}).forEach( function(doc) {
	var found = false;
	var extractorname = "terra.demosaic";
	db.metadata.find({"attachedTo._id": doc._id, "creator.name": extractorname}).forEach( function(subdoc) {
		found = true;
	});
	if (!found) {
		print(doc.id);
	}
});
```

I think we may need to introduce an index on metadata collection for this, it was pretty sluggish locally for me handling the metadata subquery.

**Comment by max-zilla** [comment]
@robkooper FYI the demosaic queue went from ~104,000 last night when i stopped the pipeline to ~36,000 this morning with one extractor running. 

About to shut down Clowder and dump the database so I can run the update queries.

(posted this in other issue initially)

**Comment by max-zilla** [comment]
@craig-willis @jterstriep @dlebauer I've stopped Terra Clowder (production) for an hour or two this morning while I run some database updates in prep for next week. Will get it back up ASAP.
- update Clowder file paths for the PLY files we moved, to point to correct location
- assigning Danforth pilot data to "Danforth Site" ownership instead of Max Burnette
- moving Danforth pilot data into Bellweather Facility space instead of Maricopa space

At that point I'll run one test query to see how fast it executes, and may need to add an index to database if it's slow.

Then I can fire things back up while I run the queries to get list of file/dataset IDs for each extractor that we need to submit for processing.

**Comment by max-zilla** [comment]
This database update has been completed and Clowder is back up.

@jterstriep I am starting to generate lists of dataset IDs for various extractors - I'll loop over these when the time comes to queue them all for extraction.

**Comment by rachelshekar** [comment]
can this be closed?

**Comment by max-zilla** [comment]
no. jeff is picking this back up this week.

**Comment by max-zilla** [comment]
Going to close this issue and move discussion to #195 / new issues.
