### ISSUE TITLE
Loss of JPEG output from the SWIR Sensor

### ISSUE THREAD

**Issue by jdmaloney** [terraref/computing-pipeline#198]
Our morning data report indicated that the SWIR sensor stopped sending the JPEG file for each data set to the gantry-cache starting on 2016-11-02, and also so far for 2016-11-03 (don't know about the 4th yet).  These don't show up on the gantry-cache or in its logs.  Is this a known or desired situation?

**Comment by smarshall-bmr** [comment]
The SWIR has just been reinstalled after being out for a month. Expect some anomalies while we get it back online.

**Comment by rachelshekar** [comment]
@jdmaloney - has this been corrected?

**Comment by jdmaloney** [comment]
@rachelshekar Yes, I'll close the issue.
