### ISSUE TITLE
Tractor data points fall outside of the plot boundaries

### ISSUE THREAD

**Issue by Mamatemenrs** [terraref/computing-pipeline#199]
Some of the tractor data points do not overlay with the plot boundary. The problem might be due to the accuracy of the tractor GPS.  One solution is to review each tractor data and manually edit to move them to fit the plot polygons. Has anyone noticed this issue?

**Comment by Mamatemenrs** [comment]
![tractor_aug25_1](https://cloud.githubusercontent.com/assets/22641377/20039638/cd9e8d4a-a40c-11e6-8522-dc8821ec787c.jpg)
![fig2](https://cloud.githubusercontent.com/assets/22641377/20039639/cf0ccde0-a40c-11e6-8509-aaa9e5c92ae0.jpg)

**Comment by rickw-ward** [comment]
![image](https://cloud.githubusercontent.com/assets/21243879/20040126/00a1ba58-a40f-11e6-8a80-53f0ff5c22d3.png)

**Comment by anfrench** [comment]
... and 4)we think that both RTK systems are accurate to cm level, 5) that the non-USDA RTK system has a constant bias at the farm level, meaning that we ought to be able to shift the utm eastings and northings by constant values for all MAC surveys. Those x and y shifts have been mentioned previously but are subject to revision.

**Comment by rickw-ward** [comment]
Talked with John Heun of Pedro's program.  More clarity on how to do this will come tomorrow.

**Comment by dlebauer** [comment]
See documentation https://terraref.gitbooks.io/terraref-documentation/content/user/geospatial-information.html

**Comment by rachelshekar** [comment]
@Mamatemenrs - can this issue be closed?

**Comment by Mamatemenrs** [comment]
Yes, please.
