### ISSUE TITLE
Sample data space 

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#200]
@dlebauer @craig-willis @robkooper @jterstriep 
I have created a sample data space with two examples of various sensors.
https://terraref.ncsa.illinois.edu/clowder/datasets?space=57e42cd44f0cff4b58dd3eea

Where we had extractors, I chose examples where the extractor had been run. No particular reason for any dates or locations. 

I was thinking we could:
- have this space accessible by a shared 'demo' account people can log in as on Thursday
- use one or more of these for a tool launcher example

In addition to these examples we can show the two sample webpages that have been built by @pless and @ZongyangLi:
  - full field mosaic in Google Maps interface  (currently on Roger - we need to get this publicly available somehow)
  - canopy cover interactive example - http://www.cs.wustl.edu/~pless/TERRA/page.html 

The latter is accessible; @robkooper what do you think is best process to expose the html on Roger for the first one? 

@jterstriep any updates on the qsub code? I have a list of datasets to submit for extraction e.g. for demosaic, but didn't catch you on Friday. We can still get that started this week if you are ready but I am thinking we describe the extractor processing as 'in progress' on Thursday so we don't have to rush things in the next day.

**Comment by rachelshekar** [comment]
@max-zilla - should this be closed?

**Comment by dlebauer** [comment]
@max-zilla do we need to re-create this sample data space? We need this for the Feb milestone

**Comment by max-zilla** [comment]
Yes, this needs to be recreated. @robkooper could potentially recover from old database but I think easiest to just make a new one with a couple good samples of each dataset. I'll make sure this gets created next week.

**Comment by max-zilla** [comment]
rebuilding it here: https://terraref.ncsa.illinois.edu/clowder/spaces/57e42cd44f0cff4b58dd3eea

**Comment by max-zilla** [comment]
The sample dataset is now populated.
