### ISSUE TITLE
Toolserver security and authentication

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#204]
NCSA security has started scanning Nebula VMs for security vulnerabilities. One identified vulnerability is unsecured Docker containers, specifically Cloud9 and other services that provide shell access. Currently, toolserver containers use default passwords.

### Description
We should consider adding authentication to the Tool Server containers using non-default passwords. This would also prevent other Clowder users from accessing another user's running instance.   Similarly, we should consider using a reverse_proxy to provide access to running containers instead of opening the Docker ephemeral port range.  

Both of these problems (reverse_proxy and authentication) have been addressed as part of the NDS Labs Workbench [toolmanager](https://github.com/nds-org/ndslabs-toolmanager) and could be incorporated into the TERRA toolserver, if desired. Specifically:
* Front the toolserver with an Nginx or Jupyter https://github.com/jupyterhub/configurable-http-proxy.  
* Add the ability to set basic authentication username/password per container. We've done this with Nginx as well, basically adding htpasswd to the container.  A decision would need to be made whether to use the user's Clowder credentials or require them to set container credentials.

**Comment by robkooper** [comment]
I would like for it to use clowder username and password. This can be done by going to the clowder/api/users/me endpoint with a username and password.

I would love to see how toolmanager works and how it comparses to the toolserver we have. If possible it would be good to use toolmanager.

**Comment by craig-willis** [comment]
Thanks @robkooper.  The "toolmanager" is basically an extended (and misnamed) version of the toolserver to run in the Labs Workbench environment developed for NDSC6.  The idea was to show how to extend the TERRA toolserver to work with other services, in this case Dataverse.  
The main changes were:
* using dind (docker in docker), which is likely unnecessary for TERRA
* fronting with nginx as a reverse proxy, to avoid opening the ephemeral port range. I new proxy rule gets written to the nginx.conf for each container. One caveat is tools may need actual re-writing rules (e.g., JupyterLab), so you can't just add any service for free.

Regarding Clowder user passwords -- I assume they are hashed?  To leverage htpasswd, we either need access to the original password or it needs to be in one of the standard formats (e.g., https://httpd.apache.org/docs/2.4/misc/password_encryptions.html)

**Comment by craig-willis** [comment]
Closing since we will be using Labs Workbench to replace toolserver.
