### ISSUE TITLE
FLIR calibration

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#206]
How close are we to having calibrated data from this sensor?

**Comment by dlebauer** [comment]
@rachelshekar based on https://github.com/terraref/computing-pipeline/issues/151#issuecomment-247247854, my understanding is that this sensor is internally calibrated and the output is in units of milli Kelvin (mK). @ZongyangLi, @Mamatemenrs or @remotesensinglab could you please confirm and close this?

**Comment by ZongyangLi** [comment]
@rachelshekar @dlebauer 
I think there is a parameter in metadata to describe the calibrated vs. uncalibrated data: `"sensor_fixed_metadata": {
"calibrated": "true"
}`

If the raw data is uncalibrated, it would be done in the extractor.
Codes mentioned in #151 had provided an extractor to generate the calibrated data from this sensor. And it had been deployed by @max-zilla .
