### ISSUE TITLE
FLIR - compute plot level means

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#207]
This follows from issue #151 which processed output from the FLIR camera and put Level 1 FLIR data in /sites/ua-mac/Level_1/flirIrCamera

This issue should include the following steps:

* [x] subset FLIR images to the plot level
  * if there is any soil in the image, it should be excluded from the temperature calculation
* [x] generate thumbnail with plot boundaries shown
* [ ] compute mean temperature for the plot
* [ ] insert values into BETYdb

## completion criteria

* [ ] post a sample of the data that will go into BETYdb
* [ ] test deployment to dev environment
* [ ] deploy to production

**Comment by rachelshekar** [comment]
@solmazhajmohammadi - can we use RGB to mask FLIR?

**Comment by rachelshekar** [comment]
Solmaz: I think 3D fusion with IR data would be a better option, using RGB is also good idea. I still have not had a chance to look at the data and test it.

**Comment by rachelshekar** [comment]
@solmazhajmohammadi -please test the data

**Comment by rachelshekar** [comment]
@ZongyangLi - are you still waiting for feedback from @solmazhajmohammadi on this?

**Comment by solmazhajmohammadi** [comment]
@rachelshekar I'm working on deploying it on clowder

**Comment by max-zilla** [comment]
@solmazhajmohammadi let me know if you want to discuss anything. I am just about ready to re-deploy the flir extractor that populates Level_1 directory and get that running again.

**Comment by rachelshekar** [comment]
@solmazhajmohammadi please share the code with Max

**Comment by czender** [comment]
@hmb1 this issue is analogous to what we wish to do with the hyperspectral instruement data

**Comment by solmazhajmohammadi** [comment]
I am writing FLIR mosaic extractor. will finalize this by the end of next week
 still needed to add the search limitation to the code(Issue https://github.com/terraref/computing-pipeline/issues/224), we will discuss this with @max-zilla tomorrow

**Comment by max-zilla** [comment]
@solmazhajmohammadi @ZongyangLi we are actually intending to do this part:
- subset FLIR images to the plot level

...for other sensors as well, so to the extent we can do this in a general way we can reuse the code. we have a shapefile of the plots now (and loaded into geostreams) so maybe we can have a call on next steps for this?

**Comment by ZongyangLi** [comment]
@solmazhajmohammadi  said it's a better option to use 3d fusion with FLIR data to exclude soil from flir camera data. So I didn't do much investigate here. 
I think it will be quite straightforward to get a plot level temperature if we can exclude soil first.

**Comment by solmazhajmohammadi** [comment]
@max-zilla @ZongyangLi 
Subseting the images to the plot level would be a good idea, It helps todo the overlaying RGB and IR as well. Since the IR and RGB data is collected at the same time, this would be another option to exclude the soil from plant, and we can compare the result with 3D +IR

**Comment by max-zilla** [comment]
@ZongyangLi @solmazhajmohammadi #265 I am starting to focus on - to get all images chopped into plot tiles.

**Comment by rachelshekar** [comment]
Changing this to April milestone since dependent on https://github.com/terraref/computing-pipeline/issues/265

**Comment by rachelshekar** [comment]
moved to June; dependent upon https://github.com/terraref/computing-pipeline/issues/265

**Comment by rachelshekar** [comment]
Full field image may not be accurate for this extractor because there is no rule when there are multiple observations for each point.  
If individual images, will use last image recorded per plot.
@dlebauer  - Should we run this on full field or individual images?  If individual, then close.

**Comment by max-zilla** [comment]
We have full field stitching completed and have added code to iterate across the full field for each plot. Just need to finish tests to verify the plot-level means are generated properly, but this will be included in terrautils PR for tomorrow.

**Comment by max-zilla** [comment]
Closing this issue to finalize in https://github.com/terraref/computing-pipeline/issues/465
