### ISSUE TITLE
Conversion of captured images to plot-level tiles

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#209]
This piece of functionality is necessary for several extractors and project deliverables. It is related to #159 that factors out geospatial metadata extraction.

- https://github.com/terraref/computing-pipeline/issues/207 FLIR - compute plot level means
- https://github.com/terraref/computing-pipeline/issues/85 Create full field stitched mosaic

We want to avoid duplicating effort if possible, and share code that may address multiple needs.

DELIVERABLES ARE:

- [x] discussion & determination whether code can be shared across these issues or not

and if appropriate, code snippets that:

- [ ] ingest a set of images & geospatial information, from disk or Clowde
- [ ] ingest plot definition geometries
- [ ] chop images into plot tiles, either in MEMORY or written to FILES on disk

...to the extent this generalized code is feasible. These snippets can be generalized libraries or modules (outside Clowder or any specific extractor) in the /scripts directory so anyone can use them.

**Comment by dlebauer** [comment]
@yanliu-chn and @jterstriep this is the issue that came up today. We discussed options in December but have not yet come up with a generalized approach. I think we determined that it will be helpful to have a generalized approach. However, the next step is to come up with a plan of action. Can one of you take the lead on this?

**Comment by max-zilla** [comment]
I'm going to close this issue as a similar discussion is occurring in #265. Should've just added those comments to this issue initially.
