### ISSUE TITLE
Seraching for a set of data with the same gantry position(IR+3D Fusion)

### ISSUE THREAD

**Issue by solmazhajmohammadi** [terraref/computing-pipeline#224]
@max-zilla, do we have a script to do the following search?
 -Searching among all the IR json files to provide the data that are collected in the same row scan( same gantry position in X axis).

Can we use the whole-field mosaic script for a row scan of IR data? Otherwise I have a Matlab script to do it, I can rewrite it in C++

This is blocking https://github.com/terraref/computing-pipeline/issues/224

**Comment by max-zilla** [comment]
@solmazhajmohammadi i think this should be possible. I'll try to take a look before Thursday.

**Comment by max-zilla** [comment]
@solmazhajmohammadi while this isn't currently possible via UI until I finish rebuilding instance ( #221 ) I can run queries directly against the Mongo database.

For example:
```
> db.metadata.findOne({
"content.lemnatec_measurement_metadata.sensor_fixed_metadata.sensor product name":"A615",
"content.lemnatec_measurement_metadata.gantry_system_variable_metadata.position x [m]":"163.1635"
}, 
{"_id":0, "attachedTo._id":1})

{ "attachedTo" : { "_id" : ObjectId("587185cb4f0cc129fb7a380d") } }
```
...this query says to find all datasets with product name A615 (the FLIR sensor) and a gantry X position of 163.1635. 

The result (I restrict to just one) is an ID of dataset in Clowder. From that ID, we can determine the file path on disk. So I could generate a list of flirIrCamera files on Roger. We can try the full-field mosaic script (https://github.com/terraref/computing-pipeline/issues/85) to see if that will work but I haven't done that before yet.

Do you know the x coordinate you want?

**Comment by rachelshekar** [comment]
x coordinate within one mm. 
what is the margin of error?
what should be done with duplicate data?  use time stamp?

**Comment by max-zilla** [comment]
No specific coordinates, idea is to get coordinate from 3D scanner for various rows and get position of IR around the 3D scan position for each row.

**Comment by solmazhajmohammadi** [comment]
@max-zilla Here is an example:
If the gantry position for 3d-scanner is "X", I should look for all the data that is taken with following X position: 
Range:[ (X - 1.961) to (X + 0.761)]
 The result of the query should be around 10-30 images(depend on the overlap between images, gantry position and etc. ) 1-3 row scan with different Y position.

Following steps should limit the duplicated data:


_**Velocity**=set velocity in IR metadata ("y set velocity [m/s]") 
**Y_min**= among all the IR data with same X position("position x [m]"), find the minimum Y position ("position y [m]") 
**Y_max**= among all the IR data with same X position("position x [m]"), find the maximum Y position ("position y [m]") 
**Y_end**= end poistion in the IR metadata ("y end pos [m]")
**Row_scan**= max ( | (Y_min - Y_end) | , | (Y_max - Y_end) |)
**Number_of_rows**= number of different Y positions (it should be1-3 rows)
**Time_min**= find the start of the scan(minimum time)_



_**1: all the IR data should have same Velocity**
**2:  Row_scan should be greater than 18m (meaning: it is a full row scan)** 
**3: All the data should be taken within following time range:
Time=Time_min + Row_scan/Velocity*Number_of_rows + some_constant_time**_

**Comment by dlebauer** [comment]
when this is finished, can move on to https://github.com/terraref/computing-pipeline/issues/224

**Comment by max-zilla** [comment]
Once we split these files into plot-level, this issue should become unnecessary because we can find data in the same plot/day instead of needing specific gantry position. #265

**Comment by max-zilla** [comment]
issue that affects fusion algorithm - temp changes alignment, due to expansion of metal. may be few cm movement from this shift.

**Comment by dlebauer** [comment]
closing since no one is curently working on sensor fusion
