### ISSUE TITLE
Install empty BETYdb on Nebula Open Stack for TERRA project

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#23]
BETYdb is configured to be deployed and synced across many servers, and is used by distinct projects and research programs. The central database, betydb.org, is hosted at IGB (betydb.org; ebi-forecast.igb.illinois.edu).

I propose that we create a new instance of BETYdb for this project as a subdomain of terraref.ncsa.illinois.edu (on some server). This will distinguish it (and its contents and applications, which are distinct) from the central BETYdb.org. This would allow us to launch a 'fresh' instance for the program, while still retaining the capacity to import and share data with the original and other instances.

The TERRA program is focused specifically on a large number of genotypes / lines within a single genus (Sorghum), a small number of sites with very high precision measurements of plots, subplot, and individual plant locations, and will store data for a very specific subset of traits, data formats, and sites. Establishing a distinct instance of BETYdb will make this easier. Furthermore, it will enable users within the TERRA program to focus on this very specific subset of BETYdb instances, many of which may be deployed on the Nebula OpenStack.

At deployment, all tables should be empty, and we can import specific records where necessary (e.g. the subset of Sorghum species that will be studied).

**Comment by dlebauer** [comment]
duplicate of #24

**Comment by robkooper** [comment]
Any reason to start with empty database and pre-populate it with the data from the other sites (i.e. give it a new unique id)?

**Comment by dlebauer** [comment]
We should have a unique id, and open to pushing data out.

Are you asking why not pull data from EBI, BU, BNL, UW, etc? The reason is
that most (99.99%) of the records are outside the scope of this project,
which will have a few species and sites, and I think it will be much easier
for users if all of the content is specific to our sensors, sites, and
species.

We can discuss next week.

Also, I am suggesting nebula because I understand it is a production
environment; and seems a good fit conceptually with ADS. Is a this the
correct rationale?
