### ISSUE TITLE
Subset brightest pixels for PSII images. 

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#240]
Adjust approach to use the brightest pixels and use these to compute Fv/Fm.

This is a suggestion from the group at Rothamstead, but should be discussed first.

### Completion Criteria

* [x] decide how to threshold the images
* [x] implement in the pipeline.

**Comment by nfahlgren** [comment]
On the one hand, thresholding these images is easy because fluorescence is very selective for plant vs non-plant. On the other hand, fluorescence will be low for leaves angled away from the camera, so thresholding will have to compromise somewhere.

**Comment by dlebauer** [comment]
@nfahlgren the idea from Malcolm was to threshold the 'brightest pixels' (which needs to be defined) ...

**Comment by dlebauer** [comment]
By brightest - I mean those that are oriented perpendicular to the camera, excluding those angled away.

**Comment by TinoDornbusch** [comment]
@nfahlgren  I have two ways in mind:
1. Compute Probabilty density function of intensity in the PS2 image. Use the 99 percentile for measure of brightest Pixel (to avoid outliers). Use a threshold relative to this.
2. Use a local adaptive threshold

**Comment by dlebauer** [comment]
@TinoDornbusch are you working on this? Will it be ready by the end of May?

**Comment by max-zilla** [comment]
do we want to come back to this, or is this issue obsolete now given our other approach with Solmaz' extractor?

**Comment by dlebauer** [comment]
extractor in https://github.com/terraref/extractors-multispectral (is that the best place for this?)

**Comment by nfahlgren** [comment]
@dlebauer looks like we put all the extractors that deal with specific wavelengths in some way in there.

**Comment by solmazhajmohammadi** [comment]
@max-zilla 2017-5-26 is the only day that light and dark adopted data was collected.

Here is the set of collected output data:
FM_Dark:
![test_fm_dark](https://user-images.githubusercontent.com/17046539/27449384-de3ac958-574d-11e7-893f-7a4a1eabea65.png)
FM_Light:
![test_fm_light](https://user-images.githubusercontent.com/17046539/27449421-f8b574d6-574d-11e7-9002-901fcc5484ae.png)
Fv_Dark:
![test_fv_dark](https://user-images.githubusercontent.com/17046539/27449434-04a05b62-574e-11e7-9485-de34da7667c9.png)
FvFm_Dark:
![test_fvfm_dark](https://user-images.githubusercontent.com/17046539/27449445-0de7016c-574e-11e7-8829-759d6d4bec30.png)
Fv/Fm files are already calculated in the PSII extractor, the new features are:

NPQ:
![test_npq](https://user-images.githubusercontent.com/17046539/27449456-17f70724-574e-11e7-802f-d730d884bf7b.png)
Phi_PSII:
![test_phi_psii](https://user-images.githubusercontent.com/17046539/27449463-1ea9b788-574e-11e7-9b02-029d7d3a8de4.png)
qN:
![test_qn](https://user-images.githubusercontent.com/17046539/27449473-29f978d0-574e-11e7-80d0-2e3de8b1c1bd.png)
qP:
![test_qp](https://user-images.githubusercontent.com/17046539/27449480-2e80e758-574e-11e7-9a47-8bc7c2f555ce.png)
Rfd:
![test_rfd](https://user-images.githubusercontent.com/17046539/27449492-3aca2826-574e-11e7-8369-4c8a8cffb6eb.png)

The mask used in the code, is setting a threshold to 10% of max value.
