### ISSUE TITLE
Come up with a good way to populate traits.cultivar_id based on traits.site_id and of ensuring the two are consistent.

### ISSUE THREAD

**Issue by gsrohde** [terraref/computing-pipeline#241]
We discussed using some sort of trigger function that would be activated whenever a trait is inserted or the site_id or cultivar_id of a trait is updated.

See https://github.com/PecanProject/bety/issues/475.

**Comment by rachelshekar** [comment]
@gsrohde - what is the action here?  Or is it a discussion?

**Comment by dlebauer** [comment]
Action is writing and implementing the trigger function

**Comment by gsrohde** [comment]
Closing.  This is superseded by issue https://github.com/PecanProject/bety/issues/475 and pull request https://github.com/PecanProject/bety/pull/504.
