### ISSUE TITLE
Toolserver instability issues

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#242]
We've had several reports of the toolserver being unavailable on both Clowder instances. When investigating the reports, the toolserver instances have been running and responsive.

The purpose of this ticket is to track incidents, identify the root cause, and resolve the problem.

The toolserver API is currently open on port 8080, unsecured. The contain logs suggest a fair amount of malicious traffic (SPAM, attempted logins, etc).  Current node is m1.medium (2vcpu, 4GB RAM) which is insufficient for running even a few copies of containers like Jupyter or Rstudio.

### Completion Criteria   
* [x] Both toolserver instances are monitored by Nagios/Checkmk
* [ ] Improve logging
* [x] Restrict access to port 8080 to Clowder instances only
* [ ] Provision larger instance for production (nrcd1-xlarge)

**Comment by craig-willis** [comment]
The main toolserver instance was affected by the OpenStack outage on Sunday (FS was read-only).  The API was responding but wouldn't create new instances.  I've rebooted the instance.  The toolserver-dev instance was unaffected.

**Comment by robkooper** [comment]
Can we start with blocking port 8080 to the world and only give access to NCSA.

**Comment by craig-willis** [comment]
I've added a new security group for the toolservers restricting 8080 to 141.142.208/20 to cover the two Clowder instances.  I also added the Docker ephemeral range. I hate that we open this, but until I get the nginx proxy in place it needs to stay open.

**Comment by craig-willis** [comment]
@robkooper Are both instances monitored now?

**Comment by robkooper** [comment]
which 2 instances?

**Comment by craig-willis** [comment]
toolserver (141.142.210.18) and toolserver-dev (141.142.210.19)

**Comment by robkooper** [comment]
both monitored

**Comment by rachelshekar** [comment]
There has been a discussion of SSO within TERRA.  Nebraska said it's easier that it used to be.  However, this is not the highest priority. - David
Globus SSO would be complex because it has a shared endpoint. - @jdmaloney will double check

**Comment by craig-willis** [comment]
Closing this since Toolserver will be replaced by Labs workbench.
