### ISSUE TITLE
Add tools to toolserver

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#243]
Tracking ticket for updates to the production toolserver instance.

List of tools to add
* jupyter+plantCV 
* rocker/geospatial
* rocker/ropensci (RStudio analysis environment) 
* ndslabs/cloud9-pyclowder (Cloud9 devlopment environment for pyClowder)
* ndslabs/jupyterlab-pyclowder (JupyterLab alpha environment)

# Completion criteria
* [x] Confirm list of tools to add
* [x] Update tools on toolserver instance
* [x] Update tools in SCM

**Comment by dlebauer** [comment]
Two more to add:

* jupyter+plantCV (This could replace the Basic Jupyter notebook)
* rocker/geospatial
