### ISSUE TITLE
Deploy Labs Workbench for Phenome2017

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#244]
The Phenome2017 workshop will use a dedicated instance of the Labs Workbench environment.   This will need to support ~30 users running rocker/ropensci and rocker/geospatial environments.

### Completion Criteria   
* [x] Deploy dedicated cluster in OpenStack/NDS-hackathon space
* [x] Custom service catalog (i.e., git repo) with rocker tools and Jupyter/PlantCV
* [x] DNS entry for www.phenome2017.ndslabs.org
* [x] Pre-create user accounts
* [x] Acceptance testing
* [ ] Documentation as needed

**Comment by craig-willis** [comment]
* http://www.phenome2017.ndslabs.org/ is now responding.
* https://github.com/nds-org/phenome2017-specs currently has service definitions for the rocker/ropensci and geospatial containers

**Comment by craig-willis** [comment]
Added Jupyter/PlantCV container. The container includes the PlantCV github repo under /plantcv including sample data. I've attached a very simple Jupyter notebook based on the PlantCV documentation.

[PlantCV.ipynb.zip](https://github.com/terraref/computing-pipeline/files/750925/PlantCV.ipynb.zip)

**Comment by nfahlgren** [comment]
Not sure if any of this would be useful: https://github.com/danforthcenter/plantcv-workshop. We have some PlantCV Jupyter notebooks and some R Jupyter notebooks we used for a workshop.

**Comment by craig-willis** [comment]
Thanks, @nfahlgren. I'll leave it to David to decide.

Curious -- do you already have Docker images with the Jupyter/R + PlantCV dependencies installed?

**Comment by nfahlgren** [comment]
@craig-willis I don't, but I should learn how to set up one up one of these days...

**Comment by craig-willis** [comment]
@nfahlgren Well, we have one for you now:

https://hub.docker.com/r/terraref/jupyter-plantcv/
https://github.com/terraref/toolserver-dockerfiles/tree/master/plantcv

I just launched the container, opened a terminal in Jupyter and cloned your workshop tutorial repo and the notebooks worked like a charm!

If you're ever interested in taking ownership of the Dockerfile and image, it's yours for the taking.

**Comment by nfahlgren** [comment]
@craig-willis nice, thanks!
