### ISSUE TITLE
add extractor for met data from Illinois

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#245]
Update the [extractors-meteorological](github.com/terraref/extractors-meteorological] extractor to accept met data collected from the UI Energy Farm.

Data are available on Box here: https://uofi.app.box.com/files/0/f/11140468834/Public and a sample to get started with are here: 
[Weather CEN_Avg15_test.txt](https://github.com/terraref/computing-pipeline/files/743283/Weather.CEN_Avg15_test.txt)

They are updated every few days, so the extractor will need to 

* download the files
* recognize the difference
* convert data to std. format defined in #156
  * fields to keep include 
     * "TIMESTAMP", 
     * "AirTC_Avg",         "air_temperature, K": 
     * "RH1_Avg",         "relative_humidity, %": 
     * "WindSpd_Avg",                 "wind_speed, m/s":
     * "WindDir_Avg",      "wind_to_direction, degrees"
     * "PAR_APOGE_Avg",  "surface_downwelling_photosynthetic_photon_flux_in_air, mol m-2 s-1":
     * "RAIN_Tot",         "precipitation_rate, mm/s":
     * "PRESSURE_Avg", air_pressure (Pa) 
   * https://github.com/terraref/computing-pipeline/issues/156#issuecomment-252115559
   * for any variables not defined in 156, get names / units here: http://cfconventions.org/Data/cf-standard-names/39/build/cf-standard-name-table.html
* insert into geostreams API
  * there will be three 'sensors' representing three met stations named 'SE', "NE" and "CEN" ... prepend "Energy Farm Met Station" to the sensor name

For more info on the met data format see the PEcAn specification:  https://pecan.gitbooks.io/pecan-documentation/content/developers_guide/Adding-an-Input-Converter.html

These are 15 minute averages, so (unlike the current extractor) the data do not need to be upscaled. 

### Completion Criteria

* [x] figure out how to get the extractor triggered by data that appears on box (@max-zilla?)
* [x] write extractor that is triggered by the raw data type and inserts into the geostreams API
* [x] deploy extractor to the terraref Clowder instance

**Comment by harshagrawal28** [comment]
I have modified the extractors-meteorological to process data from UI energy farm but I don't know how the extractor can be triggered by data that appears on box. 

 I tried testing the extractor on my local instance of Clowder but I was unable to upload the metadata.  It works when I try the wordcount extractor but not using meteorological. This content is new to me so I would need some help on this.

**Comment by dlebauer** [comment]
Please follow up with @Zodiase;  @max-zilla may also have some suggestions- 

For the data on Box, I imagine the workflow could go something like:

* set up daily cron job to 
  * download files from Box
  * diff oldfile newfile > maricopa-met-YYYYMMDD.csv
  * triggered by maricopa-met-YYYYMMDD.csv

But I am less familiar with the extractor configuration.

**Comment by harshagrawal28** [comment]
The current meteorological extractor is triggered when a new dataset of 24 files is uploaded to Clowder. When should this extractor for the Energy farm be triggered? Any particular way the files will be uploaded to Clowder?

As of now, the extractor is triggered by seeing any .dat file and is able to get the difference between the new and old file. The old file is stored on my local machine but where should it be stored when the extractor is deployed?

**Comment by rachelshekar** [comment]
@max-zilla please advise

**Comment by harshagrawal28** [comment]
I have created a pull request for this extractor here terraref/extractors-meterological#4.

**Comment by max-zilla** [comment]
@harshagrawal28 thanks, will take a look
