### ISSUE TITLE
Change Clowder landing page title and description

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#247]
The current landing page is not informative for users that are not familiar with Clowder.

For example, the [SEAD](https://sead2.ncsa.illinois.edu/) project simply calls the instance "SEAD"  and provides a description of the service. 

I suggest that we consider the following:
* Rename Clowder to "Sensor Data Portal" or similar
* Remove references to Clowder from the landing page
* Provide a brief description of the service and what first time users should do and expect (e.g., click Sign-up to register for access, etc.).

**Comment by dlebauer** [comment]
That sounds great ... In the description, there should also be a description of the tool launcher. Is there a simple way to link to the environment manager from the front page or user home page?

**Comment by craig-willis** [comment]
I'll need input from @max-zilla or @robkooper  on this one. We can certainly link to the environment manager from the description, but I'm not sure how difficult it would be to add it elsewhere in Clowder.  I'm also not sure of the steps or effort required to customize Clowder as I've suggested above.

**Comment by robkooper** [comment]
@craig-willis made you admin, you can change some aspects right now.

**Comment by robkooper** [comment]
If there is a writeup somewhere we can add a link to the Help menu as well (I will need to do that from the command line).

**Comment by craig-willis** [comment]
@rachelshekar Do you want to weigh in on what to call this and what should be in the description?

**Comment by rachelshekar** [comment]
@craig-willis Let's change this to sensor data portal for now and revisit later.

**Comment by craig-willis** [comment]
This was done last week, closing.
