### ISSUE TITLE
List TERRA-REF extractors, algorithms, data that we want/will have for 2017

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#249]
- [x] Add to excel spreadsheet
- Name
- Level
- Location
- ...
- [x] Add to powerpoint
- [x] Work with contributor to verify all outputs

References in Google Docs:
* [Overview slide](https://docs.google.com/document/d/1zmpXNcrxUrKsO1YwXZA3VegfI1j0S8bUjTTHimmM7p4/edit)
* [TERRA REF pipeline extractors spreadsheet](https://docs.google.com/spreadsheets/d/1LLiQSFHbEWoo_FkvG1nl-XoSq_lZ_o6VazfxmPfOH9Y/edit#gid=0)
* [list of extractors / phenotypes scheduled for fall release](https://docs.google.com/presentation/d/1be6d12byKo59On--NZHKcRAoh9K-dOQeI23sUJQcgiA/edit#slide=id.g183aafb390_0_4)

**Comment by rachelshekar** [comment]
@remotesensinglab @solmazhajmohammadi @nfahlgren @ZongyangLi  @rmgarnett 
Please make sure your work is represented correctly on https://docs.google.com/spreadsheets/d/1LLiQSFHbEWoo_FkvG1nl-XoSq_lZ_o6VazfxmPfOH9Y/edit#gid=0

**Comment by rachelshekar** [comment]
Need extractors by end of May for v1 release in November

**Comment by rachelshekar** [comment]
@rmgarnett @nfahlgren @solmazhajmohammadi @pless  @ZongyangLi 
Please review the extractors at https://docs.google.com/spreadsheets/d/1LLiQSFHbEWoo_FkvG1nl-XoSq_lZ_o6VazfxmPfOH9Y/edit#gid=1888797382 
Confirm that you intend to have these extractors ready for the November release.

Please let us know if anything is missing.

**Comment by rachelshekar** [comment]
For November release:
Due date for extractors = May 31
Due date for 2016 data = May 31

**Comment by remotesensinglab** [comment]
Hi Rachel,
The due date for the milestones highlighted in yellow is May 31? it will take some time for us as it rely on field data collected in this summer. 

Thanks,

**Comment by dlebauer** [comment]
@remotesensinglab can you write this against the 2016 data, or else put up a draft that uses simulated / sample data?

**Comment by max-zilla** [comment]
For what it's worth, we also have some 2017 imagery with plants in them from the last couple weeks, not sure what your criteria is but perhaps those could work?

**Comment by remotesensinglab** [comment]
We can write a model/index however the it is still ongoing research which requires grout-truth data to calibrate for the sorghum. I would not be comfortable to throw out some indices that are not tested. I hope to have something in a couple of months with the data to be collected this summer. Stomatal conductance and fluorescence data to be measured this summer would be very helpful for this.

**Comment by rachelshekar** [comment]
Data list: https://docs.google.com/spreadsheets/d/1dpO8HTnBVF-ql79hbLkqHiyaWN3tibrzTCuefe2iL8U/edit?usp=sharing
