### ISSUE TITLE
Permissions on Danforth Globus endpoint

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#251]
@nfahlgren when I connect to the Danforth Center Biomatics Globus endpoint with my mburnet2 account, I can see the sorghum_pilot_dataset folder listed but if I try to browse into it:
```
EndpointPermissionDenied

Denied by endpoint, Command Failed: Error (list) Endpoint: Danforth Center Bioinformatics (26fcc6fe-bbd7-11e6-9b65-22000a1e3b52) Server: chronos.bioinformatics.danforthcenter.org:2811 Command: MLST ~/sorghum_pilot_dataset/ Message: Fatal FTP Response --- 500 Command failed : Path not allowed.\r\n
```

I need to get the SnapshotInfo.csv files with plant barcodes so I can rebuild the Clowder collection with proper metadata (danforth pipeline parses barcode from it into several traits that extractor requires to be present). Can you grant me permission on those (or at least share the CSV file so I can get the barcodes)? Thanks.

**Comment by nfahlgren** [comment]
@max-zilla sorry about that, I locked down filesystem access to home directories and a few explicitly shared paths. I added the sorghum_pilot_dataset path to the whitelist, so you should have access now.

**Comment by max-zilla** [comment]
Bingo. Thanks @nfahlgren
