### ISSUE TITLE
Dataset URL sent to tool launcher missing protocol

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#256]
The dataset URL sent to the tool launcher is missing the protocol, resulting in failed download.   This may be a Clowder or Nginx configuration problem?

What I see in the tool launcher:
```
terraref.ncsa.illinois.edu/clowder-dev/api/datasets/58920d9ae4b007e405e03301/download
```

[ToolManager line 57](https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/clowder/browse/app/controllers/ToolManager.scala#57)
```
val hostURL = request.headers.get("Host").getOrElse("")
```

[ToolManagerPlugin line 214](https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/clowder/browse/app/services/ToolManagerPlugin.scala#214)
```
val dsURL = hostURL+controllers.routes.Datasets.dataset(datasetId).url
```

Via Chrome Developer Tools, I see the following host header:
```
Host:terraref.ncsa.illinois.edu
```

### Completion criteria
* [ ] Clowder sends correct URL or
* [ ] Toolserver updated to handle empty protocol

**Comment by robkooper** [comment]
use https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/clowder/browse/app/controllers/Utils.scala#17

**Comment by rachelshekar** [comment]
Craig to do a short-term fix.  Rob/Max will work on a long-term solution.

**Comment by max-zilla** [comment]
Pull request created: https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/clowder/pull-requests/1118/overview
