### ISSUE TITLE
Remove existing genomic data

### ISSUE THREAD

**Issue by nfahlgren** [terraref/computing-pipeline#258]
The current genomic raw data in `/hudson-alpha/raw_data/2016-03-21/` is somewhat derived (it was converted from bzip2 to gzip). I would like to upload the original bzip2 files as @phloz's pipeline now takes bzip2. Could we remove the above folder since I will replace it?

It's not blocking anything as is, so it's low priority.

**Comment by dlebauer** [comment]
Please go ahead and delete it if you have permissions. If not, let me know.

**Comment by nfahlgren** [comment]
@dlebauer ah I see, I can request deletes from Globus. Not sure if you or someone approved it, but it worked. Thanks!

**Comment by dlebauer** [comment]
sorry - I thought you were talking about cyverse ... I love to rm -rf
everything!

**Comment by nfahlgren** [comment]
Who doesn't :)

Noah
--
Director, Bioinformatics Core Facility
Donald Danforth Plant Science Center
975 North Warson Road
St. Louis, MO 63132
Email: nfahlgren@danforthcenter.org
Phone: 314-587-1676
