### ISSUE TITLE
Create a dedicated test location for all sensors

### ISSUE THREAD

**Issue by nshakoor** [terraref/computing-pipeline#260]
From email conversations with @solmazhajmohammadi and @rmgarnett, can we dedicate part of the field (5-6 meters) for regular test routines for the 3D scanner, hyperspectral, and other sensors? We can put the spectralon target as well as multiple targets with different known heights in the field and scan the area every day or week. We should have a separate pipeline running this dataset to make sure that collected data is OK.

**Comment by smarshall-bmr** [comment]
@nshakoor @solmazhajmohammadi @rmgarnett @remotesensinglab I should be able to set aside some area at the north end of the field to set up targets and reimplement the 6m daily scan. Do you have any specific scans you would like? @dlebauer would you have any recommendations for setup of the script so it runs through a separate pipeline? It would be great if this separate pipeline could be run locally or provide quick feedback for sanity checking as I collect data. As of now I still have to manually download data from the cache server and convert the bins myself if I want to view data before it's available on Clowder.

**Comment by rmgarnett** [comment]
Indeed there should be a larger discussion here.  Ideally we could have a quick, lightweight sanity check for the entire sensor suite that could be completely automated while taking only a small fraction of the field and the scanner time.

**Comment by rachelshekar** [comment]
FYI @max-zilla

**Comment by dlebauer** [comment]
@nshakoor what are the next steps on this? Should we discuss at the next Tuesday teleconference?

**Comment by craig-willis** [comment]
Stale issue. No comments in last 2 months. If necessary, create new issues based on this discussion.
