### ISSUE TITLE
Summarize trait data from current season

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#261]
Create a web page that summarizes:

* current experiments: records in experiments table for current season (or most recent season)
  * select records in experiments table w/ no end_date, or if none exist the most recent end_date
* records from managements table that occurred during currently running experiments
   * select all records from managements where date between experiments.start_date and experiments.end_date
* trait data collected during currently running experiments
* for each value of variables.name (or variable_id in traits table), plot:
  * histogram
  * time series of boxplots (or similar, including median, quantiles, outliers max/min) (time is (traits.raw_date)
  * time series of records per day observed (traits.raw_date)
  * time series of records per day created (traits.created_at)
  * these should be colored by the value in the 'methods' field

Generate a table with the following
* number of NULLs for each of the following fields in the traits table: site_id, citation_id, cultivar_id, treatment_id, variable_id, user_id, method_id, cultivar_id,

For the purposes of developing a prototype (and until the experiments api is deployed) please start with Sorghum Season 2 which ran from 2016-08-03 to 2016-12-02

### Completion Criteria   

* [x] code to generate web page in the reference-data repository
* [ ] live web page for each season with above listed summaries.

**Comment by dlebauer** [comment]
@nickheyek

**Comment by rachelshekar** [comment]
@nickheyek -  can you please give an update on this below?

**Comment by nickheyek** [comment]
Sure!
At this point I have implemented code to pull data from the BETYdb API and create box plots for data associated with each variable measured in a given experiment. This is written in Python using the Pygal library.
Additionally, I have implemented a web application using the Flask web framework that displays the box plots mentioned above. Also on this web application is a timeline of managements data associated with a given experiment.
Currently I am in the process of making corrections and improvements to the existing code. I am also waiting for an 'experiments' endpoint to be added to the beta BETYdb API so that my application can function independently (right now it requires just plugging in a date range).
My code is in the reference-data repository within experiment-trait-data-visualizer under the 'feature' branch.
Let me know if there's anything else you need.

**Comment by dlebauer** [comment]
Have you submitted a pull request? You can visualize html checked into
GitHub with htmlpreview.github.io/ or http://rawgit.com/

Perhaps put the html in a separate repository or gist for review.

**Comment by nickheyek** [comment]
I have not submitted a pull request, I will do so today.
Because the HTML is not static it won't render without the backend,
but I can create a static HTML equivalent with placeholder data.
I'll also do that today.

**Comment by rachelshekar** [comment]
@max-zilla where will we put html files like this?

**Comment by max-zilla** [comment]
talked with @robkooper @craig-willis @jterstriep 

Initial plan is to create a new /html directory under /sites/ua-mac alongside raw_data and Level_1. We can deploy the python code to pull from BetyDB and generate the HTML page with a cron job running in a VM that has Roger mounted, maybe the terra.org VM even. That cron job will run python script to generate latest HTML. Then we serve the static HTML file from where it is. 

Craig had mentioned running in a container as another option.

**Comment by dlebauer** [comment]
@max-zilla here is the pull request: https://github.com/terraref/reference-data/pull/110

**Comment by dlebauer** [comment]
This is a flask application. It has a cache. @nickheyek is planning to have it update the cache each day. It could be dynamic except that the API call is too slow.

**Comment by dlebauer** [comment]
@gsrohde is there an experiments API endpoint ready to be deployed?

**Comment by dlebauer** [comment]
@gsrohde actually I realized that I submitted a PR a few weeks ago https://github.com/PecanProject/bety/pull/484 that --should-- add the experiments endpoint.

**Comment by gsrohde** [comment]
OK, I pulled that request.

**Comment by robkooper** [comment]
So since this is a flask app, we should either create a docker container, or a VM that hosts the machine and add a link in the terraref web app.

@nickheyek is this a docker container already?

**Comment by nickheyek** [comment]
It is not. Unfortunately I do not have any experience with Docker.

**Comment by robkooper** [comment]
We will need to create you a VM and give you access to the VM so you can deploy your code there. @dlebauer can you work with me to get @nickheyek access to NCSA accounts.

**Comment by gsrohde** [comment]
@robkooper Can you figure out why Travis is failing after I pulled this?  It complains 'relation "experiments" does not exist'.

**Comment by robkooper** [comment]
@gsrohde can you create a new issue for that. That is not related to this issue.

**Comment by dlebauer** [comment]
Indirectly related because the app will eventually use the experiments
table

I think Nick already has an NCSA account as a guest. Is that correct Nick?

**Comment by nickheyek** [comment]
Not that I know of.

**Comment by dlebauer** [comment]
@robkooper I've submitted a guest account request for Nick. Is it possible for him to use terraref.ndslabs.org to deploy the VM/docker image?

**Comment by rachelshekar** [comment]
@dlebauer  -  this is waiting for review.

**Comment by dlebauer** [comment]
The first draft is here: http://141.142.211.143:5000/

But it has a few issues:

* does not dynamically update
* only has data from one season.

@nickheyek and I will work on this this summer. A good target would be the July Sprint. I'll convert this to an epic.

**Comment by rachelshekar** [comment]
@nickheyek do you have a more recent draft with a different URL than http://141.142.211.143:5000/
I think David showed me something a bit different...

**Comment by nickheyek** [comment]
That is the most recent draft. I had planned to begin working on creating a higher quality R/Shiny version when the SPIN internship period begins on the 12th.

**Comment by dlebauer** [comment]
@nickheyek has this been replaced by a new epic?

**Comment by nickheyek** [comment]
Yes

**Comment by dlebauer** [comment]
Can you link to the new epic and close this one?

**Comment by nickheyek** [comment]
https://github.com/terraref/reference-data/issues/142
