### ISSUE TITLE
Mass conversion of raw data to plot-level tiles

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#265]
in brief discussion between @dlebauer and I last Friday, we talked pros & cons of just splitting all our imagery data into plot tiles, like for every sensor we would:
1) transfer raw data to Roger
2) level 1 extractors convert raw data into GeoTIFF
3) we have process that scans a day of GeoTIFFs from a sensor and creates plot-level tiles
4) level 2+ extractors operate on plot GeoTIFFs
5) later on we remove original raw files and only keep plot-level

idea being that in step 3 we use a more generalized version of the [stereoTop full field mosaic extractor](https://github.com/terraref/extractors-stereo-rgb/tree/master/mosaic) that operates on geoTIFFs. Thus we funnel all extractors -> GeoTIFF format (we can still make JPGs for quick previewing). To kick things off:

PROS
- scientists likely to care about plot-level analysis in most cases; easier to work with and understand what you're seeing
- easier to compare same plot location across time/sensors w/ aligned imagery
- reduce stitching/overlap handling required on data scientist side if we don't perform this clip for them, or reduce computational overhead if we otherwise would dynamically query plots from netCDF files (for example)
- we could consistently organize data by sensor x time x plot across entire project structure, not just in geostreams/bety GIS databases (e.g. in Clowder and in filesystem directories)

CONS
- muddles data organization somewhat; datasets as organized on Roger disk and in Clowder would no longer apply. instead each plot could include 2+ distinct timestamps that were stitched together to form the plot image you're seeing so we'd have:
```
raw_data/
  stereoTop/
    2016-02-02/
      2016-02-02_12-32-32-123 Range 23 Pass 6/
        files
```
Now, maybe if we apply givens about the gantry we could assume we wont have more than 1 capture per plot, per sensor, per minute, so we drop the milliseconds from the timestamp or something. or we sort by plot:
```
raw_data/
  stereoTop/
    2016-02-02/
      Range 23 Pass 6/
        2016-02-02_12-32-32-123 
          files
```
- impact on storage plans. effectively plot tiles would become defacto "lowest level raw data" that is in the data release, so the actual raw imagery could be archived and deleted. this would be a complex process with all the issues JD and i face elsewhere in terms of making sure a full day of data is present before performing the tiling, 
- less flexibility if, theoretically, one wanted to query some arbitrary ground footprint later on that is not a specific plot boundary - if we dont implement mechanisms to dynamically query netCDF, for example. if we DON'T precompute the tiles, perhaps we can offer a dynamic way to chop things on the fly.

I think one way or another we need to provide imagery at the plot-level; either pre-clipped, or some means to quickly clip on demand (e.g. for plot-level extractors). so maybe a better question is, **what's easier: a bunch of complexity to achieve the clipping above, or something like THREDDS to juggle big netCDFs on the fly?** As I write this out, pre-clipping seems like a tall order, but maybe it saves us headaches later on... decided to just toss it on the table.

tagging @jdmaloney @jterstriep @yanliu-chn as FYI also.

**Comment by max-zilla** [comment]
Note that the script I linked does NOT create plot-level tiles. Basic logic for mosaic extractor is:
- convert stereoTop .BIN files to GeoTIFF (this shouldn't be necessary since demosaic already does that - we should update to make it check for those first)
- get list of all GeoTIFFs inside the field bounds for one day, and create a VRT (virtual TIF) that combines them all
- feed VRT to [gdal2tiles_parallel.py](https://github.com/GitHubRGI/geopackage-python/blob/master/Tiling/gdal2tiles_parallel.py) which prepares for Google Maps global tiles

The theoretical plot clipping extractor would chop the VRT into new TIFs based on each polygon in our plot definition.

**Comment by max-zilla** [comment]
@robkooper @jdmaloney @yanliu-chn @dlebauer @czender 

Just spoke with Rob about moving this forward. I basically suggested:

- we have extractors that convert raw sensor images into standard geocoded GeoTIFF format
- we have a work script we run on Roger filesystem directly outside Clowder, probably a worker with some hefty memory.
  - loop across each sensor x day directory of GeoTIFFs
  - stitch the day's images together into one full field image (using VRT, or streaming or something)
  - clip full field image into images by plot
  - create aggregate metadata for the new plot image (e.g. timestamp down to the minute it was captured, even if multiple captures are blended into one plot)
  - organize data in Clowder by plot & date, once you get to single day collection you see a nice list of a single plot-level image for each sensor for that plot
  - we no longer store raw data/metadata in Clowder - the plot-level GeoTIFFs are "base level" data products for outside world

Main questions/concerns:
- What does this mean for data usage projections i.e. our 10 PB estimate? we need to get a basic sample of the code working on one of the datasets to see how big the plot images are - the stereoTop existing mosaic code isn't a perfect comparison
- How quickly can we be confident we have all the images from a day to be able to stitch & chop? 48 hours? 36?
- do we need a buffer around plot boundaries/is there concern about the non-overlap between polys in the shapefile? this could be both a boon in terms of overall file size for a day, and a negative if there is anything of interest in between:
![screen shot 2017-03-15 at 10 35 21 am](https://cloud.githubusercontent.com/assets/14166971/23956658/35320b80-096b-11e7-85a7-becc974a6aec.png)

**Comment by czender** [comment]
Mentioning @hmb1 since he is looking into efficient means of clipping netCDF to shapefiles...

**Comment by max-zilla** [comment]
@czender thanks. forgot to mention that I tagged you because I imagine the hyperspectral data might do this slightly differently than the others... e.g. maybe we bypass the GeoTIFF and modify your script to generate the .nc files per plot instead?

**Comment by czender** [comment]
That's one possibility. If you have an ESRI shapefile or geoTIFF for a plot for which there's a corresponding hyperspectral image, please send it our way for experimentation...

**Comment by dlebauer** [comment]
@max-zilla To answer some questions

> What does this mean for data usage projections i.e. our 10 PB estimate? 
   
we are well below the 10PB estimate at this point, and if we do get closer, we can eliminate some of the intermediate data products and then if we still need to save space we can use lossy compression / downscaling

> How quickly can we be confident we have all the images from a day to be able to stitch & chop? 48 hours? 36?

Isn't this information available as the difference between collection and transfer dates? (or maybe the more important time range is the beginning to end of transfer of one day's data)

(ignoring outliers caused by transfer downtime) 

> do we need a buffer around plot boundaries/is there concern about the non-overlap between polys in the shapefile? this could be both a boon in terms of overall file size for a day, and a negative if there is anything of interest in between:

You are correct that ~ 50% of the plot goes away if you just keep the plots. This is because of four rows, only the two in the middle are kept because the outside rows are 'border rows'. While the border rows do provide useful information prior to canopy closure, we have decided to start with these plot boundaries #187. Although the discussion of plot definitions is ongoing (https://github.com/terraref/reference-data/issues/60#issuecomment-275736954) I suggest we move forward with these plot definitions and exclude the alleys and border rows. 

I am still confused about the use of a shapefile. I know we have discussed this before, but I was under the impression that our workflows would be based on OGC compliant data formats, and that we would import the plot boundaries into the PostGIS database where it can be queried in geojson or WKT format.

**Comment by dlebauer** [comment]
@czender @hmb1 are these files sufficiently aligned to the x,y grid that `ncks -d x,xmin,xmax -d y,ymin,ymax in.nc out.nc` would be sufficient and efficient?

**Comment by NewcombMaria** [comment]
@dlebauer and @max-zilla the 4-row plot arrangement and the issue of the 2 outer rows of each 4-row plot being 'border rows' only applies to Sorghum-season2.  Other seasons (Sorghum-season1, Wheat-season3, and the upcoming Sorghum-season4) are all planted as 2-row plots with both rows considered as data-collection rows.  The big differences between 2-row plot and 4-row plot arrangements is why Roman suggested making single rows the smallest units and building 'plots' by combining the single-rows of interest.

**Comment by max-zilla** [comment]
@dlebauer we have the plot boundaries in PostGIS and can build on that, I just used the shapefile as representative of the geometry we're working with so I could include that little picture.

@NewcombMaria that is helpful, thanks.

**Comment by czender** [comment]
@dlebauer @hmb1 the rectangles above look rectangular to me so ncks will be efficient and fast on them. i am thinking of how best to use shapefiles at the "plant scale", e.g., how to mask the irregular regions of soil (or leaves) within a plot, as this seems like a useful capability for manipulating the hyperspectral data. we do not yet have a specific request like "can we get a netCDF file with valid values within this shapefile and _FillValues elsewhere", though it seems only a matter of time and we want to stay ahead of the curve...

**Comment by dlebauer** [comment]
@czender: @remotesensinglab is working on per-pixel classifications of sun/shade and plant/soil. That should be easier than irregular polygons (unlike plots, these irregular shapes will change in each image).

@NewcombMaria good point. We should re-visit Roman's proposal moving forward. For now we will keep these plot definitions for Sorghum Season 2.

**Comment by czender** [comment]
OK. then the `ncks -d x,xmin,xmax -d y,ymin,ymax in.nc out.nc` method should suffice for HS imagery once @FlyingWithJerome commits the branch with the correct downsampled coordinates...

**Comment by dlebauer** [comment]
PS what I envision is that the classification algorithm could add new boolean variables like 'sun_leaf' 'shade_soil', etc to the reflectance index data product. @remotesensinglab does that make sense?

**Comment by remotesensinglab** [comment]
Hi David,
Yes, that is what I have in mind as well. Thanks,

Wasit

**Comment by max-zilla** [comment]
@czender that min/max arg looks perfect. FWIW you can grab the shapefile from my image above here:
https://github.com/terraref/extractors-metadata/tree/master/sensorposition/shp/sorghumexpfall2016v5

...we can (and soon should) use geostreams API to get boundaries of each plot like so:
```
GET https://terraref.ncsa.illinois.edu/clowder/api/geostreams/sensors?key=Pb3AUSqnUw&sensor_name=Range 10 Pass 2

RESPONSE
[
  {
    "id": 288,
    "name": "Range 10 Pass 2",
    "created": "2017-02-02T18:04:52Z",
    "type": "Feature",
    "properties": {
      "type": {
        "id": "MAC Field Scanner",
        "title": "MAC Field Scanner",
        "sensorType": 4
      },
      "name": "Range 10 Pass 2",
      "popupContent": "Range 10 Pass 2",
      "region": "Maricopa"
    },
    "geometry": {
      "type": "Point",
      "coordinates": [
        -111.974990376,
        33.0748710865,
        0
      ]
    },
    "min_start_time": "2016-06-30T18:11:40Z",
    "max_end_time": "2016-12-31T21:58:08Z",
    "parameters": [
      "centroid",
      "file_ids",
      "fov",
      "sources"
    ]
  }
]
```
Right now it just has the centroid point in geometry but I have a script to run soon that'll store the polygon of each plot in these. Range 10 Pass 2 is the plot in this case.

**Comment by max-zilla** [comment]
As a first target of this effort, I would propose:

- [ ] select a sensor that has working converter to GeoTIFF (https://docs.google.com/spreadsheets/d/1LLiQSFHbEWoo_FkvG1nl-XoSq_lZ_o6VazfxmPfOH9Y/edit#gid=1888797382) - FlirIR would be a good choice as it also serves #207 directly
- [ ] verify converter is embedding appropriate georeference information in GeoTIFF 
- [ ] target one recent day for that sensor and develop script to stitch them together & clip by plot (the main work in early going)
- [ ] generate a set of clipped plots for that day and check 'em out (any QA concerns, file size, preserved georeference, etc)
- [ ] verify other GeoTIFF converters also compatible with script
- [ ] run on one day for other sensor GeoTIFFs

@yanliu-chn do you have suggestions for who could write the script in item 3? Also tagging @ZongyangLi @solmazhajmohammadi as they haven't been mentioned in this thread yet

**Comment by rachelshekar** [comment]
@solmazhajmohammadi , @remotesensinglab @Paheding  @pless  @ZongyangLi - what is the standard way of handling data for overlapping images?  Is the data averaged?

**Comment by max-zilla** [comment]
@yanliu-chn suggests stitching together raw data as non-georeferenced image.

**Comment by max-zilla** [comment]
@ZongyangLi suggests using GeoTIFF and stereoTop for initial tests instead of FlirIR.

**Comment by Paheding** [comment]
@max-zilla  Are we going to have stitching for hyperspectral data? It would be very helpful for developing plant level classification algorithms.

**Comment by dlebauer** [comment]
@Paheding The hyperspectral data are 0.75m x 20m non-overlapping swaths, so I do not think it would make as much sense to stitch these.

**Comment by max-zilla** [comment]
@yanliu-chn @ZongyangLi  the demosaic geotiffs are misaligned south of the plots:
<img width="143" alt="screen shot 2017-03-17 at 3 32 14 pm" src="https://cloud.githubusercontent.com/assets/14166971/24061869/374c8eaa-0b27-11e7-943b-dcd67cc27004.png">

also, the left/right of demosaic are offset up/down and not left/right. im thinking some coordinates/offsets/XY are mixed up in the extractor:
<img width="460" alt="screen shot 2017-03-17 at 3 31 15 pm" src="https://cloud.githubusercontent.com/assets/14166971/24061891/4bee38a4-0b27-11e7-9a82-a39eeaa9119d.png">

(from /ua-mac/Level_1/demosaic/2016-11-18/2016-11-18__11-15-00-680/)

**Comment by ZongyangLi** [comment]
@max-zilla I think the misaligned in the south might cause by lack of data in those region, because all the geo-information are base on the metadata in the json file. 

For the left/right and up/down question, I do rotate a 90 degree to each image, that's base on my understanding of gantry position, if you could imagine that you are looking into the images from west to the east in the field, the left image is the 'up' image and the right image is the 'down' one. I may make some mistake, @dlebauer could you have a check if I was wrong.

**Comment by ZongyangLi** [comment]
Besides, since the 'Field of View' in the metadata is still not reasonable as mentioned in #126 , the script I uploaded is still using my assumption of the FOV. 

To get a better full stitched map, it might be useful to only use one side images.

**Comment by dlebauer** [comment]
Not clear why https://github.com/terraref/computing-pipeline/issues/126 was closed but I reopened it.

**Comment by yanliu-chn** [comment]
@ZongyangLi I and @max-zilla checked the code to georef the geotiff files. I see that the code calculated the bbox latlon using a math formula that assumes the earth is a perfect sphere. On the other hand, the code assigns EPSG:4326 as the projection. This project's datum uses an ellipsoid to model earth. 

The right way, IMHO, to do this is:
- transform the center latlon to UTM12 (EPSG:32612) using either [pyproj](https://pypi.python.org/pypi/pyproj?) or [gdal python](https://pcjericks.github.io/py-gdalogr-cookbook/projection.html)
- figure out the UTM12 coord of the two corner points of the bbox
- transform the UTM12 coord of the bbox to latlon (EPSG:4326)

Besides, what is your current way to calculate the cell size? do you assume square cells, i.e., the cellsize along the lat direction is the same as that along the lon direction?

**Comment by ZongyangLi** [comment]
@yanliu-chn I think you are right, the earth model should be an ellipsoid.

Could you explain more about the idea of cell size as a square cell?

**Comment by yanliu-chn** [comment]
So suppose the camera outputs a (x pixels * y pixels) image. The first question is what is the resolution of each pixel? if it is cx mm *  cy mm, is cx == cy? 

but anyway, this image would cover (x * cx)mm * (y * cy)mm spatial extent. cx and cy are two values you pass to geotiff's geotransform metadata.

the cellsize problem arises when we convert to latlon projection bc 1) 1 degree of lat, in meters, is not equal to 1 degree of lon ; 2) 1 degree of longitude, in meters, is different on different part of earth. therefore, if cx==cy in meters, they might be different in degrees. but at field view level, i think the difference is marginal. we only need to know how long in meters one degree of lat/lon is in Arizona. of course, the best way to know it is to let GDAL/Proj4 handle it. you can create a SRS object with UTM12 cell size, transform to EPSG:4326, then you know the cell size in degrees.

**Comment by ZongyangLi** [comment]
Then my assumption is a square cell.

**Comment by yanliu-chn** [comment]
sounds good. then you can calculate the cell size accordingly.

**Comment by max-zilla** [comment]
@ZongyangLi if you would make a branch with suggested changes to this: https://github.com/terraref/extractors-stereo-rgb/blob/master/demosaic/terra_demosaic.py

I can run it on a few test datasets and see how it looks in the map. I'm open to just stitching the left side or right side instead of both if you feel the results would be better, not sure the pros/cons for that approach.

**Comment by ZongyangLi** [comment]
@max-zilla I can try it. I was thinking @yanliu-chn is the expert in this subject, would it be much more straightforward to let @yanliu-chn finish this?

**Comment by yanliu-chn** [comment]
i might not get it done faster than you bc i'm constantly overloaded and has a very small percentage of my time in this project.

**Comment by remotesensinglab** [comment]
Clipping and storing data per plot would really helpful for someone who knows what is planted in each plot and interested just in several plots from plant research point. I also agree the pros of doing so mentioned above for data storage and management. 

However, for me a mosaicked whole field image would be more useful for developing and testing methods. Plus the plots change from season to season. I run my algorithms on entire field and show variations of plant phenometrics over the field for pubs. For this same reason, we mosaic UAS image tiles as one.

Perhaps, there is possibility of developing options to download the image as one mosaic by defining area of interest?

**Comment by solmazhajmohammadi** [comment]
I have been looking at the cropping 3D data to the plots
![untitled](https://cloud.githubusercontent.com/assets/17046539/24215693/84a87e00-0f07-11e7-9e09-1ad26ac9aafa.jpg)
Pointclouds depend on the direction of the gantry is generated in different coordinate system. It seems to be a shift in the pointclouds depend on the direction. We need to find this shift, this issue depends on the [issue#44](https://github.com/terraref/reference-data/issues/44)

**Comment by max-zilla** [comment]
@remotesensinglab we've been discussing retaining the full mosaic, but we may not be able to store them all every day as a full-resolution image without doing some careful thinking about space usage and processing time for the overall pipeline, as those files will be significant in size. need to run a few tests first.

**Comment by dlebauer** [comment]
@max-zilla we make both first. There are many options for dealing with redundant  (stitched & subset) files but unless there is a compelling reason to test, first priority is to implement and identify use cases and patterns. Options for removing redundant files can wait a year so we can release both in Nov beta release.  One or more major commercial cloud providers are interested in hosting such files.

**Comment by max-zilla** [comment]
@ZongyangLi let me know how things are going re: the coordinate fix - if you're running into trouble, we can maybe get some other cyberGIS eyes on things aside from @yanliu-chn to help out

**Comment by ZongyangLi** [comment]
@max-zilla 
I did some investigation on this last week. My understanding of Yan's suggestion is:
1. Use the lat/lon SE as (0, 0), and use gdal to convert it into UTM 12 in a flat coordinate system.
2. Use metadata in json file to get the meta image's center UTM 12 coordinate.
3. Use Field of View in json file to get the bbox of image, base on the assumption of square cells, also in UTM 12.
4. Transfer the bbox from UTM 12 back to lat/lon.

So here is my problem, we do not have a True 'Field of View' for stereo camera, how to figure out Step 3?

**Comment by yanliu-chn** [comment]
My comments were for fixing the problem in https://github.com/terraref/extractors-stereo-rgb/blob/master/demosaic/bin_to_geotiff.py in getting the bbox and setting the correct geotransform properties in geotiff.

if the coord info in the camera uses gantry coord, please refer to https://github.com/terraref/documentation/blob/master/spatial-reference-system-data.md to convert to USDA coord which if in meters is UTM12; if in degress, is in EPSG:4326.

**Comment by ZongyangLi** [comment]
@max-zilla 
Added a function called 'get_bounding_box_fixed' here:
https://github.com/terraref/extractors-stereo-rgb/commit/39107d7e3e3423c789d229d45579d2c973e4efce

Please have a check and see if the stitching looks better.

**Comment by max-zilla** [comment]
@ZongyangLi we don't have the stitching code written yet - we need corrected geoTIFFs to write the code against, and I will probably not be the person writing that code.

https://terraref.ncsa.illinois.edu/clowder/datasets/58dbd6724f0c430e2bd7b246

I ran your updated code and the image shifted position and orientation:
![screen shot 2017-03-29 at 11 07 09 am](https://cloud.githubusercontent.com/assets/14166971/24464636/1145ecd6-1470-11e7-93cf-fe9eeae41142.png)
Upper image is old version; lower image is new version. You can see by looking at the sliver of spectralon panel on the right side that the image was flipped vertically. 

This image is from the upper right corner of field:
![screen shot 2017-03-29 at 11 07 20 am](https://cloud.githubusercontent.com/assets/14166971/24464658/2042871c-1470-11e7-9bc4-5b98d5943959.png)

Pink plots in the image with range/pass:
![screen shot 2017-03-29 at 11 11 39 am](https://cloud.githubusercontent.com/assets/14166971/24464758/80644ebe-1470-11e7-839b-a38cad9e1c8b.png)

The metadata reports:
```
gantry_system_variable_metadata:
position x [m]: 207
position y [m]: 4.501
position z [m]: 0.631

location in camera box x [m]: 0.877
location in camera box y [m]: 2.276
location in camera box z [m]: 0.578
```

So, I used the GANTRY -> MAC UTM that @yanliu-chn linked here:
https://github.com/terraref/documentation/blob/master/spatial-reference-system-data.md 
...and compared that to using your get_bounding_box_fixed() formula:
```
YAN FORMULA
> formula_convert(-207, 4.501)
(409005.84550139995, 3659767.9647077997)
> utm.to_latlon(409005.84550139995, 3660182.0475077997, 12, 'S')
(33.076425455503376, -111.97489868337381)

```
Here's that location:
![screen shot 2017-03-29 at 11 37 31 am](https://cloud.githubusercontent.com/assets/14166971/24465820/2476ff94-1474-11e7-8106-a43589dfad50.png)

...but our actual image seems a bit off:
![screen shot 2017-03-29 at 11 40 39 am](https://cloud.githubusercontent.com/assets/14166971/24465939/9b177624-1474-11e7-8c87-9c6149d5d0b6.png)
(see the lower, fixed image)

I'll try to dig into more examples because this particular image looks like it was in roughly the right spot to begin with, but we know that isn't the case everywhere. More after lunch.

**Comment by ZongyangLi** [comment]
@max-zilla 
I didn't use Yan's formula to fix the bounding box, I used a script in https://github.com/terraref/extractors-metadata/blob/use-pyclowder-geostreams/sensorposition/terra_sensorposition.py#L58, and I realize now that might be wrong.
I will try to use those formula and update the script after lunch.

**Comment by max-zilla** [comment]
@ZongyangLi thanks - yeah the sensorposition code will also need to be fixed I believe, when we have a working formula for this extractor I'll use that in the other extractor(s) as well.

**Comment by yanliu-chn** [comment]
@max-zilla @ZongyangLi I need to point out that MAC itself has a shift of 2.5m due to its initial error on reference location (and inherited by all the data using MAC). So to get lat lon, we will need gantry->USDA. 

you can either do gantry->MAC in UTM12; UTM12->latlong; MAC -> USDA documented in https://github.com/terraref/documentation/blob/master/spatial-reference-system-data.md, or check Solmaz's comment in https://github.com/terraref/documentation/issues/7#issuecomment-217183545 , which I don't know how the transformation matrix was created and which GPS system it referred to (MAC or USDA).

**Comment by ZongyangLi** [comment]
@yanliu-chn 
The idea of 2.5m shifting means we need to add `Latitude: Uy = My - 0.000015258894
Longitude: Ux = Mx + 0.000020308287` to get a lat/lon, is that right?

**Comment by yanliu-chn** [comment]
@ZongyangLi  Yes.

**Comment by yanliu-chn** [comment]
@ZongyangLi let me explain. gantry->mac will get you the coord in meters; then you convert the coord to latlon (UTM12->EPSG:4326); then use the mac->usda formula to get the correct lat lon.

you can directly adjust the 2.5m in UTM12 along x and y direction if you know how many meters 0.000015258894 degrees of lat and 0.000020308287 degrees of lon are.

**Comment by ZongyangLi** [comment]
@max-zilla I have just uploaded a bounding box method with formula in the repo.

https://github.com/terraref/extractors-stereo-rgb/tree/master/demosaic

**Comment by max-zilla** [comment]
@ZongyangLi this looks close to correct based on the formula I applied above (original is the lower image, fixed is upper):
![screen shot 2017-03-29 at 2 37 01 pm](https://cloud.githubusercontent.com/assets/14166971/24472971/494da84a-148d-11e7-9d6e-a57646864568.png)
Again, for:
```
gantry_system_variable_metadata:
position x [m]: 207
position y [m]: 4.501
position z [m]: 0.631

location in camera box x [m]: 0.877
location in camera box y [m]: 2.276
location in camera box z [m]: 0.578
```

This seems to agree with our basic plot model:
```
# GANTRY GEOM (GANTRY CRS) ############
#			      N(x)             
#			      ^                   
#			      |                   
#			      |                   
#			      |                  
#      W(y)<------SE                  
#                                     
# NW: (207.3,	22.135,	5.5)      
# SE: (3.8,	0.0,	0.0)              
#######################################
```
North corner X is 207.3 and our gantry position is 207; since in this CRS X is along the north/south axis and increases as we move north, we expect to be just below the northern boundary.

Similarly, East Y is 0 (aka the rightmost boundary) and West Y is 22.135; ours is 4.5 so we expect to be roughly 1/5 of the way across the field.

So this looks reasonable, although I notice the left/right images look identical - does that surprise you?

I think next step is to trigger this new version of extractor on a whole day of datasets and bring them all into a map to see how it looks and start to work on stitching. I'm also going to look at the metadata work @craig-willis has done to see if we can pull the parameters in this script from a standard location instead of having them hardcoded.

**Comment by max-zilla** [comment]
@ZongyangLi @yanliu-chn I am generating a full day of demosaic TIFFs here:
```
/sites/ua-mac/Level_1/demosaic/2017-02-07/
```

there are ~4,200 of these to generate, might be completed by the time of the TERRA meeting but not sure.

**Comment by max-zilla** [comment]
@pless and @ZongyangLi can focus on the stitching component of this. getting one big GeoTIFF for Feb 7.

@jterstriep has volunteered to handle the clipping to individual plot boundaries from that big GeoTIFF.

**Comment by rachelshekar** [comment]
FOV issue is https://github.com/terraref/computing-pipeline/issues/126

**Comment by max-zilla** [comment]
@ZongyangLi @yanliu-chn @jterstriep  @smarshall-bmr looks better w/ new calculations, but we can see where we need the FOV correction:
![screen shot 2017-03-31 at 2 28 55 pm](https://cloud.githubusercontent.com/assets/14166971/24566311/abb710a6-161e-11e7-8b9c-571c80f0de00.png)

Four images of same basic part of field with different images turned on/off:

Image A:
![screen shot 2017-03-31 at 2 29 25 pm](https://cloud.githubusercontent.com/assets/14166971/24566322/b61187a2-161e-11e7-9aa3-997332d18fb1.png)

Image A+B (see split in left tire tread)
![screen shot 2017-03-31 at 2 29 36 pm](https://cloud.githubusercontent.com/assets/14166971/24566332/b96b4582-161e-11e7-8ef3-bedc21fe6577.png)

Image A+B+C (see another split in center dirt)
![screen shot 2017-03-31 at 2 29 49 pm](https://cloud.githubusercontent.com/assets/14166971/24566338/bbf8d29c-161e-11e7-942a-1306673bad80.png)

Image A+C (gap between images despite areas that should overlap)
![screen shot 2017-03-31 at 2 30 19 pm](https://cloud.githubusercontent.com/assets/14166971/24566340/be660dba-161e-11e7-87f5-c6e5e4505dfa.png)

In phone discussion with Zongyang, thinking was that FOV correction would correct for this.

**Comment by dlebauer** [comment]
What is a robust, simple approach that we can use at this point?
Should we differentiate between images before and after canopy closure?
* when plants are small and lots of ground is visible, adjust plot boundary for scanner height so that ground footprint is consistent
* when canopy is fully closed, use plot boundary  at canopy height?
Does it help if we stitch using both the image features and geospatial (field of view) information?

@solmazhajmohammadi could you please update this issue with a summary of your findings to date?

**Comment by solmazhajmohammadi** [comment]
Feature based registration without considering the z height, this is working for registration in small area. When the image area gets bigger, number of the features increases and it is hard to register the images after that. (due to false match)
I did a little bit research on this: ASIFT algorithm seams to be a solution for this problem. This is a great opensource work, which forces the algorithm to only consider affine transformation. So we dont get false arbitrary matches. 
http://www.ipol.im/pub/art/2011/my-asift/article_lr.pdf

**Comment by Paheding** [comment]
@solmazhajmohammadi  SIFT based algorithms are very robust to image translation, rotation, and scaling, however the SIFT might be still patented. Alternatively, we can use SURF method ( article:
 [http://www.vision.ee.ethz.ch/~surf/eccv06.pdf](url)). As for mismatched features, RANSAC [http://www.cs.columbia.edu/~belhumeur/courses/compPhoto/ransac.pdf](url) method can be used before feature extraction to eliminate outlier features, so that the false matches can be resolved.

**Comment by solmazhajmohammadi** [comment]
@Paheding take a look at the figure 26 on the paper I posted. I have not tried ASIFT in the big plot size images yet, I think this approach warranty the affine transformation between the features.  When the number of the registered images get higher RANSAC didnot help on the false matches.

**Comment by Paheding** [comment]
@solmazhajmohammadi Correct, there are some drawbacks of RANSAC.  Here is an optimized RANSAC algorithm [https://pdfs.semanticscholar.org/6dc8/6d312ca1c5b18e53ecb98fa6b5fc1053e023.pdf](url), which tends to be better than the classic RANSAC.  Source code: [http://www.cb.uu.se/~aht/code.html](url). Combination of the optimized RANSAC and ASIFT would be more robust. 
Besides, another quick solution could be make a threshold to restrict the number of registered images.

**Comment by dlebauer** [comment]
Is this ready to be closed? #306 covers some remaining issues.

**Comment by max-zilla** [comment]
Yes, I believe so - current plan is for @jterstriep to develop service to query plots on-demand instead of mass conversion ahead of time. There are other issues where this is being discussed.

**Comment by dlebauer** [comment]
@jterstriep could you link to or create the issue that covers the on demand plot subsetting?
