### ISSUE TITLE
Update Level 1 data and metadata formats, make consistent across project

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#270]
A large epic to cover getting all metadata consistent for Nov 2017 release. 

Scope of this epic is:

* file type and format
* names and units in metadata. 
* organization of metadata in Clowder + embedded (e.g. EXIF) 
* pointers to upstream provenance (incl. input data + algorithm version)  
* organization of sensor metadata is out of scope, except for how it is linked to 
* how to store quality information, including
  * precision / error terms

**Comment by dlebauer** [comment]
the name of this epic Implies that it is limited to level 1. But I think it should be all data products on the filesystem and in Clowder 

Also in scope:  standard human readable file names

**Comment by dlebauer** [comment]
for relevant (raster) files, include the comment For RGB and other relevant images, please include comment https://github.com/terraref/computing-pipeline/issues/126#issuecomment-295800623

> "This stitched image is computed based on an assumption that the scene is planar. There are likely to be be small offsets near the boundary of two images anytime there are plants at the boundary (because those plants are higher than the ground plane), or where the dirt is slightly higher or lower than average."

**Comment by max-zilla** [comment]
terrautils has been implemented across extractors to provide one gateway for filename and metadata conventions, so this is coming along nicely.
