### ISSUE TITLE
websites and APIs should provide useful information when servers are down 

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#273]
When data servers are down (e.g. /clowder, /thredds, /bety), they should redirect to terraref.org/maintenance

https://github.com/terraref/terraref.github.io/blob/master/maintenance.md 

So that users are not getting unhelpful errors.

API should also send an appropriate message

### Completion Criteria   

* [x] browsers redirect to terraref.org/maintenance
* [x] API provides an appropriate error message

**Comment by robkooper** [comment]
redirection see http://terraref.ncsa.illinois.edu/clowder-dev/
api not sure I want to redirect, I'd rather have it throw an error.

**Comment by robkooper** [comment]
This will need to be fixed/updated when services are detected down.
