### ISSUE TITLE
Reevaluate BMS

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#274]
* Need to upload Sorghum Ontology
* Look at storing genomic and trait data
* test out BRAPI

**Comment by rachelshekar** [comment]
@dlebauer - update?

**Comment by dlebauer** [comment]
I'll discuss with @craig-willis about this based on what he has learned at the BRAPI hackathon about what breeding database we need, if any, to meet the needs of the TERRA program. Then we will open new issues as needed.
