### ISSUE TITLE
Full field stitched mosaic

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#275]
how to support
how to ensure that it can be used with any dataset

**Comment by rachelshekar** [comment]
Robert Pless would like to have full field image available via webpage.

**Comment by remotesensinglab** [comment]
A full field stitch image would be very helpful for us, too. Especially, a full field hyperspectral image.

**Comment by dlebauer** [comment]
I'm fairly certain that the hyperspectral scans aren't adjacent, though
perhaps we could fill gaps with missing values that would compress well.
The file would still be ~TB scale.
