### ISSUE TITLE
Install Labs Workbench

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#278]
We're testing a version of Labs Workbench that includes support for mounting shared data to containers (such as TERRA ROGER data via NFS).  This version also includes support for fetching/mounting data from Clowder, per the current tool server.  

### Completion Criteria   

* [x] Determine usage requirements
* [x] Install Labs Workbench instances for TERRA dev and production
* [ ] Import user accounts from Phenome workshop?
* [x] Mount ROGER data via NFS to each compute node
* [ ] Acceptance testing
* [ ] Documentation

**Comment by craig-willis** [comment]
DNS/TLS opened as separate ticket #290

**Comment by dlebauer** [comment]
I wrote up documentation [here](http://htmlpreview.github.io/?https://raw.githubusercontent.com/terraref/tutorials/master/workbench/ndslabs_workbench_intro.html) in the tutorials. Is there further documentation needed?

**Comment by dlebauer** [comment]
what is required for acceptance testing? I think it is okay, aside from a few bugs like the fact that my environment shuts down. But in general the functionality is awesome / better than I had imagined!

**Comment by craig-willis** [comment]
@dlebauer  I hadn't defined any acceptance criteria other than that stakeholders (i.e., you) are happy.  With your documentation and OK, we can close this and open specific tickets for bugs/enhancements.

Your comment about "my environment shuts down" -- is this the hanging problem you've mentioned?  The reason I ask is that we do have  a feature that containers are shutdown after n hours of inactivity.  The point here is to conserve resources.

**Comment by dlebauer** [comment]
@craig-willis we can close this. I conflated the two hanging big and shut down feature. Being able to use the persistent home directory makes shutting down a non issue. And there was no hanging today so I will keep my fingers crossed
