### ISSUE TITLE
Explore / prototype examples of using YesWorkflow for provenance capture and documentation

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#279]
### Yes Workflow 

First steps:

* review #149
* start here: https://github.com/yesworkflow-org/yw-prototypes
* look at online example: http://absflow.westus.cloudapp.azure.com/

The initial goal is to focus on capturing inputs and outputs. The objective of this issue is to explore what it would look like to implement YesWorkflow in our pipeline for a few example extractors, so that we can evaluate as a team.

### Completion Criteria

* [x] markup extractors in github.com/terraref/extractors-metadata 
* [x] submit pull request w/ yesworkflow comments 
* [x] add visualization to the pull request to illustrate the output (or maybe this can be generated by online viewer?)
* [ ] summarize findings
  - what is the minimum useful feature set (or, most important tags)
  - what about provenance capture (backend database?)

**Comment by harshagrawal28** [comment]
YesWorkflow is basically a way of commenting the code using certain keywords to produce a flowchart showing the stages of computation and flow of data in the code.

Each YesWorkflow tag begins with an '@' symbol.
The most important tags in YesWorkflow are:
```@begin -  Specifies the beginning of a code block (or one stage of computation). It should be always paired with @end keyword
@end - Specifies end of one code block
@in - Specifies the input data of a code block 
@out - Specifies the output of a code block
@param - Specifies the parameters needed for the code block to process the input data
@as - forms an alias for the actual variable specified in @in or @out. If @as is present after @in or @out, the name after @as will be displayed in the workflow.
@desc specifies the description of the code block
```

All keywords are case-insensitive. `@param,@in, @out` should appear between @begin and @end tags

Example:
The first pair of `@begin,@end` specifies the whole script.
```
# @begin convert_metadata_to_netcdf
# @in metadata
# @param output_path
# @out NetCDF

# code to extract metadata 
# @begin metdata_to_JSON
# @in metadata
# @out JSONdata
# @end metadata_to_JSON


# This function writes the netCDF file to outfile
def met2cf_geostreams(jsondata, outfile):
      # code to perform conversion

      # @begin met2cf_geostreams @desc writes NetCDF file to output_path 
      # @param outfile #@as output_path
      # @in JSONdata
      # @end met2cf_geostreams
      
# @end convert_metadata_to_netcdf
```
Above code produces the following workflow:
<img width="305" alt="yw" src="https://cloud.githubusercontent.com/assets/15992787/24414389/ed243c4e-13a3-11e7-82a3-aea67291ec41.PNG">

**Comment by dlebauer** [comment]
@tmcphillips and @ludaesch We currently have a large assortment of scripts orchestrated by RabbitMQ. RabbitMQ gets a message when a new file or dataset is generated and this may trigger one or more downstream processes. But there is currently no 'formal' relationship between the different steps.

It seems useful to annotate scripts using YesWorkflow. But is there a way to do so that also links the output of one script to the input of another? - either as a general way to describe the workflow or as a way to track the provenance of a particular file?

**Comment by dlebauer** [comment]
This can be closed. I'll follow up w/ @ludaesch
