### ISSUE TITLE
plantcv extractor code integration

### ISSUE THREAD

**Issue by yanliu-chn** [terraref/computing-pipeline#28]
Need Rob's help to get dockerfile part and extractor source code into the two code repos on opensource.ncsa.illinois.edu

**Comment by dlebauer** [comment]
@yanliu-chn does this duplicate #10?

**Comment by yanliu-chn** [comment]
I don't see any overlapping. #10 is to define statement of work.

**Comment by dlebauer** [comment]
@yanliu-chn sorry wrong repository. I meant - is this a duplicate of #13
