### ISSUE TITLE
rapid turnaround QAQC map of scanner data

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#285]
following on #85...

heat map of plots by sensors - how many are inserting information, max/min of basic traits, etc.

- [ ] I should discuss with @robkooper @jdmaloney on whether we can leverage existing infrastructure to get us part/most of the way there
- [ ] use association of dataset to plot (sensorposition extractor) to get sensor capture timestamps by plot & aggregate
- [ ] as trait-generating extractors are run, include those traits (e.g. min/max) in same database as these
- [ ] if we chop datasets into plot-level tiles, simplifies this somewhat.

**Comment by dlebauer** [comment]
@max-zilla do you have any suggestions for implementation (in python and/or d3.js)? I've asked @nickheyek to begin protoyping this. What would eventually be easiest to integrate into geodashboard? Or should we just add this to html reports?
