### ISSUE TITLE
Get full field mosaic script running on cron job

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#286]
Following #85...

We want to get the full-field mosaic generation script running on each day starting w/ most recent completed day and moving backwards. 

Version committed to accomplish this, ready for ROGER-specific modification, is here:
https://github.com/terraref/extractors-stereo-rgb/blob/master/mosaic/terra_mosaic.py

@jterstriep and I will see if anything else needs to be done and set up a cron job to run this script on most recent available date and moving backwards in time until we have everything processed (or space becomes an issue potentially). Jeff, I'll follow up in this issue in next day or so.

**Comment by max-zilla** [comment]
If we are going to convert everything to plot tiles (with gaps in between potentially) how does this fit in? With properly geocoded tile geotiffs it's possible we can use the same Google Maps display component.

**Comment by max-zilla** [comment]
This will be run on all sensors as part of #265.

**Comment by max-zilla** [comment]
https://github.com/terraref/extractors-stereo-rgb/blob/master/fieldmosaic/full_day_to_VRT.py
I am working to get this triggering properly on stereoTop as part of pipeline, but in meantime I have this python script (modification of @ZongyangLi script) that we can run on my extractor VM on a per-day basis like:
```
python full_day_to_VRT.py -d "2017-04-27"
```
...it doesn't care how many TIFs there are in the directory, but this uses the TIFs from the bin2tif extractor directly instead of converting the BIN files a 2nd time.

**Comment by dlebauer** [comment]
@max-zilla for the VRT, I notice that the files have paths like `/home/extractor/sites/ua-mac/Level_1/stereoTop_geotiff/2017-04-27/2017-04-27__09-58-42-323/stereoTop`

but the physical path (from `pwd -P`) is `/gpfs/largeblockFS/projects/arpae/terraref/sites/ua-mac/Level_1/`. I think @jterstriep mentioned that it is sufficient to have relative paths, which would facilitate migration to another machine (for users who want to recreate the directory structure, including us if we ever leave ROGER).

**Comment by max-zilla** [comment]
@dlebauer yes, those are the paths on the VM where I'm generating the VRT. relative paths are probably the way to go, I'll take a look and ask @jterstriep if I can't figure it out - when I generate VRTs for other days today/tomorrow I'll try to apply relative paths.

**Comment by max-zilla** [comment]
I've updated the VRT script with a flag to use relative paths:
```
if relative:
            # e.g. <up from date>/<up from fullfield>/stereoTop_geotiff/2017-01-01/file.tif
            fname = "../../"+sensor+"_geotiff/"+date+"/"+os.path.basename(fname)
        list_obj.write(fname + '\n')
```
