### ISSUE TITLE
Clean up EnvironmentLogger directory

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#287]
After ROGER maintenance is done, @jdmaloney and I should work together to clean up the EnvironmentLogger database of files named "enviromentlogger" (missing first 'n') that should be duplicates of the corrected versions with a typo in the name. 

None of the erroneous files appear to be in Clowder so there shouldn't be any issue deleting these.

**Comment by jdmaloney** [comment]
This clean up has been completed today, duplicates with wrong spelled names are gone, and single files with wrong name have been moved to correct name.
