### ISSUE TITLE
plantcv image_analysis script testing

### ISSUE THREAD

**Issue by yanliu-chn** [terraref/computing-pipeline#29]
In plantcv source code, I tested the image_analysis scripts to handle three types of input images: NIR_SV, VIS_SV, VIS_TV. However, when i randomly pick three images from the sample data in box, one from each type, only VIS_SV worked with tweaking. The other two types crashed opencv.

David, could you help test these scripts (under plantcv/scripts/image_analysis/) to see how robust these scripts are and figure out under which conditions they work or do not work? I do not have the domain expertise to test them. 

It is also good to identify those that work for the demo.

The error I encountered is:
`
OpenCV Error: Assertion failed ((scn == 3 || scn == 4) && (depth == CV_8U || depth == CV_32F)) in cvtColor, file /home/ubuntu/software/opencv/modules/imgproc/src/color.cpp, line 3959
Traceback (most recent call last):
  File "/home/ubuntu/plantcv/scripts/image_analysis/vis_tv/vis_tv_z3000_L1.py", line 118, in <module>
    main()
  File "/home/ubuntu/plantcv/scripts/image_analysis/vis_tv/vis_tv_z3000_L1.py", line 61, in main
    device, brass_mask1 = pcv.rgb2gray_hsv(brass_mask, 'v', device, args.debug)
  File "/home/ubuntu/plantcv/lib/plantcv/rgb2gray_hsv.py", line 14, in rgb2gray_hsv
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
cv2.error: /home/ubuntu/software/opencv/modules/imgproc/src/color.cpp:3959: error: (-215) (scn == 3 || scn == 4) && (depth == CV_8U || depth == CV_32F) in function cvtColor
`

**Comment by dlebauer** [comment]
@yanliu-chn Did you select random images from multiple folders, or a random folder? As I understand it, the lowest level folder is the atomic unit so there would be no reason to combine random images from multiple folders into a single pipeline.

@nfahlgren should be able to clarify. Please paste the code that you used that caused the above error.

**Comment by yanliu-chn** [comment]
I did not choose a folder. I tested with one image:
`
~/plantcv/scripts/image_analysis/vis_tv/vis_tv_z3000_L1.py -i ./VIS_TV_z3000_329934.jpg -o output
`
That image is randomly chosen.

If folder is the atomic unit, how do you expect to use Clowder to upload a folder? As I understand it, Clowder works at file level for uploading. So uploading the folder as a zipped file? This is a design issue and we can discuss it later.

For the demo, how do you want to put it together?

Even as folder, image_analysis scripts will likely fail if the images I tested failed.

**Comment by yanliu-chn** [comment]
Maybe I didn't give correct arguments for those images. This is where I need help with. What should be the arguments I give to these scripts? image_analysis.pl accepts a lot of command line arguments. But those analysis scripts only take one input image and an output dir as argument. image_analysis.pl just sorts the image types and call the correct script.

**Comment by nfahlgren** [comment]
@yanliu-chn you used the correct arguments, it looks to me like the images that fail cannot be opened by OpenCV because they are either not 8-bit or 32-bit, or they have something other than 1 (gray-scale), 3 (RGB) or 4 (RGB+alpha) channels. Maybe the LemnaTec NIR images are an unusual format?

**Comment by yanliu-chn** [comment]
I used VIS_TV script and sample image. But NIR images also failed. Only VIS_SV images worked.

**Comment by dlebauer** [comment]
> Maybe the LemnaTec NIR images are an unusual format?

I downloaded the jpeg versions of these files rather than png since the
jpgs are smaller.

Would that cause a problem?

**Comment by yanliu-chn** [comment]
JPGs worked for VIS_SV.

**Comment by yanliu-chn** [comment]
VIS_TV images works now after adding the `-m masks/vis_tv/**maskfile.png**` in extractor.
