### ISSUE TITLE
Experiments tables missing from BETYdb dump

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#293]
The experiments and experiments_sites tables are missing from the current BETYdb dump.

Completion criteria:
* [ ] Experiments* tables (and any other new tables) are included in the dump

**Comment by dlebauer** [comment]
Moving this to github.com/pecanproject/bety repository

**Comment by dlebauer** [comment]
moved to https://github.com/PecanProject/bety/issues/491

**Comment by robkooper** [comment]
need to make sure we dump database and can be downloaded. It should end up at 

https://terraref.ncsa.illinois.edu/bety/dump/bety.tar.gz

**Comment by robkooper** [comment]
Cronjob now running:
# dump bety every hour
0 * * * * /home/kooper/dumpbety.sh

Script:
```
#!/bin/bash

wget -q -O /home/bety/dump.bety.sh https://raw.githubusercontent.com/PecanProject/pecan/master/scripts/dump.bety.sh
chmod 755 /home/bety/dump.bety.sh

sudo -u bety /home/bety/dump.bety.sh -q -m 6 -o /home/bety/bety/public/dump
```
