### ISSUE TITLE
deploy web apps on terraref

### ISSUE THREAD

**Issue by robkooper** [terraref/computing-pipeline#295]
The two web apps that @pless and @zongyangli developed are on ROGER in /projects/arpae/terraref/users/dlebauer/webapps/ 

I couldn’t find any issues on GitHub though I know we’ve discussed a few times how to present html output, from making a viewer within Clowder to mounting the directory on the terraref web server.

* [x] move webapps to better location
* [ ] mount sites folder if needed
* [ ] deploy web apps on terraref.ncsa.illinois.edu

**Comment by dlebauer** [comment]
@nickheyek please ping Rob  and link to this issue when you submit your pull request

**Comment by rachelshekar** [comment]
@robkooper please update

**Comment by robkooper** [comment]
We should have  a better location than users/dlebauer/webapps

Talked to @nickheyek, created a VM for now to place his servcer on. Next step is to make into a docker container.

**Comment by dlebauer** [comment]
I moved the existing web apps to `/projects/arpae/terraref/sites/ua-mac/www` (since these are data products specific to the ua-mac site).

**Comment by robkooper** [comment]
Running see:
https://terraref.ncsa.illinois.edu/webapps/ua-mac/canopy_cover/page.html
https://terraref.ncsa.illinois.edu/webapps/ua-mac/canopy_height/page.html

Bugs / Improvements
- both html files refer to JPG images, but only PNG images are in the folder
- rename page.html to be index.html

**Comment by dlebauer** [comment]
I've changed page.html to index.html

I've also added https://terraref.ncsa.illinois.edu/webapps/ua-mac/canopy_cover_alpha which has the jpg images. The png images are the plots and jpg are the RGB images.

**Comment by ZongyangLi** [comment]
The jpg RGB images are generated only in first testing data in May 2016, to demonstrate what's the plot represent for. It will be too much RGB images for a whole season visualization. So I didn't create them in the following webpage.
