### ISSUE TITLE
Back up Postgres DB on gantry

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#296]
The Postgres pipeline DB on Roger side is backed up already - @robkooper correct me if I'm wrong.

Right now there's no backup for the AZ gantry side pg db. We could recover the relevant info from the Roger side, but would be good to back this up now so we don't need to recover anything if that time comes.

Talking with JD and one simple approach would be:
- periodically create DB dump file on gantry (e.g. daily, can be triggered by pipeline service)
- move via Globus (same pipeline as all other data - ends up in /sites directory)
- rsync w cron job to move to backup location on Roger (JD would move from /sites to a /terra/backup location with other backup data)

That approach requires a couple cron-type jobs, will think more on it to see if more elegant solution comes to mind.

**Comment by robkooper** [comment]
Correct backed up in cron:
0 11,23 * * * /usr/bin/pg_dumpall | gzip --rsyncable > /home/backup/postgresql/dumpall.sql.gz

and the /home/backup folder is:
/gpfs/largeblockFS/projects/arpae/terraref/backup

**Comment by jdmaloney** [comment]
@robkooper This is for the postgres on the machine in AZ (doesn't mount ROGER), will sync it to that directory though.

**Comment by robkooper** [comment]
this is the cronjob for postgresql

**Comment by jdmaloney** [comment]
Database is being backed up twice a day and the dump is sent over to ROGER for safety
