### ISSUE TITLE
Specify sensor metadata with less redundancy in flat files

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#297]
@czender commented on [Thu Apr 13 2017](https://github.com/terraref/extractors-environmental/issues/9)

Now that the EL has a flat (not grouped) structure to simplify metadata appearance, we attach the sensor metadata directly to each field it measures. This leads to redundancy as shown below. Shall we make this less redundant? e.g., by creating a "dummy" sensor variable and pointing to it from each relevant variable?

```
   float airPressure(time) ;
      airPressure:units = "pascal" ;
      airPressure:sensor_description = "This dataset contains documentation, datasheets, and metadata about the Theis CLIMA sensor." ;
      airPressure:sensor_created = "Mon Jan 09 09:17:06 CST 2017" ;
      airPressure:sensor_id = "5873a9724f0cad7d8131b4d3" ;
      airPressure:sensor_authorId = "578f76948e7e1aecb7cad4c5" ;
      airPressure:sensor_spaces =  ;
      airPressure:sensor_thumbnail = "5873a97f4f0cad7d8131b56d" ;
      airPressure:sensor_name = "Thies CLIMA" ;
      airPressure:standard_name = "air_pressure" ;

    float precipitation(time) ;
      precipitation:units = "meter second-1" ;
      precipitation:sensor_description = "This dataset contains documentation, datasheets, and metadata about the Theis CLIMA sensor." ;
      precipitation:sensor_created = "Mon Jan 09 09:17:06 CST 2017" ;
      precipitation:sensor_id = "5873a9724f0cad7d8131b4d3" ;
      precipitation:sensor_authorId = "578f76948e7e1aecb7cad4c5" ;
      precipitation:sensor_spaces =  ;
      precipitation:sensor_thumbnail = "5873a97f4f0cad7d8131b56d" ;
      precipitation:sensor_name = "Thies CLIMA" ;
      precipitation:standard_name = "precipitation_flux" ;

```

---

@rachelshekar commented on [Thu Apr 13 2017](https://github.com/terraref/extractors-environmental/issues/9#issuecomment-293949120)

@craig-willis - can you give input on this?

---

@rachelshekar commented on [Thu Apr 13 2017](https://github.com/terraref/extractors-environmental/issues/9#issuecomment-293950160)

David - Treat each sensor as individual with metadata for each.

---

@czender commented on [Thu Apr 13 2017](https://github.com/terraref/extractors-environmental/issues/9#issuecomment-293953053)

@craig-willis we now have the EL-measured variables assigned to one of four sensors. During discussion @dlebauer prefers finer granularity if possible. Can we differentiate the sensor information from precipitation from pressure? Idea is for each distinct mechanical sensor to have its own metadata.

---

@dlebauer commented on [Thu Apr 13 2017](https://github.com/terraref/extractors-environmental/issues/9#issuecomment-293959653)

@craig-willis is it possible to disaggregate the Thies Clima and store metadata for each of the 'sub-sensors'. I think this is preferred because Thies Clima is a bespoke aggregation of sensors, but what we need for interoperability is, e.g., for any temperature sensor to have similar metadata. Here is a list of some - but not all - of the useful metadata for these independent sensors:

<img width="732" alt="screen shot 2017-04-13 at 11 29 18 am" src="https://cloud.githubusercontent.com/assets/464871/25014265/a3fd70da-203c-11e7-98e3-04c8d6b2b345.png">

**Comment by craig-willis** [comment]
@dlebauer @czender I'll need to look at this in more detail but in short yes we can and I understand the requirement.

**Comment by max-zilla** [comment]
this could fall into same scope as metadata cleanup.

**Comment by dlebauer** [comment]
@czender please speak w/ @FlyingWithJerome and close if this has been covered by recent PR.

**Comment by max-zilla** [comment]
@craig-willis this is the PR I was talking about earlier: https://github.com/terraref/extractors-environmental/pull/14/files
