### ISSUE TITLE
Downtime for Terraref Clowder May 2, 2017

### ISSUE THREAD

**Issue by robkooper** [terraref/computing-pipeline#298]
I will need to bring down TERRAREF clowder instance for about 1 day to migrate the database and elasticity search capabilities to new servers. My goal is to do this Wednesday April 19, 2017.

* [x] Create elasticsearch machines (3 for now)
* [x] Create mongodb machines (3 for now)
* [x] Create postgresql machine (1 for now)
* [x] Modify clowder page to maintainance page
* [x] Migrate mongo database
* [x] Migrate postgres database
* [x] Update clowder for new elasticsearch/mongodb/postgres servers
* [x] Update ingestion services for new postgres server @max-zilla 
* [x] Start clowder
* [x] Reindex clowder
* [x] Remove maintenance page

**Comment by robkooper** [comment]
@dlebauer @rachelshekar please send to appropriate people.

**Comment by dlebauer** [comment]
@robkooper until we resolve #300 I'll send the notifification thus:  @terraref/developers, @terraref/principle-investigators @terraref/users-testers-onlookers

**Comment by robkooper** [comment]
Process has started, creating machines. Waiting for increased quotas on openstack to finish creation of all machines needed.

**Comment by rachelshekar** [comment]
This totally passed me by.  Please notify downtime to: terraref-users@lists.illinois.edu

**Comment by robkooper** [comment]
![terraref](https://cloud.githubusercontent.com/assets/1580696/25636877/62f0e6d8-2f48-11e7-8e15-af7302e8419a.png)

Overview of the system as it is running now
- terraref is the frontend for everything, runs nginx
- terra-clowder runs the data management system clowder, connected to terra-mongo-[123], terra-es-[123], terra-postgres and roger filesystem (using NFS mount)
- terra-geodashboard runs the geodashboard software, connected to terra-clowder
- terra-thredds runs the thredds server (experimental), connected to roger filesystem (using NFS moutn)
- terra-es-[123] run elasticsearch 2.4 and for a cluster
- terra-mongo-[123] run mongo 3.6 in a replicated cluster, terra-mongo-3 is an arbiter and does not hold any data
- terra-postgres runs postgres 9.5
