### ISSUE TITLE
Document method/provide module to access pyclowder on Roger and elsewhere

### ISSUE THREAD

**Issue by czender** [terraref/computing-pipeline#299]
### Description
Environmental Logger (EL) now uses pyclowder.geostreams which is not provided in any module on roger. Formerly EL could be fully exercised from command line after `module load gdal-stack-2.7.10`.  Would be great to have a generic module that allowed EL to run with geostreams from command line for testing purposes.

**Comment by dlebauer** [comment]
Would also be nice (for the purposes of modularity / flexibility) if EL continued to produce the netcdf file even if geostreams / pyclowder are not available (e.g. try-catch) so that @czender's original workflow does not fail.

**Comment by jterstriep** [comment]
This should be handled as a virtualenv in Python. Basically, create a
virtualenv for EL and have a requirements.txt file with the following:

wheel==0.24.0
pika==0.10.0
requests==2.11.1
urllib3==1.19
https://opensource.ncsa.illinois.edu/bitbucket/rest/archive/latest/projects/CATS/repos/pyclowder2/archive?format=zip

Then 'pip install -r requirements.txt'. If that sounds like gobbly-gook,
let me know and I can write-up better explanation for developing/running
extractors on ROGER.

**Comment by rachelshekar** [comment]
@czender can this issue be closed?

**Comment by czender** [comment]
yes
