### ISSUE TITLE
Integrate plantcv extractor in Clowder

### ISSUE THREAD

**Issue by yanliu-chn** [terraref/computing-pipeline#30]
Need Rob's help to get nebular Clowder info and test plantcv extractor deployed on ROGER.

ROGER plantcv instance: 141.142.168.55

**Comment by yanliu-chn** [comment]
http://141.142.208.144/clowder/

You can create a username/password, either me or david L will need to give the OK.

If you want to test extractor:
amqp://guest.guest@141.142.208.144/%2F should be possible with exchange == clowder

To see rabbitmq you can use http://141.142.208.144:15672/ (guest/guest)

**Comment by yanliu-chn** [comment]
plantcv extractor is working with nebula Clowder now:

http://141.142.208.144/clowder/files/56411ff5e4b0a81e04e39739

**Comment by dlebauer** [comment]
Looks great! @nfahlgren what do you think?

**Comment by nfahlgren** [comment]
Looks great to me. Would it eventually also display the numerical data extracted from the image?

**Comment by dlebauer** [comment]
> Would it eventually also display the numerical data extracted from the image?

Yes ... #31; feel free to elaborate there ...
