### ISSUE TITLE
How would you like to be notified of resource downtime?

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#300]
Following #298 we need to find a way of notifying users of upcoming downtime. Should this be an email list, or is it effective to notify people by mentioning teams via GitHub?

As a test, the following mentions should notify @terraref/developers, @terraref/principle-investigators and @terraref/users-testers-onlookers and this issue will serve as a survey

Can anyone who sees this please reply with your preference:
*  👍 to indicate that notification like this via GitHub is preferred over a dedicated email list
*  👎 if you prefer a dedicated email notification or
* 😕 if you prefer not to be notified until your code breaks or you hit http://terraref.org/maintenance/
* 💬 otherwise feel free to comment below

### Completion Criteria

* [x] Decide how to inform people
* [x] Create a single team with everyone for notifications (@terraref/users) or yet another email list

**Comment by czender** [comment]
I prefer GitHub
-- 
Charlie Zender, Earth System Sci. & Computer Sci.
University of California, Irvine 949-891-2429 )'(

**Comment by remotesensinglab** [comment]
Github is good for this.

**Comment by SolmazHajmohammadi-LemnaTec** [comment]
GitHub.
Maybe only one github issue that people can subscribe for email notifications as well. So it will cover the both options

**Comment by rachelshekar** [comment]
email list for registered alpha testers is terraref-users@lists.illinois.edu 

i think we should do email and github.  hopefully this won't happen so often to bother people.
