### ISSUE TITLE
Check scanner3D height code

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#303]
@ZongyangLi I am trying to deploy the scanner3D plant height extractor today:
https://github.com/terraref/extractors-3dscanner/tree/master/plant_height

However I'm getting errors when trying to scan the west PLY:
https://github.com/terraref/extractors-3dscanner/blob/master/plant_height/terra_plant_height.py#L133
```
2017-05-03 14:34:14,878 [Thread-13      ] INFO    : root - Loading /home/extractor/sites/ua-mac/Level_1/scanner3DTop/2017-05-03/2017-05-03__05-47-35-181/f97fdfcc-8d24-4625-8ce1-da4f166afefd__Top-heading-west_0.ply & calculating height information
2017-05-03 14:34:14,879 [Thread-13      ] ERROR   : pyclowder.connectors - [5909d2374f0c2ca933f89e8c] standard error : 'unicode' object has no attribute 'readline'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyclowder/connectors.py", line 316, in _process_message
    self.process_message(self, host, secret_key, resource, body)
  File "terra_plant_height.py", line 134, in process_message
    plydata = PlyData.read(ply_west)
  File "/home/extractor/extractors-3dscanner/plant_height/plyfile.py", line 268, in read
    data = PlyData._parse_header(stream)
  File "/home/extractor/extractors-3dscanner/plant_height/plyfile.py", line 210, in _parse_header
    line = stream.readline().decode('ascii').strip()
AttributeError: 'unicode' object has no attribute 'readline'
2017-05-03 14:34:14,879 [Thread-13      ] INFO    : pyclowder.connectors - [5909d2374f0c2ca933f89e8c] : ERROR: standard error : 'unicode' object has no attribute 'readline'
```

Can you check to see if your code handles that PLY file properly to see if it's a problem in my python code & how it's referencing the ply file, or something else?

**Comment by ZongyangLi** [comment]
@max-zilla I downloaded the exactly ply file you were testing and ran 
`plydata = PlyData.read(ply_path)`
on my test env, I do not get any error report.
This is quite wired, could you please try that 'PlyData.read()' again in another separated env or another ply file and see if it is still reporting the same error?

**Comment by max-zilla** [comment]
@ZongyangLi I was able to also run this with no errors in a separate py environment, I suspect I'm not passing args properly. Let me take another look.

**Comment by max-zilla** [comment]
@ZongyangLi ok, just had to wrap unicode name in str() before passing to read()

Now I am encountering missing metadata field:
```
Metadata file missing key: scanisinpositivedirection
```
This is likely an old metadata key. if you look at the metadata here:
https://terraref.ncsa.illinois.edu/clowder/datasets/590238f74f0c38c084d7b75a
...do you know if we could use any of the other fields to determine correct value here? is that key just a boolean value? Not sure if that was originally something LemnaTec provided or what.

**Comment by max-zilla** [comment]
@ZongyangLi ok, just had to wrap unicode name in str() before passing to read()

Now I am encountering missing metadata field:
```
Metadata file missing key: scanisinpositivedirection
```
This is likely an old metadata key. if you look at the metadata here:
https://terraref.ncsa.illinois.edu/clowder/datasets/590238f74f0c38c084d7b75a
...do you know if we could use any of the other fields to determine correct value here? is that key just a boolean value? Not sure if that was originally something LemnaTec provided or what.

**Comment by ZongyangLi** [comment]
@max-zilla 
This is a really important value to determine the algorithm and the output, in each scan there should be one key tells us the scan direction.

One other field I know relate to this value is 'position y [m]' in 'gantry_system_variable_metadata', if 'position y [m]' is '0', 'scanIsInPositiveDirection' should be 'True',  else if 'position y [m]' is '22.135' or something else that I didn't check, it should be 'False'.

**Comment by max-zilla** [comment]
@ZongyangLi ok, I'll add the simple position y check for now so I can run it.

In meantime, @smarshall-bmr @solmazhajmohammadi @dlebauer @craig-willis anyone know why this metadata field might've disappeared at some point? Not sure when this was changed.

**Comment by max-zilla** [comment]
first successful output run!
https://terraref.ncsa.illinois.edu/clowder/datasets/5909d38f4f0c2ca933f8a603 

Closing this issue for now. In the other issue I mentioned that we need to get the values (at least the highest value) to geostreams which should be quick.
