### ISSUE TITLE
Update Workbench Docker images

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#304]
We currently have multiple Docker images each with different dependencies. Consolidate or add broader support for tutorials in a single container:

### Completion Criteria   
* [x] Add Python to Rstudio environments
* [x] Combine the Rstudio environments
* [x] PlantCV and pyClowder dependences
* [x] Geospatial support in Jupyter

**Comment by dlebauer** [comment]
@craig-willis is it possible to also hook these containers up to bety by keeping an SSH tunnel open like 

```
ssh -Nf -L 5432:localhost:5432 bety6.ncsa.illinois.edu
```

**Comment by craig-willis** [comment]
@dlebauer Probably -- but just curious, why is it necessary/desirable to connect to BETY via localhost instead of the full name?

**Comment by dlebauer** [comment]
Good question. That is the method @robkooper suggested ... also how we are
connecting GIS software.

**Comment by dlebauer** [comment]
I know some instances of betydb allow anyone to connect locally but
restrict remote access for security. Not sure if that is related.

**Comment by robkooper** [comment]
this is using a ssh tunnel to create so that we don't not have to open the postgres database to anybody that does not have access to the machine itself.

**Comment by craig-willis** [comment]
@robkooper I met with David to discuss this.  It sounds like the basic requirement is to allow Workbench users to easily connect to the BETY read-only Postgres user.  To support SSH tunneling, the user would either need to have an account/key or we would need to have some generic account available to Workbench users.  I could setup a service to proxy the request via SSH tunnel.  Another option would be to simply open the BETY server to allow the Workbench server to connect to 5432. Either way is possible, but it seems that opening access from the Workbench service might be easier?

**Comment by gsrohde** [comment]
@craig-willis I'm not sure if this helps (you may already understand this) but bety6.ncsa.illinois.edu is "local" once you are through the ssh tunnel.  So the full name is specified in setting up the tunnel but needn't then be specified in the database connection.  While one could allow remote connections directly to the database, Rob considers it more secure to restrict to local connections and then use a tunnel to get around the restriction.

**Comment by craig-willis** [comment]
Thanks, @gsrohde. From my understanding, this method also requires each user to have an account on the BETY server with associated credentials (either u/p or SSH key).  In talking with David, it sounded like we want to allow Workbench users to access BETY readonly without requiring a separate OS account to access the BETY server.

**Comment by gsrohde** [comment]
@craig-willis Conceivably you could use a shared machine account with limit permissions.  One problem with this is that if the credentials need to be changed, then everyone needs to be notified.  Possibly there are other better ways of doing this that are beyond my ken.  See also https://github.com/terraref/computing-pipeline/issues/262 for some background on this.

**Comment by robkooper** [comment]
We can look and see what needs to be done to allow for a viewer that can access the database inside NCSA. I do want to spend some time to make sure this is secure. I want to make sure we limit this user to only those tables that are needed. For example this viewer account should not need to see the users table (which contains the encrypted passwords, and api keys).

**Comment by craig-willis** [comment]
As discussed in weekly meeting: Some users have access to the machine and a postgres account (separate from the web UI). It sounds like there are security issues we'd need to address to allow direct access to BETY. Otherwise, we can use the sync feature to a separate copy. Rob is talking with NCSA security about allowing access to Postgres.  One option would be to setup a Postgres container on Workbench with anonymized data to allow users to do analysis.

**Comment by dlebauer** [comment]
related: https://github.com/terraref/reference-data/issues/111

**Comment by dlebauer** [comment]
@craig-willis in the R container, please replace `devtools::install_github("ropensci/traits")` with `devtools::install_github("terraref/traits")`. Once it is live I will probably have a few simple r package dependencies to add since I haven't tested the code on a single container yet.

**Comment by craig-willis** [comment]
I've created an rstudio-terraref image that contains Rstudio, Python2, Python3, Plantcv dependencies.   You can test this in Workbench by importing the following service spec:

```
{
  "key": "rstudioterra",
  "label": "RStudio TERRA-REF",
  "description": "IDE for the R programming language.",
  "logo": "/asset/png/logos/rstudio-logo.png",
  "image": {
    "registry": "",
    "name": "craigwillis/rstudio-terraref",
    "tags": [
      "latest"
    ]
  },
  "display": "stack",
  "access": "external",
  "ports": [
    {
      "port": 8787,
      "protocol": "http",
      "contextPath": "/"
    }
  ],
  "repositories": [
    {
      "url": "https://github.com/rocker-org/rocker-versioned",
      "type": "git"
    }
  ],
  "readinessProbe": {
    "type": "http",
    "path": "/images/rstudio.png",
    "port": 8787,
    "initialDelay": 1,
    "timeout": 360
  },
  "volumeMounts": [
    {
      "mountPath": "/home/rstudio"
    }
  ],
  "resourceLimits": {
    "cpuMax": 500,
    "cpuDefault": 100,
    "memMax": 2000,
    "memDefault": 50
  },
  "tags": [
    "7",
    "28",
    "40"
  ],
  "info": "https://nationaldataservice.atlassian.net/wiki/display/NDSC/RStudio",
  "authRequired": true
}
```

Dockerfile is here:
https://github.com/terraref/toolserver-dockerfiles/blob/kitchensink/kitchensink/rstudio/Dockerfile

Let me know if you need any changes.  I'll start working on the Jupyter environment.

**Comment by craig-willis** [comment]
I still need to complete the Jupyter image.

**Comment by craig-willis** [comment]
Added gdal to Jupyter image, fixed plantcv branch (dev > master).

**Comment by dlebauer** [comment]
@craig-willis what steps are remaining before closing this issue?

**Comment by craig-willis** [comment]
Create automated builds in Dockerhub (in process) and confirm builds are working (smoke test). Hopefully close out today.

**Comment by craig-willis** [comment]
New Docker Images:
* https://hub.docker.com/r/terraref/rstudio-terraref/: RStudio (rocker/geospatial) + TERRA packages + Python + PlantCV
* https://hub.docker.com/r/terraref/jupyter-terraref/: Jupyter + NetCDF + GDAL + PlantCV

I've updated the original "RStudio Server" application to use the new image instead of the original rocker image.  One snag, I'd like to delete some of the other applications (i.e., R geospatial, Jupyter + NetCDF) -- but many of them are or were in use by team members. I'll need to email folks to get them to remove these applications or let me know if they are still in use.

**Comment by craig-willis** [comment]
@dlebauer  Do you want to re-open this ticket or start a separate discussion?  Is this something we need to think about before the November release?

**Comment by dlebauer** [comment]
I think open another issue for future (target the Nov 2018 release). I
think it should be sufficient for now if we retain home directories from
deleted containers and encourage people to use github repositories for the
code that they write. Isn't reproducibility planned as part of a core NDS
workbench feature?

**Comment by craig-willis** [comment]
https://github.com/terraref/computing-pipeline/issues/344
