### ISSUE TITLE
Change extractors to query plot boundaries from betydb

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#307]
I've added all plots through the current season At Maricopa 

This means that extractors should be able to query terraref.ncsa.illinois.edu/bety/api/beta/experiments

Ideally extractors can now query experiments to find all experiments given the date and location, and then find the associated sites. This will require @gsrohde to deploy the experiments endpoint. 

This will replace the current user of an ad hoc shape file in the extractors

**Comment by max-zilla** [comment]
@dlebauer @gsrohde do we currently have a means to query sites table by lat/lon? 

I am working on terrautils and hoping to replace the "query a local shapefile for overlapping polygons and assign sites that way" code with "query BETYdb with my centroid lat/lon and get any site(s) that is within".

@robkooper didn't think such an endpoint existed yet - does it? 

A middle ground could be querying by experiements and iterate over all the sites to check each one for overlap, but that is slow and Postgres could do this more efficiently internally (this code will trigger on every dataset, every day).

**Comment by max-zilla** [comment]
@jterstriep FYI, we can both use this.

**Comment by gsrohde** [comment]
@max-zilla I'm almost certain no such query is currently possible within the API.  It seems like such a filter wouldn't be difficult to implement.  I'm imagining an additional parameter such as `containing=40,-88`.

**Comment by max-zilla** [comment]
@jterstriep gonna dump this on ya since I just wrote it for terrautils:
```
import requests

def get_sites(host="https://terraref.ncsa.illinois.edu/bety", city=None, sitename=None):
    """Get list of sites from BETYdb, filtered by city or sitename prefix if provided.

        e.g.
            get_sites(city="Maricopa")
            get_sites(sitename="MAC Field Scanner Season 2")

    city -- city parameter to pass to API
    sitename -- string to filter returned sites by sitename prefix
    """
    sess = requests.Session()
    sess.auth = ("guestuser", "guestuser")

    betyurl = host + "/sites.json"
    if city:
        betyurl += "?city=%s" % city

    r = sess.get(betyurl)
    r.raise_for_status()

    if sitename:
        all_results = r.json()
        filtered = []
        for currsite in all_results:
            if 'site' in currsite:
                if 'sitename' in currsite['site']:
                    if currsite['site']['sitename'].startswith(sitename):
                        filtered.append(currsite)
        return filtered
    else:
        return r.json()
```

Can be used like so:
```
>> s = terrautils.betydb.get_sites(sitename="MAC Field Scanner Season 2")
>>> len(s)
350
>>> s[0]
{u'site': {u'city': u'Maricopa', u'geometry': u'POLYGON ((-111.975032369538 33.0763972541809 353.0, -111.975015978712 33.0763972619415 353.0, -111.975015956477 33.0763640256532 353.0, -111.975032347404 33.0763640178919 353.0, -111.975032369538 33.0763972541809 353.0))', u'country': u'USA', u'notes': u'', u'time_zone': u'America/Phoenix', u'sitename': u'MAC Field Scanner Season 2 Range 52 Pass 1', u'state': u'Arizona', u'greenhouse': False}}
>>> s[1]
{u'site': {u'city': u'Maricopa', u'geometry': u'POLYGON ((-111.974999587779 33.0763972697008 353.0, -111.974983196953 33.0763972774571 353.0, -111.974983174837 33.0763640411677 353.0, -111.974999565657 33.0763640334115 353.0, -111.974999587779 33.0763972697008 353.0))', u'country': u'USA', u'notes': u'', u'time_zone': u'America/Phoenix', u'sitename': u'MAC Field Scanner Season 2 Range 52 Pass 2', u'state': u'Arizona', u'greenhouse': False}}
```
I think since GDAL is already a requirement for terrautils, until the API is extended I'll try writing a quick function to parse the geometry field and allow you to provide a lat/lon and return all sites that intersect it.

**Comment by dlebauer** [comment]
@max-zilla there is a geometry endpoint on the API but I doubt you can query sites w/ a lat/lon point using the API as this is a special type of geospatial query. 

but using SQL to find sites containing a file with the point 33.075950795147, -111.975025821879 and date 2016-11-01

```sql
SELECT id, sitename, st_asgeojson(geometry)
FROM
	sites
WHERE
	ST_CONTAINS (
		geometry,
		st_geomfromtext ('POINT(-111.975025821879 33.075950795147)', 4326)
	)
AND id IN (
	SELECT
		site_id
	FROM
		experiments_sites
	WHERE
		experiment_id IN (
			SELECT ID
			FROM
				experiments
			WHERE
				DATE '2016-11-01' BETWEEN start_date AND end_date
		)
)
```

Is it possible to query the database directly to perform such queries? Currently the API is very slow and lacks functionality to support both the 'contains' and 'between' operators.

**Comment by jterstriep** [comment]
@max-zilla, the sitename is pretty non-standard within bety. Generally, I had to string search for '%Season N%' but Season 2 has two different definitions of plots. The different formats are as follows:

MAC Field Scanner Season 1 Field Plot N
MAC Field Scanner Field Plot N Season 2
MAC Field Scanner Season 2 Range N Pass N   # non-standard plot boundaries
MAC Field Scanner Season 3 Range N Column N
MAC Field Scanner Season 4 Range N Column N

I think there is a full field boundary that doesn't match up in the table as well. It would be nice to standardize this.

**Comment by max-zilla** [comment]
FYI @gsrohde has implemented support for lat/lon sites filter into BETY and it's in testing:
https://github.com/PecanProject/bety/pull/514

**Comment by rachelshekar** [comment]
@max-zilla please update

**Comment by max-zilla** [comment]
@gsrohde has the "contains" bety code been pushed to the terra instance, and if not can we do so? I have the python code to request plots by location but wasn't sure if your API update has been deployed yet (I know you merged the pull request)

**Comment by gsrohde** [comment]
@max-zilla It hasn't been pushed yet.  I'd like wait until I get sign-off from @robkooper on pull request https://github.com/PecanProject/bety/pull/522 and then do a formal release which includes that as well, but if this is really holding you up, I could perhaps just push those changes to terra-ref sooner.

**Comment by dlebauer** [comment]
https://github.com/PecanProject/bety/pull/522/files is for sites cultivars
constraints. Why is that holding this up?

**Comment by dlebauer** [comment]
Sorry I misunderstood. Can max review the PR?

**Comment by gsrohde** [comment]
Perhaps.  Or if not, I'm pretty sure I got it right, so maybe I can just go ahead and incorporate it.  Rob is the one who urged me to put Rails changes in pull requests (I assumed he mainly meant those involving database changes), but we also need to be able make changes in a timely manner.  

Of course, we also were going to try not to do new releases at the very end of the week, but we could make an exception.

**Comment by dlebauer** [comment]
I think it is good to have pull requests, but also ok for max to review them

**Comment by max-zilla** [comment]
The SQL looks functional to me but I'm not familiar with the "why" for this sequence fix - probably still good to have @robkooper take a quick look, but the pull request is small so hopefully that'll be quick.

**Comment by max-zilla** [comment]
These updates are in progress.

@dlebauer @craig-willis do we have a mapping for season to date? @jterstriep pointed out these patterns in Bety sitenames:
```
MAC Field Scanner Season 1 Field Plot N
MAC Field Scanner Field Plot N Season 2
MAC Field Scanner Season 2 Range N Pass N # non-standard plot boundaries
MAC Field Scanner Season 3 Range N Column N
MAC Field Scanner Season 4 Range N Column N
``` 

I would like to add a small method to terrautils that will determine season to use based on a dataset's timestamp, akin to this (dates are placeholder):
```
{
    'Season 1': {
        'begin': '2016-04-01',
        'end': '2016-07-31',
        'template': 'MAC Field Scanner Season 1 Field Plot {plot}'
    },
    'Season 2 (Plots)': {
        'begin': '2016-08-01',
        'end': '2017-10-31',
        'template': 'MAC Field Scanner Field Plot {plot} Season 2'
    },
    'Season 2 (Range/Pass)': {
        'begin': '2016-11-01',
        'end': '2017-12-31',
        'template': 'MAC Field Scanner Season 2 Range {range} Pass {pass}'
    }
}
```

**Comment by dlebauer** [comment]
@max-zilla 

The experiments table lists seasons with start / end dates: https://terraref.ncsa.illinois.edu/bety/api/beta/experiments?key=9999999999999999999999999999999999999999

Each experiment is linked to a set of plots via the experiments_sites table that can be queried thus:

**Comment by max-zilla** [comment]
@dlebauer thanks, this is much simpler.

**Comment by dlebauer** [comment]
Can this be closed?
