### ISSUE TITLE
Create "terrautils" python library/repository

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#308]
Create a new terrautils repository and stub out a Python library (setup.py, requirements.txt, etc). This repo and library will be used going forward for TERRA-specific helper functions (e.g., interfacing to BETY, Clowder, sensor metadata, etc) from extractors and globus pipeline.

Completion criteria:
* [x] Create repo
* [x] Create basic library/framework
* [x] Review

**Comment by max-zilla** [comment]
Created: https://github.com/terraref/terrautils

Craig, feel free to close this once you take a look. Tried to add stubs for initial methods we're adding as well.
