### ISSUE TITLE
Implement terrautil interfaces for metadata

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#310]
As outlined in the [Terra Utils library discussion](https://docs.google.com/document/d/16pxlpmI0Re6Zp5eCRcqF9tuyJ20aBoFtf9nho5DBHQw/edit), add support for the following to the terrautils library:

* Fixed metadata
** get(sensor)
** clean(json)
** clean(sensor metadata)
* Variable thesaurus
** get_synonym(variable

Completion criteria
* [x] Design documentation
* [x] Implement
* [ ] Documentation
* [ ] Testing
* [ ] Review

**Comment by craig-willis** [comment]
Design notes
https://docs.google.com/document/d/16pxlpmI0Re6Zp5eCRcqF9tuyJ20aBoFtf9nho5DBHQw/edit

**Comment by craig-willis** [comment]
PR:
https://github.com/terraref/terrautils/pull/5

**Comment by craig-willis** [comment]
@max-zilla  How are we documenting the terrautils library going forward?

**Comment by max-zilla** [comment]
@craig-willis for release, i would start with a short paragraph about each module and what kinds of things it contains. detail beyond that might be excessive for now...

**Comment by dlebauer** [comment]
I am a big fan of inline documentation ... would it make sense to put the short paragraphs inside the .py files and use pydoc https://docs.python.org/2/library/pydoc.html or similar to generate html documentation?
