### ISSUE TITLE
Deploy BETYdb summary app

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#311]
The app in PR terraref/reference-data#110 provides a Python Flask app that summarizes available data in BETYdb, with daily updates 

I got it close to running thus:

```
cd /gpfs/largeblockFS/projects/arpae/terraref/sites/ua-mac/www
git clone git@github.com:terraref/reference-data
cd reference-data
git fetch origin 
git checkout -b feature origin/feature
cd experiment-trait-data-visualizer_sample
python -m pip install -r requirements.txt --root ~/.pip/
python3 app.py

module load python/3.4.2
export PYTHONPATH=/gpfs/smallblockFS/home/dlebauer/.pip/sw/python/3.4.2/lib/python3.4/site-packages:$PYTHONPATH
export BETYdbKey=`cat ~/.betykey` # from terraref.ncsa.illinois.edu/bety/users
python3 app.py
```

### Discussion

This is a lightweight job, so could run on head node without anyone noticing (a single web page w/ a few charts. I've put a sample (compiled on laptop and moved to the webapps folder) here: https://terraref.ncsa.illinois.edu/webapps/ua-mac/experiment-trait-data-visualizer_sample/

Does this go in a container? Or can it run on the head node?

### Completion Criteria

* [ ] updated app is in terraref/sites/ua-mac/www/experiment-trait-visualizer and served here: https://terraref.ncsa.illinois.edu/webapps/ua-mac/experiment-trait-data-visualizer_sample/
* [ ] deployment instructions documented

**Comment by robkooper** [comment]
This is already running on a special node: http://141.142.211.143:5000/ right now. Eventually it needs to be linked into the nginx server. This was done by @nickheyek

**Comment by dlebauer** [comment]
@nickheyek is the scheduler and cache working? The most recent files in the cache on the terra-traitvis server /home/nheyek/reference-data/experiment-trait-data-visualizer/api_data_cache/ are from April 20. We've updated a bunch of the data. How can this be re-triggered?

**Comment by rachelshekar** [comment]
@nickheyek please update

**Comment by nickheyek** [comment]
This issue describes the previous version of the BETYdb trait data summary app.
The current version is still not ready for full deployment, in the process of ironing out some issues.
Hopefully will be able to deploy to VM by early next week.

**Comment by dlebauer** [comment]
Nick if this one is replaced by a new epic please add a link and close this

**Comment by nickheyek** [comment]
https://github.com/terraref/reference-data/issues/142
