### ISSUE TITLE
Add Google analytics to Workbench

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#312]
Add TERRA project analytics ID to workbench instance for tracking purposes.

Completion criteria
* [x] Tracking ID added to webui configuration
* [ ] Confirm tracking information appearing in analytics.

**Comment by craig-willis** [comment]
Spoke with Mike from Workbench team and we recommend that you have a single TERRA "Account" with multiple applications/properties.  We would just need the tracking ID that I can put in the webui container to start tracking.

**Comment by dlebauer** [comment]
Tracking ID sent via Slack PM

**Comment by craig-willis** [comment]
Looking at the real-time report, this appears to be working.
