### ISSUE TITLE
Workbench approval and support emails

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#313]
Currently Workbench has a single email address for all account approval and support requests. For NDS, we use a mailing list -- ndslabs-support@... -- and membership is managed through the list.  

We discussed this, but I'm not sure what's the best solution at this point.  My inclination is to setup a TERRA support list similar to NDS that can be used across all services.  We also discussed setting up forwarding rules.

**Comment by robkooper** [comment]
@mchenry set up a special address support@nationaldataservices to allow for this. We can use support+terra@national to send it to the right domain.

Right now me and kenton get this email, but the goal is to have this go into a jira for a specific group.

**Comment by craig-willis** [comment]
David provided a different email address for https://github.com/terraref/computing-pipeline/issues/314

**Comment by craig-willis** [comment]
Closing this in favor of #314.
