### ISSUE TITLE
Update Workbench to 1.0.10

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#314]
Workbench 1.0.9 has a bug in the approval process, preventing approval flag from being respected. This is fixed in 1.0.10, but will require additional changes/considerations:

* [x]  What is the support email address for approval/support requests? terraref-support@lists.illinois.edu
* [x] Need to update the UI customization to 1.0.10 (minor bugfixes)
* [x] Set correct forum (no forum) and chat service (terra-ref.slack.com) URLs
* [x] Add terms of service link back in

Deploying this will require brief downtime (< 5 minutes) for the webui.

**Comment by dlebauer** [comment]
support email address: terraref-support@lists.illinois.edu

**Comment by dlebauer** [comment]
@robkooper regarding which email address to use for account approval ... I don't have a preference between support+terra@nationaldataservice.org and terraref-support@lists.illinois.edu so long as the approval requests are forwarded to Rachel, me, and anyone else who can be trusted and is willing to accept this great responsibility.

**Comment by craig-willis** [comment]
Upgrade is complete.  This includes fix for the approval process, change to use terraref-support@lists.illinois.edu for registration and support requests, and addition of Google analytics tracking ID.  I'll leave this open until we've had the chance to confirm the changes.

**Comment by robkooper** [comment]
I think in this case we should just use the terraref-support.

**Comment by craig-willis** [comment]
Email, approval, and analytics changes all appear to be working.  Closing this.
