### ISSUE TITLE
Change API endpoint from /api/beta to /api/v1

### ISSUE THREAD

**Issue by gsrohde** [terraref/computing-pipeline#320]
For now, simply make v1 a duplicate of beta and deprecate the beta path.  We should plan on maintaining beta for a few years before removing it.

**Comment by gsrohde** [comment]
This should be fixed by pull request https://github.com/PecanProject/bety/pull/527.

**Comment by rachelshekar** [comment]
@gsrohde can this be closed?

**Comment by rachelshekar** [comment]
@gsrohde please deploy and close
