### ISSUE TITLE
PI4 instance

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#321]
This is just to track work done to deploy the TERRA-REF Workbench for the upcoming PI4 class.  The PI4 class will run 5/26 - 6/9 with ~20 students accessing R/Jupyter/OpenRefine containers to access the TERRA-REF dataset.

* [x] Provision Workbench instance
* [x] Create custom catalog using existing TERRA-REF containers
* [x] NFS exports/mounts for data
* [x] Add OpenRefine container
* [x] Import users
* [ ] Acceptance/review

**Comment by dlebauer** [comment]
It's awesome, thanks for pulling this together. I'll let you know if anything comes up but seems ready to go. If you could set up the cron job of do ones more import of betydb before next Tuesday then please close the issue.

**Comment by craig-willis** [comment]
I've added the bety postgis instance.  For pi4.ndslabs.org, you should be able to connect with the following:

Host: terra-bety.default
Port: 5432
User: bety
Password: bety
DB: bety

**Comment by craig-willis** [comment]
Closing this.  Will open a new ticket to address lessons learned from pi4 workshop.
