### ISSUE TITLE
DNS entries for traits and sensors.terraref.org

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#322]
From issue #290.

DNS for terraref.org is now managed by NCSA.  We have setup workbench.terraref.org. It would be useful to setup these additional entries:

* traits.terraref.org > bety (currently https://terraref.ncsa.illinois.edu/bety)
* sensors.terraref.org > clowder (currently https://terraref.ncsa.illinois.edu/clowder)
* thredds.terraref.org --> https://terraref.ncsa.illinois.edu/thredds
* traitvis.terraref.org --> http://traitvis.workbench.terraref.org/ (or could this be embedded in bety or provided at traits.terraref.org/traitvis??)
* (maybe?) documentation.terraref.org --> documentation hosted on a docker container

In discussions with @robkooper, there are a few issues.  

1. bety and clowder are currently configured to respond to a specific path (as in the above URLs).   
2. much of the documentation, tutorials, and code point to the original URLs (particularly API calls).  If we do this, we'll want to make sure we don't break existing functionality.   It's not clear to if we can support both name and path based access to the services.

**Comment by dlebauer** [comment]
To be clear this would be nice but isn't essential. And I think there is
value in keeping these at default paths like /bety because that might be
easier in the long run. Would terraref.org/bety be easier to implement?

Would it help to do the change alongside the beta release? Then use sed to
find/replace everything in docs and code?

**Comment by dlebauer** [comment]
How much effort will this take? If we are going to do it, it seems like it would be a good idea to do so while I am updating the documentation and preparing the initial data publication.

**Comment by craig-willis** [comment]
We're not going to do this for now. Re-open if a priority.
