### ISSUE TITLE
Generate full field flirIR image from week of May 22

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#327]
@nshakoor reports a need of the group:

> Is there a way to pull an IR scan from a clear day last week and overlay a plot map onto it? For one of our field campaigns, we need to quickly choose 2-4 genotypes that are giving a different IR signature from the IR camera. These lines will be phenotyped extensively on the ground using hand held instruments.

We have converters for the IR data to geoTIFF and code written for the stereo RGB camera to stitch geoTIFFs into a full field mosaic, but we haven’t tested how the RGB parameters look when applied to IR camera – it may end up that we need different FOV calibrations from Stuart.

But we’re probably talking ~inches of misalignment I’d guess, so you can likely get some insight from it regardless. 

I will update this issue when I have some result to look at.

**Comment by ZongyangLi** [comment]
@max-zilla 
parameters for flir data stitching has been created, please see comment here:
https://github.com/terraref/computing-pipeline/issues/309#issuecomment-303523904

**Comment by max-zilla** [comment]
@ZongyangLi did you implement a fix for rotating 90 degrees? i included the parameters I believed you meant:
```
elif sensor=="flirIrCamera":
        HEIGHT_MAGIC_NUMBER = 1.0
        camH_fix = camHeight + HEIGHT_MAGIC_NUMBER
        fov_x = fov_x * (camH_fix/2)
        fov_y = fov_y * (camH_fix/2)
        return (_get_bounding_box_with_formula(center_position, [fov_x, fov_y]))
```

...but the full field stitch has everything rotated 90 degrees.
![screen shot 2017-06-08 at 9 09 26 am](https://user-images.githubusercontent.com/14166971/26933040-00c82994-4c2b-11e7-9b70-159899243534.png)

I fixed the Byte/Float32 issue, but this rotation issue still remains.

**Comment by ZongyangLi** [comment]
@max-zilla 
I had made that 90 degrees fix here: https://github.com/terraref/extractors-multispectral/blob/master/flir2tif/Get_FLIR.py#L287

I am going to try this again. BTW, thanks a lot for the fix of Byte/Float32 issue, that is really something I was missing.

**Comment by max-zilla** [comment]
@ZongyangLi that's it! thanks. The dockerfile i was running was missing the rot90 piece.

As an aside, why are we reshaping these to 640x480? Is there a reason not to use default resolution?

**Comment by ZongyangLi** [comment]
@max-zilla You're right, we should not use default resolution, the reason I use a default value is at the time I created the code, there is only a parameter call: `"sensor description": "IR Sensor 640x480",` and I think this might not be a exactly resolution parameter, so I leave it in the origin code. Maybe it's time to update the resolution from metadata now?

**Comment by max-zilla** [comment]
for what it's worth, 640x480 doesn't seem too bad. Heres a full-res image (in red) overlaid with the full field mosaic that I generated at 10% resolution:
![screen shot 2017-06-08 at 9 40 55 am](https://user-images.githubusercontent.com/14166971/26934286-958c15ec-4c2e-11e7-9b81-b607e9553450.png)

![screen shot 2017-06-08 at 9 39 58 am](https://user-images.githubusercontent.com/14166971/26934244-7816dc9a-4c2e-11e7-9a88-853450994f38.png)

**Comment by max-zilla** [comment]
The rotation fix looks good:
<img width="380" alt="screen shot 2017-06-08 at 11 14 08 am" src="https://user-images.githubusercontent.com/14166971/26939054-b00e9130-4c3b-11e7-8b05-c4bde319ce4b.png">
05/29 isn't quite complete yet, but I should have a full field example for Nadia over the weekend.

**Comment by dlebauer** [comment]
@smarshall-bmr can you confirm that the FLIR sensor resolution is 640x480 pixels?

**Comment by max-zilla** [comment]
I have
