### ISSUE TITLE
Full field and plot level viewer and API

### ISSUE THREAD

**Issue by jterstriep** [terraref/computing-pipeline#329]
# Description
Users would like to have a way to review full field images and easily extract plot level data. Two use cases exist 1) user reviews full field/plot image as a map service for display within a browser and/or 2) an API provides easy access to full field/plot images for UIs, extractors, desktop tools, etc.

### Discussion Issues
* Deploy map service, API, or both?
* Full field image can be large and require special file formats.
* Use of compression will reduce image quality. Is that acceptable?
* Move to netCDF and Thredds server might make the API unnecessary.
* Consistent naming of level 1 files

### API (discussion only)
/sites/:site/sensors/:sensor/:date

/sites/:site/sensors/:sensor/:date/plots/:range/:column

### Completion Criteria 
* [ ] Discuss and determine most useful services if any. Create new issues to reflect the decision.

**Comment by dlebauer** [comment]
key search parameters / endpoints:

* cultivar_id + optional date
* sitename
* filetype: (netcdf &or geotiff), jpg?

Should extractors call API or directly query BETYdb and clip files on disk

**Comment by jterstriep** [comment]
The current service takes the sensor name and date and returns a geotiff clipped to the boundary of the sitename. The current clipping service requires site, sensor, and date. Using those three parameters we can navigate the filesystem to locate the full field stitched image.

We can either assume that users will first query betydb to get a list of sitenames (ie based on cultivar_id and date) or we could provide a wrapper that handles the betydb query internally.

**Comment by dlebauer** [comment]
Two pull requests are open:
* Nick made BETYdb api
* Jeff's student hooked into GDAL

Extractors via terrautils don't need API, API is mainly aimed at end users and search interface.

Next steps (by end of July)

* terrautils merged
* API draft
  * flask app w/ API + web interface
  * need to know - where is it going to live and how will it be integrated into the search interface that @craig-willis is working on

@jterstriep and @max-zilla please close this, create an epic that links associated tasks.

**Comment by rachelshekar** [comment]
@jterstriep reminder

**Comment by dlebauer** [comment]
Current implementation is here: http://141.142.170.38:8000/api/v1/sites/ua-mac/sensors/stereoTop/2017-04-27?sitename=MAC

Where will this be deployed? What are next steps?

**Comment by dlebauer** [comment]
* update to use terrautils library
* most important is the API full field clipper
  * has a form and a map interface

**Comment by dlebauer** [comment]
@jterstriep please close this, create an epic that links associated tasks.

**Comment by craig-willis** [comment]
This is a stale issue with no comments in last 2 months. Please create new issues if work remains or put this content in the documentation.
