### ISSUE TITLE
Scale up Workbench instance based on PI4

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#331]
The TERRA-REF Workbench instance is currently a single-node 4VCPU/32GB RAM instance.  This has worked reasonably for local development work.   For comparison, the PI4 workbench instance is a multi-node configuration with 4 instances for a total of 16VCPU/96GB RAM.  This has been generally effective for supporting ~30 simultaneous users accessing Jupyter/Rstudio/Openrefine/PGstudio instances for workshop tutorials.  The multi-node configuration is more scalable (can easily add nodes), but also consumes more resources (minimal configuration requires 3 instances -- 1 master (4VCPU/8GB) and 2 compute nodes of any size.  Each node also has different volumes (boot volume, docker image storage, and GFS bricks). The pi4 instance was deployed in the NDS-hackathon project on Nebula because the TERRA project didn't have sufficient resources to support scaling.

On a side note, to access TERRA-REF data each compute node needs to be able to mount the sites directory on ROGER.  The end solution was to assign nodes in NDS-hackathon from a range of IPs that could be added to the export rules on ROGER.  Previously, IPs were added one-by-one.

This ticket is meant to serve as a discussion:
[ ] Do we want to  (and have the resources to) deploy a multi-node Workbench instance?
[ ] Is it better to host these and related workshops on NDS resources (finite lifetime) or scale up TERRA resources to handle bursts of usage?

**Comment by dlebauer** [comment]
Lets wait until we observe that terraref users need additional resources. For future workshops, we will use the workshop specific instance to enable scaling up if necessary (and possible)

**Comment by dlebauer** [comment]
@craig-willis can this be closed?

**Comment by craig-willis** [comment]
With new Kubernetes cluster, this is done.
