### ISSUE TITLE
update 3dscanner plant_height

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#332]
Currently this extractor generates two numpy files:
```
ls /projects/arpae/terraref/sites/ua-mac/Level_1/scanner3DTop_plant_height/2017-05-06/2017-05-06__05-05-58-934
scanner3DTop - 2017-05-06__05-05-58-934 highest.npy  scanner3DTop - 2017-05-06__05-05-58-934 histogram.npy
```

In #303 we mention pushing the max value to geostreams - this isn't implemented yet. 

Additionally we should convert the .npy files to an image or geotiff.

**Comment by max-zilla** [comment]
@nickheyek maybe in next day or two you can sit with me while I make this update & can double as a more in-depth explanation of this extractor and geostreams.

**Comment by nickheyek** [comment]
Sounds great

**Comment by dlebauer** [comment]
Not just max height but 5% quantiles

**Comment by rachelshekar** [comment]
closing; https://github.com/terraref/computing-pipeline/issues/210 has more information
