### ISSUE TITLE
Hyperspectral solstice calibration diurnal scan

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#333]
@dlebauer and @czender @solmazhajmohammadi - please update and assign to Stuart

Fixed x and y location of target preferred to reduce man hours of finding targets; best to run in same mode  every time (trigger mode v. free-running).  However, VNIR isn't working in trigger mode right now so this may not be possible.

**Comment by czender** [comment]
One reason to re-calibrate is to potentially avoid the need to manually identify the target location, which currently drifts with the 20170415 images as shown in #281. If that issue cannot be eliminated , then a new calibration will require just as much work as the 20170415 calibration. Aother reason to recalibrate is to obtain imagery at peak solar zenith angles (~10 degrees) that are reached near solstice.

**Comment by solmazhajmohammadi** [comment]
@smarshall-bmr please update the script that you are running, comment out the delays for dark measurement in SWIR camera. and disable the dark measurement in SWIR (this should be done in a separate night scan). This would make it easier to georeference the datacube.

**Comment by dlebauer** [comment]
@smarshall-bmr any updates on this? Have you been able to run another calibration?

**Comment by rachelshekar** [comment]
Rerun on 8/9 with these targets: 75, 25, 99, 2 color, ceramic tile

**Comment by rachelshekar** [comment]
@hmb1 please check data and close issue

**Comment by dlebauer** [comment]
@hmb1 will you be able to use scans where targets are in 1/2 shade, 1/2 sun?

**Comment by dlebauer** [comment]
The scan has been completed; this issue can be closed.

**Comment by dlebauer** [comment]
For 8/9 the calibration images are every 5th scan
