### ISSUE TITLE
Synthesize existing BETYdb python code

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#337]
In order to complete #309 we need to add BETYdb functions for getting and posting data to Bety Postres database.

Some code already (partially) exists:
- https://github.com/terraref/terrautils/blob/master/terrautils/betydb.py (Max's placeholder - some extractors use submit_traits)
- @nickheyek has looked at the bety R package and has some code I believe.
- @jterstriep and his team have some code for sites.

We should look at what we have and integrate. As a first step, @nickheyek @jterstriep can you link to the relevant code and tag your team so we can all take a look?

**Comment by nickheyek** [comment]
The functions I had implemented existed originally for the BETYdb Trait Summary Flask app which has been replaced by an R/Shiny app that uses the OpenSci package.
There were only a couple of functions for accessing trait records within a date range, and accessing additional data from variable ids.
While it's no longer on Github, replicating those functions could be done pretty quick.
Is there a list of functions for interfacing with BETYdb that you think would be useful?

**Comment by gsrohde** [comment]
@max-zilla, @nickheyek: Regarding date ranges, please be aware that dates stored in the traits table are (or should be) stored in UTC if the time zone of the trait site is known and populated in the database.  This means, for example, that a trait measured at a Maricopa site with `date` value `2017-06-07 00:02:02` was actually measured on 2017-06-06 local time.

For trait measurements with `timeloc` value 9 (time unknown), but on a known date (`dateloc` value 5), the convention is to store the time as midnight local time on the known date (which, for Maricopa sites, means these appear as timestamp values with the hour portion being `07`).

(I've written draft documentation of all these conventions but have yet to publish it.)

**Comment by max-zilla** [comment]
@nickheyek not a specific list but key things I think based on discussions with @dlebauer 

- generic API bety_get(endpoint, parameters) function where endpoint is just "sites" or something and we have all the BETY url & requests stuff hidden in there. I think David pointed to a similar generic method in R.

- a few nice functions that wrap bety_get() with explicit parameters, e.g. get_sites_by_date(start,end) that could generate the correct query for bety_get

- perhaps a helper function to parse results from BETY into a dictionary or list or some other python data structure that makes sense

- a POST function that lets us submit a CSV to bety. I already have something like this in there but it's not generic.

**Comment by nickheyek** [comment]
Got it, I'll get started on this today, thanks!

**Comment by max-zilla** [comment]
@nickheyek @jterstriep I took a look at Nick's PR and Benny's branch:
https://github.com/terraref/terrautils/pull/2
https://github.com/terraref/terrautils/compare/gdal_functions

I would generally summarize:
- nick's code provides bulk of bety utility functions - a basic query() function with some wrappers for traits/sites/etc.
- benny's code provides a lot that doesn't overlap (gdal, sensor files) as well as improving documentation, pulling some defaults/constants up to top of file. 
- primary method from benny's betydb file is get_sitename_boundary which basically calls the /sites endpoint (we could use nick's code) and returns a GeoJSON polygon of the vertices. 

Although it sounds like other updates may be coming, I think right now I'd be inclined to use Nick's file as a base, implement Benny's boundary() function and apply his updates to formatting/constants then go from there. wont do anything until Jeff takes a look however.

**Comment by dlebauer** [comment]
Has this been deployed? If so, can it be closed?

**Comment by max-zilla** [comment]
yes, this is done.
