### ISSUE TITLE
Queue hyperspectral data for extraction

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#339]
With latest hyperspectral extraction code (including the -h flag recently added for additional outputs) I need to queue all hyperspectral datasets for another round of extraction and, once complete, purge any deprecated results from previous extractions that are not needed.

- [x] queue hyperspectral datasets from 2016
- [x] queue from 2017
- [ ] run batch extraction jobs on Roger until queue completed

**Comment by max-zilla** [comment]
Data has been queued, updated extractor on Roger, submitted 5 48-hour extractor jobs. They're in the queue waiting to start - it'll do 2017 first, then 2016.

**Comment by craig-willis** [comment]
Done for 2017. Separate issue for 2018.
