### ISSUE TITLE
Discuss Blue Waters data management, archiving

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#34]
Introduce project to Jim Glasgow and discuss limits, scenarios for accessing HDFS via Lustre on Blue Waters.

Also (David) discuss with Patrick Mulrooney

Waiting on feedback from Jay about allocations.

**Comment by dlebauer** [comment]
@rachelshekar could you please coordinate a meeting in early 2016? @dlapine, is there anyone else who should attend?

**Comment by rachelshekar** [comment]
@jdmaloney should anyone be added?
@dlebauer - can you confirm that I should invite Jim Glasgow, JD Maloney, Patrick Mulrooney and you?

**Comment by dlebauer** [comment]
I'll discuss with Patrick over break, and see if he is interested in participating. Has Jay gotten the letter from Ed specifying NCSA's contributions and the resources we may need? I don't know that it is worth having the conversation without a more concrete statement of the resources that our project will have.

**Comment by rachelshekar** [comment]
@dlebauer - Did you speak with Patrick?  
Should I follow up with Jay about NCSA resources or did he get back to you?

**Comment by dlebauer** [comment]
Jay got the letter, and it is attached. Sorry I forgot to update here.

[TERRA Project BW Storage and CyberGIS Roger Support Letter Final v2.pdf](https://github.com/terraref/computing-pipeline/files/135274/TERRA.Project.BW.Storage.and.CyberGIS.Roger.Support.Letter.Final.v2.pdf)
