### ISSUE TITLE
PR to use Bety Postgres contains query in terrautils

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#343]
@nickheyek 

Last week @gsrohde updated the Bety instance for TERRA to include the "contains" patch allowing us to query Bety sites by lat/lon.

https://github.com/terraref/terrautils/blob/master/terrautils/betydb.py#L131

can you make a PR updating this method to use get_sites(contains=...) as suggested there, and test it? You should be able to just get a couple random sites from Bety, get their coordinates, and query with a close by 'contains' location to make sure you get the right responses.

This will be a big improvement performance wise I expect.

**Comment by nickheyek** [comment]
Sure!

**Comment by nickheyek** [comment]
The BETYdb API still seems to ignore contains as a valid keyword argument for the sites table. Is it possible that the API has not yet been updated with this change?

**Comment by max-zilla** [comment]
https://github.com/PecanProject/bety/pull/514

Here @gsrohde suggests it has been deployed, but I didn't try to test yet

**Comment by max-zilla** [comment]
containing= is the correct parameter actually I think.

**Comment by nickheyek** [comment]
Yup that's right, works perfectly, I'll implement this into terrautils now
