### ISSUE TITLE
Environmental Logger data to Netcdf

### ISSUE THREAD

**Issue by hmb1** [terraref/computing-pipeline#347]
@czender 
@solmazhajmohammadi 

Have created a python script that converts Environmental Logger files in json format to NetCDF.
The script is located at https://github.com/terraref/extractors-hyperspectral/blob/master/hyperspectral/EnvironmentLogger2NetCDF.py[](url)

For the first timestamp (record) it extracts the sensor's "wavelength". This var is repeated in all records and "as far as I can tell"  remains constant across  json files (will double check this 

for each subsequent record  it extracts 
the vars "spectrum"  and "sunDirection "

The other vars are a below.
Charlie do we want any of theses ? 
What are the units of "spectrum" ?

  "airPressure": {
          "value": "1013.5734122745",
          "unit": "hPa",
          "rawValue": "8.21436201055941"
        },
        "brightness": {
          "value": "88.9093295083",
          "unit": "kilo Lux",
          "rawValue": "4.41755424665059"
        },
        "relHumidity": {
          "value": "43.6384166997",
          "unit": "relHumPerCent",
          "rawValue": "4.36384166997284"
        },
        "temperature": {
          "value": "34.6696371349",
          "unit": "DegCelsius",
          "rawValue": "7.46696371349223"
        },
        "windDirection": {
          "value": "126.1818292795",
          "unit": "degrees",
          "rawValue": "3.50505081331828"
        },
        "precipitation": {
          "value": "0.1108655354",
          "unit": "mm/h",
          "rawValue": "0.010986663411359"
        },
        "windVelocity": {
          "value": "1.655323954",
          "unit": "m/s",
          "rawValue": "0.275887325663015"
        }
      },
      "sensor par": {
        "value": "923.3158344524",
        "unit": "umol/(m^2*s)",
        "rawValue": "9.91673788304236"
      },
      "sensor co2": {
        "value": "432.0595775852",
        "unit": "ppm",
        "rawValue": "10.9129532413625"
      },

**Comment by czender** [comment]
It sounds like you "duplicated" work of @FlyingWithJerome in
`git clone git@github.com:terraref/extractors-environmental.git
`
Specifically, environmental_logger_json2netcdf.py. Unsure if you're aware of that.
Is there a problem you trying to solve that can't be done with that?

**Comment by hmb1** [comment]
Hi Charlie,
I couldn't get Jerome's 'hyperspectral_flux_based_calibration.py' script to work ( I think he used some third-prty software to do the intial conversion to netcdf ) also some of the script did not make sense
