### ISSUE TITLE
Send hyperspectral indices to BETYdb

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#348]
@czender @hmb1 

I am updating hyperspectral extractor to use latest terrautils code. I'm also going to add support for the -m flag if an appropriate soil mask is found.

However, one last piece is @dlebauer wants to push the indices to BETYdb. I began with a snippet of code something like this:
```
from netCDF4 import Dataset

ind_file = "some hyperspectral indices file"
with Dataset(ind_file, "r") as netCDF_handle:
		memberlist = netCDF_handle.get_variables_by_attributes(sensor=lambda x: x is not None)
		for members in memberlist:
				# TODO: Figure out how to handle this
				data_points = _produce_attr_dict(members)

def _produce_attr_dict(netCDF_variable_obj):
	'''Produce a list of dictionary with attributes and value'''
	attributes = [attr for attr in dir(netCDF_variable_obj) if isinstance(attr, unicode)]
	result     = {name:getattr(netCDF_variable_obj, name) for name in attributes}

	return [dict(result.items()+ {"value":str(data)}.items()) for data in netCDF_variable_obj[...]]
```

As you have more experience with netCDF, can you help me extract appropriate trait from that Dataset?

Here is a sample CSV for BETY from the canopy cover extractor:
```
local_datetime,canopy_cover,access_level,species,site,citation_author,citation_year,citation_title,method
2017-07-30T14:14:44,0.524408570161,2,Sorghum bicolor,MAC Field Scanner Field Plot 0 Season 2,"Zongyang, Li",2016,Maricopa Field Station Data and Metadata,Canopy Cover Estimation from RGB images
```

where "canopy_cover" corresponds to a trait, not sure if one already exists for the hyperspectral index or not.

btw, here is the PR where I am implementing: https://github.com/terraref/extractors-hyperspectral/pull/32/files

**Comment by hmb1** [comment]
HI Max,
This is the typical meta-data for an index  in  the first part of the NetCDF file:    

       float NDVI705 ;
                NDVI705:_FillValue = 1.e+36f ;
                NDVI705:cell_methods = "y, x: mean" ;
                NDVI705:description = "Formula: (R750 - R705)/(R750 + R705); Citation: Gitelson and Merzlyak (1994)" ;
                NDVI705:label = "Reflectance Index" ;
                NDVI705:long_name = "Normalized Difference 750/705 Chl NDI" ;
                NDVI705:max = 0.9858156f ;
                NDVI705:min = -0.9924927f ;
                NDVI705:notes = "Normalized Difference 750/705 Chl NDI NDVI705" ;
                NDVI705:standard_name = "normalized_difference_chlorophyll_index_750_705" ;
                NDVI705:type = "trait" ;
                NDVI705:units = "ratio" ;

In the **data:** section there will the value of the index (averaged over the plot )
 NDVI705 = -0.1020982 ;

**Comment by dlebauer** [comment]
@max-zilla the variable name should match one in BETYdb, e.g.

https://terraref.ncsa.illinois.edu/bety/api/beta/variables?key=9999999999999999999999999999999999999999&name=NDVI705

**Comment by max-zilla** [comment]
@hmb1 @czender I feel like I'm close, but can't get a value for NDVI705 by plot.

On Roger:

```
module load netCDF
module load pythonlibs
python
```
then in python...
```
>>> f = r"/projects/arpae/terraref/sites/ua-mac/Level_1/hyperspectral/2017-07-10/2017-07-10__18-06-40-881/710ddf11-e2f2-483c-b0c2-a223cdf3fdff_ind.nc"
>>> nc = Dataset(f, "r")
>>> nc.ncattrs()
[u'title', u'created_by', u'Conventions', u'Project', u'terraref_script', u'workflow_invocation', u'terraref_hostname', u'terraref_version', u'feature', u'history', u'NCO', u'history_of_appended_files', u'nco_openmp_thread_number', u'camera']
>>> nc.getncattr('NCO')
u'"4.6.6-alpha03"'
>>> nc.get_variables_by_attributes(standard_name='NDVI705')
[]
>>> nc.get_variables_by_attributes()
[]
```
Can you show me correct python here? Unless the problem is more complex than I understand - do we have per-plot values for NDVI705 in this file and we need to iterate over something?
I'm trying to use http://unidata.github.io/netcdf4-python/#netCDF4.Dataset to figure this out as it seems like it should be quick, but I can't

**Comment by dlebauer** [comment]
@max-zilla the `_ind.nc` files are full resolution. I believe that these still need to be averaged by plot before exporting to BETYdb. This is covered by #183, where the task of averaging at plot level has been checked, though it is not clear if this has actually been done.

I suspect @hmb1 or @czender can provide an efficient implementation using NCO or similar.

**Comment by hmb1** [comment]
HI Max,
 the actual netcdf name of the variable is 'NDVI705'   
and  standard_name = "normalized_difference_chlorophyll_index_750_705"

the data for **NDVI705** is a  scalar and represents the average value over the plot 

The variable **NDVI705_pxl** below is the per-pixel value over the plot 

float NDVI705_pxl(y, x) ;
                NDVI705_pxl:_FillValue = 1.e+36f ;
                NDVI705_pxl:cell_methods = "y, x: maximum" ;
                NDVI705_pxl:long_name = "Reflectance of image" ;
                NDVI705_pxl:standard_name = "surface_albedo" ;
                NDVI705_pxl:units = "1" ;

...Henry

**Comment by dlebauer** [comment]
> the data for NDVI705 is a  scalar and represents the average value over the plot

The file spans many plots, so one average value will not be particularly meaningful. I think @max-zilla has implemented code to subset by the plot boundary, average, and insert into BETYdb.

> The variable NDVI705_pxl below is the per-pixel value over the plot

I think that the averages from above can be dropped from the file and the suffix "_pxl" removed from these variable names.

**Comment by hmb1** [comment]
Thats quite a bit of work and all the attributes are associated with the  root name and not the _pxl name

**Comment by max-zilla** [comment]
@dlebauer @hmb1 in this snippet of python code:
```
with Dataset(ind_file, "r") as netCDF_handle:
			ndvi = netCDF_handle.get_variables_by_attributes(
					standard_name='normalized_difference_chlorophyll_index_750_705')
			NDVI705 = ndvi[0].getValue().ravel()[0]
```

...my thinking had been that I could use Dataset() with x/y coordinates to query only a subset of the .nc file (if that's possible), collect all the per-pixel values for that bounding box and average them.

Since the file is 100 GB, i could see that being slow.

A middle ground that is probably not satisfying would be to assign the single NDVI705 value we calculate for the swath, and assign it to all plots covered by that swath...

**Comment by dlebauer** [comment]
@hmb1 what is nco command to take a hyperslab and average the values in the array?

**Comment by hmb1** [comment]
with the indices file we have the coordinates x,y  
so to   subset using the bounding box xmin,xmax ymin, ymax  
ncks -d x, xmin,xmax -d y ymin,ymax    <netcdf_in_file> <netcdf_out_file>

Very important the xmin,xmax etc must be floating point numbers other wise NCO will interpret them as an index number

e.g  
>**ncks d x, 0.4,5.0 -d y 10.0,15.4 in.nc out.nc**

...Henry

**Comment by craig-willis** [comment]
Stale issue, closing. @dlebauer   please open a new issue if work remains.
