### ISSUE TITLE
Install PlantCV extractor in Nebula; improve documentation

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#35]
Need to review documentation from #28, ensure that it works and that it is accessible through / linked from terraref/documentation repository

**Comment by nfahlgren** [comment]
@dlebauer can we close this? Partially duplicate of #68 and open a separate issue(s) for documentation review for #68 and #31?

**Comment by dlebauer** [comment]
OK heres the issue for documentation with a rough outline https://github.com/terraref/documentation/issues/13
