### ISSUE TITLE
Make list of files w/ calibration images from 8/9 

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#350]
@smarshall-bmr provide list of hyperspectral image files from 8/9 and 8/16 that contain the calibration targets

**Comment by dlebauer** [comment]
Stereo images can be used to extract the angle of the targets for calibration.

**Comment by smarshall-bmr** [comment]
List of VNIR measurements with targets from Wednesday 8/16

2017-08-16_7-28-10-447
2017-08-16_08-23-30-532
2017-08-16_09-18-51-027
2017-08-16_10-14-11-561
2017-08-16_11-09-33-766
2017-08-16_12-04-55-281
2017-08-16_13-00-18-945
2017-08-16_13-55-40-810
2017-08-16_14-51-03-595
2017-08-16_15-46-26-089
2017-08-16_16-41-48-344
2017-08-16_17-37-12-578
2017-08-16_18-32-34-443
2017-08-16_19-27-56-548

**Comment by smarshall-bmr** [comment]
The platform that holds the targets blew over in the morning of the 8/9 scans. I caught it in the afternoon but the 75% panel apparently got flipped over in the process of putting everything back upright. The images from the morning are all too dark for me to identify if the targets are in place so the first scan I can confirm the presence of the target starts after I set the target stand back up.

2017-08-09_14-03-33-100
2017-08-09_14-58-55-675
2017-08-09_15-54-17-040
2017-08-09_16-49-39-074
2017-08-09_17-44-59-529
2017-08-09_18-40-21-734
2017-08-09_19-35-34-198

For what it's worth the target stand is 2m tall while the surrounding plants are around 3.7m tall.

**Comment by hmb1** [comment]
Hi Stuart,
thanks for the updates  this image is from the VNIR scan on:
 VNIR/2017-08-16/2017-08-16__11-09-33-766

If you identify the targets in the image  that would be grand: 


![frame 00028](https://user-images.githubusercontent.com/6428656/29563514-d6d18388-8735-11e7-808f-517bab8268e0.png)

**Comment by hmb1** [comment]
Hi stuart,
the scans from 2017-08-09 are pretty variable  - if you could again identify the targets 
thanks

![frame](https://user-images.githubusercontent.com/6428656/29565032-2a8c3b66-873c-11e7-8c38-70361e797a72.png)

**Comment by rachelshekar** [comment]
@hmb1 thinks the hyperspectral camera many not be directly above the targets.  It is also possible that the camera is not parallel to the ground.  @smarshall-bmr  - can you look into the latter issue?

**Comment by hmb1** [comment]
Issue closed as calibration data from the above two days is unusable

**Comment by dlebauer** [comment]
Why is it unusable and what needs to be done in the future to ensure that calibration scans are usable?
