### ISSUE TITLE
Updates to soil mask data product

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#351]
* look at hyperspectral inputs for example (see https://github.com/terraref/reference-data/issues/83)
* add definitions for x, y coordinates
* add latitude and longitude
* name and define the soil variable
   * e.g. soil_area_fraction (~inverse of cf vegetation_area_fraction) with units = 1 
   * or could use attributes 'flag_values' and 'flag_meanings' for categorical var.
* should be either level 2 or 3

**Comment by Paheding** [comment]
@dlebauer  I have added those metadata to the soil mask data product and pushed the updated extractor via GitHub.
@max-zilla  I tested it locally, it works as expected.  Let me know if it gives any error on your end.

**Comment by Paheding** [comment]
@dlebauer Can we close this issue.

**Comment by dlebauer** [comment]
@Paheding I've closed and created an issue to review the extractor and output here: https://github.com/terraref/reference-data/issues/184
