### ISSUE TITLE
Kubernetes cluster for extractors and Workbench

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#353]
After discussions with @robkooper and @max-zilla, we're exploring using the same container cluster (via Kubernetes) to support both the extractor pipeline and Workbench.  This will allow us to share common infrastructure on OpenStack and a common method for scaling up when needed.  This will also reduce the time required for reprocessing, allowing us to easily scale up in the short term.

Initial design notes are here:
https://docs.google.com/document/d/1LrCyc-iezxFbBsGrzqAg_G7UPOgi-Zcqv39Pwz9rjWU/edit#

I ran a preliminary test earlier this week with the Stereo RGB extractor using a Kubernetes cluster in the NDSLabs-Hackathon space on Nebula.  We will run some additional usage/performance tests this week. If all goes well, we will deploy a Kubernetes cluster in the TERRA project space on Nebula that will serve both the extractor pipeline and Workbench system going forward.

Completion criteria:
* [x] Prototype replication controller using Stereo RGB extractor
* [x] Test usage requirements with sample data prior to full reprocessing
* [x] Increase allocation on Nebula
* [x] Deploy Kubernetes cluster
* [x] Create replication controllers for existing extractors
* [x] Move Workbench instance

**Comment by craig-willis** [comment]
@jdmaloney  If possible, please change the export from ROGER to 141.142.210.150/29 to read-write. We'd like to use this for testing before deploying in the TERRA project on OpenStack.

**Comment by jdmaloney** [comment]
@craig-willis I'm seeing an export to: 141.142.210.144/29 is that the one you're desiring the change for?  Just want to double check, as there is no export for the above CIDR range.

**Comment by craig-willis** [comment]
@jdmaloney My mistake -- I couldn't find my original request.  That should be ti.

**Comment by craig-willis** [comment]
After discussions with @robkooper , will deploy in the Nebula OpenStack TERRA project. On ROGER today, there are 7 instance with a total of 24VCPUs and 60GB RAM for extractors. The  Nebula Workbench instance uses 4 VCPU/32GB RAM (and was scaled up to 4 instances with total 16VCPU/96GB for PI4 workshop).  We currently have 24VCPU/100GB RAM available on OpenStack. Kubernetes requires master/controller instance, which we usually deploy as 2x8. 

Initial deployment:
* kubernetes-master1: 2 cpu 8GB RAM
* kubernetes-compute (x4): 4 cpu 8GB RAM

**Comment by craig-willis** [comment]
Deployed terra-wb-master1: 2 cpu 4 GB RAM and two compute nodes terra-wb-node1, terra-wb-node2 as 4cpu 8GB instances.  Have allocated IPs and waiting for exports from ROGER.  Instance will be deployed as www.workbench.terraref.org and the old single-node system users and data will be migrated.

**Comment by craig-willis** [comment]
www.workbench.terraref.org now points to Kubernetes cluster (with valid TLS).  Note, users have not been migrated yet, so the system isn't usable.

Also, created new repo https://github.com/terraref/workbench-catalog to house service specifications instead of using nds-org branch.
