### ISSUE TITLE
Change heightmap extractor to produce GeoTIFFS

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#354]
Currently the 3dscanner heightmap extractor produces BMP files that are not georeferenced.  The extractor should be updated to produce accurately georeferenced GeoTIFFs that can also be used for fullfield stitching.  

Using the existing terrautils create_geotiff method, it looks like there are a number of factors with the 3D scanner that need to be considered (and currently aren't). Per discussions with @solmazhajmohammadi and @max-zilla:

* We are scanning about 5.5 meters extra (~2.75 m on each side) so scanDistance of 21.8 is actually 27.3.
* Y FOV in fixed metadata is probably wrong (currently 0.8). PLY files are ranging from 0.727 to -0.705, so FOV is ~1.432m.
* Need to account for scan direction (0, 1)

Looking at two specific examples:
* 2017-07-01__00-00-54-461: Scan direction negative. The bounding box for heading east scanner: start line is 21.34m to -0.66m and the width of image is from 95.535 to 96.945 --> some approximation is involved in this, since I'm only seeing the plants in the FOV and not the ground and this calculation is just based on the canopy height. You can play with this number of FOV to see which one is more accurate scan.
* 2017-07-01__00-02-41-951: Scan direction positive. The bounding box for heading east scanner: -1.444 to 21.031 these numbers are for heading east scanner, the heading west scanner is gonna be 2.75m offset added to these numbers

Completion criteria:
[ ] heightmap extractor produces GeoTIFF output with accurate georeference information
[ ] Review
[ ] Testing (load generated GeoTIFFs in QGIS at a minimum)

**Comment by craig-willis** [comment]
The terrautils method calculate_gps_bounds (https://github.com/terraref/terrautils/blob/master/terrautils/extractors.py#L293) needs to be updated to handle the 3dscanner data.

**Comment by max-zilla** [comment]
this was done.
