### ISSUE TITLE
Upload 2016 PhenoTractor data to trait database

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#358]
The earlier issue https://github.com/terraref/computing-pipeline/issues/211 was closed, apparently before the data was inserted into the trait database. 

Data are in https://docs.google.com/spreadsheets/d/1NNKtmWFBdoh2iaaXZh9fsu_nNRLMpytJ8Av1bHxpgIg/edit#gid=698446872 Need to be uploaded

Method = 'Maricopa Phenotractor'
Citation title = 'Maricopa Field Station Data and Metadata'

### Completion Criteria

* [ ] reformat data as needed for upload
* [ ] upload data from four dates in the spreadsheet.
* [ ] upload raw datasets to Clowder (?)

**Comment by NewcombMaria** [comment]
I can help with the steps to reformat data and upload the data to betydb.  I'll talk with Pedro and we'll make a plan.  I've never uploaded to clowder but if that's of interest I can learn with some guidance from someone in Illinois.

**Comment by dlebauer** [comment]
Issue moved to [terraref/reference-data #192](https://github.com/terraref/reference-data/issues/192) via [**ZenHub**](https://www.zenhub.com/)
