### ISSUE TITLE
Update PlantCV extractor and upload experiment LT1

### ISSUE THREAD

**Issue by nfahlgren** [terraref/computing-pipeline#366]
### Description 

 
Once the Globus monitor service at the Danforth Center is running successfully (issue #365), the PlantCV extractor can be updated (https://github.com/terraref/extractors-lemnatec-indoor/pull/3) and redeployed and the TERRA-REF experiment LT1 (TM015_F_051616 and TM016_F_052716) can be uploaded and processed.

**Comment by nfahlgren** [comment]
@dlebauer is there anything else you need from me on this issue? I listened to the recording of the meeting from yesterday and it sounds like there is confusion about where this is at.

**Comment by dlebauer** [comment]
Sorry when I spoke of my concern about these data I didn't realize that this issue and PR https://github.com/terraref/extractors-lemnatec-indoor/pull/3 had been submitted last week. I apologize for being anxious!

At this point it would be helpful if you can confirm that the experiment metadata including treatments, cultivars, experiments, and managements are in BETYdb so the BETYdb inserts will work. Or let me know if you need me to upload from a spreadsheet.

@max-zilla is there anything Noah can do to help make sure the pipeline is ready to deploy?
