### ISSUE TITLE
Add License file PRs to each extractors repository

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#370]
Add a file called LICENSE.md to each extractor or software repository, submit a pull request, and assign all of the contributors to the repository for review.

The project specification is to use an MIT/BSD (or CC-BY 4.0) compliant license. Contributors can approve the PR or suggest an alternative MIT/BSD-compatible LICENSE. In cases w/ IP (only sunshade extractor so far) it is up to the authors to provide a copyright / reuse statement.

Probably easiest to use the GitHub interface: https://help.github.com/articles/adding-a-license-to-a-repository/

Here is an example: https://github.com/terraref/extractors-environmental/pull/26

**Comment by weiqin61** [comment]
extractor-stereo-rgb
https://github.com/terraref/extractors-stereo-rgb/pull/22

**Comment by weiqin61** [comment]
extractor-multispectral
https://github.com/terraref/extractors-multispectral/pull/16

**Comment by weiqin61** [comment]
extractor-3dscanner
https://github.com/terraref/extractors-3dscanner/pull/13

**Comment by weiqin61** [comment]
computing-pipeline
https://github.com/terraref/computing-pipeline/pull/371

**Comment by weiqin61** [comment]
extractors-meterological
https://github.com/terraref/extractors-meterological/pull/6

**Comment by weiqin61** [comment]
https://github.com/terraref/extractors-hyperspectral
I don't have access to add a file

**Comment by weiqin61** [comment]
extractors-metadata
https://github.com/terraref/extractors-metadata/pull/9

**Comment by weiqin61** [comment]
https://github.com/terraref/extractors-sunshade

I don't have access to add a file

**Comment by weiqin61** [comment]
https://github.com/terraref/extractors-lemnatec-indoor

I don't have access to add a file

**Comment by weiqin61** [comment]
terrautils

https://github.com/terraref/terrautils/pull/37

**Comment by weiqin61** [comment]
extractors-hyperspectral
https://github.com/terraref/extractors-hyperspectral/pull/41

**Comment by weiqin61** [comment]
extractors-lemnatec-indoor
https://github.com/terraref/extractors-lemnatec-indoor/pull/6
