### ISSUE TITLE
get_site_boundaries("2017-06-30", city = "Maricopa") does not work as expected

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#372]
```py
get_site_boundaries("2017-06-30", city="Maricopa")
```

should return all sites in Maricopa associated with all experiments that were running on that date. 

There were six experiments on that date:

```sql
SELECT * from experiments 
   WHERE start_date < '2017-06-30' AND end_date > '2017-06-30'
```

| id         | name                                | start_date | end_date   |
|------------|-------------------------------------|------------|------------|
| 6000000017 | MAC Season 4: Border Plots          | 2017-04-20 | 2017-09-18 |
| 6000000016 | MAC Season 4: Short BAP Accessions  | 2017-04-20 | 2017-09-18 |
| 6000000015 | MAC Season 4: Medium BAP Accessions | 2017-04-20 | 2017-09-18 |
| 6000000014 | MAC Season 4: Tall BAP Accessions   | 2017-04-20 | 2017-09-18 |
| 6000000010 | MAC Season 4: All BAP Accessions    | 2017-04-20 | 2017-09-18 |

So I would expect it to return the same sites as the following query:

```sql
SELECT DISTINCT sitename, st_astext (geometry) AS geometry
FROM sites WHERE ID IN (
		SELECT DISTINCT site_id
		FROM experiments_sites
		WHERE experiment_id IN (
				SELECT ID FROM experiments
				WHERE start_date < '2017-06-30' 
                                  AND end_date > '2017-06-30'
                                  AND city = 'Maricopa'
			)
	);
```

results here:  https://gist.github.com/dlebauer/f7ecdbee9f976fc43e3e096891d79a62

However, it seems to only return sites associated with the first experiment that meets the query conditions ('MAC Season 4: Border Plots')

**Comment by max-zilla** [comment]
https://github.com/terraref/terrautils/blob/master/terrautils/betydb.py#L163
Bug is here, we get list of experiments but then return in first iteration of loop (first experiment found). Probably didn't catch this because it was tested where only one experiment was active.

**Comment by max-zilla** [comment]
I will fix this weekend, should be quick.

**Comment by jterstriep** [comment]
I think there is an additional problem. The postgis API defaults to returning 200 records so any call to get_sites will get only that limited set. Of course, you can work around this by passing in special args (limit, etc) but is this the desired behavior?

**Comment by dlebauer** [comment]
limit=none can be hard coded as default for all tables except traits.

**Comment by dlebauer** [comment]
PS remember to return _distinct_ sites since experiments are not independent

**Comment by jterstriep** [comment]
I'm in favor of setting limit=none as the default for get_sites which would
impact most of the other betydb get_ functions.

**Comment by max-zilla** [comment]
https://github.com/terraref/terrautils/pull/39 this should address these requirements, merged this morning.
