### ISSUE TITLE
Process for finding unprocessed files

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#373]
Working with @max-zilla on this.  Due to various unexpected outage scenarios, we have files that were dropped at different stages during the processing pipeline.  This is resulting in a low number of fullfield images being generated:

Define and execute the following process:
* Identify raw datasets with missing datasets in level1.  Trigger extraction on those missing datasets
* Identify level1 datasets with records missing in the rulemonitor database. Update rulemonitor DB to trigger fullfield when complete

**Comment by craig-willis** [comment]
We've identified a large number of missing rgb_geotiffs and re-queued for processing along with a smaller number of missing records in the rule monitor databases.   All of these are processing now, but the number of fullfield images is still unchanged.

**Comment by craig-willis** [comment]
This ultimately depends the GPFS database solution and will need to be postponed until a future sprint.

**Comment by max-zilla** [comment]
Have loaded @jdmaloney initial file list into a postgres database (rulemonitor db on terra-postgres, filesystem table) with filepaths queryable to facilitate this process. Will follow on with this in #398
