### ISSUE TITLE
Stereo RGB bin2tif unit test

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#374]
PyClowder 2:
https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/pyclowder2/browse/pyclowder

Here is a sample stereoTop dataset including 2 bin files and metadata.json:
[stereoTop sample.zip](https://github.com/terraref/computing-pipeline/files/1471598/stereoTop.sample.zip)

The raw metadata.json file must be cleaned in order to work with the extractor code:
```
import json
from terrautils.metadata import clean_metadata, get_terraref_metadata

f = open("metadata.json", 'r')
raw_metadata = json.load(f)
f.close()
clean_metadata = clean_metadata(raw_metadata, "stereoTop")
# Find specific TERRA subset of metadata (to ignore other kinds)
terra_metadata = get_terraref_metadata(clean_metadata, 'stereoTop')
```

Then you can pass that metadata into the image shapes part:
https://github.com/terraref/extractors-stereo-rgb/blob/master/bin2tif/terra_bin2tif.py#L94

...to get the GPS bounds. Then call process_image:
https://github.com/terraref/extractors-stereo-rgb/blob/master/bin2tif/terra_bin2tif.py#L125

...and create_geotiff:
https://github.com/terraref/extractors-stereo-rgb/blob/master/bin2tif/terra_bin2tif.py#L127

...and that is about it to go from bin to geotiff. Hopefully this gets you started.

Once you have geotiff outputs we can discuss what should actually be tested to verify output.

**Comment by weiqin61** [comment]
The very first initialization is done, the next step is to think of what to test in the unittest and how to make it.

**Comment by max-zilla** [comment]
thanks for this, @weiqin61 

For others, this uses the unittest package:
https://docs.python.org/2/library/unittest.html
I've not used this before but it seems useful.

**Comment by weiqin61** [comment]
after spoke with @max-zilla and @craig-willis this morning, we decided to move the `test_bin2tif.py` to the same directory as where `bin_to_geotiff.py` is, so that we can import it.
The new commit related to this issue is https://github.com/terraref/extractors-stereo-rgb/commit/d36cb045be6f4ef10c0aa062ce056fc550f09913
Now you can run
```
cd extractors-stereo-rgb/bin2tif/
python -m unittest test_bin2tif
```

**Comment by max-zilla** [comment]
example is done
