### ISSUE TITLE
Example refactoring extractors to minimize # scripts

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#377]
Now that we have version 1.0 of extractors, we should clean them up as part of unit testing writing. 

Just talked with @weiqin61 and she is going to create pull requests for ply2las, eventually flir and bin2tif to show how we'd like to structure.

Goals:
- review deprecated python scripts e.g. @ZongyangLi Get_FLIR.py and move any functions/constants we use into the main terra_flir2tif.py python file
- those functions can go outside the Extractor class so that any developers wanting to use parts of the code, e.g. the temperature conversion for FLIR data, can import and use just that function without needing the Clowder pipeline pieces. this also makes unit testing easier.
- remove old functions - we have a lot of code that is now standardized in terrautils but we did not remove old versions from extractor scripts like Get_FLIR which could cause confusion for people reading code.

We do not want to lose any functionality or code that is usable, but instead remove redundant code and minimize number of files in each repository / make a clean and consistent structure.

**Comment by max-zilla** [comment]
@craig-willis @robkooper fyi. after further discussions with @jterstriep and @dlebauer the current thinking is...

1. move all non-Clowder components of extractor into a python package named after the sensor. 

for example, in the stereo-rgb repo we would have a stereo-rgb python package that is generic from Clowder - it just takes input files or data and does the actual science on the data. we didn't really discuss this but I think it would make sense to include all extractor functions in the package - for example stereo-rgb package would have functions for bin2tif, canopy_cover, height_recovery, texture_analysis, etc. all the sub-extractor folders in the repo.

idea being we have a package that people can use e.g. in workbench to manipulate the files completely cleanly and separately from extractor stuff.

then we modify the extractor script (e.g. terra_bin2tif.py) to import that package and use it. we modify the Dockerfile to install that package. then we have a clear script for all our collaborators to focus on and separate out the "communicating with Clowder as an extractor" piece.

2. later, we can consider a new "extractors" repo that collects all of the extractor scripts in one place as they will be fairly similar, and the existing extractors-multispectral, stereo, etc. repositories just become the "science module" for that sensor.

we can also add things like R packages to work with the sensors to the "science" repo and keep the Clowder/RabbitMQ components separate. 

will go over this on the call today.

**Comment by weiqin61** [comment]
I am starting splitting the extractor functions out of the extractor repository and make them into modules now. The first step is splitting 3d scanner functions out of the `extractor-3dscanner` repo and set up a new repo `scanner_3d`. The repo is a python package that continues modules and tests.
https://github.com/terraref/scanner_3d
If this refactor works, I will refactor other repos and add more tests and readme.

**Comment by max-zilla** [comment]
Example for bin2tif is done and ongoing work can be tracked here: https://github.com/terraref/computing-pipeline/issues/375
