### ISSUE TITLE
Move data and processing from ROGER to Condo

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#378]
We are in the process of syncing data from ROGER to the Condo. This issue tracks all steps to move both data and processing to use the Condo mounts by 12/10.

Tasks:
* [x] Change Globus to use Condo endpoint
  * [x] Create endpoint on Condo (JD)
  * [x] Change scripts in AZ (JD)
  * [x] Disable/confirm Danforth 
* [x] Complete sync from ROGER to Condo 
* [x] Clowder/Kubernetes
  * [x] Shutdown RabbitMQ
  * [x] Change Clowder mounts 
  * [x] Change Kubernetes mounts
  * [x] Start RabbitMQ

To start processing, prioritize the following:
* [ ] RGB raw, level_1, fullfield
* [ ] FLIR raw, level_1, fullfield

**Comment by jdmaloney** [comment]
@craig-willis NFS mount information:
host: cnfs.ncsa.illinois.edu
Note: Since we have our own file system on the condo, paths are truncated.  All paths start at /terraref/...

**Comment by max-zilla** [comment]
Folder requirements for extractors...

canopycover/meantemp
```Level_1/fullfield```
bin2tif
```raw_data/stereoTop
Level_1/rgb_geotiff```
flir2tif
```raw_data/flirIrCamera
Level_1/ir_geotiff```
ply2las
```raw_data/scanner3DTop
Level_1/scanner3DTop
Level_1/laser3d_mergedlas```
plant_height
```raw_data/scanner3DTop
Level_1/scanner3DTop
Level_1/laser3d_heightmap```

**Comment by craig-willis** [comment]
Update on this -- there has been some delay, but the endpoint will  likely be up on Condo by end of week.

**Comment by craig-willis** [comment]
Globus endpoint is available, but there will be another migration in ~2 months (tracked as separate issue). Nothing to do for Danforth until the endpoint changes. Starting back on full-field analysis now.

**Comment by max-zilla** [comment]
gpfs scratch is last remaining data, covered specifically in issue #394
