### ISSUE TITLE
Modify backup to nearline/port backup code

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#384]
Port backup code to Condo.

Completion criteria TBD.

* [ ] Need to update documentation https://github.com/terraref/documentation/edit/master/data-backup.md

**Comment by craig-willis** [comment]
Moving this to the current sprint temporarily.  @jdmaloney the scratch move is a higher priority. Let me know if you can't complete both in this two-week timeframe.

**Comment by max-zilla** [comment]
@jdmaloney any updates here?

**Comment by jdmaloney** [comment]
Backup bundling is running, but progressing slowly due to NFS/Nebula limitations.  Per conversation with Max I'm closing this ticket since it is running.
