### ISSUE TITLE
Finalize stereo_rgb science package

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#386]
Evaluate current state of the science package, including Max's PR:
https://github.com/terraref/stereo_rgb/pull/3

We can update the PR with additional fixes/adjustments.

- complete the review + merge
- function names, file structures, docstrings, test structure
- push to pypi

**Comment by jterstriep** [comment]
I'd like to add additional bullet points to Max's comment which should be true of all the science packages since these are really libraries.
* Remove all print statements 
* Use proper logging based on getLogger(__name__)
* Don't use logging.basicConfig
* Don't mask Exceptions. Exceptions should be caught and re-raised with an informational message.

**Comment by jterstriep** [comment]
The current code catches exceptions and "prints" a message but then continues execution as if nothing had happened. That's almost certainly wrong.

**Comment by max-zilla** [comment]
Remaining work:
- pypi uploading
- brief code review with @robkooper @jterstriep @craig-willis

**Comment by craig-willis** [comment]
Moving to new milestone. As discussed, this separate from work now in issue #396.

**Comment by max-zilla** [comment]
- move get_image_shape to terrautils()
- entry_points in setup.py for conversion & canopy cover
- update test.py
- move test data outside repository - GitHub large file service? Clowder?

**Comment by max-zilla** [comment]
also need to published to pypi

**Comment by dlebauer** [comment]
* [ ] need to update readme
* does it make sense to have nested stereo_rgb/stereo_rgb/ directories?
* would it make sense to keep bin2tif which produces a Level 1 product separate from, e.g, canopy_cover that produces a Level 3 (trait) product?

**Comment by jterstriep** [comment]
Regarding readmes -- Unfortunately, pypi does not support the same markdown
as github so directly using the REAMDE.md when publishing doesn't work
well. I ended up creating a description.rst for the terrautils package. We
should do the same for stereo_rgb.

The nested stereo_rgb/stereo_rgb is the proper format for packages. The
first stereo_rgb is more like the distribution name and the second is the
actual package name. A distribution could have more than one package but
typically it's one-to-one with distribution and package set to the same
name.

**Comment by max-zilla** [comment]
Wei has updated the tests and get_image_shape() is in terrautils in this PR: https://github.com/terraref/terrautils/pull/45

- update readme
- decide final structure - pypi? include this + terrautils in larger library?

**Comment by max-zilla** [comment]
https://github.com/terraref/stereo_rgb/pull/5 - final PR changes
https://github.com/terraref/documentation/pull/182 - documentation for how to do this

**Comment by dlebauer** [comment]
It looks like all of the PRs have been merged except https://github.com/terraref/extractors-stereo-rgb/pull/25, which just needs max's review

**Comment by max-zilla** [comment]
reviewed, cleaned up and merged.
