### ISSUE TITLE
Clean up pyclowder2 pull request

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#387]
https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/pyclowder2/pull-requests/53/overview

This is latest pyclowder2 PR that adds additional Client functionality but it needs work.

**Comment by max-zilla** [comment]
@jterstriep should have permissions on bitbucket now.

**Comment by craig-willis** [comment]
Per discussion, this is limited in scope to the changes requested for TERRA and understood that it will likely require work from pyclowder team with ongoing communication.

**Comment by max-zilla** [comment]
any updates Jeff?

**Comment by jterstriep** [comment]
A new pull request has been created for pyclowder and has been approved by @robkooper  but has not been merged into master yet. But pyclowder was published to PyPI and is currently available there.
