### ISSUE TITLE
Document data pipeline architecture 

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#39]
This will require input from Lemnatec, MAC, and NCSA

Summarize data flow, from sensors to NCSA. Can be proposed. Need to know what computer/networking hardware and what it will be doing.

* Start with outline of based on Dec 4 2015 teleconference  
* summarize email thread specify cache server (what we ordered and why)
* get Lemnatec to document resources that they will provide (define interface with sensors data stream)

**Comment by rachelshekar** [comment]
Diagram is in progress.  After he visits UA, he will have a better idea of how to complete the diagram.

**Comment by rachelshekar** [comment]
Data transfer architecture (gantry to roger) @jdmaloney 

Data processing architecture @max-zilla 

Use for reports, users, publications

These should be unified or complementary 

This includes machines being used, resources

**Comment by jdmaloney** [comment]
![uploads/435f40a8-9c67-48d5-8b4b-000b60a4fa3a/Screen Shot 2016-01-07 at 9.49.35 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F435f40a8-9c67-48d5-8b4b-000b60a4fa3a%2FScreen+Shot+2016-01-07+at+9.49.35+PM.png)

**Comment by dlebauer** [comment]
@jdmaloney do you have the source file for this architecture diagram? can you please move it to google drive https://drive.google.com/drive/u/0/folders/0By_PDCcY5g2JNWd5ajdtQzcwS2s

**Comment by dlebauer** [comment]
also please put information about the globus endpoints in documentation?

**Comment by jdmaloney** [comment]
Document uploaded, is it okay if I put all the documentation together with issue #51?

**Comment by dlebauer** [comment]
>  put all the documentation together with issue #51?

"Add documentation if necessary" is an implicit step before closing any issue. Merge if necessary.
