### ISSUE TITLE
Clean up Mongo DB

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#391]
- deduplicate collections
- unify date hierarchy and fix orphaned collections
- ensure proper nesting of all Level_1 data

**Comment by dlebauer** [comment]
* [ ] add annual, monthly, and complete collections for Thermal IR GeoTIFFs. There are only daily collections like this one: https://terraref.ncsa.illinois.edu/clowder/collection/5a02fa3f4f0c624704c7d8c6
