### ISSUE TITLE
Missing trait data in BETYdb that should be generated by extractors

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#392]
At present I see data from the canopy_height extractor, but none of the following that I expect:

* surface_temperature from FLIR
** Update extractor
* hyperspectral indices from hyperspectral pipeline
* canopy_cover from the stereo rgb pipeline

**Comment by craig-willis** [comment]
@dlebauer  (or @gsrohde  I've been looking at the canopy_cover extractor to see why it isn't posting to BETY.  After working through several bugs in the python code, I'm now getting an HTTP 400 when POSTing to the traits endpoint. Below is a snippet of the CSV file:

```
local_datetime,canopy_cover,access_level,species,site,citation_author,citation_year,citation_title,method
2016-05-01T12-00-00-000,0.0,2,Sorghum bicolor,MAC Field Scanner Season 1 Field Plot 144,"Zongyang, Li",2016,Maricopa Field Station Data and Metadata,Canopy Cover Estimation from RGB images
2016-05-01T12-00-00-000,0.0,2,Sorghum bicolor,MAC Field Scanner Season 1 Field Plot 145,"Zongyang, Li",2016,Maricopa Field Station Data and Metadata,Canopy Cover Estimation from RGB images
```

What is the best way for me to troubleshoot the 400 error?

**Comment by robkooper** [comment]
which machine are you posting this to? you should see something in bety/logs/production.log

**Comment by gsrohde** [comment]
The problem (or at least _a_ problem) is the format of date/time.  The time portion should use colons and decimal points as separators: 12:00:00.000

The API does send a response to requests, but I don't know if your extractor captures it.  It might be useful to have a debug mode that logs this somewhere so you at least get a clue as to what is going wrong.

**Comment by craig-willis** [comment]
Thank you, @gsrohde. Apparently the extractor is not outputting the error string -- I'll update.  I am seeing one when POSTing manually. 
```
{
  "metadata": {
    "URI": "https://terraref.ncsa.illinois.edu/bety/api/beta/traits.csv?key=XXXX",
    "timestamp": "2018-02-06T12:42:39-06:00"
  },
  "errors": "{:schema_validation_errors=>[\"Element 'trait-data-set': Missing child element(s). Expected is one of ( entity, defaults, trait-group, trait-data-set, trait ).\"]}"
}
```

It looks like the file doesn't conform to requirements in more ways than one.

**Comment by gsrohde** [comment]
Try replacing "-d" with "--data-binary".

**Comment by craig-willis** [comment]
Thanks, @gsrohde. I missed that in the bety docs

**Comment by craig-willis** [comment]
@gsrohde Similar question for the meantemp extractor:

```
{
  "metadata": {
    "URI": "https://terraref.ncsa.illinois.edu/bety/api/beta/traits.csv?key=GZJZWnJpnDBhmKk7k6vb46z6lW6vjxSniRivRl2I",
    "timestamp": "2018-02-08T15:21:01-06:00"
  },
  "errors": "UNEXPECTED EXCEPTION ActiveRecord::StatementInvalid. The species id 2588 is not consistent with the cultivar id 6000001095.  It should be 11130."
}
```

Sample record:
```
local_datetime,canopy_cover,access_level,species,site,citation_author,citation_year,citation_title,method
2017-03-21T12:00:00,315.872,2,Sorghum bicolor,MAC Field Scanner Season 3 Range 21 Column 15,"Zongyang, Li",2016,Maricopa Field Station Data and Metadata,Mean temperature from infrared images
```

**Comment by craig-willis** [comment]
Ah, I think I see what happened.  The dataset I chose was a wheat fullfield image, but the extractor is hardcoded for Sorghum.  @max-zilla is this something we've already addressed?

**Comment by craig-willis** [comment]
Update on this issue.  The surface_temperature variable and methods have been created.  The extractor is currently failing to post to BETY due to values outside of the allowable range.  For this input file: https://terraref.ncsa.illinois.edu/clowder/files/5a0cfa184f0ca87e15c1763d?dataset=5a0cfa164f0ca87e15c175e7, 85/865 values are < 0.

**Comment by dlebauer** [comment]
I changed the units from K to C and valid range - can you try again?

**Comment by craig-willis** [comment]
@dlebauer Max noted that the negative values were related to numpy nodata values (-99) on the border rows.  Would it be sufficient to ignore nodata values when calculating the mean temp?

**Comment by dlebauer** [comment]
Yes go ahead. Most of the other T values are in C

**Comment by max-zilla** [comment]
https://github.com/terraref/extractors-multispectral/pull/12 I thought we decided the opposite?

**Comment by dlebauer** [comment]
I think we should use cf conventions with level 1 sensor data. BETYdb is less strict. I changed it because I assumed the extractor was failing because of incorrect units. So I searched variables in BETYdb and saw most are in C. I think it is a good idea to have a standard and SI units is an easy overall approach to remember but in the case of T it appears C is the convention and will likely be easier to use for trait users. I delegate the specification to our library scientist Craig.

**Comment by dlebauer** [comment]
PS for more context: CF is a convention. There is no convention for traits. We can and keep cf for traits in this case.  Maybe it makes sense in the pipeline. The important thing will be to provide trait data in a more standardized way - eg however it is stored in BETYdb can be changed / harmonized when it is exported to ICASA and BRAPI. Note that we have standard name and standard units fields in BETYdb.

**Comment by craig-willis** [comment]
https://github.com/terraref/extractors-multispectral/pull/22

**Comment by dlebauer** [comment]
other than hyperspectral, which is no longer expected, these are now in the database and this can be closed https://traitvis.workbench.terraref.org/
