### ISSUE TITLE
Transfer gpfs_scratch directory to Condo

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#394]
When last talked with @jdmaloney we had transferred the /sites directories completely to condo but the EnvironmentLogger and VNIR data in /gpfs_scratch on Roger still needs transferred.

**Comment by craig-willis** [comment]
Per meeting today, this is high priority as it is blocking any progress on VNIR, soil_mask and canopy_height data products.

**Comment by craig-willis** [comment]
As of this morning, we have some initial data transferred from ROGER scratch and can start testing the soil_mask and hyperspectral indices.

**Comment by craig-willis** [comment]
All done.
