### ISSUE TITLE
Review and refactor stereo_rgb science package

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#396]
Per review of stereo_rgb science package in https://github.com/terraref/computing-pipeline/issues/386, we have identified a few concerns that need to be addressed for this as an example of the new "Science package" module (for example, it should be using standard modules for csv generation and ordered dictionaries)

Completion criteria:
* [x] Review existing code, make recommendations for changes
* [x] Implement recommended changes
* [x] Submit PR
* [x] PR Merged
* [ ] pytest passed, published to pypi

**Comment by max-zilla** [comment]
Reviewed and merged the big PR. additional work can be done in additional PRs.
