### ISSUE TITLE
Run soil mask and indices for existing VNIR data 

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#399]
The hyperspectral workflow to generate NC from raw data is partially complete.  This task is to run the soil_mask and hyperspectral indices process for the existing VNIR data to generate review data.

Completion criteria:
* [x] VNIR data copied from ROGER scratch to condo (blocking)
* [x] Register existing datasets with Clowder?
* [x] Run soil_mask extractor on existing inputs
* [ ] Run hyperspectral indices extractors with soil mask inputs
* [x] Document process
* [ ] Create review issue and other issues for any encountered problems.

**Comment by craig-willis** [comment]
Trying to run soil_mask on existing inputs and running into OOM errors via Kubernetes.  @max-zilla  will maybe need some help purging the queue(s) so we can process only the small stuff in the short term.

**Comment by max-zilla** [comment]
look into possible running without soil masks. get indices that aggregate over soil AND leaves. right now soil mask is prerequisite for indices.

**Comment by dlebauer** [comment]
* need to clear message queue
* trigger on small files that we can actually handle
  - assume all v. lg files are errors (?)

**Comment by max-zilla** [comment]
the soilmask extractor has been updated and re-deployed on kubernetes, but the new files Henry created from 2017 need to be uploaded to Clowder in order to trigger the rest of the workflow.

**Comment by max-zilla** [comment]
running upload script on 1785 .nc VNIR files from 2017 now. e.g.:
https://terraref.ncsa.illinois.edu/clowder/datasets/5b72e7154f0c25c7b2813d72

**Comment by max-zilla** [comment]
Moved filesize limit down to 20GB and resubmitted.

**Comment by craig-willis** [comment]
Added #500 to create larger memory node now that we have resources.

**Comment by max-zilla** [comment]
@craig-willis are there any outstanding issues with node 7 or can i queue this?

**Comment by max-zilla** [comment]
Closing this for now until Vasit's team can resolve #514
