### ISSUE TITLE
install dependencies on Roger

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#4]
@robkooper to email Dan Lapine with specific instructions on dependencies required to install on Roger
* [x] copy technical specifications here (or create page in terraref/documentation)
* [x] Python + virtual env
Dan can contact @yanliu-chn for additional informaiton

required for #13

**Comment by dlebauer** [comment]
update:

* will install dependencies on one or more VMs
* will mirror on nebula (these will be separate for testing / system evaluation)

Next steps:

* will mount nebula VM on ADS
* NFS mount to Roger GPFS 
  * JD needs VM ip

**Comment by robkooper** [comment]
This should be those dependencies to be able to run plantcv on the HPC. The thought is for the extractor that executes plantcv as a job on roger.

**Comment by dlebauer** [comment]
#40 to put on HPC
