### ISSUE TITLE
Submit PlantCV extractors to Roger queue

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#40]
Launch job that launches an extractor, this can then start processing images as it comes out. qsub launches extractor on a node, will run until job. So any image that comes in goes to that node.

* [x] setup extractor on Roger node
* [x] Demonstrate with Fahlgren et al sample data sets; 
* [x] profile pipeline to get first estimate of computing resources that will be required.

(in the future, sandeep is adding a new module to with an alternative approach)

**Comment by yanliu-chn** [comment]
Discussed with Rob and Rui on the architecture change for batch processing of images using plantcv on ROGER. The batch processing module will include:
- A scheduling agent: this agent watches the rabbitmq through the management API of rabbitmq. Whenever it sees the number of plantcv uploads is over a threshold, it makes a decision to submit jobs to ROGER. Job submission parameters affected by the decision include how many nodes to ask for, how long the job should run. This agent, in theory, can replace/complement the plantcv extractor in cloud.
- A plantcv batch processing script on ROGER: this script runs a number of plantcv extractor instances, depending on the number of cores available (if using GPU, just one).

**Comment by yanliu-chn** [comment]
Stress test 1 is done
- 1500 images
- the agent booked 4 nodes, each with 10 extractors on ROGER, so 40 extractors ran for 600 seconds.
- all images were processed in 422 seconds. results appear to be correct.

**Comment by dlebauer** [comment]
@yanliu-chn are you still working on this? could you add instructions for setting this up and triggering it to the [terraref clowder docs](https://github.com/terraref/documentation/blob/master/clowder.md) and / or [README file in the clowder repository](http://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/extractors-plantcv/browse/README.md)?

**Comment by yanliu-chn** [comment]
This is done already. I just added instructions to the readme.md.

**Comment by dlebauer** [comment]
see #68
