### ISSUE TITLE
Bring back THREDDS and Pecan machines

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#402]
Per planning meetings, we need to bring back Thredds and Pecan machines.  (There was also a comment to look at adding envt logger data https://github.com/terraref/reference-data/issues/222, but I'm not sure if we committed to this).

Completion criteria:
* [x] THREDDS machine is running
* [x] Pecan machine in is running as expected
* [ ] Address reference-data/issues/222, if in scope

**Comment by dlebauer** [comment]
Not committed to providing envt logger data on thredds but if it is a quick update it would be nice to provide the concatenated daily files

**Comment by robkooper** [comment]
I'll use #406 as to solve terraref/reference-data#222
