### ISSUE TITLE
Publish terrautils to pypi

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#404]
We want the terrautils package to be published.

Completion criteria:
* [x] Terrautils published to pypi
* [x] Documentation describing how to do this in the future
* [x] Review documentation with team members

**Comment by max-zilla** [comment]
@jterstriep hoping to finish this week

**Comment by jterstriep** [comment]
Terrautils has been uploaded to PyPI in both source and wheel distributions. Two version are currently available. Version 1.1.0 supports the terraref namespace so code would 'import terraref.terrautils', version 1.0.0 supports the original 'import terrautils'.

Installation automatically installs all dependencies listed in the setup.py. This is slightly different from the group's practice of placing all dependencies in requirements.txt. Setup.py was updated to include all
dependencies from requirements.txt. One additional dependency was pyclowder but this has been published to PyPI and terrautils now pulls it from PyPI.

One remaining dependency is GDAL which is left as an exercise to the user. We might need to add better guidance.

Publishing to PyPI is straightforward and well documented in [python's packaging guide](https://packaging.python.org/tutorials/distributing-packages/). Beware that
PyPI is currently transitioning from pypi.python.org to pypi.org. The two systems are linked but there are some changes which makes older documentation incorrect. The TL;DR versions is as follows:
```
python setup.py build sdist
python setup.py build bdist_wheel
twine upload -r pypi dist/*
```

A couple additional considerations. Publishing implies versions which are currently specified directly in setup.py. These should be matched with tags on GitHub. Lastly, I am the owner of the terrautils package. Other people should create PyPI accounts and I can add them as owners.

**Comment by max-zilla** [comment]
This introduces the terraref package space (1.1) so using pip install will need to use the new import.

pip install terrautils==1.0.0 will be the same as before.

**Comment by max-zilla** [comment]
tag & push current docker image as 1.0.0.

new version of docker becomes 1.1.0 and extractors building from it will require the new import syntax.

**Comment by max-zilla** [comment]
https://github.com/terraref/terrautils/pull/46

**Comment by craig-willis** [comment]
@robkooper Please add max-zilla as owner

**Comment by max-zilla** [comment]
follow on with: https://github.com/terraref/computing-pipeline/issues/429
