### ISSUE TITLE
refactor laser3D extractor

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#405]
Following from https://github.com/terraref/computing-pipeline/issues/338

We want to move science functionality that currently exists in https://github.com/terraref/extractors-3dscanner into the new https://github.com/terraref/scanner_3d repository

* looks like the directory 'scanner_3d' currently contains ply2las and plant_height
  * these should be separate modules
  * plant height extractor should be renamed 'canopy_height' for consistency
* additional modules:
  * Leaf angle parameters
  * Summary stats (could be in terra utils 
      * generate a sample, histogram, mean, sd, effective n, for any matrix or vector  

Singularity container for lastools: https://groups.google.com/forum/#!topic/lastools/TqQxc40EbAo/discussion (which requires Wine)

Here is the proposed workflow; [it can be edited here](https://docs.google.com/drawings/d/1GLKlU9M2GO2XnOA7RaJCEmOTr-8UfELJSkUqgQFuqYA/edit): 

![image](https://user-images.githubusercontent.com/464871/39593711-38f6702a-4ed0-11e8-9e47-04eb1f9f71e5.png)

```
query BETYdb for intersecting plots 
for each plot 
  find all intersecting las files
  lasclip to plot
  lasmerge to single file
  las2dem elevation raster geotiff file (digital elevation model or dem)
  las2dem -slope an angle raster geotiff file.

for each plot 
  find angle.tiff 
  read in values as vector
  compute sample, histogram, mean, sd, neff, other stats
  insert mean, sd, neff, theta, ... into BETYdb
  insert same + sample of 1000 and histogram into geostreams
  create summary figures as thumbnails in clowder for QA/QC. 
```

Code to compute leaf angle parameters is in https://github.com/terraref/computing-pipeline/issues/338#issuecomment-357304136

To identify data levels refer to documentation: https://terraref.gitbooks.io/terraref-documentation/content/data-product-creation.html

**Comment by dlebauer** [comment]
@jterstriep you mentioned using a python interface or equivalent of lastools. I found laspy but not equivalent functions for lasclip, lasmerge, or las2dem. Any suggestions?

**Comment by weiqin61** [comment]
https://github.com/terraref/canopy_height
Here is the package for canopy_height

**Comment by max-zilla** [comment]
We want to look at using other libraries e.g. laspy

**Comment by max-zilla** [comment]
@weiqin61 perhaps look at one of our merged LAS files and see if we can use laspy las2dem to generate an angle map/heightmap.

**Comment by dlebauer** [comment]
@weiqin61 could you give an update on the progress with this?

**Comment by max-zilla** [comment]
waiting on https://github.com/terraref/computing-pipeline/issues/460 to finalize.

**Comment by max-zilla** [comment]
both ply2las and heightmap are deployed and the science package update was pushed. 
https://github.com/terraref/laser3d/pull/11
