### ISSUE TITLE
Calculating plot boundaries from bety query(BUG)

### ISSUE THREAD

**Issue by ZongyangLi** [terraref/computing-pipeline#408]
### Description 

In my recent test in canopy_height extractor, something unexpected appear:

From a BETY query from [terrautils](https://github.com/terraref/terrautils/blob/master/terrautils/betydb.py#L123) we can get these two records for example:

MAC Field Scanner Season 4 Range 42 Column 12 W: { "type": "MultiPolygon", "coordinates": [ [ [ [ -111.974868140365928, 33.07603706158018, 0.0 ], [ -111.974859955686057, 33.076037064238221, 0.0 ], [ -111.974859941204954, 33.07600549653791, 0.0 ], [ -111.974868125881912, 33.07600549387994, 0.0 ], [ -111.974868140365928, 33.07603706158018, 0.0 ] ] ] ] }

MAC Field Scanner Season 4 Range 42 Column 12 E: { "type": "MultiPolygon", "coordinates": [ [ [ [ -111.974876325045784, 33.076037058921628, 0.0 ], [ -111.974868140365928, 33.07603706158018, 0.0 ], [ -111.974868125881912, 33.07600549387994, 0.0 ], [ -111.974876310558841, 33.076005491221416, 0.0 ], [ -111.974876325045784, 33.076037058921628, 0.0 ] ] ] ] }

With a transfer code from [terra_common](https://github.com/terraref/extractors-3dscanner/blob/master/plant_height/terra_common.py#L414) I will be able to get the gantry coordinate, the result is:
MAC Field Scanner Season 4 Range 42 Column 12 W: 
(409006.40567221015, 3660140.669734837, 12, 'S’)  [165.60868695609696, 7.298223485293512]
(409007.16964207997, 3660140.6629346884, 12, 'S’)  [165.60785435201203, 6.533175054254918]
(409007.13849138987, 3660137.16307467, 12, 'S’)  [162.10869683422376, 6.532832847588195]
(409006.3745215191, 3660137.169874821, 12, 'S’)  [162.1095294410902, 7.2978812795919925]

MAC Field Scanner Season 4 Range 42 Column 12 E:
(409005.6417023401, 3660140.676534989, 12, 'S’)  [165.60951956389837, 8.063271916634257]
(409006.40567221015, 3660140.669734837, 12, 'S’)  [165.60868695609696, 7.298223485293512]
(409006.3745215191, 3660137.169874821, 12, 'S’)  [162.1095294410902, 7.2978812795919925]
(409005.61055164936, 3660137.1766749695, 12, 'S’)  [162.11036204517512, 8.062929710634783]

**High light issue:**
In COL 12 W, the y coordinate is [6.53, 7.29]
In COL 12 E, the y coordinate is [7.29, 8.06]

From my understanding, that LemnaTec coordinate system in the Metadata has the 0,0 location in the SE corner of the field, and our field maps have the lowest Range and Row (0,0 point) in the SW corner of the field. So West subplot should have a bigger value of Y coordinate. But I am getting the smaller value.

@dlebauer @jterstriep @max-zilla I am wondering if this is a bug from my parsing code, or it comes from data in the database. If it comes from my parsing code, I may need your help to find out what's the problem in my code, and I'm wondering if it can be done in terrautils?

**Comment by dlebauer** [comment]
@ZongyangLi thanks - you found an error in the underlying data that should have been caught in https://github.com/terraref/reference-data/issues/194#issuecomment-334314169 but was overlooked. I will fix it.

**Comment by dlebauer** [comment]
@ZongyangLi see if it is fixed now.

**Comment by ZongyangLi** [comment]
@dlebauer Yes it fixed now.

My further concern is about the reprocessed canopy_height data. It will have such an issue within two subplots.

**Comment by dlebauer** [comment]
you or I can rename the plots for the reprocessed data, correct?

**Comment by dlebauer** [comment]
@ZongyangLi please remind me when it is time to upload the canopy_height data so that I can fix it.

**Comment by ZongyangLi** [comment]
@dlebauer 
Sorry I don't quite get the idea. When you say upload the data did you mean upload created csv file from extractor?
I thought the data was uploaded when the canopy_height extractor run in the pipeline. 

To my understanding, the canopy_height extractor is continues running on clowder pipeline now, it had uploaded error data into BETYdb. The key time point is the time when you fixed s4 E/W records. We need to fix those error data before 'that' time point and keep correct data after 'that' time point. Is it correct?

**Comment by dlebauer** [comment]
Yes this should be fixed when we refactor the laser3d extractor and reprocess the height data
