### ISSUE TITLE
Using CoGe for genomics pipeline

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#41]
CoGe is a genomics pipeline developed by @mbomhoff and @elyons.

Following the Dec 11 2015 standards committee meeting, CoGe can provide the pipeline defined in terraref/reference-data#19 as well as a web interface and REST API. 

There is an instance at U Arizona (https://genomevolution.org/coge/) hosted by Eric Lyons that is available for researchers to use. If prudent we can create VM / docker files for use locally.
### CoGe Documentation
-  Homepage https://genomevolution.org/coge/
- The workflow is described here: https://genomevolution.org/wiki/index.php?title=LoadExperiment
- Documentation for installing CoGe on a Ubuntu server: https://genomevolution.org/wiki/index.php/Install_coge
- The REST API is documented here: https://docs.google.com/document/d/1GXOPIVvyTwoGR2IRjDNmdd2nj_6d8db7jx9hG8RxTDc/edit
- [Yerba](https://github.com/LyonsLab/Yerba) is a job management framework developed for CoGe by @mbomhoff 
### Next steps:
- [x] ~~@max-zilla assess feasibility of creating a CoGe VM or Docker file hosted on OpenStack?~~
  - ~~[ ] Where is computing done? How will VM submit jobs to HPC queue?~~
  - we will run the analyses remotely at UA
- [x] Get example data and meta-data from Danforth to develop / demonstrate the pipeline 
  - [x] How should data be transferred (@jdmaloney)?
  - [x] what is unique identifier for an accession (@nfahlgren)? (addressed by terraref/reference-data#65)
  - [x] Which reference genome should we use?
- [x] Define API calls for 
  - [x] uploading data to Cyverse data store using i-commands [Documentation](https://pods.iplantcollaborative.org/wiki/display/DS/Using+iCommands)
  - [x] calling the desired CoGe pipeline (see examples for [creating an experiment](https://docs.google.com/document/d/1GXOPIVvyTwoGR2IRjDNmdd2nj_6d8db7jx9hG8RxTDc/edit)
- [x] user may also want to use tools for downstream analysis - how should these be coupled to the CoGe pipeline? 
  - GOBII being used by the UI / Gore / Buckler teams
  - For addtional analyses (e.g. de novo sequencing?) we can start with the scripted pipelines used by HPCBio ([Documentation](https://github.com/HPCBio/BW_VariantCalling/blob/master/UserDocumentation.txt)).

**Comment by dlebauer** [comment]
I am currently moving some example data for pipeline development to the Roger server (provided by @nfahlgren et al):

* paired-end DNA sequencing files in FASTQ format (for each sample there are two files, one for each end of the DNA fragments). 
* files are individually gzipped, with a total compressed size of 600GB. They will be unzipped following transfer
* will be stored on Roger in /home/dlebauer/terraref/genomics until further notice

**Comment by max-zilla** [comment]
Are the data to analyze in CoGe (e.g. 600GB sample) totally distinct from the imagery data we're getting from LemnaTec? I was planning to represent the genomics pipeline somehow in revising that architecture diagram - is there a vision for launching a CoGe VM from Clowder with selected data like we are doing with PlantCV, for example? Is it largely separate from the phenomics workflow?

**Comment by dlebauer** [comment]
> Are the data ... distinct from the imagery data ...? 

Yes. the betydb.cultivars table will link to accessions in the genomics database. A genomics analysis would then query vectors / arrays of data associated with a unique record in the cultivars table.

> is there a vision for launching a CoGe VM from Clowder with selected data like we are doing with PlantCV, for example? 

Yes. In both cases, the VM/docker will need to access to HPC computing resources

> Is it largely separate from the phenomics workflow?

Yes. The big picture is that the phenomics workflow will fill rows in the betydb.traits table for each plant, plot, or unit of replication; it will also send files to the betydb.dbfiles table.

**Comment by dlebauer** [comment]
@nfahlgren This is the coge pipeline I ran https://genomevolution.org/r/j8c7

I'd appreciate feedback on the settings, the pipeline configuration, and if we will be able to run the fastq files through CoGe in this way.

**Comment by nfahlgren** [comment]
@dlebauer I can only see the steps that were run but it looks good in general. The FPKM/cufflinks section would not be needed in this case since the uploaded fastq files are DNA sequences rather than RNA. I'm not familiar with all the programs they use, but based on the file exchange formats it looks like the right steps that we need to get polymorphism calls. An hour and a half to completely process one fastq file also seems very reasonable.

**Comment by nfahlgren** [comment]
@dlebauer I can only see the steps that were run but it looks good generally. This input file has genomic DNA sequences, so the steps involving FPKM/cufflinks would not be necessary since those are for RNA expression.

I'm not familiar with all the particular programs they implement but it looks like it outputs what we need (polymorphism calls) and takes care of all the steps in between.

One thing to think about is that in this example you uploaded a single fastq file, which is valid for experiments done with single-end sequencing, but I think we will be doing paired-end sequencing, so there will be two input files per sample (sequences from the left and right ends of the same DNA fragment). I assume they have both single- and paired-end modes?

**Comment by elyons** [comment]
Yes, CoGe supports both single and paired end reads.

**Comment by dlebauer** [comment]
@elyons and @mbomhoff 

* We currently have some sample files for testing on our server 'Roger' (roger-login.ncsa.illinois.edu) in `/projects/arpae/terraref/raw_data/hudson-alpha/test_data`. 
* The CoGe API documentation indicates that it can take data from the CyVerse Data Store, HTTP, or FTP. I gather the Cyverse data store is easiest / most commonly used and our project has a 2TB allocation. 

Are these the next steps:

* install [icommands](https://pods.iplantcollaborative.org/wiki/display/DS/Using+iCommands) on Roger 
* icommands to transfer from Roger to Cyverse data store,
* Then create script to generate API calls based on the template in #69 (from [example in CoGe API documentation](https://docs.google.com/document/d/1GXOPIVvyTwoGR2IRjDNmdd2nj_6d8db7jx9hG8RxTDc/edit#))

**OR**

would it be easier to just FTP / HTTPS directly from either Roger or the Clowder front-end (@max-zilla)?

@nfahlgren what is the relevant meta-data that we should send in the API call?

**Comment by mbomhoff** [comment]
@dlebauer Setting up icommands and transferring the data to the CyVerse
Data Store is ideal method due performance -- the icommands perform
parallel transfers.  For testing small datasets the FTP/HTTP method is
adequate.

**Comment by mbomhoff** [comment]
I just updated the CoGe API spec ("Experiment Add with Downstream Analyses") to reflect minor changes to the JSON request format when we recently added Methylation and ChIP-seq pipelines.

**Comment by dlebauer** [comment]
I've started to transfer the files to the iplant datastore. We have a project allocation at `/iplant/home/shared/terraref/`

(transfer details in the [TERRA REF documentation](https://github.com/terraref/documentation/blob/master/coge_comparative_genomics_platform.md))

The test files are in `raw_data/hudson-alpha/test_data/`. I've created a folder `output/` for CoGe output (perhaps in `output/coge/`? Is there a convention / preferred method here?

In the `raw_data` folder Noah has write and Matt has read permissions. Both have write permissions to `output/`

**Comment by rachelshekar** [comment]
@nfahlgren  - where are you on this?

**Comment by nfahlgren** [comment]
I hit two roadblocks:

The Agave API documentation for obtaining a token no longer exists (http://agaveapi.co/authentication-token-management/). I think Ramona told me you have to be on campus to have access to the Agave API currently, but maybe I'm mistaken.

I have access to the `/iplant/home/shared/terraref` data store through the Discovery Environment, but I don't seem to be able to access any files in it through the CoGe web interface. I can see other data sets in `/iplant/home/shared`, so maybe our sharing settings are blocking access?

**Comment by nfahlgren** [comment]
@mbomhoff and @elyons, could you help me out with the comment above? Thanks!

**Comment by mbomhoff** [comment]
Hi Noah, items in the shared folder aren't automatically made public so you will have to share the terraref folder with the "coge" user.  

I think Agave reorganized their docs, check here:  http://developer.agaveapi.co/#authorization

**Comment by nfahlgren** [comment]
@mbomhoff thanks! The group who generated these data want to keep it private until the publish, does sharing with the coge user make the data public or just makes it available through CoGe?

**Comment by mbomhoff** [comment]
@nfahlgren I see, yes it will effectively make them public for any user logged into the CoGe web site, however they will remain private within the DE.

**Comment by nfahlgren** [comment]
@dlebauer it looks like you have to modify the sharing, I don't have permission. Can you share the terraref volume with the users `coge` and `pozersky` (Phil from Todd's lab)?

**Comment by dlebauer** [comment]
@nfahlgren I gave you owner permissions, and Phil and the CoGe team write permissions on the following directories:

* raw_data/
* output/
* sites/

I put the `sites` folder on there to be consistent with the directory structure on Roger and Globus. But it is redundant with the original raw_data and output folders. It looks like the original test data is in the raw_data folder. Could you please clean up the directory structure - i.e. merge terraref/raw_data and terraref/sites/hudson-alpha/raw_data, delete what you don't need (is the test data useful?) and etc.

:file_cabinet: 👍

**Comment by nfahlgren** [comment]
@dlebauer I met with @phloz today to discuss this issue. One thing I realized is that I don't know what our goal is here. What specific things do we want to accomplish? We are (mostly) able to process individual samples, but it's less clear to me how we would aggregate the data into a full data set.

**Comment by dlebauer** [comment]
@nfahlgren can you please update this issue and create a new one if we are going to do something else with the [documented pipeline](https://terraref.gitbooks.io/terraref-documentation/content/genomic-data-standards.html)?

**Comment by rachelshekar** [comment]
Phil from Todd’s group is working on this
@nfahlgren and @nshakoor  - where did we leave this? Should we discuss using / contributing to CoGe? Or should we discuss deploying pipeline at NCSA? Both? Other? 
CoGe only partially meets our needs.  Should we work with CoGe developers to implement changes?  This may take longer than we have
Can use pipeline that Phil’s group is using.  Should we implement this at NCSA?  Phil will process data at Danforth.  Need to follow up with @dlebauer

**Comment by rachelshekar** [comment]
David,
     
    I was able to get the CoGe API to work so submissions to CoGe can be done on the command line.    However, after our conference call on Nov. 7th, I steered away from pursing
     the CoGe pipeline based on that conversation.   While I’ll proceed as instructed, I’m still of the opinion that CoGe is not geared to this large of a genomic analysis undertaking because of its limited compute footprint, the difference in pipeline tools compared
     to what I have set up here at the Danforth Center, and to a lesser extent, the addition tools that would have to be added to their pipeline to reach a final product. Matt Bomhoff was very helpful in my communications with him and the CoGe pipeline definitely
     has merit but as I said, not on the scale of 384 genomes and especially with the data size of this second set of 192 lines.  My workflow is currently running and it handled the first set 192 samples but I have had to make some modifications to accommodate
     scaling up to the second set of data.   The data has to progress further into the workflow to have a good handle on when I’ll have a final data product available but will update as best I can its progress and projected completion. 
    
     
    Best,
     
    Phil

**Comment by rachelshekar** [comment]
Phil,

David and I have both received commitments from Eric Lyons and others at CyVerse that they will continue to improve CoGe and their infrastructure to enable TERRA-REF’s needs. My recommendation is that David do what he can to implement CoGe in the TERRA-REF framework. But if CoGe/CyVerse is insufficient at this time for our internal DDPSC needs then you should use whatever other tools and pipelines you need.

Todd

**Comment by dlebauer** [comment]
@mbomhoff is CoGe ready to support the TERRA pipeline?
@phloz what is the timeline for getting this started ?

**Comment by mbomhoff** [comment]
@dlebauer I am finishing it up now, should be deployed by end of next week.  For reference, this is the guide I am using:  https://terraref.gitbooks.io/terraref-documentation/content/genomic-data-product.html

**Comment by dlebauer** [comment]
Thanks Matt, is it ready now? Can we start sending our jobs?

**Comment by mbomhoff** [comment]
The functionality described in the guide I referenced above is available for use.  I have been working on some additions (incl. Variant Recalibration) based on a conversation with @phloz that are still under development.

**Comment by dlebauer** [comment]
I am going to close this issue and open a new one related to running the genomics pipeline
