### ISSUE TITLE
Unexplained Reprocess of scanner3DTop Data

### ISSUE THREAD

**Issue by jdmaloney** [terraref/computing-pipeline#412]
Description:
Noticed a large amount of generated on gantry-cache that did not co-incide with data being gathered by the normal daily scans.  This data showed up in the MovingSensor.reproc2016-8-18 directory and looks to be that all scanner3DTop data from ~2017-07 and onward got reprocessed.

Details:
The reprocessing dates (based on file create time) started close to Jan 12.  There is about 26TB of data that came from this reprocessing.  Not all (but most) of the reprocessed data was transferred back to NCSA, we need to figure out why it all didn't make it back.  Dates with non-updated files reside in: 2017-08-22, 2017-09-20, and some Oct/Nov. dates specifically

Completion Criteria:

- [ ] Figure out what caused the reprocessing @NewcombMaria 

- [ ] Prevent it from happening again (prevent unplanned reprocessing) @NewcombMaria 

- [ ] Figure out why certain dates of data didn't make it back to NCSA @max-zilla  and @jdmaloney

**Comment by NewcombMaria** [comment]
@jdmaloney the cache server shows where the 2018-01-12 reprocessing by the ply worker began.  The best I can determine is that the reprocessing tracks back to steps that Stuart took after Slack general channel discussion on Jan 12 and the resulting gitbhub #389 (Scanner 3DTop data in SWIR dataset subdirectory).  Stuart wrote in slack on 2018-01-12 that he reset the pl-worker to repopulate the LemnaTecMovingSensor.reproc folder.  

![ply_file_directory_reprocesstransition](https://user-images.githubusercontent.com/22008637/36075224-f2b7e8d4-0f08-11e8-9af3-0c06b6f8b4b6.jpg)

**Comment by NewcombMaria** [comment]
To prevent unplanned reprocessing from happening again I will check the settings in the ply-worker hardwarelni.xml file and ensure that the settings don't change going forward.  I don't know why some specific dates did not transfer back to NCSA.  In Oct/Nov we did not have a crop in the field - data from those months are not important.  Data from August and Sept 20 dates are important.

**Comment by jdmaloney** [comment]
@NewcombMaria Thanks for looking into this, I began deleting the data on the gantry-cache that we'd already brought back here to NCSA and it started to repopulate again so something is still running and automatically creating those file (the recreation started pretty much right after I deleted those files).

The IP Address of the machine that appears to be doing the work is 10.160.21.81 if that helps any.

**Comment by max-zilla** [comment]
we may need input from LemnaTec (@TinoDornbusch maybe?) to modify the start date of PLY Worker,  so that we aren't reprocessing repeatedly.

Should also consider status of raw_data - if we have old raw_data that is triggering PlyWorker, we should verify it has been transferred and delete from cache server.

**Comment by NewcombMaria** [comment]
@jdmaloney and @max-zilla the PlyWorker needed to be re-started over the weekend and again it started re-processing files in the MovingSensor.reproc2016-8-18 directory.  It might be that some of the processed folders were removed while the associated old raw_data remained on the gantry cache?  I'm not certain.  For now we decided yesterday to stop the PlyWorker temporarily.

**Comment by jdmaloney** [comment]
Removing files from /gantry_data/LemnaTec/3DScannerRawDataTopTmp/scanner3DTop has cleared up this issue and now we know how to control what gets processed.  We'll be adding removal of files from that directory to our clean up procedures.
