### ISSUE TITLE
Set up deep learning environment on Comet or Roger

### ISSUE THREAD

**Issue by ZongyangLi** [terraref/computing-pipeline#416]
The following extractors are looking for a gpu based deep learning environment. It's a good time to build a docker container or Singularity Image file for this.

All the dependencies I am using now are:

- Normal python lib: pyyaml, sympy, h5py, cython, numpy, scipy

- Some particular lib: opencv3, easydict, pytorch

Some other dependencies might need to be added as project ongoing.

**Comment by craig-willis** [comment]
@ZongyangLi  Sorry for the delay getting started on this.  I'm working on an image now and have opened a ticket with SDSC support. From their response, they are testing an official Pytorch image now.  I'll still try to get mine running in the short term

> Yes, that's the right definition file. However, I think Marty's working on a pytorch image (that is in testing) and we should have it ready soon so I will assign the ticket to him and he can follow up with details
>> I'm working with a collaborator on creating a  Singularity image to leverage Pytorch on Comet.
>> I see that there is an image with torch dependencies on the system under /share/apps/gpu/singularity/.  Are the image definition files for these available as well?
>> I've also come across some definitions on Github that may be related: https://github.com/mkandes/naked-singularity/tree/master/definition- files/us/ucsd/sdsc/comet/torch 
>> My current plan is to extend the torch image to add pytorch, unless  there's a better approach.

**Comment by craig-willis** [comment]
Just for tracking purposes:
http://www.sdsc.edu/support/user_guides/comet.html talks a bit about the official images on Comet
https://github.com/mkandes/naked-singularity/tree/master/definition-files/us/ucsd/sdsc/comet contains  Martin's definition files

**Comment by craig-willis** [comment]
From Comet/XSEDE support:
> We've successfully completed the single-node job tests for our new PyTorch Singularity containers [1] [2]. We're still checking if the multinode options are working properly, but I thought I'd let you know where to find the images in case you only have single-node jobs to run.
> Let me know if you have any questions.
> [1] /oasis/scratch/comet/mkandes/temp_project/singularity/images/pytorch-cpu.img
> [2] /oasis/scratch/comet/mkandes/temp_project/singularity/images/pytorch-gpu.img

@ZongyangLi  Will this work?

**Comment by craig-willis** [comment]
Latest update 
>We successfully completed our multinode tests of the 'tcp' and 'gloo' distributed backends [1] available in the new PyTorch Singularity containers [2] [3]. They work as expected. Please let us SDSC User Services Group

**Comment by craig-willis** [comment]
@ZongyangLi Have you had the chance to look at the images provided by SDSC?

**Comment by ZongyangLi** [comment]
@craig-willis Sorry about the delay, I will have a try next.

**Comment by craig-willis** [comment]
Removing milestone.  Zongyang, please update this issue when you've had the chance to review.

**Comment by ZongyangLi** [comment]
I am currently working on this.

Since we don't have a gpu resource right now, I need to convert the code from gpu to cpu first. And the result seems unexpected now. So I have not try the Singularity image yet.

**Comment by craig-willis** [comment]
Thanks, Zongyang. Just to confirm -- you don't have access to GPUs via your Comet allocation?

**Comment by ZongyangLi** [comment]
No I did not apply for a gpu resource.

**Comment by craig-willis** [comment]
Closing this issue. @ZongyangLi  please open a new issue if you need anything further.
