### ISSUE TITLE
Coordinate documentation for transfer vs. processing

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#42]
Continuation from #16 
Data transfer architecture (gantry to roger) @jdmaloney 

Data processing architecture @max-zilla 

Use for reports, users, publications

These should be unified or complementary 

This includes machines being used, resources

**Comment by max-zilla** [comment]
I put up the initial rough architecture slide on [Google Drive](https://drive.google.com/file/d/0B42lleyRvKnlR205R00zeGZlLWs/view?usp=sharing). We can discuss today.

The first 4 slides are from previous drafts. I tried to simplify and condense into one. @jdmaloney not sure what level of detail you had in mind, I can get further into the weeds if it makes sense.

**Comment by jdmaloney** [comment]
Got some work done on my diagram today.  Waiting on info from Noah on the Danforth WAN connection information, and does anyone have a good idea for what we should put for the transfer mechanism between the Gantry and Server.  It’s something I hope to learn more about while I’m in Phoenix.  I’m just attaching the screenshot of my slide in it’s current state as I still need to finish up these last two areas and don’t want to bother with the intermediate upload, but wanted to solicit advice.

Best,

J.D. Maloney
Storage Engineer | Storage Enabling Technologies Group
National Center for Supercomputing Applications (NCSA)
University of Illinois Urbana-Champaign
1205 W. Clark St. Urbana, IL 61801

**Comment by max-zilla** [comment]
@jdmaloney I think the screenshot might've been lost in transmission, unless I'm missing it... don't see it on github or in the email reply.

**Comment by jdmaloney** [comment]
![uploads/55016af7-c30f-431f-886d-ca3a1bc5291d/Screen Shot 2016-01-07 at 9.49.35 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F55016af7-c30f-431f-886d-ca3a1bc5291d%2FScreen+Shot+2016-01-07+at+9.49.35+PM.png)

**Comment by jdmaloney** [comment]
Is it there now?

J.D. Maloney
Storage Engineer | Storage Enabling Technologies Group
National Center for Supercomputing Applications (NCSA)
University of Illinois Urbana-Champaign
1205 W. Clark St. Urbana, IL 61801

**Comment by max-zilla** [comment]
Yep! Looking good so far. Thanks.

**Comment by jdmaloney** [comment]
[Prototype Architecture.pptx](https://github.com/terraref/computing-pipeline/files/90737/Prototype.Architecture.pptx)

**Comment by max-zilla** [comment]
I will migrate the key aspects of this discussion and the attached slides to #15 - the main issue regarding documentation. Then I'll close this issue.
