### ISSUE TITLE
refine clip_raster function for edge cases

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#422]
I wanted to provide some sample clipped geotiffs to use as test for the extractor revisions to use instead of fullfield mosaic. However, the first one I chose is encountering an error so I wanted to share.

https://drive.google.com/file/d/1fSgjg29u2BzvjftaAmXcfWt7pa4LB6f5/view?usp=sharing
https://drive.google.com/file/d/1QZeNzZWfChNZh6H0BWuXFFAVJzaV57ey/view?usp=sharing
Here are links to the two .tif files used in the script below.

Please use this branch of terrautils to test:
https://github.com/terraref/terrautils/tree/improve-datapoint-creation-logic
```
python setup.py install 
```

Then download the .tif files and change these paths:
```
from terrautils.products import get_file_listing, extract_file_paths
from terrautils.gdal import clip_raster
from terrautils.betydb import get_site_boundaries
from terrautils.formats import create_geotiff
from terrautils.spatial import geojson_to_tuples_betydb
from pyclowder.connectors import Connector
import json

#c = Connector({})
#f = get_file_listing(c, "http://terraref.ncsa.illinois.edu/clowder/", "CLOWDER_KEY", "RGB GeoTIFFs Datasets", "MAC Field Scanner Season 4 Range 26 Column 6", since='2017-04-25', until='2017-04-27')
#p = extract_file_paths(f)

b = get_site_boundaries('2017-04-26')
geojs = b["MAC Field Scanner Season 4 Range 26 Column 6"]
bounds = geojson_to_tuples_betydb(json.loads(geojs))

print("clipping left")
c1 = clip_raster("rgb_geotiff_L1_ua-mac_2017-04-26__13-21-19-041_left.tif", geojs)
create_geotiff(c1[0], bounds, "/left_clip.tif")

print("clipping right")
c2 = clip_raster("rgb_geotiff_L1_ua-mac_2017-04-26__13-21-19-041_right.tif", geojs)
create_geotiff(c2[0], bounds, "right_clip.tif")
```
I commented out the bit that fetches file paths because I'm just providing the two files directly for this debugging. The clip_raster method should fail here:
```
File "/usr/local/lib/python2.7/site-packages/terrautils-1.0.0-py2.7.egg/terrautils/gdal.py", line 140, in clip_raster    premask.shape[-1]), premask.dtype)
ValueError: negative dimensions are not allowed
```

My detective work so far:
![screen shot 2018-03-15 at 1 35 54 pm](https://user-images.githubusercontent.com/14166971/37484188-d6a0a440-2855-11e8-8ecd-aa9bb34724f2.png)
Here is the plot in red with the image in bottom right. Some variables are shown that feed into this part of the code which fails:
https://github.com/terraref/terrautils/blob/improve-datapoint-creation-logic/terrautils/gdal.py#L137

```
ulX, lrX, ulY, lrY
-3172 1481 -8433 2046

pxWidth, pxHeight
4653 10479

gt
(-111.97496310886508, 3.520366904853611e-09, 0.0, 33.075436552427476, 0.0, -3.012727963542923e-09)

minX, maxX, minY, maxY
-111.974974277 -111.974957894 33.0754303867 33.0754619597

premask.shape
(3296, 2472)

iY
-8433

(premask.shape[-2] - abs(iY), premask.shape[-1])
(-5137, 2472)
```
So clearly the premask shape 3296 - abs(iY) 8433 = -5137 and numpy doesnt like those dimensions. But I'm not sure I fully understand what's going on here. I imagine we want to end up with a raster the size of the plot with just the lower right filled in but wanted to share with @ZongyangLi before spending much more time.

**Comment by ZongyangLi** [comment]
@max-zilla 
May I ask where are these gdal.py codes comes from? I do not remember I had write such codes.

The one I can find most similar to this is here: http://karthur.org/2015/clipping-rasters-in-python.html
I am wondering if this gdal.py is the newest version for this blog?

**Comment by dlebauer** [comment]
@ZongyangLi it looks like they were contributed by a @PoppinBenny (Xingchen? @jterstriep do you know?) 

see https://github.com/terraref/terrautils/blame/improve-datapoint-creation-logic/terrautils/gdal.py#L137

**Comment by ZongyangLi** [comment]
@dlebauer Thanks, I see. I updated my comment for this.

**Comment by max-zilla** [comment]
@ZongyangLi Benny was a student last semester, no longer on the project. It seems the code was indeed copied from that site although not perfectly - I added some corrects and we're closer.
https://github.com/terraref/terrautils/pull/51

However I'm seeing weird artifacts in the clip.

LEFT IMG
![screen shot 2018-06-14 at 10 07 00 am](https://user-images.githubusercontent.com/14166971/41420759-d0a6e21e-6fba-11e8-8883-2c4db44e3bf3.png)
LEFT IMAGE w/ CLIP OVERLAID
![screen shot 2018-06-14 at 10 07 07 am](https://user-images.githubusercontent.com/14166971/41420760-d0b94fbc-6fba-11e8-86df-47853c818925.png)
LEFT CLIP
![screen shot 2018-06-14 at 10 07 13 am](https://user-images.githubusercontent.com/14166971/41420761-d0ca639c-6fba-11e8-8833-5eac4a362a2f.png)

There are diagonal pattern pixels appearing with (241,241,241) values:
![screen shot 2018-06-14 at 10 07 28 am](https://user-images.githubusercontent.com/14166971/41420814-f1a7cf6e-6fba-11e8-8b03-76c62e8c12c2.png)
![screen shot 2018-06-14 at 10 07 41 am](https://user-images.githubusercontent.com/14166971/41420815-f1bfb57a-6fba-11e8-80a7-aafe5483cad0.png)
![screen shot 2018-06-14 at 10 07 32 am](https://user-images.githubusercontent.com/14166971/41420822-f4d6db4e-6fba-11e8-9245-83e10aba6ee9.png)

I'm guessing this is some kind of rounding or georeferencing error, trying to figure out where this is being introduced...

**Comment by max-zilla** [comment]
part of me wonders if we should just scrap this code and use something simpler if possible...

**Comment by max-zilla** [comment]
Overhauled this to use rasterio for clipping. It includes nodata values where the plots don't overlap but otherwise works. Maybe this is OK for now - extractors can filter these zeroes if desired.
![screen shot 2018-06-15 at 8 53 06 am](https://user-images.githubusercontent.com/14166971/41471558-9c3ca1e8-7079-11e8-899d-28d24ebdf49c.png)
![screen shot 2018-06-15 at 8 53 11 am](https://user-images.githubusercontent.com/14166971/41471559-9c4e24e0-7079-11e8-91d8-391cf64d4712.png)

**Comment by max-zilla** [comment]
Jeff raised some concerns about this code (the idea of the utility of folders full of image shards) but this is ready as-is if there is use.

**Comment by max-zilla** [comment]
merged.
