### ISSUE TITLE
Utilize lasmerge from lastools

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#423]
As part of the laser3d refactor, we want to move away from PDAL to some other package for merging to LAS files. (PDAL was designed to work with PLY files, not LAS).  After some analysis, lastools was selected. This task is to update the laser3d  science package to use the lastools merge function.

Completion criteria:
* [x] Implement change
* [x] Unit test including test data
* [ ] Update documentation
* [ ] Merged PR

**Comment by max-zilla** [comment]
Quick update that uses plyfile and laspy to avoid LAStools licensing issues:
```
from plyfile import PlyData, PlyElement
import laspy
import copy
import math
import numpy

inp = '/Users/mburnette/Downloads/PLYTEST/a2ed3da5-4aaf-4983-a6a1-d8dd644f5913__Top-heading-east_0.ply'
out = '/Users/mburnette/Downloads/PLYTEST/testout.las'
pco = {'y': 48.458000000000006, 'x': 118.65199999999999, 'z': -0.19499999999999962}

plydata = PlyData.read(inp)
w = laspy.base.Writer(out, 'w', laspy.header.Header())
w.header.scale = [0.01, 0.01, 0.01]
w.set_header_property("x_offset", pco['x']*1000)
w.set_header_property("y_offset", pco['y']*1000)
w.set_header_property("z_offset", pco['z']*1000)
w.set_x(plydata['vertex']['x'], True)
w.set_y(plydata['vertex']['y'], True)
w.set_z(plydata['vertex']['z'], True)
w.header.update_min_max()
w.close()
```

can discuss more in person.

**Comment by max-zilla** [comment]
I will share test files from August 2017 for comparison. LAS files are not same size from new/old method but the individual datapoints have fewer fields - are all points still present?

**Comment by max-zilla** [comment]
look @ changing LAS data type to support floats for lat/lon, but header having offset and scale that should be sufficient.

**Comment by max-zilla** [comment]
- properly georeferencing LAS files first.
- Band1 in output geotiff to Float32 with better name if possible (CF name)
- can we clip LAS to plots on the fly? merge point clouds? rethink workflow here

**Comment by craig-willis** [comment]
Speaking with @weiqin61, this issue is still active -- there is a PR ready for review
https://github.com/terraref/laser3d/pull/8
