### ISSUE TITLE
Globus task status updates from gantry cache are failing

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#425]
Globus transfers are completing, but the gantry cache can't close status (thinks things are still ongoing when they aren't).  

Completion criteria:
* [x] identify problem
* [x] fix problem

**Comment by dlebauer** [comment]
from @robkooper: Sounds like the gantry-side database needs to be updated when there is a successful transfer. Currently the status is not updated.

**Comment by craig-willis** [comment]
@jdmaloney Any thoughts on this?  Max mentioned that he asked you to look into the problem.

**Comment by sbrad77** [comment]
Hi Shannon,
I’m out of the office in Europe until the 7th of June, I’ll take a look at this when I get back.

Best,
JD Maloney

**Comment by max-zilla** [comment]
It seems this is occurring for very old tasks that are no longer queryable via Globus (even on UI):
```
3bd8340c-67f1-11e7-a9a3-22000bf2d287 error checking with Globus for transfer status
ClientError.NotFound (404 Not Found): No task found with id '3bd8340c-67f1-11e7-a9a3-22000bf2d287'
```

Going to update service to account for this.

**Comment by max-zilla** [comment]
@jdmaloney I think this comes down to 2 issues:
1) old tasks returning 404 that weren't being caught
2) for ones that were, the terra-logging InfluxDB is down and currently we do not continue if that's the case.

I just created this branch and deployed:https://github.com/terraref/computing-pipeline/tree/catch-globus-404s so once I verify the 404 bug is fixed I will close. Until Nebula stuff is resolved and terra-logging is back up this will be difficult to determine however.

**Comment by max-zilla** [comment]
https://github.com/terraref/computing-pipeline/pull/470

**Comment by max-zilla** [comment]
Gantry monitor seems fine so far in resolving 404s and catching gaierror. terra-logging still not running to my knowledge but i think this is ready to be closed.
