### ISSUE TITLE
Document how to interface with BETYdb

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#43]
API for programmers

**Comment by rachelshekar** [comment]
Embed documentation with source code
Have process that runs over it and generates document
Talk to @robkooper

**Comment by dlebauer** [comment]
@gsrohde what is the status of this issue?

**Comment by gsrohde** [comment]
There is now documentation in GitBook.  Closing this issue.  Will make new issues if and when specific documentation shortcomings become apparent.
