### ISSUE TITLE
Setup tasks for ECSS prototype

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#430]
Tasks:
* [x] Grant access to Globus endpoint
* [x] Grant access to Bridges project 
* [x] Get bin2tif components installed on Bridges, ideally via Singularity
* [x] Setup HTCondor VM/EL7

**Comment by rynge** [comment]
Starting with the submit host (141.142.209.167), please make sure firewalls allow connections on port 9618 and 11001. The first one is for HTCondor, the second one for pyGlidein. See the two arrows in:

https://github.com/WIPACrepo/pyglidein/blob/master/docs/overview.png

For the HTCondor config on the submit host, first create a pool_password by running:

condor_store_cred -c -f /etc/condor/pool_password

This will set the shared secret the different parts of the pool will use to communicate. You can pick any password here, but at least initially, I would appreciate if it was one I know.

On the submit node, add the attached [50-central-manager.config](https://github.com/terraref/computing-pipeline/files/1877653/50-central-manager.config.txt) to /etc/condor/config.d/ and restart HTCondor with:

systemctl restart condor

Verify that it still works by running condor_q and condor_status.

If you want to have a worker in a VM, the procedure is similar. Install HTCondor, set the pool password (has to match obviously as it is a shared secret) and install the 
[50-worker.config](https://github.com/terraref/computing-pipeline/files/1877658/50-worker.config.txt)
 file under /etc/condor/config.d/ . Once HTCondor is restarted, you should be able to see it with condor_status on the submit node.

At this point you should have a working HTCondor pool. To add resources from Bridges dynamically, we need to install and configure pyGlidein. Again, on the submit host and as a non-privileged user:

virtualenv venv
. venv/bin/activate
pip install --upgrade setuptools
pip install minio
pip install tornando==4.5.3
pip install pyglidein

Long-term, the pyglidein server should be made a service. For now, run
it by hand to get a feel for how it is working:

pyglidein_server --delay 60 --port 11001 --constraint=MayUsePSCBridges==True

This will continuously check the HTCondor queue for jobs matching the constraint. An example job is attached [test.submit](https://github.com/terraref/computing-pipeline/files/1877662/test.submit.txt). Note how the job expresses that it could use Bridges (+MayUsePSCBridges = True) and in this case will only execute on a Bridges node (requirements = regexp("bridges.psc.edu", Machine)). We have a lot of flexibility here, but this is a good starting point.

On Bridges, we need a pyglidein client install. On one of the head nodes under your user account:

module load python2
virtualenv venv
. venv/bin/activate
pip install --upgrade setuptools
pip install pyglidein

Untar the ~rynge/config.tar.gz file (I left it on Bridges as it was too big to attach here). In it is a glidein tarball which contains the HTCondor binaries, some config and a pool password file with password from above. The secrets file is not used, but has to exist, and the terraref-bridges.config controls the clients behavior (how to react when new glideins are needed, and slurm config). I have tested things here with my own submit VM, so I think it should work out of the box, but minor changes might be necessary. The tarball= has to be changed to point to your own glidein.tar.gz location.

If you have pending job, try the client:

pyglidein_client --config=terraref-bridges.config --secrets=secrets

Once we have this working, we can create the service for the server and the Bridges cronjob for the client.

**Comment by craig-willis** [comment]
@rynge  I have things mostly working between the VM and Bridges using your example, but the job isn't getting picked up by the client:

Server is running and logging calls to jsonrpc:
```
$ pyglidein_server --delay 60 --port 11001 --constraint=MayUsePSCBridges==True
INFO:server:condor_q
condor_q -global -autoformat:, RequestCPUs RequestMemory RequestDisk RequestGPUs -format "%s" Requirements -constraint "JobStatus =?= 1" -constraint MayUsePSCBridges==True -allusers
INFO:tornado.access:200 POST /jsonrpc (128.182.108.81) 2.86ms
INFO:tornado.access:200 POST /jsonrpc (128.182.108.81) 1.64ms
```

Submitted test job:
```
condor_submit test.submit
Submitting job(s).
1 job(s) submitted to cluster 2.
```

Job is idle on submit node:
```
$ condor_q
-- Schedd: htcondor-submit.os.ncsa.edu : <141.142.209.167:9618?... @ 04/05/18 21:09:27
OWNER  BATCH_NAME            SUBMITTED   DONE   RUN    IDLE  TOTAL JOB_IDS
centos CMD: /bin/hostname   4/5  21:09      _      _      1      1 2.0

1 jobs; 0 completed, 0 removed, 1 idle, 0 running, 0 held, 0 suspended
```

Client returns immediately with nothing to do
```
$ pyglidein_client --config=terraref-bridges.config --secrets=secrets
2018-04-05 17:02:20,295 DEBUG {u'jsonrpc': u'2.0', u'result': [], u'id': 0}
2018-04-05 17:02:20,295 INFO no state, nothing to do
2018-04-05 17:02:20,307 DEBUG avg_idle_time for Cluster: 0s.
2018-04-05 17:02:20,307 DEBUG min_idle_time for Cluster: 0s.
2018-04-05 17:02:20,307 DEBUG max_idle_time for Cluster: 0s.
2018-04-05 17:02:20,343 DEBUG {u'jsonrpc': u'2.0', u'result': u'', u'id': 1}
```

Likely a configuration problem on my part.

**Comment by rynge** [comment]
@craig-willis The server output above does not show that it found any jobs, and hence the client did not think any new glideins were needed. Are you still running the server? It should have a line on stdout like:

INFO:server:state is updated to [{'count': 1, 'cpus': 1, 'memory': 1024, 'gpus': 0, 'disk': 5242.88, 'os': None}]

**Comment by craig-willis** [comment]
Thanks @rynge.  I've restarted things and do not see that line. 

Here's the submit call:
```
$ condor_submit test.submit
Submitting job(s).
1 job(s) submitted to cluster 4.

$ condor_q
-- Schedd: htcondor-submit.os.ncsa.edu : <141.142.209.167:9618?... @ 04/06/18 14:37:43
OWNER  BATCH_NAME            SUBMITTED   DONE   RUN    IDLE  TOTAL JOB_IDS
centos CMD: /bin/hostname   4/6  14:37      _      _      1      1 4.0

1 jobs; 0 completed, 0 removed, 1 idle, 0 running, 0 held, 0 suspended
```

Adding the --debug flag to pyglidein_server, I see the following during startup:
```
$ pyglidein_server --delay 60 --port 11001 --constraint=MayUsePSCBridges==True --debug
INFO:server:condor_q
condor_q -global -autoformat:, RequestCPUs RequestMemory RequestDisk RequestGPUs -format "%s" Requirements -constraint "JobStatus =?= 1" -constraint MayUsePSCBridges==True -allusers
DEBUG:server:1, 1024, 5242880, undefined, ( regexp("bridges.psc.edu",Machine) ) && ( TARGET.Arch == "X86_64" ) && ( TARGET.OpSys == "LINUX" ) && ( TARGET.Disk >= RequestDisk ) && ( TARGET.Memory >= RequestMemory ) && ( TARGET.HasFileTransfer )
```

Condor version is 8.6.10
```
$ yum info condor
Installed Packages
Name        : condor
Arch        : x86_64
Version     : 8.6.10
```

**Comment by rynge** [comment]
@craig-willis You do have the line:

DEBUG:server:1, 1024, 5242880, undefined, ( regexp("bridges.psc.edu",Machine) ) && ( TARGET.Arch == "X86_64" ) && ( TARGET.OpSys == "LINUX" ) && ( TARGET.Disk >= RequestDisk ) && ( TARGET.Memory >= RequestMemory ) && ( TARGET.HasFileTransfer )

Please try running the client now.

**Comment by craig-willis** [comment]
@rynge  Behavior is the same, but here's the server output with debug:

```
$ pyglidein_server --delay 60 --port 11001 --constraint=MayUsePSCBridges==True --debug --user=centos
INFO:server:condor_q
condor_q -global -autoformat:, RequestCPUs RequestMemory RequestDisk RequestGPUs -format "%s" Requirements -constraint "JobStatus =?= 1" -constraint MayUsePSCBridges==True centos
DEBUG:server:1, 1024, 5242880, undefined, ( regexp("bridges.psc.edu",Machine) ) && ( TARGET.Arch == "X86_64" ) && ( TARGET.OpSys == "LINUX" ) && ( TARGET.Disk >= RequestDisk ) && ( TARGET.Memory >= RequestMemory ) && ( TARGET.HasFileTransfer )
DEBUG:util:{}
DEBUG:util:{u'params': {}, u'jsonrpc': u'2.0', u'method': u'get_state', u'id': 0}
INFO:tornado.access:200 POST /jsonrpc (128.182.108.57) 3.32ms
DEBUG:util:{u'Cluster': 0}
DEBUG:util:{u'Cluster': 0}
DEBUG:util:{u'Cluster': 0}
DEBUG:util:{u'Cluster': 0}
DEBUG:util:{u'Cluster': 0}
DEBUG:util:{u'Cluster': 0}
DEBUG:util:{u'glideins_running': {u'Cluster': 0}, u'avg_idle_time': {u'Cluster': 0}, u'max_idle_time': {u'Cluster': 0}, u'glideins_launched': {u'Cluster': 0}, u'min_idle_time': {u'Cluster': 0}, u'glideins_idle': {u'Cluster': 0}}
DEBUG:util:{u'metrics': {u'glideins_running': {u'Cluster': 0}, u'avg_idle_time': {u'Cluster': 0}, u'max_idle_time': {u'Cluster': 0}, u'glideins_launched': {u'Cluster': 0}, u'min_idle_time': {u'Cluster': 0}, u'glideins_idle': {u'Cluster': 0}}, u'timestamp': 1523049745, u'uuid': u'willis8@br006.pvt.bridges.psc.edu'}
DEBUG:util:{u'params': {u'metrics': {u'glideins_running': {u'Cluster': 0}, u'avg_idle_time': {u'Cluster': 0}, u'max_idle_time': {u'Cluster': 0}, u'glideins_launched': {u'Cluster': 0}, u'min_idle_time': {u'Cluster': 0}, u'glideins_idle': {u'Cluster': 0}}, u'timestamp': 1523049745, u'uuid': u'willis8@br006.pvt.bridges.psc.edu'}, u'jsonrpc': u'2.0', u'method': u'monitoring', u'id': 1}
INFO:tornado.access:200 POST /jsonrpc (128.182.108.57) 2.79ms
```

I did change the Glidein.tarball and Cluster.user values in the client config from rynge to willis8.

I've added you to sudoers on the VM, if useful.  I'm currently running the server under the default centos user.

**Comment by rynge** [comment]
@craig-willis It seems pyglidein does not work with the newest version of Tornando. In the previous post, I had specified an older version using tornado==4.5.3, but that has already broken. The updated instructions for the server are now:

virtualenv venv
. venv/bin/activate
pip install --upgrade setuptools
pip install minio
pip install https://github.com/tornadoweb/tornado/archive/v4.5.3.zip
pip install pyglidein

I have updated and tested the venv for the centos user. Please try starting the server now, and then run the client.

**Comment by craig-willis** [comment]
That did it.  Thanks, @rynge.  Since our allocation is on Bridges large memory partition, I do need to tweak some of the settings, but I see how this will work.

**Comment by rynge** [comment]
Cool. Note that you can have multiple partitions specified in the config file. I would recommend to just having one for now to keep it simple, but keeping in mind that you can have multiple ones if the workloads in the future require it.

**Comment by craig-willis** [comment]
Provided basic bin2tif scripts for use in Condor/Pegasus pilot.
