### ISSUE TITLE
Resolve globus-uploader bottleneck

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#434]
While diagnosing problems with the full-field generation process, I noticed that the overall pipeline is still working through February (2/8 in process as of 4/19).  The current [globus-uploader](https://github.com/terraref/computing-pipeline/blob/master/scripts/globusmonitor/globus_uploader_service.py) assumes a single process.  We can easily parallelize this by adding another status (e.g., PENDING).

For example, changing from
`"SELECT * FROM globus_tasks WHERE status = '%s' order by completed ASC limit 1" % status`
to 
`"UPDATE globus_tasks set status = 'PENDING' WHERE globus_id IN ( SELECT globus_id FROM globus_tasks WHERE status = '%s'  order by completed ASC limit 1) RETURNING *" %status`

would allow us to run multiple globus-uploaders.  Of course, this might just identify more downstream bottlenecks, but would get more than  a slow trickle moving through the pipeline.

**Comment by craig-willis** [comment]
@dlebauer I made a temporary change yesterday to see if we could easily parallelize the globus-uploader component.  The system is now working through 2/9 at a rate of ~2-3 days worths of data per day.  There's no way it will make it through the complete backlog before next week, and scaling the cluster nodes alone won't help and will require more fundamental system changes.

Given our discussion yesterday about the sorghum planting next week and that the winter wheat isn't a focus, I'm inclined to flag the remaining dates for future processing.  In short, I would change the state of all unprocessed tasks for February, March and (maybe) early April.  Any new data would be processed and work through the backlog with any free cycles.

Is this acceptable?

**Comment by craig-willis** [comment]
Blocked by https://github.com/terraref/computing-pipeline/pull/409

**Comment by dlebauer** [comment]
@craig-willis that sounds like a good plan though it would be okay to hold off until we know the planting date and see if we are close enough. 

What does 'change the state' mean? This would prioritize new data? 

@NewcombMaria when is Sorghum planting planned?

**Comment by craig-willis** [comment]
@dlebauer
Yes. The way the globus-uploader works now each task can have a state of SUCCEEDED (transfer complete), PROCESSED (submitted to clowder), ERROR (re-try later), or FAILURE (don't retry later).   The processing loop starts with tasks in the SUCCEEDED state then, once those are complete, moves on to tasks in the ERROR state.

I'm confirming with Max, but I believe if I put the current backlog into the ERROR state, any newly transferred data will be processed first.

**Comment by craig-willis** [comment]
Re-opening this since it's really still a problem and actively being worked on.
* As of today, we're running 2 uploaders because of failures with Elastic Search
* The problem with ES is actually not related to load, it's because Puppet is restarting the nodes too frequently because of incorrectly identified changes.  However, the more uploaders running, the more errors we see.
* I've manually set the status to BACKLOG for pre-April data. We will manually stage in the backlog once we can better predict our daily pipeline processing rates.

**Comment by max-zilla** [comment]
https://github.com/terraref/computing-pipeline/pull/441

This PR adjusts status handling because there was a dict not shared between parallel instances which would result in duplicates potentially. Merged and deployed.

**Comment by max-zilla** [comment]
We can close this issue when we merge: https://github.com/terraref/computing-pipeline/pull/443
