### ISSUE TITLE
"Hanging" extractors

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#440]
We've noticed that extractors can sometimes get into a "hung" state where there is work to do in the queue but nothing is being processed.  After further investigation, it looks like there are "unacknowledged" messages in the queue although the extractors report "Done processing". This indicates a bug in pyclowder2, most likely in 

https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/pyclowder2/browse/pyclowder/connectors.py#704

As the return values of calls to  basic_publish and basic_ack are not checked.  If network failure or similar causes errors, then it may cause the unack'd scenario.

We have two resolutions to this problem:
* [ ] In the short term, provide a cronjob on the Kubernetes master node that deletes all pods for a select list of replica controllers every configurable (e.g., 24 or 48) hours.
* [x] Fix and test pyclowder, which

**Comment by craig-willis** [comment]
Ready to merge Clowder PR, can close this PR when deployed for TERRA.

**Comment by max-zilla** [comment]
I should review this: https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/pyclowder2/pull-requests/67/overview

Once this is merged, we make new version of pyclowder (2.1) and build/deploy with terrautils.

**Comment by max-zilla** [comment]
@robkooper and I will update terrautils to use this new pyclowder docker image then update extractors.

**Comment by max-zilla** [comment]
This was been buiit into pyclowder2 and a new terrautils was deployed using it, starting with globus-uploader.
