### ISSUE TITLE
LeafAngle package (about to be) deleted from CRAN

### ISSUE THREAD

**Issue by RemkoDuursma** [terraref/computing-pipeline#444]
Since there was some discussion about the use of (my) `LeafAngle` package, I have to let you know it will be deleted from CRAN. It is quite outdated (I wrote it in 2008-9), and better implemented in `RLeafAngle` (not mine). 

But you can still install it via,

```
devtools::install_bitbucket("remkoduursma/leafangle")
```

**Comment by dlebauer** [comment]
@RemkoDuursma thanks for letting us know - it seems like a simple update and coincidentally we got the PR using LeafAngle today: https://github.com/terraref/laser3d/pull/9

If you have any thoughts or references related to estimating leaf angles from point clouds or surface elevation maps (both ~1mm resolution) they would be appreciated!

We will either switch the source to bitbucket or go ahead and change to using the RLeafAngle package (and add estimates of extinction coefficient and % sunlit leaf). 

@weiqin61 the RLeafAngle package is on CRAN here: https://cran.r-project.org/web/packages/RLeafAngle/index.html and the reference is [1-s2.0-S016819230600390X-main.pdf](https://github.com/terraref/computing-pipeline/files/2009551/1-s2.0-S016819230600390X-main.pdf)
