### ISSUE TITLE
Change fullfield resolution,  percentage for generation, and image used for trait calculation

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#447]
Changes to fullfield generation process both increasing resolution and percentage of images required for generation.

Currently, the value is 2% for RGB fullfield and 20% for IR:
https://github.com/terraref/extractors-stereo-rgb/blob/master/fieldmosaic/terra_fieldmosaic.py#L147

Completion task:
* Add separate image for QC at ~20% or < 500MB
* Change percentage for fullfield generation (rulechecker) to ~95%
* Add full-resolution image for canopy cover. Canopy cover should trigger on this image.

**Comment by max-zilla** [comment]
Just pushed rulechecker that requires 98% of GeoTIFFs. Also pushed field mosaic that will generate 2/10/100 resolutions regardless of sensor and trigger trait extractors directly so there is less noise on those queues (and cc will only run on 100% image)

**Comment by craig-willis** [comment]
Can close when PR merged

**Comment by craig-willis** [comment]
Spot checking a few fullfields, and we're certainly seeing the 3 resolutions.  I've opened the thumb and 10pct in QGIS and they look okay.  One concern looking at 6/2/2018:

![image](https://user-images.githubusercontent.com/4334350/40941124-86e34544-680f-11e8-8d34-264b51e69497.png)

We have > 99% coverage on the rgb_geotiffs (missing <1% likely due to race condition in processing), however there are missing rows in the image.

@NewcombMaria Is this an artifact of the changes scan program? Max mentioned possibly related to FOV as well.

**Comment by NewcombMaria** [comment]
@craig-willis the day scans running now skip over the walkways between plots to save some run-time.  I'm keeping track of this type of coverage in the scan log in column J 'field_area'.  

I can view the thumb for 6/2 for the afternoon sun_flir_ scan, but not the morning shade_rgb_eastedge thumb.  The thumb of the afternoon sun_flir_ scan looks good except at the south end. The skipped rows are expected.  However the east edge of the image in the earlier comment from today is not what I expected - I expected an even east edge on this day, similar to the west edge.  

scan log:  https://docs.google.com/spreadsheets/d/1dZYE6UbF9rmYuUNLkpUNJzXkc7kHPAZhoBxQtGuCUXc/edit#gid=1793149806

**Comment by craig-willis** [comment]
Thanks, @NewcombMaria . We're still not processing fullfields as quickly as we'd like -- the 6/2 images were completed later on 6/4, 6/3 images are available now.  As for the south end of the image, this is likely due to our 98% threshold, which we're working on.  Do you think the problem with the east edge is an artifact of our processing or the scan program?

**Comment by craig-willis** [comment]
@max-zilla I'm not seeing any fullfields for FLIR even though we have data.  Looking at the ir_geotiff tab on the tracking spreadsheet https://docs.google.com/spreadsheets/d/1emUW6xu9i0zMh1jUupgqPmIIz_IVjDv-DZWEKbZNCz8/edit#gid=192543672  rulemonitor has incomplete data for 5/19-5/25 as well as 6/2.  We have reasonable coverage for RGB GeoTiff for the same period.

**Comment by craig-willis** [comment]
We have explanations and corrective measures for the missing fullfields.  In the case of FLIR for 5/19 - 5/25, the flir2tif extractor was missing the fix for metadata/upload order. In the case of 5/25 specifically, we have zero byte files due to the NFS outage.  We can merge this PR, but I'd like one final walk-through of the changes to make sure we've covered everything (changes to fullfield extractor + rulechecker, any follow-on issues that we need to create related to zero-byte file handling, fullfield colormap, etc).

**Comment by craig-willis** [comment]
Fullfields are generating correctly. Created separate issue to track trait generation. https://github.com/terraref/computing-pipeline/issues/468
