### ISSUE TITLE
Front end development

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#45]
David, Luigi, Max

**Comment by yanliu-chn** [comment]
Docker files for PlantCV is in my fork of Clowder docker files: https://opensource.ncsa.illinois.edu/bitbucket/users/yanliu/repos/dockerfiles/browse/clowder/plantcv?at=refs%2Fheads%2Ffeature%2Fplantcv

Not sure if you could access it. But I have sent Rob a pull request in the main repo.

**Comment by dlebauer** [comment]
I don't think this is a public repository, and I can't find the pull request here https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/clowder/pull-requests (is that where it should be? @robkooper?)

@davidraila I put the iPython notebook here: https://github.com/terraref/computing-pipeline/blob/master/scripts/PlantCV_demo.ipynb

**Comment by yanliu-chn** [comment]
This is the request:

https://opensource.ncsa.illinois.edu/bitbucket/projects/BD/repos/dockerfiles/pull-requests/5/overview

**Comment by max-zilla** [comment]
Somewhat related to #11. 

Tracking Clowder UI development with this JIRA issue: https://opensource.ncsa.illinois.edu/jira/browse/CATS-224

**Comment by robkooper** [comment]
In general we try to tag everything in JIRA with TERRA, so you can do search across all projects using:
https://opensource.ncsa.illinois.edu/jira/issues/?jql=labels%20%3D%20TERRA
