### ISSUE TITLE
Confirm FLIR end-to-end pipeline

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#450]
With the FLIR device online, we need to confirm the FLIR pipeline is working end-to-end:

Task is complete when: 
* [x] 98% coverage (pending the locking fix)
* [x] Fullfield generated since FLIR came online with 2%/10%/full resolution
* [x] mean temp traits are in BETY and valid and written to disk
* [x] Flir extractor improvements match bin2tif

**Comment by NewcombMaria** [comment]
This issue has overlap with reference-data issues #230 (FLIR temp conversion with window: results from in-house calibration).  R scripts for temp conversion are referenced at
 https://github.com/terraref/reference-data/issues/230

**Comment by craig-willis** [comment]
PR https://github.com/terraref/extractors-multispectral/pull/27/ depends on this review.
