### ISSUE TITLE
Cache BETY data in uploader

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#454]
The globus uploader process may be causing heavy load on BETY resulting in 500 errors due to frequent calls to the sites/experiments tables. Since this data is generally static and read-only, it should be possible to cache in the uploader to reduce the number of errors/retries during processing.

**Comment by max-zilla** [comment]
https://github.com/terraref/terrautils/blob/master/terrautils/betydb.py

- create a global variable at the top of this file with a dict of the data
  - get_sites
  - get_experiments
  - ...start with these and possibly more later
- in the functions that reference these data, refer to global variable and only make the call if the data doesn't exist in the call

If you have terrautils installed:
```
from terrautils.betydb import get_site_boundaries
b = get_sites('2017-04-26', city="Maricopa")
```
...you can then examine the list of sites like b[0] and think about how to cache them.

**Comment by max-zilla** [comment]
this is completed and deployed.
