### ISSUE TITLE
Automatic cleanup failed on cache server

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#458]
Around June 1st the gantry cache filed causing processing and pipeline failures.  

We need to understand what happened
Document process and make sure Max/Craig have access to do what is needed

**Comment by max-zilla** [comment]
@jdmaloney any updates on this topic?

**Comment by jdmaloney** [comment]
@max-zilla Purge script is fixed, I'm re-writing the 2-day verify script first before turning it back on

**Comment by max-zilla** [comment]
In progress on Condo

**Comment by jdmaloney** [comment]
Waiting on backup to Nearline to complete (raw_data will be done by end of day), Level_1 will begin this weekend

**Comment by robkooper** [comment]
@jdmaloney what is the status of the backup?

**Comment by max-zilla** [comment]
@jdmaloney i believe this was issue relevant to the gantry cleanup we discussed this morning

**Comment by max-zilla** [comment]
@jdmaloney any updates on this?

**Comment by max-zilla** [comment]
@jdmaloney please update

**Comment by max-zilla** [comment]
@srstevens can we schedule a sit-down in the next couple weeks to discuss this?
