### ISSUE TITLE
Search clowder for data

### ISSUE THREAD

**Issue by robkooper** [terraref/computing-pipeline#46]
Should have a complex query capability to find data in clowder. This should allow the user to do complex queries like find all data that has LAI > 10 AND is type XYZ.

See https://opensource.ncsa.illinois.edu/jira/browse/CATS-328

**Comment by JeffWhiteAZ** [comment]
A suggested use cases for searches:
To monitor a single plot over time: Identify all imagery (all or selected sensors) for a location. Location might be a plot ID, point location with radius, or bounding rectangle. The time range would be user selected. The images could be retrieved in their original un-stitched form or in whatever stitched format is available (full field or swaths down the center-line of plots).

**Comment by max-zilla** [comment]
Making substantial progress here, but not ready to close issue yet. Lots of extractor dev focus as well.

**Comment by max-zilla** [comment]
Once this is merged this should be done, at least for a first cut:
https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/clowder/pull-requests/994/overview

**Comment by dlebauer** [comment]
@max-zilla it seems like the next step is to create new issues for more manageably sized tasks and close this one ... correct?

**Comment by max-zilla** [comment]
Yep, just haven't gotten around to it yet.

**Comment by max-zilla** [comment]
Closing this issue for #231.
