### ISSUE TITLE
Get LASTools working in Wine with blast2dem

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#460]
https://github.com/terraref/laser3d/pull/10

This PR attempts to re-introduce LASTools support using wine so that we can install wine in the heightmap dockerfile like this: https://github.com/terraref/extractors-3dscanner/pull/26/files

However I've been unable to get good results from blast2dem using this method. We need to figure out right parameters to convert LAS to GeoTIFF DEM, possibly including clipping of point cloud to plot boundary (although we could also clip the LAS files separately if necessary).

**Comment by weiqin61** [comment]
https://github.com/LAStools/LAStools/blob/3fceab161f4d3faccbada8bdfbb0962484b33697/ArcGIS_toolbox/scripts/blast2dem.py

find a link that might help, at least it shows how to use blast2dem in python with flags

**Comment by max-zilla** [comment]
Max needs to send data to test: 1) LAS file and 2) plot geometry to try clipping

**Comment by max-zilla** [comment]
@weiqin61 one recent LAS file you can test with is accessible via Globus:
```/ua-mac/Level_1/laser3d_mergedlas/2018-06-01/2018-06-01__01-37-22-494/canner3DTop_L1_ua-mac_2018-06-01__01-37-22-494_merged.las```

The file is ~1.5 GB.

This LAS file crosses the field across columns in Range 30. Example (with geotiff conversion that is best we currently have but we should be able to improve):

![screen shot 2018-06-15 at 9 54 09 am](https://user-images.githubusercontent.com/14166971/41474615-14347dd0-7082-11e8-9dde-8785dbba8f46.png)

The 3 boxes are 3 plots I show as an example:

MAC Field Scanner Season 4 Range 30 Column 5
```
{ "type": "MultiPolygon", "coordinates": [ [ [ [ -111.974990712657487, 33.075605717463773, 0.0 ], [ -111.974974343378051, 33.075605722793924, 0.0 ], [ -111.974974328860199, 33.075574155092227, 0.0 ], [ -111.97499069813378, 33.07557414976219, 0.0 ], [ -111.974990712657487, 33.075605717463773, 0.0 ] ] ] ] }
```

MAC Field Scanner Season 4 Range 30 Column 6
```
{ "type": "MultiPolygon", "coordinates": [ [ [ [ -111.974974343378051, 33.075605722793924, 0.0 ], [ -111.974957974098572, 33.075605728121921, 0.0 ], [ -111.974957959586561, 33.075574160420111, 0.0 ], [ -111.974974328860199, 33.075574155092227, 0.0 ], [ -111.974974343378051, 33.075605722793924, 0.0 ] ] ] ] }
```

MAC Field Scanner Season 4 Range 30 Column 7
```
{ "type": "MultiPolygon", "coordinates": [ [ [ [ -111.974957974098572, 33.075605728121921, 0.0 ], [ -111.974941604819037, 33.075605733447773, 0.0 ], [ -111.974941590311886, 33.075574165655659, 0.0 ], [ -111.974957959586561, 33.075574160420111, 0.0 ], [ -111.974957974098572, 33.075605728121921, 0.0 ] ] ] ] }
```

If you want more plots you can use:
```
from terrautils.betydb import get_site_boundaries
b = get_site_boundaries('2017-04-26')

#will return the geometry for this plot
b["MAC Field Scanner Season 4 Range 30 Column 6"]
#you can see all plots returned with
b.keys()
```

**Comment by weiqin61** [comment]
https://groups.google.com/forum/#!searchin/lastools/blast2dem|sort:date/lastools/v9p3x-8eXEw/_8D1CW_RAgAJ

The post explains why we see white stripes when first using blast2dem, cause we need to use buffers when processing in tiles. Also, there is a 2 billion points limit when using blast2dem, which comes back to the bounding box issue.

**Comment by max-zilla** [comment]
Current progress...
```
# CREATE SHP FROM PLOT GEOJSON
ogr2ogr -nlt MULTIPOLYGON -skipfailures -t_srs EPSG:32612 r30c5.shp r30c5.geojson

# CLIP LAS BY SHP KEEPING 1/2 POINTS (2.8 million)
wine /home/clowder/LAStools/bin/lasclip.exe -i scanner3DTop_L1_ua-mac_2018-06-01__01-37-22-494_merged.las -poly r30c5.shp -o r30c5.las -keep_random_fraction 0.5

# CONVERT CLIP TO TIF w/ .001m resolution
wine /home/clowder/LAStools/bin/blast2dem.exe -i r30c5.las -o r30c5.tif -utm 12N -force_precision -step .001
```

3 plots:
<img width="837" alt="screen shot 2018-06-22 at 12 50 40 pm" src="https://user-images.githubusercontent.com/14166971/41791472-7199872e-761b-11e8-9d18-022ae679a8c8.png">

Same-day fullfield:
<img width="855" alt="screen shot 2018-06-22 at 12 50 48 pm" src="https://user-images.githubusercontent.com/14166971/41791499-7fbae60e-761b-11e8-809d-ff2744e51143.png">

Range 30 Col 6:
<img width="749" alt="screen shot 2018-06-22 at 12 55 29 pm" src="https://user-images.githubusercontent.com/14166971/41791522-8f586e88-761b-11e8-9f3d-83f322f37ee4.png">

R30C6 point cloud:
<img width="427" alt="screen shot 2018-06-22 at 12 53 56 pm" src="https://user-images.githubusercontent.com/14166971/41791540-9a5e8182-761b-11e8-9be2-b9f0a980fc50.png">

Still needs work but wanted to paste current code.

**Comment by max-zilla** [comment]
@robkooper and i discused a quick check - read PLY into numpy and write directly to geotiff instead of going through LAS first

**Comment by max-zilla** [comment]
Reading PLY into numpy simply returns 3 long arrays with XYZ coordinates:
```
[[  4.08992375e+05   4.08992375e+05   4.08992375e+05 ...,   4.09009156e+05
    4.09009156e+05   4.09009156e+05]
 [  3.66008925e+06   3.66008925e+06   3.66008925e+06 ...,   3.66008900e+06
    3.66008900e+06   3.66008900e+06]
 [  3.90553772e-01   3.90229523e-01   3.89984429e-01 ...,   3.66384566e-01
    3.65714967e-01   3.66277993e-01]]
(3, 76584572)
```

Converting this to geotiff is not trivial - there are 76,584,572 coordinates in this example but software to write numpy to geotiff requires cell resolution information. If we take the min/max of XY for this array...
```
(3660089.0, 3660090.2, 408987.41, 409009.56)
```
...we can use (max-min)/scale to get the number of pixels desired in output raster. For example at scale .001m:
```
(3660090.2 - 3660089.0) / .001 = 1200
(409009.56 - 408987.41) / .001 = 22150
```

... we could expect to have a raster thats 22150 x 1200 = 26,580,000 pixels.

So the question becomes how to convert our arrays of 76,584,572 coords to 26,580,000 pixels, binned by each cell in the output raster and averaged/maxed per cell. 

The idea of precalculating each pixel boundary by dividing xsize by 22150 and ysize by 1200 and iterating through 26 million cells, for each finding the coordinates that fall within those boundaries then performing some aggregation on them seems agonizingly slow.

So, plan C. We create a temporary LAS file that doesn't have geocoding (because that is breaking everything) and use PDAL to convert that. We can maintain a separate LAS geocoded merged pointcloud for other purposes.
![screen shot 2018-06-26 at 12 52 28 pm](https://user-images.githubusercontent.com/14166971/41930201-f833613e-793f-11e8-946e-67b1b67f1fc4.png)

**Comment by max-zilla** [comment]
Current plan is to use this PLY conversion for LAS and for stitched heightmap. implementation is done.
