### ISSUE TITLE
Create pipeline operational checklist and log

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#462]
We need an operational checklist and log for the pipeline.

* How do we know that each component is running as expected?
* How do we know what to expect as output for each day?
* How does the team know when a problem occurs?

Started tracking Stereo and FLIR, but we need something more complete.
https://docs.google.com/spreadsheets/d/1emUW6xu9i0zMh1jUupgqPmIIz_IVjDv-DZWEKbZNCz8/edit#gid=1024884416

**Comment by max-zilla** [comment]
https://docs.google.com/document/d/1q-JyPKlOh_7Y3BJeTg2gHSJ9XIUoecXEVGrx5Iz11vA/edit Notes started here.

**Comment by max-zilla** [comment]
To start, I will ask @tcnichol to start performing these daily checks and updating spreadsheet.

Will require various parties granting access to necessary systems.

**Comment by max-zilla** [comment]
see also some revisions to spreadsheet: https://docs.google.com/spreadsheets/d/1emUW6xu9i0zMh1jUupgqPmIIz_IVjDv-DZWEKbZNCz8/edit#gid=0
