### ISSUE TITLE
Update flir2tif extractor to match bin2tif

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#464]
The flir2tif extractor is our of sync with bin2tif (logging enhancements, etc).

* [x] Review existing branches and either close or implement
* [x] Confirm changes made to bin2tif are applied to flir2tif
* [ ] Release/tag

**Comment by max-zilla** [comment]
PR was merged:
https://github.com/terraref/extractors-multispectral/pull/28

With nebula outage have been unable to deploy yet.

**Comment by max-zilla** [comment]
v1.2 is running and outputs look good including PNG.

https://terraref.ncsa.illinois.edu/clowder/datasets/5b4602214f0ca37248d7de28
