### ISSUE TITLE
Update meantemp to use new BETY/geostreams extractors

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#465]
Related to #445 and #463. Apply same changes to meantemp:

* Make sure it's running on full resolutio images
* remove uploader code from extractor - generate CSV and geostreams files
* purge bety and geostreams for S6 and resubmit
* rerun meantemp for season 6

**Comment by max-zilla** [comment]
This is continuation of #207

**Comment by max-zilla** [comment]
just need @craig-willis to approve the PR, it is deployed and working.

**Comment by craig-willis** [comment]
We have fullfields for 7/6 - 7/9 generated on 7/13-7/14 with no csv output

**Comment by max-zilla** [comment]
CSV outputs now being generated, e.g. https://terraref.ncsa.illinois.edu/clowder/datasets/5b55d9a04f0cda74074d8cf0
