### ISSUE TITLE
FLIR fullfield is missing the colormap information

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#466]
The newly generated FLIR fullfields don't have color information but the individual images do.

https://terraref.ncsa.illinois.edu/clowder/files/5b1aa7d44f0c6118f1b19dc3?dataset=5b18d5ed4f0cd6f866bab597&space=

Would be nice to have so users don't need to load the geotiff into QGIS.

**Comment by max-zilla** [comment]
Created branch to attend to both this and #455 
https://github.com/terraref/extractors-stereo-rgb/tree/fullfield-JPG-with-colormap

**Comment by max-zilla** [comment]
OK, got this working now. ~2.3 MB image output.

![out_test](https://user-images.githubusercontent.com/14166971/42762448-0509a8a0-88d6-11e8-82a3-0c9af8edc76d.png)

**Comment by max-zilla** [comment]
Note that if the results look unusual for current files, could be attributable to this newly discovered issue:
https://github.com/terraref/computing-pipeline/issues/483

...where multiple FLIR scans with same scan name are being combined into one. I have a PR for a fix that will create distinct outputs going forward.

**Comment by max-zilla** [comment]
These are being generated automatically, but I adjusted the algorithm slightly to ignore temp values <= 0 when determining scaling. Originally I was getting scaled images that over-considered the low end so all values were getting crushed at the high end:
![screen shot 2018-07-24 at 8 18 02 am](https://user-images.githubusercontent.com/14166971/43140823-24880fce-8f1a-11e8-932c-d141abe0786b.png)

Filtering only to consider pixels >0 for scaling results in a better representation of actual data:
![screen shot 2018-07-24 at 8 18 13 am](https://user-images.githubusercontent.com/14166971/43140857-3179054e-8f1a-11e8-83cb-ca4e7bd24929.png)

This could possibly be improved further if we wanted to e.g. assign a constant range to every FLIR image but I'm not sure what values would be appropriate to use.
