### ISSUE TITLE
Confirm canopycover using full resolution

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#468]
Per https://github.com/terraref/extractors-stereo-rgb/pull/33

* [x] Confirm canopycover extractor using fullfield
* [x] Confirm data in geostreams
* [x] Confirm data in BETY
* [ ] QC actual values

PR can be merged when this is done.

**Comment by max-zilla** [comment]
Canopycover is using full resolution currently. QA of data values is separate issue.
