### ISSUE TITLE
Resolve zero-byte problem

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#469]
We've encountered a problem with zero byte files in the bin2tif path, but likely elsewhere.

Possible solutions:
[ ] Check for zero byte files and treat as unprocessed (possible concurrency problem). May need additional creation time check
[ ] Alternatively we could scan for these conditions periodically, because this is usually associated with a major outage.

**Comment by max-zilla** [comment]
Generic function created here:
https://github.com/terraref/terrautils/pull/52

**Comment by max-zilla** [comment]
once we merge this PR we can implement in extractors.

**Comment by max-zilla** [comment]
merged. will make followup issue to implement.

**Comment by max-zilla** [comment]
https://github.com/terraref/computing-pipeline/issues/482
