### ISSUE TITLE
Ability to do search across BETY and CLOWDER

### ISSUE THREAD

**Issue by robkooper** [terraref/computing-pipeline#47]
Should be able to do complex queries that span both BETY and Clowder.

See https://opensource.ncsa.illinois.edu/jira/browse/CATS-552 and subtask https://opensource.ncsa.illinois.edu/jira/browse/CATS-328

**Comment by gsrohde** [comment]
@doracai The existing documentation on doing API searches is here: https://www.authorea.com/users/5574/articles/7062/_show_article

As mentioned there, results are available in both XML and JSON formats.  If I remember correctly, the XML results are a little more expressive and contain more information.  Also, the results contain information that they really shouldn't: The end users don't need to know the id column values of returned rows except possibly if there is no other uniquely-identifying column set for the table.

In my view, the existing API syntax for doing queries is rather convoluted, and David LeBauer, Rob, and I plan to meet next week to discuss extending and redesigning the API.

You can view the database schema here: https://www.betydb.org/db_docs/index.html.  Unfortunately, the software that extracts this doesn't seem to detect the CHECK constraints.  For many or most tables, we have tried to implement a candidate key based on real-world characteristics independent of the surrogate "id" key that all the tables have.  Some information about this can be found here https://docs.google.com/spreadsheets/d/1fJgaOSR0egq5azYPCP0VRIWw1AazND0OCduyjONH9Wk/edit?pli=1#gid=956483089 and here https://www.overleaf.com/read/wxptyrksypkx.  The latter is probably more up-to-date.  But not all the constraints mentioned have been implemented.

Let me know if it would be helpful to have the SQL version of the complete schema as it currently stands.

**Comment by robkooper** [comment]
Start with searching geospatially
1) query bety for sites with geno-type
2) use sites lat/lon to find in clowder geostreams information

**Comment by dlebauer** [comment]
@robkooper would the [Apache Drill](https://en.wikipedia.org/wiki/Apache_Drill) software help with this application, especially since we will need to extend this to other databases?

**Comment by rachelshekar** [comment]
Consistent use of polygons for plot tiling, Geodashboard meeting Jan 17

**Comment by max-zilla** [comment]
Closing this issue for #231.
