### ISSUE TITLE
TERRA Q11 report-due on July 25, 2018 by COB

### ISSUE THREAD

**Issue by sbrad77** [terraref/computing-pipeline#475]
[ ] Shannon needs template
[ ] Shannon needs copy of/link to previous report

Estimate - this will take more than one sprint

Hello everyone,
 
It’s Q11 report time! Please complete your parts of the attached quarterly report for the TERRA project and return to me by COB on July 25, 2018.  Please make sure to submit your report on time. It becomes increasingly difficult to submit our report on time when we do not receive everyone’s submission in a timely fashion.
 
This report includes project activities that occurred from April 1, 2018-June 30, 2018.  I have noted via track changes who is responsible for completing each component.
 
Notes:
Please make sure to fill out and include any information that pertains to section 2 “Other miscellaneous updates”.  This includes sending any publication or other output and follow-on funding.
 
Please adhere to the 499 character limitation on the milestone/deliverable summaries.  These are uploaded onto an on-line system that automatically cuts off the text at 499 characters.  You can use the general scientific narrative section below each table to discuss any milestone/deliverable in greater detail (in addition to general task activities).  There is no character limitation here.
 
Best,
Cathy
 
 
Cathy Kromer
Grant Program Manager
ARPA-E Programs & REU Internship Program
ckromer@danforthcenter.org
o: 314-587-1424
f: 314-587-1988
Donald Danforth Plant Science Center
975 N Warson Rd
St. Louis, MO  63132

**Comment by max-zilla** [comment]
@sbrad77 has created a shared google doc and started working on this.

**Comment by max-zilla** [comment]
me and @robkooper need to review the current document.

**Comment by max-zilla** [comment]
submitted yesterday!
