### ISSUE TITLE
Ability to do data analytics in clowder

### ISSUE THREAD

**Issue by robkooper** [terraref/computing-pipeline#48]
Should be able to do cluster analysis based on the metadata extracted in clowder.

See: https://opensource.ncsa.illinois.edu/jira/browse/CATS-332

**Comment by dlebauer** [comment]
@robkooper can you please clarify the use case for this within the scope of the TERRA project? In general, our focus is not on implementing new analytical methods but on facilitating data discovery and use.

**Comment by robkooper** [comment]
This is dealing with the ability to do analytics such as clustering of different datasets based on their metadata of the files and dataset. Given a group of datasets this will allow the scientist to easily find correlations between different metadata that is extracted and allow them to find a subset of datasets that have common data for further analysis.

**Comment by dlebauer** [comment]
Why closed?

**Comment by dlebauer** [comment]
Closing. We will re-open or create a new issue when we are ready to support this. Not clear how much on the fly computing we are expected to provide
