### ISSUE TITLE
Pegasus implementation plan

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#480]
We have the prototype from Mats.  Now that Nebula is back online, we need to plan how to move forward with an eye toward November data release (2016-2017 reprocessing).

**Comment by craig-willis** [comment]
First stab (short term tasks) https://docs.google.com/document/d/18LGSnq1EAXStInLOlLZZ9X3JczPze7XTuJbU1hBJSFk/edit

**Comment by max-zilla** [comment]
created issue for actual implementation, planning is complete. #494
