### ISSUE TITLE
Account for multiple scans per day of same script

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#483]
At this point the same scan script is sometimes run 2-3 times per day. Our pipeline must treat those as separate scans where necessary (e.g. field stitching).

Fortunately as illustrated by @jdemieville-ua the "script copy path on FTP server" contains a unique hash appended to the script name that we can use to differentiate instances. This should be incorporated in the metadata cleaner code.

currently in our cleaning code, we only retain "script_path_on_disk":
![screen shot 2018-07-17 at 9 22 38 am](https://user-images.githubusercontent.com/14166971/42823427-1b6fed5c-89a3-11e8-96d0-441dcacd6146.png)

As handled here:
https://github.com/terraref/terrautils/blob/master/terrautils/lemnatec.py#L397

We should also retain the FTP information for differentiation.

@craig-willis FYI.

**Comment by max-zilla** [comment]
PR for terrautils that includes this is here:
https://github.com/terraref/terrautils/pull/54

rulechecker will also need to be updated to account for this.

**Comment by max-zilla** [comment]
rulechecker also updated:
https://opensource.ncsa.illinois.edu/bitbucket/users/mburnet2/repos/terraref-rulechecker/pull-requests/4/overview

**Comment by max-zilla** [comment]
@craig-willis if you can approve the terrautils PR this can be deployed and closed.

**Comment by craig-willis** [comment]
Both look good to me.

**Comment by max-zilla** [comment]
OK. will merge and deploy.
