### ISSUE TITLE
Geometry coordinate system used in Clowder datapoints

### ISSUE THREAD

**Issue by Andrewzhzy** [terraref/computing-pipeline#484]
### Description 

I noticed the coordinate systems used in sensors and datapoints are different.
In sensors, they are something like: (-111.974925070941, 33.0752463177059, 0). I think it should be lat/lngs. But in datapoints, they are something like: (33.0752456246289, -68.0249705271937). I'm pretty confused with coordinate system that were used in datapoints metadata.

Thanks

**Comment by Andrewzhzy** [comment]
I'm using the clowder API to get scanners/cameras data from same plot in a season. Those coordinates are from the polygons. 
I got those coordinates by accessing the API: /api/geostreams/datapoints?stream_id=ID
For example I got the id from Season 4 Range 20 Column 9 is 21167
Then those coordinates was showed in geometry->coordinates
I think the ordering is not the major issue for me. 33.075245 for latitude is a reasonable number, but -68 seems too far away from the plots if it's the longitude.

**Comment by max-zilla** [comment]
I believe what we're seeing is the incorrect outputs of the old version of the 3d scanner’s sensorposition algorithm that wasn't properly being georeferenced (the coordinates are in the ocean east of Florida). The new extractor should fix this but we need to reprocess the metadata for the incorrect data. I see the coordinates as well - I will take a closer look to verify we have a corrected algorithm now.

**Comment by max-zilla** [comment]
Still tracking this down. The metadata on the objects themselves show correct coordinates, but the datapoints still have some incorrect coordinates and i havent figured out how these are being introduced or broken yet.

**Comment by max-zilla** [comment]
note to look into: -111 + -68 = -180. some weird offset in longitude?

**Comment by max-zilla** [comment]
@tcnichol a place to start looking at this might be: https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/clowder/browse/app/api/Geostreams.scala#413

**Comment by max-zilla** [comment]
Luigi indicated this may have been fixed in Clowder some time ago, and potentially may exist only before a certain date when our Clowder version was updated.

**Comment by max-zilla** [comment]
@tcnichol please test this on a local Clowder geostreams instance to see if this problem still exists in new Clowder version. if not we can create separate issue to repair or resubmit old data points.

**Comment by max-zilla** [comment]
@tcnichol updates on this?

**Comment by tcnichol** [comment]
No, apologies. Other issues came up and this one never got taken care of.

I will pause work on the other issues and look into this tomorrow.

**Comment by tcnichol** [comment]
I tested addDatapoints by creating a new sensor in a db and adding a datapoint. When I send in the coordinates 

(lon, lat, 0)

and then do a get on that datapoints, the coordinates are the same.

If there are datapoints in the db with bad coordinates, if I had a dump of that db I could get to work on coming up with a fix.

**Comment by max-zilla** [comment]
continuted in #581
