### ISSUE TITLE
Define extractor life cycle & 'definition of done' for contributors

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#486]
The team has requested a documentation of the requirements that will define the requirements for submitting an extractor.

Including

* Algorithm
* Documentation
* Tests
* working w/ Max/Todd and End User to define and evaluate the extractors

**Comment by dlebauer** [comment]
Draft is here: https://docs.google.com/document/d/1khEwLJL_em0PnX3-w08-ltoYriAA1_uqjORVxqbTKjA/edit#

**Comment by max-zilla** [comment]
Created PR here with formatting:
https://github.com/terraref/documentation/pull/194
