### ISSUE TITLE
NCSA storage outage August 15th

### ISSUE THREAD

**Issue by robkooper** [terraref/computing-pipeline#490]
The NCSA Storage Condo will undergo a maintenance window on August 15, 2018.  The maintenance will start at 0800 and should be completed by 1500.  

This will impact all of the services at NCSA since this is where the data is hosted. During this time no data will be available for download and/or computations. During this time we will have all services shutdown.

Services to shutdown:
- [x] clowder
- [x] extractors
- [x] workbench
- [x] globus uploader

**Comment by max-zilla** [comment]
back up.
