### ISSUE TITLE
Implement Pegasus workflow for bin2tif - canopy cover

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#494]
Based on the existing https://github.com/terraref/workflow-pilot/, implement the "real" version of the bin2tif pipeline given on implementation defined in https://github.com/terraref/computing-pipeline/issues/480

**Comment by max-zilla** [comment]
check for issue to create condor pool & test

**Comment by max-zilla** [comment]
this is complete, will create follow-up issue to test on Campus Cluster next.
