### ISSUE TITLE
Handling FLIR and hyperspectral changed positions

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#496]
Motion enabled and FLIR relocated today. Tomorrow: hyperspctral install in new locations.

Fixed metadata needs to handle dates.

**Comment by max-zilla** [comment]
https://github.com/terraref/sensor-metadata/pull/10/files

**Comment by max-zilla** [comment]
@NewcombMaria are the locations here: https://drive.google.com/drive/folders/1IF9JjUgWHA77Q5FkEf5ON-G49X35o9r5

the locations that went into effect before season 6? I don't recall thinking that these were moved at all last week so we're assuming the locations in Drive are the locations to apply starting 2018.

@tcnichol these are the other locations we want to update in your PR.

**Comment by max-zilla** [comment]
make the sensor JSON files into a list of objects, each has a "start_date": "xyz" field inside the object, iterate through and check:
- is the date before my target date? if yes, match_date = this one
- is the date newer than current match_date? if so, match_date = this one, otherwise keep previous match_date

**Comment by NewcombMaria** [comment]
@max-zilla the new positions in the fixed metadata files are for the camera relocations, work completed end of the day 2018-08-18 (between seasons 6 and 7). The new locations are for the following instruments:  FLIR, SWIR, VNIR, CropCircle, NDVI, PRI, and also StereoTop (RGB).  We will start scans for season7 this weekend (3d lasers) and after planting  (weather permitting), with cameras in new locations.

**Comment by tcnichol** [comment]
Okay, so I have changed FLIR, SWIR and VNIR. I just fixed the start dates in those, and I will fix the rest of the metadata this weekend. Max, that should all be done by Monday morning for you to review.

**Comment by max-zilla** [comment]
merged. followup in #502
