### ISSUE TITLE
Generate quality fieldmosaic from NRMAC results using lowsize images

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#499]
per suggestion from @Paheding and @SeanHartling we will create a new fieldmosaic product from the NRMAC outputs of fieldmosaic.

- generate a geotiff from NRMAC of with single value for all pixels @ low resolution
- track these geotiffs in rulechecker just like the left.tifs
- stitch together these to create "heat map" of field quality for each scan

**Comment by Paheding** [comment]
@max-zilla Thanks for working on this, let me know if you need any help. I assume the full-field image quality map would be very useful for users.

**Comment by Paheding** [comment]
@max-zilla Thanks, I hope the provided the algorithm flow helped.

**Comment by dlebauer** [comment]
for this and other qa/qc products (e.g. fullfield thumbnails) , would it be difficult to overlay the plot boundaries?

**Comment by max-zilla** [comment]
Created a PR to include in normal extractor:
https://github.com/terraref/quality-metrics/pull/5

And rulechecker:
https://opensource.ncsa.illinois.edu/bitbucket/users/mburnet2/repos/terraref-rulechecker/pull-requests/6/diff

**Comment by Paheding** [comment]
@max-zilla I have approved the request.

**Comment by max-zilla** [comment]
merged.
