### ISSUE TITLE
install and configure Clowder on Nebula OpenStack

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#5]
Create persistent VM that holds Clowder. This VM will contain all pieces, such as mongo, elasticsearch, rabbitmq and clowder. This will mount the ADS file system and use this to persist mongo, elasticsearch rabbitmq, and the blobs uploaded to clowder.

**Comment by dlebauer** [comment]
* how can multiple internal users write to disk? three separate processes, ea. must write to disk
  * NFS: easier if matching ids

Users:
* ubuntu user
* elastic search 
* mongo
