### ISSUE TITLE
Create large memory Kubernetes VM for soil_mask and hyperspectral

### ISSUE THREAD

**Issue by craig-willis** [terraref/computing-pipeline#500]
Create new VM in kubernetes:
* [x] 128Gb or 96Gb node
* [x] Labeled "terraref" and "large-memory"

**Comment by craig-willis** [comment]
Provisioned, but I need to get the IP added to the condo exports   141.142.209.213.

**Comment by craig-willis** [comment]
created  `terra-wb-node7` (n-rc1.xxlarge, 32VCPU, 96GB RAM)

Labeled as terraref and large-memory:
```
$ kubectl label node node7 large-memory=true
node "node7" labeled
$ kubectl label node node7 terraref=true
node "node7" labeled
```

Node is available for scheduling:
```
kubectl get nodes
NAME      STATUS    AGE
...
node7     Ready     4d
```

Will need to modify `nodeSelector` for soilmask:
```
      nodeSelector:
          terraref: "true"
          large-memory: "true"

```

**Comment by max-zilla** [comment]
@craig-willis can we close this? i can update soilmask nodeselector in #399
