### ISSUE TITLE
Check status of PS2 extractor

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#501]
https://github.com/terraref/extractors-multispectral/blob/master/psii2png/terra_psii2png.py

Inquiries into status of converting PSII data to GeoTIFF. Will look at PNG extractor and see if generation of geoTIFFs is easily done.

**Comment by max-zilla** [comment]
branch created: https://github.com/terraref/extractors-multispectral/tree/refresh-ps2-extractor

**Comment by max-zilla** [comment]
currently using Tino's Octave script

**Comment by NewcombMaria** [comment]
I talked with @MatthewHerritt to loop him into this github.

**Comment by max-zilla** [comment]
example output is here:
https://terraref.ncsa.illinois.edu/clowder/datasets/5bb503ba4f0ccf8861bc5916

GeoTIFF portion omitted for now.

**Comment by JeffWhiteAZ** [comment]
After a being requested to log into Clouder, I got a permission error when trying to view the link:
You are not authorized to access dataset "PSII PNGs - 2018-08-31__03-45-37-957"

**Comment by max-zilla** [comment]
@JeffWhiteAZ added you to the new Season 7 space. Haven't finished porting over all the users from last season's space yet. Sorry about that.

**Comment by JeffWhiteAZ** [comment]
Thanks. Can now see example output.

**Comment by MatthewHerritt** [comment]
@max-zilla I am having trouble signing in. Changed passwords twice still cannot log in.

**Comment by max-zilla** [comment]
@MatthewHerritt your Clowder account hadn't been activated yet - I just did so.

**Comment by MatthewHerritt** [comment]
@max-zilla I can see it now thanks
