### ISSUE TITLE
Storage expansion on condo

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#508]
Need to expand 1 PB amount hopefully.

**Comment by max-zilla** [comment]
@jdmaloney when you're back the three of us should have a discussion.

**Comment by max-zilla** [comment]
50 TB were added and the issue is resolved. 50 TB expansions continue until we have MOU in place.

**Comment by max-zilla** [comment]
also need a plan for archiving data e.g. for 2016 data and represent in Clowder so that users understand it may take a little time to retrieve data if its needed.

**Comment by max-zilla** [comment]
@jdmaloney @robkooper and I should sit down about this

**Comment by max-zilla** [comment]
Added 50 more TB yesterday.

**Comment by max-zilla** [comment]
@robkooper do we have the MOU done? can this be closed?

**Comment by robkooper** [comment]
nope, still moving slloooooowly

**Comment by max-zilla** [comment]
@robkooper was given OK that we are getting PB allocation but not sure if MOU is in place.

**Comment by max-zilla** [comment]
@robkooper mentioned MOU is now in place for storage. Can we close this?
