### ISSUE TITLE
Allow external people access to raw data in projects folder on Roger

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#51]
Right now, compressed zip files 1-2 GB each, 600 GB

* [x] Share data with TERRA users
* [x] write documentation file

Issues:

* What will be the authentication? a TERRA endpoint with group membership? Will they need Xsede,or Globus,account?
* now need NCSA two-factor
* convert endpoint to HTTP?
* does it make sense to set up an NCSA/TERRA share? Or setup with group and add users.

**Comment by dlebauer** [comment]
closing: now data can be accessed through globus
