### ISSUE TITLE
Push globus status into Influx database

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#511]
https://terramonitor.workbench.terraref.org/status

Every 30 seconds, hit this endpoint and insert into InfluxDB. We can do this in python and have some code snippets we can use.

**Comment by max-zilla** [comment]
Example influx code: https://github.com/terraref/terrautils/blob/master/terrautils/influx.py

1) use requests to GET the url: https://terramonitor.workbench.terraref.org/status

2) write_points to influx for each of the categories returned in JSON

**Comment by max-zilla** [comment]
to get time for database:

```
curr_time = datetime.datetime.now().strftime('%Y-%m-%dT%H:%M:%S')
completed_ts = int(parse(curr_time).strftime('%s'))*1000000000
```

**Comment by robkooper** [comment]
I use "time": str(datetime.datetime.utcnow()) (see https://opensource.ncsa.illinois.edu/bitbucket/snippets/04d9dae144f14925a64e49036ed38848)

**Comment by max-zilla** [comment]
Docker image built and deployed for next planting.
