### ISSUE TITLE
Deploy BRAPI

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#512]

**Comment by max-zilla** [comment]
https://github.com/terraref/brapi/pull/6

Once this is merged, work on creating Docker image and deploying on Kubernetes.

**Comment by max-zilla** [comment]
I will dockerize and deploy.

**Comment by robkooper** [comment]
Is already autobuilding https://hub.docker.com/r/terraref/brapi/
right now build fails

**Comment by robkooper** [comment]
build fixed, so this should be able to be deployed now.

**Comment by max-zilla** [comment]
https://brapi.workbench.terraref.org/brapi/v1/ui/ Done.
