### ISSUE TITLE
Monitor Gantry Cache Server - Implement Proposed Solution

### ISSUE THREAD

**Issue by sbrad77** [terraref/computing-pipeline#518]
Implement solution designed in ticket #517

**Comment by max-zilla** [comment]
@srstevens I talked with Rob, I think it would make sense for you to come to the dev meeting next Thursday if possible (@1pm in NCSA2000) to discuss some of these topics assigned to you and how to move forward.

**Comment by max-zilla** [comment]
They changed the IP address space in AZ so the alerts weren't coming in. We think @jdmaloney opened the right ports and fixed this.
