### ISSUE TITLE
TERRA Q12 Report - Due 10/24/2018

### ISSUE THREAD

**Issue by sbrad77** [terraref/computing-pipeline#523]
TERRA Q12 NCSA Update
https://docs.google.com/document/d/1f2EZaPvcQDJ0WckBCHUTd_l1VOutHmMFaCahnUOKdP0/edit

Notes so far included in document: 

David was wondering if M3.9 was ours - reply indicates:
the M3.9 milestone does fall under your team’s work.  She indicated Max Burnette and the NCSA group on Max’s team should be focused on making sure this gets done.
That milestone is:
M3.9 Establish data transfer and feature extraction pipeline to process raw data and generate derived data products
Minimum five phenotypes found within 10% accuracy of manual measurement of individual plants and individual plots (8/14/16)

Per David;  I think it would be helpful to summarize any new progress made during the quarter (July - Sept). e.g. fixing laser scanner and producing heat maps, deploying the psii pipeline, image quality map, etc.

Shannon: make sure start dates / end dates if appropriate are correct - the Base Start/Base End dates seem way off - but I don’t think those are ours to change

**Comment by dlebauer** [comment]
Issue moved to [terraref/admin #77](https://github.com/terraref/admin/issues/77) via [**ZenHub**](https://www.zenhub.com/)
