### ISSUE TITLE
Deploy rgb plant mask & rgb image enhancement extractor

### ISSUE THREAD

**Issue by ZongyangLi** [terraref/computing-pipeline#532]
Codes had uploaded here:
https://github.com/terraref/extractors-stereo-rgb/tree/rgb-mask-%26-GAN-enhancement/canopy-cover-enhancement

Documentation:
https://docs.google.com/document/d/1LRAtjwzyaJ5KzBiJ-4yaIorvLL4-g31OUUQNveeVHz4/edit?usp=sharing

**Comment by max-zilla** [comment]
This extractor is done, we just need to get the documentation from @ZongyangLi 's google doc into the README in github,

**Comment by max-zilla** [comment]
https://github.com/terraref/extractors-stereo-rgb/blob/master/canopy-cover-enhancement/readme.md

**Comment by max-zilla** [comment]
deployed.
