### ISSUE TITLE
Update flir, stereo, laser3d, hyperspectral extractors

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#533]

**Comment by max-zilla** [comment]
fullfield extractor
- split out thumbnail vs full version

prioritize hyperspectral
- clip to plot level
- get pushed into BETYdb
- accessing from THREDDs server

**Comment by max-zilla** [comment]
https://github.com/terraref/extractors-multispectral/pull/32/files
https://github.com/terraref/extractors-stereo-rgb/compare/update-fieldmosaic-2018

**Comment by tcnichol** [comment]
I think that the bin2tif is ready for review. Branch is issue-533 in extractors-stereo-rgb.

**Comment by tcnichol** [comment]
laser3d is on the list but I am not a member of that repository.

**Comment by max-zilla** [comment]
All 4 of these have been updated.
