### ISSUE TITLE
Plot-clipping extractor

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#535]

**Comment by max-zilla** [comment]
https://github.com/terraref/extractors-multispectral/pull/32/files#diff-a186da4a4378b6d0a96e0c8abd3bc92bR187 

new extractor that triggers on image/tiff files. file-level extractor. take the geotiff, get the list of plots active at that time, iterate over them and clip.

```
CHECK FILE pyclowder2 resource
{
	'name': '2016-08-29_22-25-45_environmentlogger.nc', 
	'intermediate_id': '584ebf6f4568efa567f5e889', 
	'parent_dataset_id': '57a39117e4b08fc70df4390a', 
	'file_ext': '.nc', 
	'type': 'file', 
	'id': '584ebf6f4568efa567f5e889'
}

PROCESS FILE pyclowder2 resource
{
	'intermediate_id': '590805034f0c20f1bf0cbb20', 
	'parent': {
		'type': 'dataset', 
		'id': '5907ce204f0c20f1bf08b876'
	}, 
	'local_paths': ['/home/sites/2017-05-01/2017-4-f5401dc98213_.nc'], 
	'file_ext': '.nc', 
	'type': 'file', 
	'id': '590805034f0c20f1bf0cbb20', 
	'name': 'e9673701-4a6b-4b6d-b334-f5401dc98213_.nc'
}
```

**Comment by max-zilla** [comment]
I think this extractor for now can go in:
https://github.com/terraref/computing-pipeline/tree/master/extractors

**Comment by tcnichol** [comment]
starting work on faster way to check if lat/lon within bounds.

**Comment by max-zilla** [comment]
@dlebauer suggests: instead of just storing centroid we store a list of all plots that intersect the dataset, then we can use that as reference for extractors like this instead of looking up each time.

**Comment by max-zilla** [comment]
@tcnichol I would start by adding a function to terrautils which takes GeoJSON bounding box like this:
```
bounding_box: {
  type: Polygon,
   coordinates: [
[33.076169809142975 ,-111.97493443261804],
[33.076169809142975, -111.97491888113808],
[33.076152080980165, -111.97491888113808],
[33.076152080980165, -111.97493443261804
]
}
```

**Comment by tcnichol** [comment]
created a new branch and pushed to terrautils

**Comment by max-zilla** [comment]
let's also update this for LAS files. Download an LAS file from 2018:
https://terraref.ncsa.illinois.edu/clowder/datasets/5b1669f34f0c64f9298e916a

download the LAS file, use the spatial metadata bounding box to create a synthetic plot that should overlap it and see if we can use PDAL or something to clip it. 

https://pdal.io/workshop/exercises/analysis/clipping/clipping.html
https://pdal.io/tutorial/clipping/index.html

https://github.com/terraref/laser3d/blob/master/terraref/laser3d/laser3d.py#L147
Here is an example elsewhere that uses PDAL pipeline. 

This will be a hackathon to figure out - we can run Docker image w/ PDAL (e.g. the ply2las image https://github.com/terraref/extractors-3dscanner/blob/master/ply2las/Dockerfile) and mount the LAS file into it then see if we can use PDAL to clip to a bounding box. Then we can implement in python.

**Comment by max-zilla** [comment]
stub created here:
https://github.com/terraref/terrautils/blob/reprocessing_2018/terrautils/gdal.py#L51

**Comment by max-zilla** [comment]
@tcnichol i made some nice headway on this yesterday & this morning. the easiest path is to use this:
https://pdal.io/stages/filters.crop.html

Basic steps will be:
1. get plot definition in lat/lon bounding box
2. convert bounding box to UTM coordinates (working on this part now)
3. write the UTM bounding box to a DTM file for PDAL
4. use crop filter to export new cropped LAS file

this avoids the need to write our coordinates into a VRT file or whatever. quick code sample:
```
# for sample, use LASPY to see min/max coordinates of this point cloud in UTM 12N coords
fi = "jul17.las"
w = laspy.base.Reader(inp, 'r')
w.get_header().min
# [408988.28125, 3660068.5, 0.381856]
w.get_header().max
# [409015.96875, 3660070.0, 3.509273]

# divide X and Y in half to define a quarter of the scan:
utm_bounds = "([408988, 409000],[3660068, 3660069])"

# write DTM file and use to clip
pdal_dtm = "pdal_test.dtm"
with open(pdal_dtm, 'w') as dtm:
    dtm.write("""{
        "pipeline": [
            "%s",
            {
                "type": "filters.crop",
                "bounds": "%s"
            },
            {
                "type": "writers.las",
                "filename": "clipped.las"
            }
        ]
    }""" % (fi, utm_bounds))

cmd = 'pdal pipeline %s' % pdal_dtm
subprocess.call([cmd], shell=True)
```
Result is "clipped.las" plot subset. Took ~25 seconds to clip.

Just need a utility function to go from the latlon to UTM so it's compatible. Testing this now:
```
def latlon_to_mac_utm(lon, lat):
    """This is used to translate latlon coordinates e.g. an experimental plot
    to UTM 12N coordinate system.
    """
    return utm.from_latlon(lat, lon)
```

idea is we feed plot bounds from BETY into this function. but yeah, we're close.

**Comment by max-zilla** [comment]
deployed and running happily over the holidays.
