### ISSUE TITLE
Points lost in 3d laser scanner

### ISSUE THREAD

**Issue by ZongyangLi** [terraref/computing-pipeline#539]
When I tried to debug my panicle detection extractor, I noticed that in some laser data, points might be missing.

For example, here is a figure to show the median value of time-series panicle volume in plot # 1592(1728 in total):
![vol_median_1592](https://user-images.githubusercontent.com/20230686/48737110-c85e7480-ec12-11e8-98de-c8ee38813a32.png)
It is wired for the 'up and down' in the first 10 days. So I extracted all my debugging output relate to plot # 1592, the following images show different between 'low-value' data and 'high-value' data:
![merged](https://user-images.githubusercontent.com/20230686/48737346-618d8b00-ec13-11e8-8e5b-99396059ef59.jpg)
<img width="1400" alt="screen shot 2018-11-19 at 10 13 43 am" src="https://user-images.githubusercontent.com/20230686/48737365-6baf8980-ec13-11e8-9a69-ac3ee2eef0ef.png">
The first image's time stamp is '2017-06-23__18-29-46-441' and the second is '2017-06-25__04-47-59-166' 
I am pretty sure that those 'up and down' plots occur in those dark area.

So I am guessing we should:
(a) Find out why the low reflected happened.
(b) Whether we can fix it.
(c) If not, how to find the way of classifying 'good or bad' data.
(d) Whether this happened in all data, for example in some day 70% points loses, in some other day only 20% points loses but we haven't realized.

@jdemieville-ua please find the time stamp you need here.

**Comment by jdemieville-ua** [comment]
@ZongyangLi : It looks like 2017-06-23__18-29-46-441 was part of the Stomatal Regulation campaign where the box was raised higher than typical. The FLIR was the primary instrument for this scan. 3D laser was on this scan by special request.

On 2017-06-23, it was running approximately 0.5m higher than on 2017-06-25. The earlier scan was not optimized for 3D lasers. Generally, the scans optimal for 3D laser have "3D" somewhere in the script name. We assume that the dark areas are where shorter plants may have been missed by the lasers.

**Comment by ZongyangLi** [comment]
@jdemieville-ua Thanks for the information.

You are right all bad data comes from 7 am to 19 pm, I will throw out all of them to see if I would have a better figure.

**Comment by max-zilla** [comment]
@ZongyangLi can this be closed?
