### ISSUE TITLE
Insert RIL g2p data from Steve K into reference database

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#54]
- [ ] Rob Alba to confirm w/ Steve K
  - enter meta-data (site, treatment, genotypes) into BETYdb
  - upload raw phenotype data
- [ ] enter with access_level = 1 until publication

**Comment by rachelshekar** [comment]
@dlebauer can this be deleted?

**Comment by rachelshekar** [comment]
@nshakoor - do you have these data from Steve K?  should this be part of the November release?

**Comment by rachelshekar** [comment]
@nshakoor following up on this

**Comment by nshakoor** [comment]
I'll follow up with Steve, but I do not think there is data he is willing
to share yet as part of the reference dataset.

**Comment by rachelshekar** [comment]
@nshakoor - what is the status of this?  Will Steve be willing to share data?  If so, when?

**Comment by rachelshekar** [comment]
Steve Kresovich has genomic and phenotypic data for the BAP.  This can be transferred as hapmap file and gbs data.  We have sequencing data for this now too.  @nshakoor will follow up with this.

**Comment by rachelshekar** [comment]
@nshakoor - please update
