### ISSUE TITLE
las file to height distribution

### ISSUE THREAD

**Issue by ZongyangLi** [terraref/computing-pipeline#542]
Initial script for las file to height distribution can be found here:

https://github.com/terraref/extractors-3dscanner/blob/las-to-height-distribution/plant_height/las_to_height.py

This is an intermediate data product relate to plant height. We plan to use this data product to estimate ground level in each plot, then estimates plant height.

To be done:
1. When clipped las file is available, generate plot level height distribution as Level 2 data.
2. Analysis on early stage field to estimate ground level in each plot.
3. Compare with field measurement to create fitting function, finally get height estimation for each plot each day.

Previous discussion also need to be considered: #363

**Comment by max-zilla** [comment]
created PR here: https://github.com/terraref/extractors-3dscanner/pull/29

**Comment by max-zilla** [comment]
updated method, deployed and running happily over the holidays.
