### ISSUE TITLE
EnvironmentLogger should create one file per day

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#543]
example dataset that will be passed to extractor: https://terraref.ncsa.illinois.edu/clowder/datasets/5b88fc7e4f0c9925916fe44d

Update environment logger to concatenate the JSON files into one chronological file before converting to .nc. 

If dataset has 23+ files, process. If it only has 23 and the output exists, don't overwrite. If there's 24 and there's an output, overwrite it.

https://github.com/terraref/extractors-environmental/blob/master/envlog2netcdf/terra_envlog2netcdf.py

**Comment by max-zilla** [comment]
When we run this for reprocessing, we're going to purge geostreams and start from scratch. Therefore it's harmless to run this on Kubernetes as a test case because any bad data it generates will be purged.

**Comment by dlebauer** [comment]
Another option is to concatenate the .nc files using something along the lines of

```sh
ncrcat 198[0123456789].nc 1980s.nc
```

which concatenates the files 1981.nc, 1982.nc, ... 1989.nc into a single file called 1980s.nc (documentation: http://nco.sourceforge.net/nco.html#ncrcat-netCDF-Record-Concatenator)

**Comment by max-zilla** [comment]
PR: https://github.com/terraref/extractors-environmental/pull/30

**Comment by max-zilla** [comment]
merged the PR.
