### ISSUE TITLE
Rstudio no longer working in workbench

### ISSUE THREAD

**Issue by robkooper** [terraref/computing-pipeline#545]
There are reports of rstudio no longer working in the workbench.

additional details from dlebauer:
* The original issue, which I can reconfirm after the image is re-built, was that the user is getting a 'can not connect to service' error.
* These days, it happens to most users
* Craig pointed out [on private Slack channel](https://terra-ref.slack.com/archives/G7Q3SQGC9/p1539980283000100) that it may be related to
  *  https://support.rstudio.com/hc/en-us/community/posts/200637798-RStudio-Server-RStudio-Initialization-Error-Unable-to-connect-to-service
  * and / or file ownership/permissions 'since I see different UID/GIDs own files in that folder for you'

**Comment by robkooper** [comment]
A potential problem discovered by the NDS team is that an update was made to the docker image by @dlebauer (https://github.com/terraref/toolserver-dockerfiles/commit/aa31ca7be689a2c3aaeaaa43d53dda51e4437473) which increased the version number to 3.5.1. It looks like this now requires a different password than rstudio.

**Comment by dlebauer** [comment]
That update is independent of the original issue, which has been persisting for well over a year. But I've just reverted the change in https://github.com/terraref/toolserver-dockerfiles/commit/a52fd599205a94304a28255286d4d10440e2fb27 so that we don't confound two issues.

**Comment by robkooper** [comment]
Either way we should make sure we set username and password for Rstudio so we don't run into this problem in the future.

Also Mike/Craig believes this might be an issue with permissions which is fixed in the newer version.

**Comment by bodom0015** [comment]
From the original report, it was not clear what exactly was the problematic behavior - "not working" has many definitions that vary from person to person. Providing clear reproducible steps to recreate the issue is definitely a helpful way to ask for help.

This feels like invalid/leftover state to me... In the linked R forum post (which I had not seen before), one user states that their version of this issue stemmed from an invalid or missing `$HOME/.rstudio` directory.

The error that I am seeing in the console seems to indicate a version change of R took place, which may have put things into an invalid state:
```r
> library(traits)
> knitr::opts_chunk$set(echo = FALSE, cache = TRUE)
> library(ggplot2)
> library(ggthemes)
> library(GGally)
> theme_set(theme_bw())
> library(dplyr)
> library(httr)
> .libPaths('~/R/library')
> 
> options(betydb_key = readLines('~/.betykey_public', warn = FALSE),
+         betydb_url = "https://terraref.ncsa.illinois.edu/bety-test/",
+         betydb_api_version = 'beta')
Error in file(con, "r") : cannot open the connection
23 May 2018 21:38:27 [rsession-rstudio] ERROR session hadabend; LOGGED FROM: rstudio::core::Error {anonymous}::rInit(const rstudio::r::session::RInitInfo&) /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:563
R version change [3.4.0 -> 3.4.2] detected when restoring session; search path not restored
09 Aug 2018 15:06:14 [rsession-rstudio] ERROR session hadabend; LOGGED FROM: rstudio::core::Error {anonymous}::rInit(const rstudio::r::session::RInitInfo&) /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:563

09 Aug 2018 15:16:07 [rsession-rstudio] ERROR r error 4 (R code execution error) [errormsg=]; OCCURRED AT: rstudio::core::Error rstudio::r::exec::executeSafely(rstudio_boost::function<void()>) /home/ubuntu/rstudio/src/cpp/r/RExec.cpp:212; LOGGED FROM: void rstudio::session::{anonymous}::processEvents() /home/ubuntu/rstudio/src/cpp/session/SessionHttpMethods.cpp:91
> 
> clear
Error: object 'clear' not found
[2018-10-19 20:18:41] [error] handle_read_frame error: websocketpp.transport:7 (End of File)
[2018-10-19 20:18:41] [fatal] handle_write_frame error: websocketpp.transport:10 (A transport action was requested after shutdown)
[2018-10-19 21:38:26] [error] handle_read_frame error: websocketpp.transport:7 (End of File)
17 Dec 2018 17:34:53 [rsession-rstudio] ERROR session hadabend; LOGGED FROM: rstudio::core::Error {anonymous}::rInit(const rstudio::r::session::RInitInfo&) /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:563
R version change [ -> 3.4.2] detected when restoring session; search path not restored
```

The line reading `R version change [3.4.0 -> 3.4.2] detected when restoring session; search path not restored` stood out to me and, although I don't understand R or what most of this output is supposed to be doing, I tried mapping in a empty directory in for `/home/rstudio/.rstudio`.

Sure enough after starting up RStudio, showed no errors in the console after logging in. But without a clear reproducible test case, I cannot be sure that this has actually done anything to fix the problem.

**Comment by dlebauer** [comment]
@bodom0015 I tried to clarify rob's original report in the post above. It is the 'cannot connect to service' issue that is concerning. I have not seen the R version change errors in the past, and the terra rstudio has been building off of the rocker/geospatial:3.4.2 for almost a year. Currently I can't reproduce the error since I am getting 502 errors.

And failure to launch errors seems to happen intermittently on other applications as well. For example, I received this in an email last Friday: 

> The file manager definitely errored out.  I think the Jupyter notebook opened a new tab but the “wheel” just spun. Just now, Rstudio actually open up a tab and let me log in with rstudio/rstudio but it wasn’t able to connect to service.

**Comment by dlebauer** [comment]
@bodom0015 also I just tried to run the code you sent and I got the 'cannot open connection error' (which is expected if you don't have a `~/.betykey_public file` but not the error related to the version of R (and I haven't seen that one before). Do you by chance have non-default debugging options set?

**Comment by craig-willis** [comment]
Thanks to @bodom0015 for looking into this.    I've also confirmed that I can start Rstudio under my account without error this morning.   @dlebauer  -- are you seeing this specific error with your instance of Rstudio?  

As noted above, there are multiple issues reported here that need to be distinguished:

1. Rstudio "Unable to connect to service" errors
2. 502 errors
3. File manager timeout/Jupyter spinning

The "Unable to connect to service" is a generic error from Rstudio with multiple underlying causes.  The most recent cause that I reported to @dlebauer was a permissions/ownership problem on the `.rstudio` directory.  I've confirmed this morning that ownership looks OK for all current users. It would be helpful to have specific usernames to confirm whether this is indeed the cause and if this is the specific error they are experiencing. As noted in the previous comment, this can also occur when the Rstudio client times out connecting to the running service -- which has numerous causes.  We should also not conflate this specific Rstudio errors with other WB errors, if possible.

As noted by @bodom0015, the remaining errors are related to running on Nebula.  As with other Terra services, WB requires constant monitoring and intervention.  All Workbench services run on node1 and node2.  Common problems include node failures, filesystem failures, NFS failures, updates to images requiring pulls, etc.  If the nodes are in a `NotReady` state, then users will likely experience problems accessing WB services. 

Just to put this in perspective -- this morning I noticed the jupyter images were not present on node1 and node2 and the basic `docker pull` has taken > 1 hour to complete on both nodes.  One solution we have for the extractor images is to add a cron task that pulls the images periodically.  I thought I had put this in place on the WB nodes, but apparently it's only on the extractor nodes:

* /etc/systemd/system/cache-images.timer 
* /etc/systemd/system/cache-images.service

This would ensure that the images were pulled outside of Kubernetes to overcome the timeout limitation.

The system is overdue for a Kubernetes upgrade, which will require complete re-provisioning and reconfiguration. This might improve things. I don't know who would have cycles to take this on.

**Comment by craig-willis** [comment]
I've enabled the cache-images timer on node1 and node 2.  Ideally this will reduce the number of problems related to docker pull.

**Comment by phloz** [comment]
I still receive the attached when navigating to Rstudio from Analysis Workbench Applications

—
Philip Ozersky
Bioinformatics & Database Developer
Todd C. Mockler Lab
(314) 587-1697
pozersky@danforthcenter.org

[cid:4341330D-33AF-46FF-ADEE-DA71A045B276]

**Comment by craig-willis** [comment]
Thank you @phloz. And that is indeed the permissions problem. 

```
18 Dec 2018 18:52:50 [rsession-rstudio] ERROR system error 13 (Permission denied) [path=/home/rstudio/.rstudio, target-dir=]; OCCURRED AT: rstudio::core::Error rstudio::core::FilePath::createDirectory(const string&) const /home/ubuntu/rstudio/src/cpp/core/FilePath.cpp:846; LOGGED FROM: int main(int, char* const*) /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:1689
```

I believe I've fixed your account and I now understand how to repeat this. Let me know if otherwise.

**Comment by max-zilla** [comment]
it's possible that unable to connect instance was killed when node 1/2 were rebooted in mid December after some issues with the kubelet service.

**Comment by dlebauer** [comment]
Just ran into the same 'unable to connect' error (https://github.com/terraref/computing-pipeline/issues/545#issuecomment-451250288) again trying to launch a brand new Rstudio application.

**Comment by craig-willis** [comment]
This is not the same problem as described above (permissions).  Rstudio reports the "unable to connect" for a variety of reasons. 

Looking at the logs, it appears to be exiting because of the password issue discussed above:
```
$ kubectl get pods -n dlebauer
NAME                    READY     STATUS    RESTARTS   AGE
s89gru-rstudio-zpt2d    1/1       Running   0          7d
sjch1p-rstudio-p5f2l    1/1       Running   0          1h
sn9prs-pgstudio-r0b2l   1/1       Running   0          7d
spe9x9-cloudcmd-g56qs   1/1       Running   0          16m

$ kubectl logs -n dlebauer sjch1p-rstudio-p5f2l
[fix-attrs.d] applying owners & permissions fixes...
[fix-attrs.d] 00-runscripts: applying...
[fix-attrs.d] 00-runscripts: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] add: executing...
Nothing additional to add
[cont-init.d] add: exited 0.
[cont-init.d] userconf: executing...

ERROR: You must set a unique PASSWORD (not 'rstudio') first! e.g. run with:
docker run -e PASSWORD=<YOUR_PASS> -p 8787:8787 rocker/rstudio

[cont-init.d] userconf: exited 1.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

You may be able to workaround this by adding a PASSWORD environment variable your instance. Otherwise, this will need to be fixed in  https://github.com/terraref/workbench-catalog/blob/master/terraref/rstudio.json.

<img width="1175" alt="screen shot 2019-01-10 at 4 52 34 pm" src="https://user-images.githubusercontent.com/4334350/51002249-4d218c80-14f8-11e9-994e-72f768afd57c.png">

This should probably be tracked as a separate issue.

**Comment by dlebauer** [comment]
We've opened two new issues to resolve the remaining issues: directories not appearing in /data (#548) and add PASSWORD envt var (#551)

**Comment by craig-willis** [comment]
This issue should probably remain open until an updated WB apiserver image has been tested and deployed.  We have a fix in the works:

https://github.com/nds-org/ndslabs/compare/1.0.12...1.0.12-hotfix

This will need to be deployed to terra-ref in two steps:
* Update the image to `ndslabs/apiserver:1.0.12-hotfix`
* `chown -R 1000:100 /var/glfs/global/` on the WB nodes

The permissions problem currently only effects newly registered users. So after this is deployed, a test case would be to:
* Register a new account
* Start Rstudio
* Create files via Rstudio
* Confirm that /var/glfs/global/user directory and contents are owned by 1000:100

**Comment by max-zilla** [comment]
@craig-willis is this still in the works? we are waiting to close this until you push the new WB image but obviously you aren't on TERRA anymore and we arent tracking NDSLabs updates...

**Comment by max-zilla** [comment]
after talking with Rob, we are going to close unless you feel it should be reopened.
