### ISSUE TITLE
Data publication next steps

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#547]
With Craig off the project, we need to determine how to move the data publication forward.
- Can we start this before reprocessing is totally complete?
- What are we publishing? A manifest of the data and how to access it? 

We need sample datasets as well, possibly for inclusion in publication but also to support things like Phenome '19 meeting and DARPA effort.

We also need to get rough idea of who will be responsible for what aspects of this. We should schedule a dedicated meeting early next week, possibly with @craig-willis to do knowledge handoff (or point us in right direction of any existing writeup) so between @tcnichol and myself we can figure out how to proceed.

**Comment by dlebauer** [comment]
Regarding where are we and next steps ... I've put this under the overarching epic https://github.com/terraref/reference-data/issues/223 

I think that the next step after finishing the current reprocessing is to generate the data package for publication. Then it will be possible to begin writing up the data paper. During writing / before publication it will be necessary to update field and computational protocols.

**Comment by max-zilla** [comment]
Closing this issue and prioritizing 223 in March sprint.
