### ISSUE TITLE
~/data/terraref/sites directories on workbench appear empty

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#548]
When I log into an Rstudio instance on Workbench, all of the data should be mounted to the ~/data directory. 

However, when I use the R studio built-in GUI file browser

![image](https://user-images.githubusercontent.com/464871/51001444-58bb8600-14ed-11e9-8d42-332cfd44cea2.png)
 
or terminal

![image](https://user-images.githubusercontent.com/464871/51001432-4f321e00-14ed-11e9-9898-b9e499126bf2.png)

 these directories appear empty. Perhaps a permissions issue?

**Comment by dlebauer** [comment]
the data are available now; can't reproduce; closing issue

**Comment by tcnichol** [comment]
I signed onto one of the workbench nodes and am seeing files inside Level_1. For the other issue, Max is out today but I will look into it, but might need his help.

**Comment by KristinaRiemer** [comment]
I now have a data folder. The only thing that I've done is change the RStudio login password, as per [this comment](https://github.com/terraref/computing-pipeline/issues/545#issuecomment-453288904), and I didn't notice if the folder started to show up right after that.

**Comment by craig-willis** [comment]
There are three different problems reported here.

* Data missing from `/data` is typically a problem with the underlying NFS mounts.  An admin can simply `df -h` on the WB nodes to confirm the mounts are present or not.  If you have the `~/data` symlink  but `/data` is empty, this is likely the case.
* The symlink to `/data` (`~/data`) and the clone of the `tutorials` folder are built into the TERRA RStudio image definition (https://github.com/terraref/toolserver-dockerfiles/blob/master/rstudio/Dockerfile#L59-L61) and created during image startup.  It's not clear from the above description why these would be missing. The account associated with the instance above appears to have both `~/data` and `~/tutorials`, but maybe that was manually resolved?
* The `kitematic` directory is [created by the base RStudio image](https://github.com/rocker-org/rocker-versioned/issues/109#issuecomment-437612168). I'm not sure how to remove this.

**Comment by max-zilla** [comment]
Can this be closed?

**Comment by dlebauer** [comment]
yes, this has been resolved
