### ISSUE TITLE
Finish processing Season 6 data 

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#553]
- improve identification of unsuitable input data w/in the extractor
- perhaps use historical time series to predict and filter what should be observed

**Comment by dlebauer** [comment]
@ZongyangLi Can you help QA/QC the canopy cover and height extractor output? eg these data look suspicious:
![418a1e0b-1786-4c9a-9f78-507fd4757ba2](https://user-images.githubusercontent.com/464871/52421921-40ba3080-2ab2-11e9-8732-4f430ee026d2.jpeg)

**Comment by ZongyangLi** [comment]
Is this a full field histogram, so the data means highest point from LAS?

**Comment by max-zilla** [comment]
@ZongyangLi the extractor operates on the plot-level LAS data, but it takes the highest point from each plot. So somewhere in the field is reported 500cm points. There had been discussion of 90th percentile or similar that could resolve this if these are outliers. We might be able to query bety to find these outlier points and go back to the LAS file where they came from.

**Comment by ZongyangLi** [comment]
Some opinion about suspicious:
1. Ladder from May to Jun may cause by gantry position, the laser scanner reach the highest point it can detected. The Gantry height move on Jun 1/6/11/14, from height 1.615/1.915/2.065/2.215/2.815, which fits the date and ladder distance.

2. It is hard to tell those 500cm outliers. I check some laser data on 07-04/07-05, there are some strange missing points in raw_data file during the scan. I am not sure what may causes by these irregular missing points to ply or LAS. We really need those LAS file to see what causes these outliers.

**Comment by max-zilla** [comment]
Removing Zongyang, the canopycover fix should be separate issue.
