### ISSUE TITLE
Flag erroneous datasets

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#557]
e.g. Flir S4 datasets - should not go beyond raw data. There's an existing issue for this - track it down.

**Comment by NewcombMaria** [comment]
@max-zilla See https://github.com/terraref/reference-data/issues/218 (Mechanism for identifying data errors), and specifically for the FLIR summer 2017, see the later comments in reference-data 182: 
 https://github.com/terraref/reference-data/issues/182 (Review FLIR fullfield extractor and output)

**Comment by max-zilla** [comment]
DES uses tags to do this. however this is often done by users and not systems, and there's no vocabulary. if we use metadata we can have a vocab/description for WHY the data is erroneous.
