### ISSUE TITLE
Improving Image quality from illumination, contrast, noise, and color aspects

### ISSUE THREAD

**Issue by Paheding** [terraref/computing-pipeline#562]
**Title**:  Improving Image quality from illumination, contrast, noise, and color aspects. 

### Description 
This extractor is designed to improve the RGB image (Gantry or UAS imaging systems) quality in term of visualization from four different aspects: illumination, contrast, noise, and color. 

_Input_    : RGB or grayscale image
_Output_ : Enhanced image

### Suggestion
This extractor can be combined with RGB image quality extractor. Whenever the image quality score is lower the expected value, this image enhancement algorithm can be triggered and apply to the raw input image.

### Workflow
![image](https://user-images.githubusercontent.com/24866799/53750939-bb3b5d80-3e70-11e9-879a-581fa30e10c7.png)

### Details

Due to the limitations of UAS (unmanned aerial system) or other imaging devices, image enhancement has become a necessary process for improving the visual appearance images. Although a great amount of effort has been focused on improving image quality from different aspects, the major obstacles are from computational or operational efficiency and complexity, such as manually adjusting the associated camera settings or algorithmic parameters that account for various image luminance or signal-to-noise ratio. To overcome these drawbacks, we propose a new adaptive yet highly efficient image enhancement method for enhancing the quality of digital color images in terms of illumination, contrast, color and signal-to-noise ratio. The proposed method is derived from a trigonometric transformation, high frequency boosting functions, wavelet transform, and a color restoration process whose characteristics adaptively change with respect to the variation of the image luminance, contrast, color and noise level.

### Completion Criteria 

FOR A FEATURE REQUEST
* [v] create algorithm
* [v] write test
* [ ] add to pipeline

`Related publication`:
_Sidike, P., Sagan, V., et al. (2018). Adaptive trigonometric transformation function with image contrast and color enhancement: Application to unmanned aerial system imagery. IEEE Geoscience and Remote Sensing Letters, 15(3), 404-408._

**Comment by max-zilla** [comment]
I sent email to @ZongyangLi and @Paheding with some questions:

How similar is this to GAN enhancement code Zongyang has worked on that was part of the work that led to soil mask extractor?
 
Will this affect the RGB soil mask extractor at all? (I doubt it)
 
Patrick proposed running this only on RGB images below a certain quality threshold – do we know what that threshold should be?

Should this be done before other steps?
- Field mosaic of RGB
- Soil removal & field mosaic of soil-removed image

**Comment by Paheding** [comment]
@max-zilla Good questions. The proposed image enhancement was designed to improve RGB or grayscale image in terms of illumination, noise, and contrast. 

- To save more storage space, I propose to apply this extractor only on the images that below the threshold (empirically set to 15-may not optimal) indicated by the image quality extractor. 

- If we want to retain radiometric values in field mosaic, we shall not apply this one before mosaic.  This extractor may be applied before the soil removal method if the image quality is insufficient. 

- This algorithm can be helpful for extracting plant biophysical parameters from RGB images such as biomass, plant height, canopy cover, etc.

**Comment by max-zilla** [comment]
Zongyang recommends keeping these enhancement methods separate for now.

**Comment by max-zilla** [comment]
This extractor is complete and has been run on a small number of test datasets. Plan to try to run on the sample RGB data later this week.

https://terraref.ncsa.illinois.edu/clowder/datasets/5c5ad0a64f0c7047afc4ce79 - 2018-06-04__09-22-54-963
https://terraref.ncsa.illinois.edu/clowder/datasets/5b1ca2564f0c64f929c68bfa - 2018-06-08__10-14-12-277
