### ISSUE TITLE
TERRA Q14 report - Due April 25, 2019

### ISSUE THREAD

**Issue by sbrad77** [terraref/computing-pipeline#568]
Hello everyone,

It’s Q14 report time! I’ve created individual templates for you to use so that you can more easily identify what parts to complete.  Please locate your template in the attachments.  This report includes project activities that occurred from January 1, 2019 – March 31, 2019. 

Due Date: COB on April 25, 2019.  Please make sure to submit your report on time.

General Notes:
1) Please make sure to fill out and include any information that pertains to section 2 “Other miscellaneous updates”.  This includes sending any publication or other output and follow-on funding.
2) Please adhere to the 499 character limitation on the milestone/deliverable summaries.  These are uploaded onto an on-line system that automatically cuts off the text at 499 characters.  You can use the general scientific narrative section below each table to discuss any milestone/deliverable in greater detail (in addition to general task activities).  There is no character limitation here.

Best,
Cathy
[https://app.zenhub.com/files/41696258/a3ad3654-b198-4e18-a347-753296438a65/download](https://app.zenhub.com/files/41696258/a3ad3654-b198-4e18-a347-753296438a65/download)

**Comment by sbrad77** [comment]
Shared Google Doc made for collaboration
https://docs.google.com/document/d/1KR3l2iJHy5yLT7kWXe5_IXL9l3ldjyusQYNJ5MWviN8/edit

Please review and prepare submission

**Comment by max-zilla** [comment]
can this be closed? i believe it was submitted

**Comment by sbrad77** [comment]
Yes - submitted by David and Shannon followed up with a physical Word copy
