### ISSUE TITLE
Use swagger.yaml to define advanced search API endpoints

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#578]
After discussions with AZ website team, we want to move onto next phase of search API (found at https://search-api.workbench.terraref.org/seasons):

- use swagger.yaml to define parameters and return values for each endpoint
- implement a hard-coded sample JSON document for each in short term

As discussed, idea to start:
- get list of seasons - return each name & date range
- given a season, return a list of valid plot names 

this could potentially be handled by a standard 'filter' endpoint that handles interactions between season, plot, (eventually) experiment and germplasm - you pick one of those, you get back a subset of the others that apply, and so on. but we start simple.

**Comment by max-zilla** [comment]
treatment, experiment, cultivar

**Comment by tcnichol** [comment]
I created a branch for this and a pull request. It is : 

https://github.com/terraref/search-api/pull/3

I'm going to label it Work In Progress as it likely needs some changes.

**Comment by max-zilla** [comment]
deployed on dev: https://search-api-dev.workbench.terraref.org/search-api/v1/ui/
