### ISSUE TITLE
TERRA Q15 Report Due July 25 2019

### ISSUE THREAD

**Issue by sbrad77** [terraref/computing-pipeline#593]
Hello everyone,

It’s Q15 report time! Please locate your individual template in the attachments.  This report includes project activities that occurred from April 1, 2019 – June 30, 2019. 

Due Date: COB on July 25, 2019.  Please make sure to submit your report on time.

General Notes:
1) Please make sure to fill out and include any information that pertains to section 2 “Other miscellaneous updates”.  This includes sending any publication or other output and follow-on funding.

2) Please adhere to the 499 character limitation on the milestone/deliverable summaries.  These are uploaded onto an on-line system that automatically cuts off the text at 499 characters.  You can use the general scientific narrative section below each table to discuss any milestone/deliverable in greater detail (in addition to general task activities).  There is no character limitation here.

Best,
Cathy
[https://app.zenhub.com/files/41696258/54c4fc03-0722-4a9c-ae4f-73b17b5943d8/download](https://app.zenhub.com/files/41696258/54c4fc03-0722-4a9c-ae4f-73b17b5943d8/download)

**Comment by robkooper** [comment]
With what was discussed today on the phone, I think we should look at this as an opportunity to review all the tasks that are still open and see what needs to be done to close them. @sbrad77 can we schedule maybe 2 hours next week to just go over the tasks and see what needs to be done (at the same time create the report).

**Comment by sbrad77** [comment]
What about extending the meeting on Thursday to two hours and discussing / creating then?

**Comment by robkooper** [comment]
Works for me.

**Comment by sbrad77** [comment]
@max-zilla - can you extend the meeting on Thursday?

**Comment by dlebauer** [comment]
Sorry all – this Thursday won’t work for me because we are having a retreat from 9AM to 2 PM on Thursday. My schedule is open all day Friday if that would work.

Thanks

David

**Comment by sbrad77** [comment]
I only have from 1 to 2 open on Friday - but you all might have 1 to 3?

**Comment by max-zilla** [comment]
Our recurring VBD meeting is 2-3 Fridays but it's cancelled this week so that would work for me.

**Comment by sbrad77** [comment]
Report sent
Cathy – 
Please find the Quarter 14 report for our group attached.  If there are any questions, please let us know.
Then looking ahead -  are there any tasks not in this Q14 report that will be on the Q15 report so we can make sure it’s covered in our future planning?
Thank you!

Shannon Bradley, MBA
[Q14 Report.docx](https://github.com/terraref/computing-pipeline/files/3387758/Q14.Report.docx)

**Comment by max-zilla** [comment]
@sbrad77 can we close this?

**Comment by sbrad77** [comment]
YES! I forgot it had not been closed. Cathy's note on future planning:

Looks like the Q16 report will have 2 new deliverables to report on:
M5.6 | Form reference data committee | Report on committee progress

M6.19 | Web-based portal and Breeders   API | Finish interface that supports   Breeder's API. Complete  transition to permanent hosting solution
