### ISSUE TITLE
install and configure Clowder on Roger OpenStack

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#6]
Create persistent VM that holds Clowder. This VM will contain all pieces, such as mongo, elasticsearch, rabbitmq and clowder. This will mount the ADS file system and use this to persist mongo, elasticsearch rabbitmq, and the blobs uploaded to clowder.

**Comment by dlebauer** [comment]
@robkooper are these the three VMs that you were referring to (Clowder, PlantCV, PEcAn)?

**Comment by robkooper** [comment]
Updated list

**Comment by rachelshekar** [comment]
after #17

**Comment by robkooper** [comment]
Created a dev machine.

**Comment by robkooper** [comment]
Done http://141.142.168.72/clowder/
