### ISSUE TITLE
Migrate TERRA Ref BETYdb instances to openstack server

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#65]
The remaining task from #24 is to migrate the simulated and ref instances of BETYdb from pecandev to openstack (Nebula or Roger)

Next steps:

* [x] deploy an empty Ubuntu 14.04 LTS virtual machine on the Roger Server
* [x] @gsrohde to migrate terra-ref and terra-test instances of BETYdb from pecandev to this server
* [x] @gsrohde to have daily backups of both betydb instances saved somewhere in /projects/arpae/terraref/ (@robkooper how is this done for the clowder mongodb?)
   * add dumpurls to [load.bety.sh
* [x]  , and ask @jdmaloney how to archive these (in a  
* [x] @robkooper to point urls to these instances

**Comment by dlebauer** [comment]
@robkooper is there anything blocking this? Or anything that JD, Scott, Max, or I could do to move this forward?

**Comment by robkooper** [comment]
vacation and the fact that I can load a blank BETY for some reason. Troubleshooting this tomorrow (Thursday).
