### ISSUE TITLE
clowder tool launcher broken

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#67]
When I launch a tool from this page: http://141.142.209.122/clowder/datasets/56d48443e4b0c7e3b16ea67e#

I get "webpage not available" here: http://141.142.210.18:32810/

The tools were working yesterday. Today, neither the tools launched yesterday and nor the new ones will load.

**Comment by max-zilla** [comment]
from discussion - this may be related to IllinoisNet wifi blocking ports.

**Comment by robkooper** [comment]
This is an issue related to the way illinoisnet and the openstack have their IP addresses setup. Both use the 172.X.Y.Z subnet and when you from your laptop try to talk to openstack cluster the networking code thinks you are on the same subnet and tries to have you connect directly using the internal ip address and not the public address.

Will try to reassign ip addresses to the 192.168.100.X subnet which should solve this problem.
