### ISSUE TITLE
add PlantCV extractor to demo clowder on Nebula

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#68]
Following from #3, after sending some test files from Danforth to Clowder, we realized that the PlantCV extractors were not running on the nebula instance of clowder (141.142.209.122/clowder). There are 33,821 datasets waiting to be processed.

@yanliu-chn can you: add the PlantCV extractors and perform the scalability tests that you did on Roger?

**Comment by max-zilla** [comment]
@yanliu-chn have there been any updates on this? doesn't seem like the extractor is running yet, or on terraref.ncsa.illinois.edu - we have some data starting to flow into the latter. didn't see the thumbnails being generated on either instance.

**Comment by yanliu-chn** [comment]
@max-zilla There has been a change on Noah's script on how to process the images. Now that files are uploaded as snapshot dataset. We need dataset-level extractor or 'pseudo' dataset extractor implementation. 

This work is ongoing in issue #31 . Could you and @robkooper participate the discussion there? @caicai89- is doing the development work.

**Comment by yanliu-chn** [comment]
Mon-Wed I'm on vacation. I will be back on Thur.

**Comment by yanliu-chn** [comment]
I have deployed the most recent plantcv extractor on nebular:

extractor VM: plantcv-extractor-v2 . IP: 141.142.210.195 
Clowder pointed to: https://terraref.ncsa.illinois.edu/clowder-dev/

I tested using Noah's test raw data and it worked: https://terraref.ncsa.illinois.edu/clowder-dev/datasets/5797c598e4b0f5630de3be8a

I think we can close this ticket.
