### ISSUE TITLE
Images from full grown plants

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#70]
_From @solmazhajmohammadi on March 10, 2016 19:28_

In order to validate the algorithm for image alignment and stitching, I need images from full-grown plants.

_Copied from original issue: terraref/reference-data#23_

**Comment by dlebauer** [comment]
@yanliu-chn or @pless do you have some sample images that Solmaz can start working with?

**Comment by yanliu-chn** [comment]
@dlebauer : I think the sample images need to be from the field/indoor scanners this project has. For software evaluation purpose, each software should have its test datasets.

**Comment by dlebauer** [comment]
@rjstrand is the wheat canopy closed (or close enough)? [The live stream suggests 'perhaps'](https://www.youtube.com/watch?v=Pp6IdkPtFC8)

@solmazhajmohammadi presumably you can get to the sample data on roger - either via ssh or globus, currently we have data from the following sensors:

- stereoTop
- VNIR
- stereoEast
- ps2Top
- SWIR
- flirIrCamera

will one of those work?

**Comment by dlebauer** [comment]
@solmazhajmohammadi does the wheat data that we have on Roger meet your needs here? If so, can this be closed?

**Comment by solmazhajmohammadi** [comment]
I took couple of images from grass and used it. But I still need hyperspectral data (with 30% overlapping).

**Comment by rachelshekar** [comment]
@solmazhajmohammadi - can this issue be closed?

**Comment by solmazhajmohammadi** [comment]
@rachelshekar Yes.
