### ISSUE TITLE
Give Roger access to beta testers

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#71]
_From @rachelshekar on January 7, 2016 17:21_

Noah Fahlgren, Rob Pless at WUSTL and Charlie Zender

Include sample data

Private owncloud server?

_Copied from original issue: terraref/reference-data#21_

**Comment by dlebauer** [comment]
_From @yanliu-chn on January 7, 2016 18:13_

the ldap groups they should be assigned to: prj_cg_users and prj_cg_arpae

**Comment by dlebauer** [comment]
_From @yanliu-chn on January 7, 2016 18:14_

If they don't have ncsa account, please let me know their email addresses. i can contact them to create sponsored guest forms.

**Comment by dlebauer** [comment]
@yanliu-chn email addresses and github usernames are

| name | email | github |
|----|----|----|
| Charlie Zender | zender_at_uci.edu | @czender |
| Noah Fahlgren | nfahlgren_at_danforthcenter.org | @nfahlgren |
| Robert Pless | pless_at_wustl.edu |  |

**Comment by dlebauer** [comment]
@jdmaloney have you been able to give Charlie, Noah, and Robert access to Roger?

**Comment by jdmaloney** [comment]
Wasn’t aware that was on my to-do list.  I’ll inquire about getting them accounts as I don’t have power to do that directly.

Best,

J.D. Maloney
Storage Engineer | Storage Enabling Technologies Group
National Center for Supercomputing Applications (NCSA)
University of Illinois Urbana-Champaign
1205 W. Clark St. Urbana, IL 61801

**Comment by dlebauer** [comment]
Or maybe Yan?

**Comment by dlebauer** [comment]
I think everyone who needs access to Roger has it, others have access to data via Globus
