### ISSUE TITLE
Spatial image processing software tools and methods investigation

### ISSUE THREAD

**Issue by yanliu-chn** [terraref/computing-pipeline#75]
@solmazhajmohammadi, @czender  , Yan, and Xingchen are investigating the spatial image processing capabilities needed in this project and software and methods available to provide the capabilities.

We set up a [wiki page](https://github.com/terraref/documentation/wiki/Georeferencing-software-for-TerraRef-geoimages) to document the findings.

This ticket is created to coordinate the investigation.

**Comment by yanliu-chn** [comment]
We will ask Liujun Li, postdoc at cybergis center, to do a presentation and demo of the current UAV data pipeline prototype in another project during Purdue group's visit on March 31. @rachelshekar will put the presentation on the agenda.

**Comment by dlebauer** [comment]
What are the action items here? Is it to set up a separate call for @yanliu-chn, @caicai89-, @pless and @solmazhajmohammadi to coordinate?
