### ISSUE TITLE
Add API section to documentation

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#77]
Should include pointers to BETYdb, Clowder and any other API documentation (with a few examples)

**Comment by max-zilla** [comment]
The updates in my [pull request to the Clowder documentation](https://github.com/terraref/documentation/pull/12/files) include a bit of detail on the Clowder API and the Globus pipeline API. Not complete but enough to get someone started.

**Comment by max-zilla** [comment]
There is an API entry for Clowder now. I'm closing this issue and creating a new entry (#113) focused on the BETY API documentation.
