### ISSUE TITLE
Quality control for initial assessment and planning

### ISSUE THREAD

**Issue by JeffWhiteAZ** [terraref/computing-pipeline#84]
Below are some initial thoughts on QC for data acquired via the scanner. From a Maricopa perspective, we want a quick way to know whether data were obtained from the right plots and whether values pass an initial quality check. This is to detect errors in the control scripts and to detect possible issues with sensor alignment/focus/sensitivity/calibration etc.
## Quality Control during Data Acquisition

During or immediately after individual scanning runs, we will need to assess the quality of the data without unduly interrupting the main data processing workflow. Simple indicators will be extracted from individual images and reported as values georeferenced to plot centroids that can thus either be displayed as heat maps or subject to statistical analyses. Examples of such analyses would include:
1. Analysis of variance (for individual experiments) to determine whether expected treatment differences are detected and to estimate measurement error (e.g., as standard errors).
2. Linear regressions among data as "sensibility tests." For example, do proxies for canopy height correlate with each other? Is canopy cover correlated with NDVI?
3. Time series analysis (based on simple regression models using time as the independent variable) that test for expected growth patterns such as that height and canopy cover increase over time.
   These indicators should be calculable via simple R-scripts for images so that the programming and data management efforts for quality control do not interfere with the main image processing and data management. Calculation of the indicators should not require co-registration of images from different instruments or other major operations on image geometry. 
   Requested summary values are listed in Table 1. 
## Pending issues
1. Which location should have responsibility for calculating the indicators? Arizona prior to transfer?
2. Who is responsible for reviewing the indicators? Someone in Arizona should participate because they will a good understanding of crop growth and field conditions.
3. What actions are taken if data don’t pass quality control? 
4. Should we have a rating system for quality of data?
5. Will the X-dimensions of images match the plot width (0.76 m) or will the dimensions be readily extrapolated or clipped to the standard plot width. Values such as canopy cover and mean temperature will be difficult to interpret if they don’t represent a standard view dimension.

| Instrument | Performance indicator |
| --- | --- |
| 3D laser scanner | 95% quantile of height (z-values) from point cloud |
|  | Canopy cover estimated as the portion of points with z-values (heights) greater than the soil height. |
| Stereo cameras | 95% quantile of height |
|  | Canopy cover estimated as the portion of points with z-vales (heights) greater than the soil height. |
| Hyperspectral cameras | Mean values of NDVI and PRI calculated for standard wave lengths |
| RGB camera | canopy cover estimated by converting the image to HSB color space and estimating the portion of pixels with hue values greater than 35 and less than 125 (for scale of 0 to 255). |
| Thermal camera | Mean temperature of image (without reflectance correction) |
|  | 5% and 95% quantiles of temperature |
| PS II | ? |
| CropCircle | mean value of NDVI for parcel |
| Skye NDVI | mean value for parcel |
| Skye PRI | mean value for parcel |

[Original Draft in Word Doc TERRA_field_scanner_QC_JWW1_MO0_PAS0_DLB0_RA0.docx](https://github.com/terraref/computing-pipeline/files/214034/TERRA_field_scanner_QC_JWW1_MO0_PAS0_DLB0_RA0.docx)

**Comment by dlebauer** [comment]
@dlebauer please flush this out so it is more general, applies to other platforms e.g. PlantCV. Test first on PlantCV ...

**Comment by rachelshekar** [comment]
@dlebauer  reminder

**Comment by dlebauer** [comment]
* Metadata consistency: check that time and geolocation of concurrently run sensor scans are consistent (eg https://github.com/terraref/reference-data/issues/226)
* scan alignment #153 
* Hyperspectral #190 
* Radiometer data https://github.com/terraref/reference-data/issues/229

**Comment by craig-willis** [comment]
@dlebauer      This is a stale issue with comments in last 2 months. Please create new issues if work remains or put this content in the documentation.
