### ISSUE TITLE
Test bil --> netcdf converter and build Clowder extractor

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#86]
@yanliu-chn and @czender 

* Need to test the script [terraref.sh](https://github.com/terraref/computing-pipeline/blob/master/scripts/hyperspectral/terraref.sh) on SWIR and VNIR sample data in the roger environment
  * Give the raw image file, takes raw image & assumes header + metadata will be present, then chews away.
  * Parallelized to take a bunch of images, will spawn a bunch of images & put one on each core; has MPI to run across multiple nodes.

**Comment by yanliu-chn** [comment]
@czender : Charlie, if you could send the following information to yanliu@illinois.edu , I can then go ahead to set up your account on ROGER cluster:
your organization name and mailing address (for sending NCSA paperwork)
phone number
org email adress

**Comment by czender** [comment]
Done

**Comment by yanliu-chn** [comment]
I have submitted the request to set up an NCSA account for you. Will let you know when it's done.

**Comment by yanliu-chn** [comment]
@czender  NCSA account created. Paperwork will be sent to you today shortly.

**Comment by czender** [comment]
i received the password. how do i ssh to the roger cluster? i.e., what's the address of the login node?

**Comment by dlebauer** [comment]
the login node is roger-login.ncsa.illinois.edu

**Comment by czender** [comment]
roger does not accept my password. old or new, doesn't matter. do i actually have an account?
zender@roger-login.ncsa.illinois.edu's password: 
Connection closed by 141.142.169.31

**Comment by czender** [comment]
my password started to work an hour later, everything's ok now

**Comment by yanliu-chn** [comment]
it should work now. I just added your account to ROGER.

**Comment by czender** [comment]
is there project disk space I should use?
pipeline needs volatile space for intermediate datasets (e.g., /tmp), and a few GB to permanently store sample data for pipeline testing.
where are the realtime/latest lemnatec data (expected to be) stored?

**Comment by yanliu-chn** [comment]
/projects/arpae is the project space
/gpfs_scratch/arpae is the scratch space. you can use as temp space.

@dlebauer @jdmaloney could you help answer the question of realtime lemnatec data location?

**Comment by czender** [comment]
i found the raw lemnatec data in, e.g., /projects/arpae/terraref/raw_data/ua-mac/MovingSensor/VNIR. next question: where to put output from hyperspectral workflow?
options:
1. alongside input (add a .nc file to existing directory)
2. dedicated directory somewhere else that does not touch input directories, e.g., /projects/arpae/terraref/hyperspectral_workflow_output
3. other?
what say ye?

**Comment by yanliu-chn** [comment]
I vote for 2.

**Comment by dlebauer** [comment]
2 is good. 

* 1 is out because `/projects/arpae/terraref/raw_data/` is read-only by design
* additional thoughts on 2, 3
  * maintaining some consistency in directory would make it easier to find and abstract file paths, for example, `/projects/arpae/terraref/raw_data/ua-mac/MovingSensor/VNIR/2016-04-11` has structure `$PROJECT/<data_level>/<site>/<sensor_class>/<date>` that for a derived level 0 data product might become `/projects/arpae/terraref/level_0/ua-mac/hyperspectral`? 
  * but replace "hyperspectral" with more precise term 'imaging_spectrometer'
  * will the choice of directory structure have any impact on setting up a THREDDS server? 

@robkooper Rob - what do you think would work best (from above or anything other than random alphanumeric strings)?

**Comment by czender** [comment]
hyperspectral workflow is installed and breaks when it can't find python netCDF4 module (yes i tried module load python and pythonlibs). hints on how to find it or use it would be appreciated (i'm a novice at python) or please someone who's a python guru install it in a central location consistent with the "module load python" paths...

**Comment by yanliu-chn** [comment]
could you try "module load gdal-stack"? it loads netcdf4 correctly.

**Comment by yanliu-chn** [comment]
is python module for netcdf a separate software not included in netcdf source code?

**Comment by czender** [comment]
yes

**Comment by yanliu-chn** [comment]
i will install it as soon as possible.

**Comment by yanliu-chn** [comment]
what else does the code depend on? i will install them too.

**Comment by jdmaloney** [comment]
Just got back in town from Globus to come to a 3pm meeting (my fill in had to leave as his wife had a baby today...legit excuse).  I definitely think Option 2 is the best, something like: /projects/arpae/terraref/processed_data/ua-mac/..... to keep things consistent.  Keeping all derivative data separate from the raw (for all processing, not just hyper-spectral) should be a template going forward.

**Comment by czender** [comment]
Thanks, @yanliu-chn. Only thing missing is Python's netCDF4 module. It would also be helpful for system NCO to be updated. module load nco gives version 4.5.1, which is pretty old. 4.5.9 is latest stable version.

I don't have write permission in /projects/arpae/terraref. Ping me when there's a writable directory for the hyperspectral workflow output and then I'll make that the default...

**Comment by yanliu-chn** [comment]
@dlebauer what is your policy for the write permission to /projects/arpae/terraref ? can we make it writeable by group but make subdir in it writeable by only owner for readonly dirs?

**Comment by dlebauer** [comment]
@yanliu-chn I like your suggestion and also defer to others (like you and JD) with more knowledge and experience

So we can go with:

> writeable by group but make subdir in it writeable by only owner for readonly dirs?

But regarding the subdirectories: I think very restricted access to the `raw_data` and `processed_data` folders would be ideal. By very restricted, perhaps `raw_data` only writable by root and globus, and `processed_data` only by root and clowder. Specifically:

1. Anything that can't be replaced is read only, especially `/projects/arpae/terraref/raw_data/` write access only for root and transfer agents like globus
2. When testing and developing code, write to scratch (if needed create a new subdirectory under `terraref/` and discuss new use cases)
3. When the code is ready for the production pipeline (e.g. automated as Clowder extractor), it should be written to a separate directory (e.g. `processed_data` as JD suggested).
4. Write access to the processed data products should also be very restricted (e.g. only Clowder+root). 

Does this seem like a sufficiently conservative approach? Does it put any undue restrictions on users (e.g. would this work for you Charlie)?

**Comment by czender** [comment]
Yes, that works for me. Default will be /gpfs_scratch/arpae/imaging_spectrometer. Clowder would just need to use the option: -O /projects/arpae/terraref/processed_data/subdir/subdir...

**Comment by czender** [comment]
@yanliu-chn try this, if you dare: 
module load anaconda
sudo conda install netcdf4

**Comment by yanliu-chn** [comment]
i didn't dare to do that. :) on the cluster, all the software packages are installed as non-root to support modules system.

I have installed python support for netcdf5, also upgraded nco to 4.5.5. I didn't find 4.5.9 src tarball.

if you do `module load gdal-stack nco`, you will load pythonlibs/0.2 which includes netCDF4 python. let me know if it works.

**Comment by czender** [comment]
Thanks, @yanliu-chn. However, the Terraref workflow requires Python 2.7+. /usr/bin/python is 2.6.6 (too old). module load python gives 3.4.4 (fine). The netCDF4 that comes with gdal-stack seems to be installed against 2.6.6, so is unusable the Terraref workflow. Unless I am doing something wrong? In any case, need help getting python 2.7+ at same time as netCDF4 python module.

**Comment by yanliu-chn** [comment]
let me build a version using 2.7+

**Comment by yanliu-chn** [comment]
done. could you do "module load gdal-stack-2.7.10 nco" and test if it works? or you can give a test command and I can try that first.

**Comment by czender** [comment]
Progress. it fails, but it breaks somewhere new (that you might be able to fix). first, the test command is...
terraref.sh -d 1 -i ~zender/data/terraref/whiteReference_raw -o whiteReference.nc
where terraref.sh =
https://github.com/terraref/computing-pipeline/tree/master/scripts/hyperspectral/terraref.sh
Second, here is the failure output I get:
zender@cg-gpu01:~$ !terraref.sh
terraref.sh -d 1 -i ${DATA}/terraref/whiteReference_raw -o whiteReference.nc
Terraref data pipeline invoked with command:
terraref.sh -d 1 -i /home/zender/data/terraref/whiteReference_raw -o whiteReference.nc
Input #00: /home/zender/data/terraref/whiteReference_raw
trn(in)  : /home/zender/data/terraref/whiteReference_raw
trn(out) : /gpfs_scratch/arpae/hyperspectral_imager/terraref_tmp_trn.nc.pid24628.fl00.tmp
ncks -O --trr_wxy=926,1600,1 --trr typ_in=NC_USHORT --trr typ_out=NC_USHORT --trr ntl_in=bil --trr ntl_out=bsq --trr_in=/home/zender/data/terraref/whiteReference_raw ~/nco/data/in.nc /gpfs_scratch/arpae/hyperspectral_imager/terraref_tmp_trn.nc.pid24628.fl00.tmp
att(in)  : /gpfs_scratch/arpae/hyperspectral_imager/terraref_tmp_trn.nc.pid24628.fl00.tmp
att(out) : /gpfs_scratch/arpae/hyperspectral_imager/terraref_tmp_att.nc.pid24628.fl00.tmp
ncatted -O --gaa terraref_script=terraref.sh --gaa terraref_hostname=cg-gpu01 --gaa terraref_version="4.6.0-beta03" -a "Conventions,global,o,c,CF-1.5" -a "Project,global,o,c,TERRAREF" --gaa history='Mon Apr 25 11:33:08 PDT 2016: terraref.sh -d 1 -i /home/zender/data/terraref/whiteReference_raw -o whiteReference.nc' /gpfs_scratch/arpae/hyperspectral_imager/terraref_tmp_trn.nc.pid24628.fl00.tmp /gpfs_scratch/arpae/hyperspectral_imager/terraref_tmp_att.nc.pid24628.fl00.tmp
jsn(in)  : /home/zender/data/terraref/whiteReference_raw
jsn(out) : /gpfs_scratch/arpae/hyperspectral_imager/terraref_tmp_jsn.nc.pid24628
python /home/zender/terraref/computing-pipeline/scripts/hyperspectral/JsonDealer.py /home/zender/data/terraref/whiteReference_raw /gpfs_scratch/arpae/hyperspectral_imager/terraref_tmp_jsn.nc.pid24628.fl00.tmp
Traceback (most recent call last):
  File "/home/zender/terraref/computing-pipeline/scripts/hyperspectral/JsonDealer.py", line 50, in <module>
    from netCDF4 import Dataset
  File "/sw/pylibs-2.7.10/lib/python2.7/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: /sw/pylibs-2.7.10/lib/python2.7/site-packages/netCDF4/_netCDF4.so: undefined symbol: _Py_ZeroStruct
terraref.sh: ERROR Failed to parse JSON metadata. Debug this:
python /home/zender/terraref/computing-pipeline/scripts/hyperspectral/JsonDealer.py /home/zender/data/terraref/whiteReference_raw /gpfs_scratch/arpae/hyperspectral_imager/terraref_tmp_jsn.nc.pid24628.fl00.tmp

**Comment by yanliu-chn** [comment]
could you do "module purge" first before module load? I ran the last debug line `python /home/zender/terraref/computing-pipeline/scripts/hyperspectral/JsonDealer.py /home/zender/data/terraref/whiteReference_raw /gpfs_scratch/arpae/hyperspectral_imager/terraref_tmp_jsn.nc.pid24628.fl00.tmp` and it worked.

**Comment by yanliu-chn** [comment]
i guess the module load command needs to be included in ~/.bashrc .

**Comment by czender** [comment]
yes, it works now that i put "module load gdal-stack-2.7.10" directly in the script. in general, do not load the nco module yourself because the script points to the latest NCO in my home directory, and the terraref.sh script may rely on some more recent features. users of terraref.sh need not load any modules by hand. running some benchmarks now. thanks for your speedy help, yanliu.

**Comment by yanliu-chn** [comment]
glad that it works now.

**Comment by czender** [comment]
@yanliu-chn please set-up an account on Roger for @FlyingWithJerome Jerome Mao, my student who is developing the environmental logger workflow. He will send you his 411.

**Comment by yanliu-chn** [comment]
Jerome @FlyingWithJerome , could you send the following information to yanliu@illinois.edu , I can then go ahead to set up your account on ROGER cluster:
your organization name and mailing address (for sending NCSA paperwork)
phone number
org email adress

**Comment by yanliu-chn** [comment]
I have created the request for your NCSA and ROGER account. It will take a few business days for the paperwork to arrive. Please check your mailbox.

**Comment by FlyingWithJerome** [comment]
@yanliu-chn  thanks!

**Comment by czender** [comment]
@yanliu-chn in the last few weeks we released NCO 4.6.0 which contains all the features necessary for Terraref. If system NCO is updated to 4.6.0, then hyperspectral workflow can be run with stable system executables rather than bleeding-edge snapshots from my personal directory :) https://github.com/nco/nco/releases

**Comment by yanliu-chn** [comment]
I will update the NCO version on ROGER asap and let you know when it is done.

**Comment by yanliu-chn** [comment]
Done. I have built 4.6.0 and make it the default to load when doing "module load nco".

@czender could you test if the build works as expected?

**Comment by czender** [comment]
It fails because the system NCO package was not installed with ncap2. Building ncap2 requires first building or installing ANTLR as described on the NCO homepage nco.sf.net

**Comment by yanliu-chn** [comment]
I see. I rebuilt nco 4.6.0 with ncap2 and antlr-2.7.7 . could you load it with `module load gdal-stack-2.7.10 nco` and test it again?

**Comment by rachelshekar** [comment]
@czender - were you able to test this?

**Comment by yanliu-chn** [comment]
I think Charlie mentioned that this has been tested.

**Comment by czender** [comment]
yes i tested this (two weeks ago) and it works. sorry for not updating this earlier.

**Comment by rachelshekar** [comment]
@czender can this be closed then?

**Comment by czender** [comment]
i don't think so. there is no clowder extractor that i know of for terraref.sh.

**Comment by yanliu-chn** [comment]
right. my team will develop the extractor next.

**Comment by rachelshekar** [comment]
@yanliu-chn  - can you/your team create a new issue for the extractor so this issue can be closed?  What is the status of that work?

**Comment by yanliu-chn** [comment]
I'm going to close this issue and transit to #81

**Comment by Zodiase** [comment]
@yanliu-chn Anything I need to work on for this issue?
