### ISSUE TITLE
Create daily process to compress and archive gantry data  

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#87]
- Each day, compress and move raw gantry data to near-line tape storage
- Keep redundant copy on Roger
- Can delete the original data (that has been compressed and has copies on roger + near line tape)

**Comment by jdmaloney** [comment]
@dlebauer Script written to bundle and compress, launches a batch job on ROGER everyday to bundle the prior day's data (will start this up once our data flow in is stable).  The automation of the send to Nearline is currently be pursued.  While the gantry endpoint, and the terraref endpoint are either personal endpoints or non-two factor endpoints, the Nearline system requires two factor authorization every so often.  Meaning the script would break after so long if I don't reactivate the end point manually.  Seeing if its possible to get a service certificate to prevent me from having to re-auth every so often, but it's looking challenging as security has only given out one, and it was for internal Blue Waters back up, not to an actual project. All data currently on ROGER has been send to Nearline by hand.

**Comment by dlebauer** [comment]
Has this been implemented? Can you add the script to the repository?

Are there any checks to ensure that it is working, i.e. what happens if it fails?

**Comment by jdmaloney** [comment]
I haven't made it automatic as I'm waiting for when the data flow is consistent from MAC (Max gets back and we get his code working for a while).  Also there is the issue with the certificates.  Once it all gets ironed out I'll add the code to the repository.  It emails me a summary so I'll know if it breaks.

**Comment by max-zilla** [comment]
The gantry monitor is current right now (it's getting new FTP entries as they appear) but I think there are still some gaps from the transition between @jdmaloney's manual transfers and my monitor. We should generate file lists between gantry and Roger before e.g. 5/4 and transfer any files that are missing on Roger. Then we can start archiving.

**Comment by max-zilla** [comment]
@jdmaloney assuming no other hiccups on transfer over the weekend, lets discuss how to start addressing these data gaps next week.

**Comment by jdmaloney** [comment]
Service certificate is possible, starting the process of getting it.  Roadblock through of time delay on files, need to address that before continuing.

**Comment by rachelshekar** [comment]
@jdmaloney - please update this issue

**Comment by jdmaloney** [comment]
Time delay was only rare occurrence, not worrying about it, continuing pursuit of service cert

**Comment by rachelshekar** [comment]
@jdmaloney - can this be closed now?

**Comment by jdmaloney** [comment]
@rachelshekar Not yet, this hasn't been fully implemented yet

**Comment by jdmaloney** [comment]
Still trying figure out how backup timing will fit in with data flow, ex. reprocessed data location etc.

**Comment by jdmaloney** [comment]
Talked with @max-zilla, we're going to be driving daily backups based off of log output as that will be the easiest and most efficient way to determine new files that are generated as all raw inputs are coming through the same globus pipleline method that ua-mac is using (slight customizations for sites, but all logged the same way which is what we care about).  All pipeline outputs will know what files they are creating and that log will also be parsed to drive backups.  Thus logs drive both the inputs and outputs of the pipeline.

**Comment by rachelshekar** [comment]
@jdmaloney  - can this issue be closed?

**Comment by jdmaloney** [comment]
@rachelshekar  Sorry still not yet, forward progress is being made.  I'll try to have it done here by end of Sept.

**Comment by rachelshekar** [comment]
@jdmaloney ???

**Comment by jdmaloney** [comment]
@rachelshekar This is running now, the code is all ready.  It's processing the backlog up to a point, and will continue once @max-zilla and I get the pipeline all fixed up.

**Comment by jdmaloney** [comment]
This has been completed, automated, and is gathering metrics that will be added into our monitoring.
