### ISSUE TITLE
opendap exploration on subsetting netcdf

### ISSUE THREAD

**Issue by yanliu-chn** [terraref/computing-pipeline#89]
Explore the online way to subset a big netcdf in order to query partial data/metadata out of it.

See THREDDS Data Server Documentation here: http://www.unidata.ucar.edu/software/thredds/current/tds/TDS.html

**Comment by caicai89-** [comment]
http://www.unidata.ucar.edu/software/thredds/current/tds/reference/NetcdfSubsetServiceReference.html

**Comment by rachelshekar** [comment]
@caicai89- where are you with this?

**Comment by caicai89-** [comment]
Based on the URL I provided, I think NetCDF Subset Service (NCSS) can do the thing.

**Comment by dlebauer** [comment]
@yanliu-chn can we put one on Roger where users can access the hyperspectral data? If so, perhaps create a new issue?
