### ISSUE TITLE
Clowder user roles

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#90]
1. What privileges should we provide users? They should be able to use the system, add metadata, create tools and collections but not delete or modify existing information.
3. To prevent accidental corruption of the data stream, would it be worthwhile to give anyone who has delete / edit permissions two accounts, one for editing / deleting and the other for viewing / annotating?  (is there ever a case where someone should be able to edit or delete a dataset from the web interface? perhaps one that they created, but not for the data products that we provide ...)
2. I created a new 'role' called "Add, Annotate, Aggregate". Are these appropriate permissions for the TERRA community of alpha-testers?

- Space: View
- Dataset: View | Create
- Collection: View | Create
- File: Add | View | Download
- Section: View
- Metadata: Add | View
- Tag: Add | View
- Comment: Add | View
- Sensor: View
- Geo Stream: Add | View
- Datapoint: Add
- Relation: View
- User: View

**Comment by robkooper** [comment]
in general you can only delete that which you are the owner of. So you can not delete something that I did (unless you have super powers see https://opensource.ncsa.illinois.edu/jira/browse/CATS-486)

**Comment by max-zilla** [comment]
There's also a separate permission for being able to launch analysis tools - seems like anyone who can view the files ought to be able to do that? 

but we should probably also flesh out the management piece of those tool instances so people can't launch 400 tools and forget about them for 6 months - there's nothing of that nature in the code right now.
