### ISSUE TITLE
Setup dedicated, replicated mongo server for Clowder 

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#91]
In order to prevent data loss and, set up a dedicated mongo database server for use with the Clowder instances.

**Comment by dlebauer** [comment]
@robkooper what is the status of this?

**Comment by robkooper** [comment]
created initial replication set, testing with another instance of clowder before using for terra.

**Comment by robkooper** [comment]
Documentation can be found at https://opensource.ncsa.illinois.edu/confluence/display/CATS/Mongo+Clusters
