### ISSUE TITLE
Missing data in gantry stream at beginning of Sorghum trials (04-2016)

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#93]
For the Sorghum trial (starting April 20), I am looking at the 

The following are generating empty folders:

* co2 sensor
* crop circle
* ndvi
* pri

The following sensors are not generating any folders

* ps2Top
* SWIR
* VNIR
* scanner3DTop

These are currently sending data:

* flir thermal 
* stereoTop

Not expected: 

* stereo[west, east]
* scanner3D[west, east]

@jdmaloney are these landing on the cache server?
@rjstrand @TinoDornbusch are these being generated by the sensor suite?

**Comment by TinoDornbusch** [comment]
I am going through the list, sensor by sensor. Will update you in due course of the day.

**Comment by jdmaloney** [comment]
@dlebauer Many of these sensor, haven't check every single one, have folders on the gantry for yesterday only

**Comment by dlebauer** [comment]
note that many have folders but no data and that I only looked for data
generated since April 10 in `MovingSensor/*/2016-04-[12]*`

**Comment by rjstrand** [comment]
Over the weekend, I was drilling down on the Stereo.  It is possible that I did not add the auxiliary sensors back in.  That should be a pretty quick add. 

For now, you should also add PSII and hyperspec cameras to the unexpected list.  PSII can only be truly tested at night and that will only be allowed in certain portions of the field.  Hyperspec will also have isolated operation due to both speed and light source issues. 

I am headed to Maricopa within the hour and Tino and I will update you.  

-Bob

**Comment by dlebauer** [comment]
@jdmaloney by 'have folders for yesterday only' are you saying that the files have been transferred from the gantry-cache to roger, and are no longer on the cache? I assume that they are only deleted from the gantry-cache _after_ they have been archived to near-line storage (correct?).

**Comment by jdmaloney** [comment]
So all data through April 7th has been brought to ROGER and Nearline, and cleaned off the cache server.  There was no data sent to the gantry between the 7th and yesterday when data began coming in again.  The data that came in yesterday (and today/going forward) has not been moved anywhere yet as Max's moving program isn't working.  Yes the policy will be to not clean data off the cache until it has been moved to Nearline.

**Comment by TinoDornbusch** [comment]
Brought all environmental sensors online and made by-eye evaluation. Look OK at first glance.

First tests with SWIR and VNIR running.

3D still not working in triggered mode and calibration data from Fraunhofer missing.

Please do not move data. I need to evaluate.

**Comment by dlebauer** [comment]
@jdmaloney I think this can be closed. Please reopen if necessary
