### ISSUE TITLE
STEREO3D height scanner

### ISSUE THREAD

**Issue by solmazhajmohammadi** [terraref/computing-pipeline#98]
Register two point cloud data from the 3D stereo scanner pair to generate a single point cloud per row scan.

**Comment by rachelshekar** [comment]
@solmazhajmohammadi - how is this going?  Have you been able to extract plant height from the data?

**Comment by rachelshekar** [comment]
Can @solmazhajmohammadi provide ply to .LAS?  converter (using gdal?)? 
http://www.pdal.io/ 
LAS is binary = smaller, better tool availability, more standardized. 
Solmaz : I can take a look at it. Can you please let me know what is the priority on this? By the release.

**Comment by solmazhajmohammadi** [comment]
PDAL image is available in docker. You can pull it with following command:
`docker pull pdal/pdal:1.3`

Following command will convert the PLY file format to LAS file:

`docker run -v /Path/ToThe/File/data:/data -t pdal/pdal pdal translate --writers.las.dataformat_id="0"  --writers.las.scale_x=".0000001" --writers.las.scale_y=".0001" --writers.las.scale_z=".000001" /data/Input.ply /data/out/Output.las `
List of the available data formats:

    0 == no color or time stored
    1 == time is stored
    2 == color is stored
    3 == color and time are stored
    6 == time is stored (version 1.4+ only)
    7 == time and color are stored (version 1.4+ only)
    8 == time, color and near infrared are stored (version 1.4+ only)
=======================================================================
Choose the scale based on the precision that you want to save the file. 
The default LAS version is "2", you can change it to "1" with adding:
 `--writers.las.minor_version="1"` 
I think version 1 is more compatible with different softwares.

=======================================================================
Suggestions:
=======================================================================
You can compress the LAS pointclouds by the following command:

`docker run -v /Path/ToThe/File/data:/data -t pdal/pdal pdal translate --writers.las.dataformat_id="0"  --writers.las.scale_x=".01" --writers.las.scale_y=".01" --writers.las.scale_z=".01" --writers.las.compression="laszip" /data/Input.ply  /data/output/CompressedOutput.las`

========================================================================
I would suggest to concatenate the east and west 3D scanners as well. Following command will merge the pointclouds:

`docker run -v /Path/ToThe/File/data:/data -t pdal/pdal pdal merge  /data/InputEast.las /data/InputWest.las  /data/output/MergedOutput.las`

It is possible to stitched together all the pointclouds from the field with the same command.

**Comment by max-zilla** [comment]
@solmazhajmohammadi This is helpful. So this can be an extractor that:
- triggers on 2 PLY files being added to a dataset in Clowder
- converts the PLY files to LAS, merge them into one pointcloud, and compress
- Add the LAS file to Clowder

@dlebauer @jdmaloney Right now the folder structures are:
```
PNG files - /sites/ua-mac/raw_data/scanner3DTop/ 
PLY files - /sites/ua-mac/Level_1/scanner3DTop/
I think LAS can be the same:
LAS files - /sites/ua-mac/Level_1/scanner3DTop/
```
Do we keep the PLY files once LAS is generated? Is it OK to keep LAS + PLY in same Level_1 directory?

**Comment by dlebauer** [comment]
yes, we can keep PLY and LAS in the same directory. My inclination would be to delete the ply file but lets keep them for now.

**Comment by solmazhajmohammadi** [comment]
Thanks @max-zilla 
you can compress the file at the same time with conversion.
Merging the point clouds is an option. I can take a look to see if we can combine the conversion and merging together. But, my suggestion is to keep the LAS files separately for East and West camera, due to the time difference between the scans. 
PDAL by default storing the points in two decimal point, set this based on decimal point that you want to store the data.

**Comment by max-zilla** [comment]
@solmazhajmohammadi I'm putting the extractor together based on the PDAL code you provided above, but it's running into errors on my local tests:
```
FILE
/ua-mac/Level_1/scanner3DTop/2016-10-18/2016-10-18__11-59-29-887/c2221324-db35-43c2-8aec-4dc55117d34e__Top-heading-east_0.ply

CMD
pdal translate --writers.las.dataformat_id="0" --writers.las.scale_x=".0000001" --writers.las.scale_y=".0001" --writers.las.scale_z=".000001" ~/Documents/TERRAref/data_examples/c2221324-db35-43c2-8aec-4dc55117d34e__Top-heading-east_0.ply ~/Documents/TERRAref/data_examples/c2221324-db35-43c2-8aec-4dc55117d34e__Top-heading-east_0.las

ERROR
PDAL: Unable to convert scaled value (-5.12524e+09) to int32 for dimension 'X' when writing LAS/LAZ file /Users/mburnette/Documents/TERRAref/data_examples/c2221324-db35-43c2-8aec-4dc55117d34e__Top-heading-east_0.las.
```

"Unable to convert scaled value to int32" - have you seen this before, and do you know of a workaround? Thanks.

**Comment by max-zilla** [comment]
here is the extractor, i think it is close to ready if we can solve this int conversion: https://github.com/terraref/extractors-3dscanner

**Comment by solmazhajmohammadi** [comment]
@max-zilla I have not had this error, but  instead of using --writers.las.scale_x=".0000001" use following command  --writers.las.scale_x=".000001" with reduced scale. It should solve the problem

**Comment by max-zilla** [comment]
@solmazhajmohammadi looks like that resolved it, thanks!

**Comment by max-zilla** [comment]
This extractor is done and deployed.

**Comment by max-zilla** [comment]
Pictures!
<img width="613" alt="screen shot 2016-11-10 at 10 22 53 am" src="https://cloud.githubusercontent.com/assets/14166971/20184910/e4b32d26-a72f-11e6-9955-b6343e190328.png">
<img width="639" alt="screen shot 2016-11-10 at 10 23 20 am" src="https://cloud.githubusercontent.com/assets/14166971/20184909/e4b09afc-a72f-11e6-8658-8ad826f6b2ee.png">
