### ISSUE TITLE
Imports from FieldBook/field data to BETYdb

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#99]
Look into importing from field data collection environments to BETYdb.

Most important is FieldBook > BETY (via BRAPI?) 
- http://www.wheatgenetics.org/field-book
- https://play.google.com/store/apps/details?id=com.fieldbook.tracker

Also worth looking at existing Excel templates that researchers use: ICASA, BMS, genomes2fields (which will be replaced by BMS)

**Comment by dlebauer** [comment]
See also terraref/reference-data#18, https://github.com/terraref/documentation/blob/master/existing_data_standards.md

**Comment by dlebauer** [comment]
For now we will use the BETYdb API or bulk upload so I am closing this. We can re-open later when needed.
